CREATE TABLE "PLUNGER_LIFT_CYCLE_POINT"
(
    "PLUNGER_LIFT_CYCLE_POINT_ID" VARCHAR(40) NOT NULL,
    "PLUNGER_LIFT_CYCLE_RESULT_ID" VARCHAR(40),
    "TIME" NUMERIC(18,2),
    "PHASE" VARCHAR(255),
    "PLUNGER_DEPTH" NUMERIC(18,2),
    "CASING_PRESSURE" NUMERIC(18,2),
    "TUBING_PRESSURE" NUMERIC(18,2),
    "PRODUCTION_RATE" NUMERIC(18,2),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_QUALITY" VARCHAR(40)
);
