CREATE TABLE "PLUNGER_LIFT_GAS_REQUIREMENTS"
(
    "PLUNGER_LIFT_GAS_REQUIREMENTS_ID" VARCHAR(40) NOT NULL,
    "PLUNGER_LIFT_WELL_PROPERTIES_ID" VARCHAR(40),
    "REQUIRED_GAS_INJECTION_RATE" NUMERIC(18,2),
    "AVAILABLE_GAS" NUMERIC(18,2),
    "ADDITIONAL_GAS_REQUIRED" NUMERIC(18,2),
    "REQUIRED_GAS_LIQUID_RATIO" NUMERIC(18,6),
    "MINIMUM_CASING_PRESSURE" NUMERIC(18,2),
    "MAXIMUM_CASING_PRESSURE" NUMERIC(18,2),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_QUALITY" VARCHAR(40)
);
