raiserror ('CREATING TABLE PARTICIPATING_AREA', 10,1) with nowait

CREATE TABLE PARTICIPATING_AREA
(
    PARTICIPATING_AREA_ID NVARCHAR(40) NOT NULL,
    UNIT_AGREEMENT_ID NVARCHAR(40),
    AREA_NAME NVARCHAR(255),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
