raiserror ('CREATING TABLE UNIT_AGREEMENT', 10,1) with nowait

CREATE TABLE UNIT_AGREEMENT
(
    UNIT_AGREEMENT_ID NVARCHAR(40) NOT NULL,
    UNIT_NAME NVARCHAR(255),
    UNIT_NUMBER NVARCHAR(255),
    UNIT_OPERATOR_BA_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    STATUS NVARCHAR(50),
    TERMS_AND_CONDITIONS NVARCHAR(255),
    APPROVAL_DATE DATETIME,
    APPROVED_BY NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
