CREATE TABLE `FLASH_COMPONENT`
(
    `FLASH_COMPONENT_ID` VARCHAR(40) NOT NULL,
    `FLASH_CALCULATION_ID` VARCHAR(40),
    `COMPONENT_NAME` VARCHAR(255),
    `MOLE_FRACTION` DECIMAL(18,2),
    `CRITICAL_TEMPERATURE` DECIMAL(18,2),
    `CRITICAL_PRESSURE` DECIMAL(18,2),
    `ACENTRIC_FACTOR` DECIMAL(18,2),
    `MOLECULAR_WEIGHT` DECIMAL(18,2),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_QUALITY` VARCHAR(40)
);
