-- RECEIVABLE Table Creation Script
-- SQL Server Version

CREATE TABLE RECEIVABLE
(
    RECEIVABLE_ID NVARCHAR(40) NOT NULL,
    TRANSACTION_ID NVARCHAR(40),
    CUSTOMER NVARCHAR(255),
    INVOICE_NUMBER NVARCHAR(100),
    INVOICE_DATE DATETIME,
    DUE_DATE DATETIME,
    ORIGINAL_AMOUNT NUMERIC(18,2),
    AMOUNT_PAID NUMERIC(18,2),
    STATUS NVARCHAR(40),
    ACTIVE_IND NVARCHAR(1),
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(4000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(40),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);

-- Primary Key
ALTER TABLE RECEIVABLE
ADD CONSTRAINT PK_RECEIVABLE PRIMARY KEY (RECEIVABLE_ID);

-- Indexes
CREATE INDEX IX_RECEIVABLE_CUSTOMER ON RECEIVABLE(CUSTOMER);
CREATE INDEX IX_RECEIVABLE_STATUS ON RECEIVABLE(STATUS);
CREATE INDEX IX_RECEIVABLE_DUE_DATE ON RECEIVABLE(DUE_DATE);
CREATE INDEX IX_RECEIVABLE_INVOICE_NUMBER ON RECEIVABLE(INVOICE_NUMBER);
CREATE INDEX IX_RECEIVABLE_TRANSACTION ON RECEIVABLE(TRANSACTION_ID);

