-- UNPROVED_PROPERTY Table Creation Script
-- SQL Server Version

CREATE TABLE UNPROVED_PROPERTY
(
    PROPERTY_ID NVARCHAR(40) NOT NULL,
    PROPERTY_NAME NVARCHAR(255),
    ACQUISITION_COST NUMERIC(18,2),
    ACQUISITION_DATE DATETIME,
    PROPERTY_TYPE NVARCHAR(40),
    WORKING_INTEREST NUMERIC(18,6),
    NET_REVENUE_INTEREST NUMERIC(18,6),
    ACCUMULATED_IMPAIRMENT NUMERIC(18,2),
    IS_PROVED NVARCHAR(1),
    PROVED_DATE DATETIME,
    COST_CENTER_ID NVARCHAR(40),
    ACTIVE_IND NVARCHAR(1),
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(4000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(40),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);

-- Primary Key
ALTER TABLE UNPROVED_PROPERTY
ADD CONSTRAINT PK_UNPROVED_PROPERTY PRIMARY KEY (PROPERTY_ID);

-- Foreign Keys
ALTER TABLE UNPROVED_PROPERTY
ADD CONSTRAINT FK_UNPROVED_PROPERTY_COST_CENTER FOREIGN KEY (COST_CENTER_ID) REFERENCES COST_CENTER(COST_CENTER_ID);

-- Indexes
CREATE INDEX IX_UNPROVED_PROPERTY_COST_CENTER ON UNPROVED_PROPERTY(COST_CENTER_ID);
CREATE INDEX IX_UNPROVED_PROPERTY_PROPERTY_TYPE ON UNPROVED_PROPERTY(PROPERTY_TYPE);
CREATE INDEX IX_UNPROVED_PROPERTY_IS_PROVED ON UNPROVED_PROPERTY(IS_PROVED);

