CREATE TABLE "LIQUID_PIPELINE_FLOW_PROPERTIES"
(
    "LIQUID_PIPELINE_FLOW_PROPERTIES_ID" VARCHAR2(40) NOT NULL,
    "PIPELINE_PROPERTIES_ID" VARCHAR2(40),
    "LIQUID_FLOW_RATE" NUMBER(18,2),
    "LIQUID_SPECIFIC_GRAVITY" NUMBER(18,2),
    "LIQUID_VISCOSITY" NUMBER(18,2),
    "LIQUID_DENSITY" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_QUALITY" VARCHAR2(40)
);
