ALTER TABLE "PIPELINE_STATION"
ADD CONSTRAINT FK_PIPELINE_STATION_PIPELINE FOREIGN KEY ("PIPELINE_ID") REFERENCES "PIPELINE"("PIPELINE_ID");

ALTER TABLE "PIPELINE_STATION"
ADD CONSTRAINT FK_PIPELINE_STATION_STATION FOREIGN KEY ("STATION_ID") REFERENCES "STATION"("STATION_ID");

ALTER TABLE "PIPELINE_STATION"
ADD CONSTRAINT FK_PIPELINE_STATION_FACILITY FOREIGN KEY ("FACILITY_ID") REFERENCES "FACILITY"("FACILITY_ID");
