ALTER TABLE "PIPELINE_MAINTENANCE_SCHEDULE"
ADD CONSTRAINT FK_PIPELINE_MAINTENANCE_SCHEDULE_PIPELINE FOREIGN KEY ("PIPELINE_ID") REFERENCES "PIPELINE"("PIPELINE_ID");

ALTER TABLE "PIPELINE_MAINTENANCE_SCHEDULE"
ADD CONSTRAINT FK_PIPELINE_MAINTENANCE_SCHEDULE_SCHEDULE FOREIGN KEY ("SCHEDULE_ID") REFERENCES "SCHEDULE"("SCHEDULE_ID");
