ALTER TABLE "PIPELINE_MAINTENANCE"
ADD CONSTRAINT FK_PIPELINE_MAINTENANCE_PIPELINE FOREIGN KEY ("PIPELINE_ID") REFERENCES "PIPELINE"("PIPELINE_ID");

ALTER TABLE "PIPELINE_MAINTENANCE"
ADD CONSTRAINT FK_PIPELINE_MAINTENANCE_MAINTENANCE FOREIGN KEY ("MAINTENANCE_ID") REFERENCES "MAINTENANCE"("MAINTENANCE_ID");

ALTER TABLE "PIPELINE_MAINTENANCE"
ADD CONSTRAINT FK_PIPELINE_MAINTENANCE_SEGMENT FOREIGN KEY ("SEGMENT_ID") REFERENCES "SEGMENT"("SEGMENT_ID");
