ALTER TABLE "PIPELINE_FIELD"
ADD CONSTRAINT FK_PIPELINE_FIELD_PIPELINE FOREIGN KEY ("PIPELINE_ID") REFERENCES "PIPELINE"("PIPELINE_ID");

ALTER TABLE "PIPELINE_FIELD"
ADD CONSTRAINT FK_PIPELINE_FIELD_FIELD FOREIGN KEY ("FIELD_ID") REFERENCES "FIELD"("FIELD_ID");
