CREATE TABLE "PIPELINE_RISK_ASSESSMENT"
(
    "PIPELINE_ID" VARCHAR2(40),
    "RISK_ASSESSMENT_ID" VARCHAR2(40),
    "ASSESSMENT_DATE" DATE,
    "RISK_SCORE" NUMBER(18,2) NOT NULL,
    "ASSESSMENT_METHOD" VARCHAR2(255),
    "RISK_FACTORS" VARCHAR2(255),
    "SEGMENT_ID" VARCHAR2(40),
    "DESCRIPTION" VARCHAR2(2000),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "EFFECTIVE_DATE" DATE,
    "EXPIRY_DATE" DATE,
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_QUALITY" VARCHAR2(40)
);
