ALTER TABLE "PIPELINE_SEGMENT"
ADD CONSTRAINT FK_PIPELINE_SEGMENT_PIPELINE FOREIGN KEY ("PIPELINE_ID") REFERENCES "PIPELINE"("PIPELINE_ID");

ALTER TABLE "PIPELINE_SEGMENT"
ADD CONSTRAINT FK_PIPELINE_SEGMENT_SEGMENT FOREIGN KEY ("SEGMENT_ID") REFERENCES "SEGMENT"("SEGMENT_ID");

ALTER TABLE "PIPELINE_SEGMENT"
ADD CONSTRAINT FK_PIPELINE_SEGMENT_START_STATION FOREIGN KEY ("START_STATION_ID") REFERENCES "START_STATION"("START_STATION_ID");

ALTER TABLE "PIPELINE_SEGMENT"
ADD CONSTRAINT FK_PIPELINE_SEGMENT_END_STATION FOREIGN KEY ("END_STATION_ID") REFERENCES "END_STATION"("END_STATION_ID");
