CREATE TABLE "PIPELINE_PROPERTIES"
(
    "PIPELINE_PROPERTIES_ID" VARCHAR2(40) NOT NULL,
    "DIAMETER" NUMBER(18,2),
    "LENGTH" NUMBER(18,2),
    "ROUGHNESS" NUMBER(18,2),
    "ELEVATION_CHANGE" NUMBER(18,2),
    "INLET_PRESSURE" NUMBER(18,2),
    "OUTLET_PRESSURE" NUMBER(18,2),
    "AVERAGE_TEMPERATURE" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_QUALITY" VARCHAR2(40)
);
