ALTER TABLE "PIPELINE"
ADD CONSTRAINT FK_PIPELINE_REGULATORY FOREIGN KEY ("REGULATORY_ID") REFERENCES "REGULATORY"("REGULATORY_ID");

ALTER TABLE "PIPELINE"
ADD CONSTRAINT FK_PIPELINE_PRIMARY_FIELD FOREIGN KEY ("PRIMARY_FIELD_ID") REFERENCES "PRIMARY_FIELD"("PRIMARY_FIELD_ID");

ALTER TABLE "PIPELINE"
ADD CONSTRAINT FK_PIPELINE_COORD_SYSTEM FOREIGN KEY ("COORD_SYSTEM_ID") REFERENCES "COORD_SYSTEM"("COORD_SYSTEM_ID");

ALTER TABLE "PIPELINE"
ADD CONSTRAINT FK_PIPELINE_LOCAL_COORD_SYSTEM FOREIGN KEY ("LOCAL_COORD_SYSTEM_ID") REFERENCES "LOCAL_COORD_SYSTEM"("LOCAL_COORD_SYSTEM_ID");

ALTER TABLE "PIPELINE"
ADD CONSTRAINT FK_PIPELINE_COORD_ACQUISITION FOREIGN KEY ("COORD_ACQUISITION_ID") REFERENCES "COORD_ACQUISITION"("COORD_ACQUISITION_ID");
