CREATE TABLE "TRACT_PARTICIPATION"
(
    "TRACT_PARTICIPATION_ID" VARCHAR(40) NOT NULL,
    "PARTICIPATING_AREA_ID" VARCHAR(40),
    "UNIT_AGREEMENT_ID" VARCHAR(40),
    "TRACT_ID" VARCHAR(40),
    "PARTICIPATION_PERCENTAGE" NUMERIC(18,6),
    "WORKING_INTEREST" NUMERIC(18,2),
    "NET_REVENUE_INTEREST" NUMERIC(18,2),
    "TRACT_ACREAGE" NUMERIC(18,2),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP
);
