CREATE TABLE "UNIT_AGREEMENT"
(
    "UNIT_AGREEMENT_ID" VARCHAR(40) NOT NULL,
    "UNIT_NAME" VARCHAR(255),
    "UNIT_NUMBER" VARCHAR(255),
    "UNIT_OPERATOR_BA_ID" VARCHAR(40),
    "EFFECTIVE_DATE" TIMESTAMP,
    "EXPIRY_DATE" TIMESTAMP,
    "STATUS" VARCHAR(50),
    "TERMS_AND_CONDITIONS" VARCHAR(255),
    "APPROVAL_DATE" TIMESTAMP,
    "APPROVED_BY" VARCHAR(255),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP
);
