CREATE TABLE "HEAT_MAP_DATA_POINT"
(
    "HEAT_MAP_DATA_POINT_ID" VARCHAR(40) NOT NULL,
    "HEAT_MAP_ID" VARCHAR(40),
    "X" NUMERIC(18,2),
    "Y" NUMERIC(18,2),
    "ORIGINAL_X" NUMERIC(18,2),
    "ORIGINAL_Y" NUMERIC(18,2),
    "VALUE" NUMERIC(18,2),
    "LABEL" VARCHAR(255),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_QUALITY" VARCHAR(40)
);
