CREATE TABLE "HEAT_MAP_CONFIGURATION"
(
    "HEAT_MAP_ID" VARCHAR(40),
    "CONFIGURATION_NAME" VARCHAR(255),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30)
);
