-- Unique index on VALUE_TYPE and VALUE_CODE
CREATE UNIQUE INDEX IX_LIST_OF_VALUE_TYPE_CODE ON LIST_OF_VALUE (VALUE_TYPE, VALUE_CODE);

-- Index on CATEGORY for filtering
CREATE INDEX IX_LIST_OF_VALUE_CATEGORY ON LIST_OF_VALUE (CATEGORY);

-- Index on MODULE for module-specific queries
CREATE INDEX IX_LIST_OF_VALUE_MODULE ON LIST_OF_VALUE (MODULE);

-- Index on SOURCE for source filtering
CREATE INDEX IX_LIST_OF_VALUE_SOURCE ON LIST_OF_VALUE (SOURCE);

-- Index on PARENT_VALUE_ID for hierarchical queries
CREATE INDEX IX_LIST_OF_VALUE_PARENT ON LIST_OF_VALUE (PARENT_VALUE_ID);

-- Index on ACTIVE_IND for active/inactive filtering
CREATE INDEX IX_LIST_OF_VALUE_ACTIVE ON LIST_OF_VALUE (ACTIVE_IND);

