CREATE TABLE PLUNGER_LIFT_CYCLE_POINT
(
    PLUNGER_LIFT_CYCLE_POINT_ID TEXT NOT NULL,
    PLUNGER_LIFT_CYCLE_RESULT_ID TEXT,
    TIME REAL,
    PHASE TEXT,
    PLUNGER_DEPTH REAL,
    CASING_PRESSURE REAL,
    TUBING_PRESSURE REAL,
    PRODUCTION_RATE REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT
);
