CREATE TABLE PLUNGER_LIFT_GAS_REQUIREMENTS
(
    PLUNGER_LIFT_GAS_REQUIREMENTS_ID TEXT NOT NULL,
    PLUNGER_LIFT_WELL_PROPERTIES_ID TEXT,
    REQUIRED_GAS_INJECTION_RATE REAL,
    AVAILABLE_GAS REAL,
    ADDITIONAL_GAS_REQUIRED REAL,
    REQUIRED_GAS_LIQUID_RATIO REAL,
    MINIMUM_CASING_PRESSURE REAL,
    MAXIMUM_CASING_PRESSURE REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT
);
