using System;
using System.Collections.Generic;

namespace Beep.OilandGas.ProductionAccounting.Reporting
{
    /// <summary>
    /// Report type enumeration.
    /// </summary>
    public enum ReportType
    {
        /// <summary>
        /// Internal operational report.
        /// </summary>
        InternalOperational,

        /// <summary>
        /// Internal lease report.
        /// </summary>
        InternalLease,

        /// <summary>
        /// Governmental report (federal, state, local).
        /// </summary>
        Governmental,

        /// <summary>
        /// Joint interest statement.
        /// </summary>
        JointInterest,

        /// <summary>
        /// Royalty owner statement.
        /// </summary>
        RoyaltyOwner
    }

    /// <summary>
    /// Represents a base report.
    /// </summary>
    public abstract class Report
    {
        /// <summary>
        /// Gets or sets the report identifier.
        /// </summary>
        public string ReportId { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the report type.
        /// </summary>
        public ReportType ReportType { get; set; }

        /// <summary>
        /// Gets or sets the report period start date.
        /// </summary>
        public DateTime ReportPeriodStart { get; set; }

        /// <summary>
        /// Gets or sets the report period end date.
        /// </summary>
        public DateTime ReportPeriodEnd { get; set; }

        /// <summary>
        /// Gets or sets the generation date.
        /// </summary>
        public DateTime GenerationDate { get; set; } = DateTime.Now;

        /// <summary>
        /// Gets or sets the generated by.
        /// </summary>
        public string GeneratedBy { get; set; } = string.Empty;
    }

    /// <summary>
    /// Represents an internal operational report.
    /// </summary>
    public class OperationalReport : Report
    {
        /// <summary>
        /// Gets or sets the production summary.
        /// </summary>
        public ProductionReportSummary Production { get; set; } = new();

        /// <summary>
        /// Gets or sets the inventory summary.
        /// </summary>
        public InventoryReportSummary Inventory { get; set; } = new();

        /// <summary>
        /// Gets or sets the allocation summary.
        /// </summary>
        public AllocationReportSummary Allocation { get; set; } = new();

        /// <summary>
        /// Gets or sets the measurement summary.
        /// </summary>
        public MeasurementReportSummary Measurement { get; set; } = new();

        /// <summary>
        /// Gets or sets the cost summary.
        /// </summary>
        public CostReportSummary Costs { get; set; } = new();
    }

    /// <summary>
    /// Represents a lease report.
    /// </summary>
    public class LeaseReport : Report
    {
        /// <summary>
        /// Gets or sets the lease identifier.
        /// </summary>
        public string LeaseId { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the production by lease.
        /// </summary>
        public decimal ProductionVolume { get; set; }

        /// <summary>
        /// Gets or sets the revenue by lease.
        /// </summary>
        public decimal Revenue { get; set; }

        /// <summary>
        /// Gets or sets the costs by lease.
        /// </summary>
        public decimal Costs { get; set; }

        /// <summary>
        /// Gets the net profit.
        /// </summary>
        public decimal NetProfit => Revenue - Costs;
    }

    /// <summary>
    /// Represents a governmental report.
    /// </summary>
    public class GovernmentalReport : Report
    {
        /// <summary>
        /// Gets or sets the reporting agency.
        /// </summary>
        public string ReportingAgency { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the report format (e.g., "ONRR", "State Form").
        /// </summary>
        public string ReportFormat { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the production data.
        /// </summary>
        public GovernmentalProductionData Production { get; set; } = new();

        /// <summary>
        /// Gets or sets the royalty data.
        /// </summary>
        public GovernmentalRoyaltyData Royalty { get; set; } = new();

        /// <summary>
        /// Gets or sets the tax data.
        /// </summary>
        public GovernmentalTaxData Taxes { get; set; } = new();
    }

    /// <summary>
    /// Represents a joint interest statement.
    /// </summary>
    public class JointInterestStatement : Report
    {
        /// <summary>
        /// Gets or sets the joint interest billing identifier.
        /// </summary>
        public string JIBId { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the operator.
        /// </summary>
        public string Operator { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the participants.
        /// </summary>
        public List<JIBParticipant> Participants { get; set; } = new();

        /// <summary>
        /// Gets or sets the charges.
        /// </summary>
        public List<JIBCharge> Charges { get; set; } = new();

        /// <summary>
        /// Gets or sets the credits.
        /// </summary>
        public List<JIBCredit> Credits { get; set; } = new();

        /// <summary>
        /// Gets the total charges.
        /// </summary>
        public decimal TotalCharges => Charges.Sum(c => c.Amount);

        /// <summary>
        /// Gets the total credits.
        /// </summary>
        public decimal TotalCredits => Credits.Sum(c => c.Amount);

        /// <summary>
        /// Gets the net amount.
        /// </summary>
        public decimal NetAmount => TotalCharges - TotalCredits;
    }

    /// <summary>
    /// Represents report summaries.
    /// </summary>
    public class ProductionReportSummary
    {
        public decimal TotalProduction { get; set; }
        public int ProducingDays { get; set; }
        public decimal AverageDailyProduction { get; set; }
    }

    public class InventoryReportSummary
    {
        public decimal OpeningInventory { get; set; }
        public decimal Receipts { get; set; }
        public decimal Deliveries { get; set; }
        public decimal ClosingInventory { get; set; }
    }

    public class AllocationReportSummary
    {
        public int WellsAllocated { get; set; }
        public int LeasesAllocated { get; set; }
        public decimal TotalAllocatedVolume { get; set; }
    }

    public class MeasurementReportSummary
    {
        public int MeasurementCount { get; set; }
        public decimal AverageAccuracy { get; set; }
        public int CalibrationsDue { get; set; }
    }

    public class CostReportSummary
    {
        public decimal TotalLiftingCosts { get; set; }
        public decimal TotalOperatingCosts { get; set; }
        public decimal TotalMarketingCosts { get; set; }
        public decimal TotalCosts => TotalLiftingCosts + TotalOperatingCosts + TotalMarketingCosts;
    }

    public class GovernmentalProductionData
    {
        public decimal OilProduction { get; set; }
        public decimal GasProduction { get; set; }
        public decimal WaterProduction { get; set; }
    }

    public class GovernmentalRoyaltyData
    {
        public decimal RoyaltyVolume { get; set; }
        public decimal RoyaltyValue { get; set; }
        public decimal RoyaltyRate { get; set; }
    }

    public class GovernmentalTaxData
    {
        public decimal SeveranceTax { get; set; }
        public decimal AdValoremTax { get; set; }
        public decimal TotalTaxes => SeveranceTax + AdValoremTax;
    }

    public class JIBParticipant
    {
        public string ParticipantId { get; set; } = string.Empty;
        public string CompanyName { get; set; } = string.Empty;
        public decimal WorkingInterest { get; set; }
        public decimal NetRevenueInterest { get; set; }
    }

    public class JIBCharge
    {
        public string ChargeId { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public decimal Amount { get; set; }
        public string Category { get; set; } = string.Empty;
    }

    public class JIBCredit
    {
        public string CreditId { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public decimal Amount { get; set; }
        public string Category { get; set; } = string.Empty;
    }
}

