CREATE TABLE "FIELD_PHASE"
(
    "FIELD_PHASE_ID" VARCHAR2(40) NOT NULL,
    "FIELD_ID" VARCHAR2(40),
    "PHASE" VARCHAR2(255),
    "PHASE_START_DATE" DATE,
    "PHASE_END_DATE" DATE,
    "PHASE_STATUS" VARCHAR2(50),
    "TRANSITION_REASON" VARCHAR2(255),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_QUALITY" VARCHAR2(40)
);
