CREATE TABLE "PRICE_INDEX"
(
    "PRICE_INDEX_ID" VARCHAR2(40) NOT NULL,
    "INDEX_NAME" VARCHAR2(255),
    "COMMODITY_TYPE" VARCHAR2(50),
    "PRICE_DATE" DATE,
    "PRICE_VALUE" NUMBER(18,2),
    "CURRENCY_CODE" VARCHAR2(255),
    "PRICING_POINT" VARCHAR2(255),
    "UNIT" VARCHAR2(255),
    "SOURCE" VARCHAR2(40),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE
);
