ALTER TABLE "ROYALTY_PAYMENT"
ADD CONSTRAINT FK_ROYALTY_PAYMENT_ROYALTY_INTEREST FOREIGN KEY ("ROYALTY_INTEREST_ID") REFERENCES "ROYALTY_INTEREST"("ROYALTY_INTEREST_ID");

ALTER TABLE "ROYALTY_PAYMENT"
ADD CONSTRAINT FK_ROYALTY_PAYMENT_REVENUE_TRANSACTION FOREIGN KEY ("REVENUE_TRANSACTION_ID") REFERENCES "REVENUE_TRANSACTION"("REVENUE_TRANSACTION_ID");

ALTER TABLE "ROYALTY_PAYMENT"
ADD CONSTRAINT FK_ROYALTY_PAYMENT_ROYALTY_OWNER_BA FOREIGN KEY ("ROYALTY_OWNER_BA_ID") REFERENCES "ROYALTY_OWNER_BA"("ROYALTY_OWNER_BA_ID");

ALTER TABLE "ROYALTY_PAYMENT"
ADD CONSTRAINT FK_ROYALTY_PAYMENT_PROPERTY FOREIGN KEY ("PROPERTY_ID") REFERENCES "PROPERTY"("PROPERTY_ID");
