CREATE TABLE "ROYALTY_INTEREST"
(
    "ROYALTY_INTEREST_ID" VARCHAR(40) NOT NULL,
    "PROPERTY_ID" VARCHAR(40),
    "ROYALTY_OWNER_BA_ID" VARCHAR(40),
    "INTEREST_TYPE" VARCHAR(50),
    "INTEREST_PERCENTAGE" NUMERIC(18,6),
    "ROYALTY_RATE" NUMERIC(18,2),
    "EFFECTIVE_DATE" TIMESTAMP,
    "EXPIRY_DATE" TIMESTAMP,
    "DIVISION_ORDER_ID" VARCHAR(40),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_QUALITY" VARCHAR(40)
);
