CREATE TABLE "ROYALTY_STATEMENT"
(
    "ROYALTY_STATEMENT_ID" VARCHAR(40) NOT NULL,
    "ROYALTY_OWNER_BA_ID" VARCHAR(40),
    "PROPERTY_ID" VARCHAR(40),
    "STATEMENT_PERIOD_START" TIMESTAMP,
    "STATEMENT_PERIOD_END" TIMESTAMP,
    "TOTAL_ROYALTY_AMOUNT" NUMERIC(18,2),
    "TOTAL_DEDUCTIONS" NUMERIC(18,2),
    "NET_PAYMENT_AMOUNT" NUMERIC(18,2),
    "STATEMENT_DATE" TIMESTAMP,
    "STATUS" VARCHAR(50),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP
);
