raiserror ('CREATING TABLE NOMINATION', 10,1) with nowait

CREATE TABLE NOMINATION
(
    NOMINATION_ID NVARCHAR(40) NOT NULL,
    PERIOD_START DATETIME,
    PERIOD_END DATETIME,
    NOMINATED_VOLUME NUMERIC(18,2),
    STATUS NVARCHAR(50),
    SUBMISSION_DATE DATETIME,
    APPROVAL_DATE DATETIME,
    APPROVED_BY NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
