raiserror ('CREATING TABLE PRODUCTION_AVAIL', 10,1) with nowait

CREATE TABLE PRODUCTION_AVAIL
(
    PRODUCTION_AVAIL_ID NVARCHAR(40) NOT NULL,
    PROPERTY_ID NVARCHAR(40),
    AVAIL_DATE DATETIME,
    ESTIMATED_VOLUME NUMERIC(18,2),
    AVAILABLE_FOR_DELIVERY NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
