CREATE TABLE `CENTRIFUGAL_COMPRESSOR_PROPERTIES`
(
    `CENTRIFUGAL_COMPRESSOR_PROPERTIES_ID` VARCHAR(40) NOT NULL,
    `COMPRESSOR_OPERATING_CONDITIONS_ID` VARCHAR(40),
    `POLYTROPIC_EFFICIENCY` DECIMAL(18,2),
    `SPECIFIC_HEAT_RATIO` DECIMAL(18,6),
    `NUMBER_OF_STAGES` INT,
    `SPEED` DECIMAL(18,2),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_QUALITY` VARCHAR(40)
);
