CREATE TABLE `RECIPROCATING_COMPRESSOR_PROPERTIES`
(
    `RECIPROCATING_COMPRESSOR_PROPERTIES_ID` VARCHAR(40) NOT NULL,
    `COMPRESSOR_OPERATING_CONDITIONS_ID` VARCHAR(40),
    `CYLINDER_DIAMETER` DECIMAL(18,2),
    `STROKE_LENGTH` DECIMAL(18,2),
    `ROTATIONAL_SPEED` DECIMAL(18,2),
    `NUMBER_OF_CYLINDERS` INT,
    `VOLUMETRIC_EFFICIENCY` DECIMAL(18,2),
    `CLEARANCE_FACTOR` DECIMAL(18,2),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_QUALITY` VARCHAR(40)
);
