CREATE TABLE `ECONOMIC_CASH_FLOW`
(
    `ECONOMIC_CASH_FLOW_ID` VARCHAR(40) NOT NULL,
    `ECONOMIC_ANALYSIS_ID` VARCHAR(40),
    `PERIOD` INT,
    `AMOUNT` DECIMAL(18,2),
    `DESCRIPTION` VARCHAR(2000),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_QUALITY` VARCHAR(40)
);
