ALTER TABLE `FORECAST_POINT`
ADD CONSTRAINT FK_FORECAST_POINT_PRODUCTION_FORECAST FOREIGN KEY (`PRODUCTION_FORECAST_ID`) REFERENCES `PRODUCTION_FORECAST`(`PRODUCTION_FORECAST_ID`);

ALTER TABLE `FORECAST_POINT`
ADD CONSTRAINT FK_FORECAST_POINT_AREA FOREIGN KEY (`AREA_ID`) REFERENCES `AREA`(`AREA_ID`);

ALTER TABLE `FORECAST_POINT`
ADD CONSTRAINT FK_FORECAST_POINT_BUSINESS_ASSOCIATE FOREIGN KEY (`BUSINESS_ASSOCIATE_ID`) REFERENCES `BUSINESS_ASSOCIATE`(`BUSINESS_ASSOCIATE_ID`);
