ALTER TABLE `PRODUCTION_FORECAST`
ADD CONSTRAINT FK_PRODUCTION_FORECAST_RESERVOIR_FORECAST_PROPERTIES FOREIGN KEY (`RESERVOIR_FORECAST_PROPERTIES_ID`) REFERENCES `RESERVOIR_FORECAST_PROPERTIES`(`RESERVOIR_FORECAST_PROPERTIES_ID`);

ALTER TABLE `PRODUCTION_FORECAST`
ADD CONSTRAINT FK_PRODUCTION_FORECAST_AREA FOREIGN KEY (`AREA_ID`) REFERENCES `AREA`(`AREA_ID`);

ALTER TABLE `PRODUCTION_FORECAST`
ADD CONSTRAINT FK_PRODUCTION_FORECAST_BUSINESS_ASSOCIATE FOREIGN KEY (`BUSINESS_ASSOCIATE_ID`) REFERENCES `BUSINESS_ASSOCIATE`(`BUSINESS_ASSOCIATE_ID`);
