CREATE TABLE `PRODUCTION_FORECAST`
(
    `FORECAST_ID` VARCHAR(40),
    `WELL_UWI` VARCHAR(255),
    `FIELD_ID` VARCHAR(40),
    `FORECAST_NAME` VARCHAR(255),
    `FORECAST_TYPE` VARCHAR(50),
    `FORECAST_START_DATE` DATETIME,
    `FORECAST_END_DATE` DATETIME,
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30)
);
