CREATE TABLE `SALES_AGREEMENT`
(
    `AGREEMENT_ID` VARCHAR(40),
    `AGREEMENT_NAME` VARCHAR(255),
    `SELLER_BA_ID` VARCHAR(40),
    `PURCHASER_BA_ID` VARCHAR(40),
    `EFFECTIVE_DATE` DATETIME,
    `EXPIRATION_DATE` DATETIME,
    `PRICING_METHOD` VARCHAR(255),
    `BASE_PRICE` DECIMAL(18,2),
    `PRICE_INDEX` VARCHAR(255),
    `DIFFERENTIAL` DECIMAL(18,2),
    `PAYMENT_TERMS_DAYS` INT,
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME
);
