CREATE TABLE `TRANSPORTATION_AGREEMENT`
(
    `AGREEMENT_ID` VARCHAR(40),
    `CARRIER_BA_ID` VARCHAR(40),
    `ORIGIN_POINT` VARCHAR(255),
    `DESTINATION_POINT` VARCHAR(255),
    `EFFECTIVE_DATE` DATETIME,
    `EXPIRATION_DATE` DATETIME,
    `TARIFF_RATE` DECIMAL(18,2),
    `MINIMUM_VOLUME_COMMITMENT` DECIMAL(18,2),
    `MAXIMUM_CAPACITY` DECIMAL(18,2),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME
);
