CREATE TABLE "GAS_LIFT_PERFORMANCE"
(
    "PERFORMANCE_ID" VARCHAR2(40),
    "WELL_UWI" VARCHAR2(255),
    "PERFORMANCE_DATE" DATE,
    "GAS_INJECTION_RATE" VARCHAR2(255),
    "PRODUCTION_RATE" VARCHAR2(255),
    "GAS_LIQUID_RATIO" VARCHAR2(255),
    "EFFICIENCY" VARCHAR2(255),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30)
);
