CREATE TABLE "GAS_LIFT_VALVE"
(
    "GAS_LIFT_VALVE_ID" VARCHAR2(40) NOT NULL,
    "GAS_LIFT_DESIGN_ID" VARCHAR2(40),
    "DEPTH" NUMBER(18,2),
    "PORT_SIZE" NUMBER(18,2),
    "OPENING_PRESSURE" NUMBER(18,2),
    "CLOSING_PRESSURE" NUMBER(18,2),
    "VALVE_TYPE" VARCHAR2(50),
    "TEMPERATURE" NUMBER(18,2),
    "GAS_INJECTION_RATE" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_QUALITY" VARCHAR2(40)
);
