CREATE TABLE "GAS_LIFT_DESIGN"
(
    "DESIGN_ID" VARCHAR2(40),
    "WELL_UWI" VARCHAR2(255),
    "DESIGN_DATE" DATE,
    "NUMBER_OF_VALVES" VARCHAR2(255),
    "TOTAL_GAS_INJECTION_RATE" VARCHAR2(255),
    "EXPECTED_PRODUCTION_RATE" VARCHAR2(255),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30)
);
