CREATE TABLE `EXCHANGE_COMMITMENT`
(
    `EXCHANGE_COMMITMENT_ID` VARCHAR(40) NOT NULL,
    `EXCHANGE_CONTRACT_ID` VARCHAR(40),
    `COMMITMENT_TYPE` VARCHAR(50),
    `COMMITTED_VOLUME` DECIMAL(18,2),
    `ACTUAL_VOLUME_DELIVERED` DECIMAL(18,2),
    `DELIVERY_PERIOD_START` DATETIME,
    `DELIVERY_PERIOD_END` DATETIME,
    `STATUS` VARCHAR(50),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME
);
