ALTER TABLE ACCOUNTING_METHOD
ADD CONSTRAINT FK_ACCOUNTING_METHOD_FIELD FOREIGN KEY (FIELD_ID) REFERENCES FIELD(FIELD_ID);

ALTER TABLE ACCOUNTING_METHOD
ADD CONSTRAINT FK_ACCOUNTING_METHOD_COST_CENTER FOREIGN KEY (COST_CENTER_ID) REFERENCES COST_CENTER(COST_CENTER_ID);
