raiserror ('CREATING TABLE ACCOUNTING_METHOD', 10,1) with nowait

CREATE TABLE ACCOUNTING_METHOD
(
    ACCOUNTING_METHOD_ID NVARCHAR(40) NOT NULL,
    ROW_QUALITY NVARCHAR(40),
    FIELD_ID NVARCHAR(40),
    COST_CENTER_ID NVARCHAR(40),
    METHOD_TYPE NVARCHAR(50),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
