ALTER TABLE ACCOUNTING_COST
ADD CONSTRAINT FK_ACCOUNTING_COST_FINANCE FOREIGN KEY (FINANCE_ID) REFERENCES FINANCE(FINANCE_ID);

ALTER TABLE ACCOUNTING_COST
ADD CONSTRAINT FK_ACCOUNTING_COST_PROPERTY FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID);

ALTER TABLE ACCOUNTING_COST
ADD CONSTRAINT FK_ACCOUNTING_COST_WELL FOREIGN KEY (WELL_ID) REFERENCES WELL(WELL_ID);

ALTER TABLE ACCOUNTING_COST
ADD CONSTRAINT FK_ACCOUNTING_COST_FIELD FOREIGN KEY (FIELD_ID) REFERENCES FIELD(FIELD_ID);

ALTER TABLE ACCOUNTING_COST
ADD CONSTRAINT FK_ACCOUNTING_COST_POOL FOREIGN KEY (POOL_ID) REFERENCES POOL(POOL_ID);
