raiserror ('CREATING TABLE ACCOUNTING_COST', 10,1) with nowait

CREATE TABLE ACCOUNTING_COST
(
    ACCOUNTING_COST_ID NVARCHAR(40) NOT NULL,
    FINANCE_ID NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    PROPERTY_ID NVARCHAR(40),
    WELL_ID NVARCHAR(40),
    FIELD_ID NVARCHAR(40),
    POOL_ID NVARCHAR(40),
    COST_TYPE NVARCHAR(50),
    COST_CATEGORY NVARCHAR(255),
    AMOUNT NUMERIC(18,2) NOT NULL,
    COST_DATE DATETIME,
    IS_CAPITALIZED NVARCHAR(255),
    IS_EXPENSED NVARCHAR(255),
    DRY_HOLE_FLAG NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
