raiserror ('CREATING TABLE ACCOUNTING_AMORTIZATION', 10,1) with nowait

CREATE TABLE ACCOUNTING_AMORTIZATION
(
    ACCOUNTING_AMORTIZATION_ID NVARCHAR(40) NOT NULL,
    PROPERTY_ID NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    WELL_ID NVARCHAR(40),
    POOL_ID NVARCHAR(40),
    FIELD_ID NVARCHAR(40),
    PERIOD_START_DATE DATETIME,
    PERIOD_END_DATE DATETIME,
    CAPITALIZED_COST NUMERIC(18,2) NOT NULL,
    PRODUCTION_BOE NUMERIC(18,2),
    TOTAL_RESERVES_BOE NUMERIC(18,2),
    AMORTIZATION_AMOUNT NUMERIC(18,2) NOT NULL,
    AMORTIZATION_METHOD NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
