raiserror ('CREATING TABLE ACTUAL_DELIVERY', 10,1) with nowait

CREATE TABLE ACTUAL_DELIVERY
(
    ACTUAL_DELIVERY_ID NVARCHAR(40) NOT NULL,
    DELIVERY_DATE DATETIME,
    ACTUAL_VOLUME NUMERIC(18,2),
    DELIVERY_POINT NVARCHAR(255),
    ALLOCATION_METHOD NVARCHAR(255),
    RUN_TICKET_NUMBER NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
