raiserror ('CREATING TABLE AFE', 10,1) with nowait

CREATE TABLE AFE
(
    AFE_ID NVARCHAR(40) NOT NULL,
    AFE_NUMBER NVARCHAR(255),
    AFE_NAME NVARCHAR(255),
    PROPERTY_ID NVARCHAR(40),
    FIELD_ID NVARCHAR(40),
    ESTIMATED_COST NUMERIC(18,2),
    ACTUAL_COST NUMERIC(18,2),
    STATUS NVARCHAR(50),
    APPROVAL_DATE DATETIME,
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
