ALTER TABLE ALLOCATION_DETAIL
ADD CONSTRAINT FK_ALLOCATION_DETAIL_ALLOCATION_RESULT FOREIGN KEY (ALLOCATION_RESULT_ID) REFERENCES ALLOCATION_RESULT(ALLOCATION_RESULT_ID);

ALTER TABLE ALLOCATION_DETAIL
ADD CONSTRAINT FK_ALLOCATION_DETAIL_ENTITY FOREIGN KEY (ENTITY_ID) REFERENCES ENTITY(ENTITY_ID);

ALTER TABLE ALLOCATION_DETAIL
ADD CONSTRAINT FK_ALLOCATION_DETAIL_AllocationRequest FOREIGN KEY (AllocationRequest_ID) REFERENCES AllocationRequest(AllocationRequest_ID);
