raiserror ('CREATING TABLE AMORTIZATION_RECORD', 10,1) with nowait

CREATE TABLE AMORTIZATION_RECORD
(
    AMORTIZATION_RECORD_ID NVARCHAR(40) NOT NULL,
    PROPERTY_ID NVARCHAR(40),
    COST_CENTER_ID NVARCHAR(40),
    PERIOD_START_DATE DATETIME,
    PERIOD_END_DATE DATETIME,
    NET_CAPITALIZED_COSTS NUMERIC(18,2),
    TOTAL_RESERVES_BOE NUMERIC(18,2),
    PRODUCTION_BOE NUMERIC(18,2),
    AMORTIZATION_AMOUNT NUMERIC(18,2),
    ACCOUNTING_METHOD NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
