raiserror ('CREATING TABLE AR_CREDIT_MEMO', 10,1) with nowait

CREATE TABLE AR_CREDIT_MEMO
(
    AR_CREDIT_MEMO_ID NVARCHAR(40) NOT NULL,
    AR_INVOICE_ID NVARCHAR(40),
    CREDIT_MEMO_NUMBER NVARCHAR(255),
    CREDIT_MEMO_DATE DATETIME,
    CREDIT_AMOUNT NUMERIC(18,2),
    REASON NVARCHAR(255),
    STATUS NVARCHAR(50),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
