ALTER TABLE ASSET_RETIREMENT_OBLIGATION
ADD CONSTRAINT FK_ASSET_RETIREMENT_OBLIGATION_ARO FOREIGN KEY (ARO_ID) REFERENCES ARO(ARO_ID);

ALTER TABLE ASSET_RETIREMENT_OBLIGATION
ADD CONSTRAINT FK_ASSET_RETIREMENT_OBLIGATION_FIELD FOREIGN KEY (FIELD_ID) REFERENCES FIELD(FIELD_ID);

ALTER TABLE ASSET_RETIREMENT_OBLIGATION
ADD CONSTRAINT FK_ASSET_RETIREMENT_OBLIGATION_WELL FOREIGN KEY (WELL_ID) REFERENCES WELL(WELL_ID);

ALTER TABLE ASSET_RETIREMENT_OBLIGATION
ADD CONSTRAINT FK_ASSET_RETIREMENT_OBLIGATION_FACILITY FOREIGN KEY (FACILITY_ID) REFERENCES FACILITY(FACILITY_ID);
