raiserror ('CREATING TABLE ASSET_RETIREMENT_OBLIGATION', 10,1) with nowait

CREATE TABLE ASSET_RETIREMENT_OBLIGATION
(
    ARO_ID NVARCHAR(40),
    FIELD_ID NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    WELL_ID NVARCHAR(40),
    FACILITY_ID NVARCHAR(40),
    ESTIMATED_COST NUMERIC(18,2) NOT NULL,
    ESTIMATED_RETIREMENT_DATE DATETIME,
    DISCOUNT_RATE NUMERIC(18,2),
    PRESENT_VALUE NUMERIC(18,2),
    ACCRETION_EXPENSE NUMERIC(18,2),
    STATUS NVARCHAR(50),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
