raiserror ('CREATING TABLE CEILING_TEST_CALCULATION', 10,1) with nowait

CREATE TABLE CEILING_TEST_CALCULATION
(
    CEILING_TEST_CALCULATION_ID NVARCHAR(40) NOT NULL,
    PROPERTY_ID NVARCHAR(40),
    CALCULATION_DATE DATETIME,
    NET_CAPITALIZED_COST NUMERIC(18,2),
    DISCOUNTED_FUTURE_NET_CASH_FLOWS NUMERIC(18,2),
    CEILING_VALUE NUMERIC(18,2),
    IMPAIRMENT_AMOUNT NUMERIC(18,2),
    DISCOUNT_RATE NUMERIC(18,2),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
