raiserror ('CREATING TABLE CONTACT_INFORMATION', 10,1) with nowait

CREATE TABLE CONTACT_INFORMATION
(
    CONTACT_INFORMATION_ID NVARCHAR(40) NOT NULL,
    OWNER_INFORMATION_ID NVARCHAR(40),
    PHONE_NUMBER NVARCHAR(255),
    EMAIL_ADDRESS NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
