ALTER TABLE COST_ALLOCATION
ADD CONSTRAINT FK_COST_ALLOCATION_COST_TRANSACTION FOREIGN KEY (COST_TRANSACTION_ID) REFERENCES COST_TRANSACTION(COST_TRANSACTION_ID);

ALTER TABLE COST_ALLOCATION
ADD CONSTRAINT FK_COST_ALLOCATION_PROPERTY FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID);

ALTER TABLE COST_ALLOCATION
ADD CONSTRAINT FK_COST_ALLOCATION_WELL FOREIGN KEY (WELL_ID) REFERENCES WELL(WELL_ID);

ALTER TABLE COST_ALLOCATION
ADD CONSTRAINT FK_COST_ALLOCATION_COST_CENTER FOREIGN KEY (COST_CENTER_ID) REFERENCES COST_CENTER(COST_CENTER_ID);
