raiserror ('CREATING TABLE COST_CENTER', 10,1) with nowait

CREATE TABLE COST_CENTER
(
    COST_CENTER_ID NVARCHAR(40) NOT NULL,
    COST_CENTER_NAME NVARCHAR(255),
    FIELD_ID NVARCHAR(40),
    ACCOUNTING_METHOD NVARCHAR(255),
    TOTAL_CAPITALIZED_COSTS NUMERIC(18,2),
    ACCUMULATED_AMORTIZATION NUMERIC(18,2),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
