raiserror ('CREATING TABLE COST_REPORT_SUMMARY', 10,1) with nowait

CREATE TABLE COST_REPORT_SUMMARY
(
    COST_REPORT_SUMMARY_ID NVARCHAR(40) NOT NULL,
    TOTAL_LIFTING_COSTS NUMERIC(18,2),
    TOTAL_OPERATING_COSTS NUMERIC(18,2),
    TOTAL_MARKETING_COSTS NUMERIC(18,2),
    TOTAL_COSTS NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
