raiserror ('CREATING TABLE COST_ALLOCATION', 10,1) with nowait

CREATE TABLE COST_ALLOCATION
(
    COST_ALLOCATION_ID NVARCHAR(40) NOT NULL,
    COST_TRANSACTION_ID NVARCHAR(40),
    PROPERTY_ID NVARCHAR(40),
    WELL_ID NVARCHAR(40),
    COST_CENTER_ID NVARCHAR(40),
    ALLOCATED_AMOUNT NUMERIC(18,2),
    ALLOCATION_PERCENTAGE NUMERIC(18,6),
    ALLOCATION_METHOD NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
