raiserror ('CREATING TABLE CRUDE_OIL_INVENTORY_TRANSACTION', 10,1) with nowait

CREATE TABLE CRUDE_OIL_INVENTORY_TRANSACTION
(
    TRANSACTION_ID NVARCHAR(40),
    INVENTORY_ID NVARCHAR(40),
    TRANSACTION_DATE DATETIME,
    TRANSACTION_TYPE NVARCHAR(50),
    VOLUME NUMERIC(18,2),
    UNIT_COST NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
