raiserror ('CREATING TABLE CRUDE_OIL_SPECIFICATIONS', 10,1) with nowait

CREATE TABLE CRUDE_OIL_SPECIFICATIONS
(
    SPECIFICATIONS_ID NVARCHAR(40),
    AGREEMENT_ID NVARCHAR(40),
    MINIMUM_API_GRAVITY NUMERIC(18,2),
    MAXIMUM_API_GRAVITY NUMERIC(18,2),
    MAXIMUM_SULFUR_CONTENT NUMERIC(18,2),
    MAXIMUM_BSW NUMERIC(18,2),
    MAXIMUM_WATER_CONTENT NUMERIC(18,2),
    MAXIMUM_SALT_CONTENT NUMERIC(18,2),
    MAXIMUM_VISCOSITY NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME
);
