ALTER TABLE CRUDE_OIL_PROPERTIES
ADD CONSTRAINT FK_CRUDE_OIL_PROPERTIES_PROPERTIES FOREIGN KEY (PROPERTIES_ID) REFERENCES PROPERTIES(PROPERTIES_ID);

ALTER TABLE CRUDE_OIL_PROPERTIES
ADD CONSTRAINT FK_CRUDE_OIL_PROPERTIES_INVENTORY FOREIGN KEY (INVENTORY_ID) REFERENCES INVENTORY(INVENTORY_ID);
