raiserror ('CREATING TABLE CRUDE_OIL_INVENTORY', 10,1) with nowait

CREATE TABLE CRUDE_OIL_INVENTORY
(
    INVENTORY_ID NVARCHAR(40),
    PROPERTY_OR_LEASE_ID NVARCHAR(40),
    TANK_BATTERY_ID NVARCHAR(40),
    INVENTORY_DATE DATETIME,
    VOLUME NUMERIC(18,2),
    UNIT_COST NUMERIC(18,2),
    VALUATION_METHOD NVARCHAR(255),
    MARKET_PRICE NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
