raiserror ('CREATING TABLE DEPLETION_CALCULATION', 10,1) with nowait

CREATE TABLE DEPLETION_CALCULATION
(
    DEPLETION_ID NVARCHAR(40),
    PROPERTY_ID NVARCHAR(40),
    WELL_ID NVARCHAR(40),
    POOL_ID NVARCHAR(40),
    FIELD_ID NVARCHAR(40),
    DEPLETION_METHOD NVARCHAR(255),
    COST_BASIS NUMERIC(18,2),
    ESTIMATED_RESERVES NUMERIC(18,2),
    PRODUCTION NUMERIC(18,2),
    DEPLETION_RATE NUMERIC(18,2),
    DEPLETION_AMOUNT NUMERIC(18,2),
    PERCENTAGE_RATE NUMERIC(18,6),
    PERIOD_START_DATE DATETIME,
    PERIOD_END_DATE DATETIME,
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    ROW_ID NVARCHAR(40)
);
