ALTER TABLE DIVISION_ORDER
ADD CONSTRAINT FK_DIVISION_ORDER_PROPERTY_OR_LEASE FOREIGN KEY (PROPERTY_OR_LEASE_ID) REFERENCES PROPERTY_OR_LEASE(PROPERTY_OR_LEASE_ID);

ALTER TABLE DIVISION_ORDER
ADD CONSTRAINT FK_DIVISION_ORDER_OWNER FOREIGN KEY (OWNER_ID) REFERENCES OWNER(OWNER_ID);
