raiserror ('CREATING TABLE EXCHANGE_PRICING_TERMS', 10,1) with nowait

CREATE TABLE EXCHANGE_PRICING_TERMS
(
    EXCHANGE_PRICING_TERMS_ID NVARCHAR(40) NOT NULL,
    EXCHANGE_CONTRACT_ID NVARCHAR(40),
    BASE_PRICE_INDEX NVARCHAR(255),
    LOCATION_DIFFERENTIAL NUMERIC(18,2),
    QUALITY_DIFFERENTIAL NUMERIC(18,2),
    TIME_DIFFERENTIAL NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
