raiserror ('CREATING TABLE EXCHANGE_CONTRACT', 10,1) with nowait

CREATE TABLE EXCHANGE_CONTRACT
(
    CONTRACT_ID NVARCHAR(40),
    CONTRACT_NAME NVARCHAR(255),
    CONTRACT_TYPE NVARCHAR(50),
    PARTIES_JSON NVARCHAR(255),
    EFFECTIVE_DATE DATETIME,
    EXPIRATION_DATE DATETIME,
    EXCHANGE_TERMS_JSON NVARCHAR(255),
    DELIVERY_POINTS_JSON NVARCHAR(255),
    PRICING_TERMS_JSON NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
