raiserror ('CREATING TABLE EXCHANGE_DELIVERY_POINT', 10,1) with nowait

CREATE TABLE EXCHANGE_DELIVERY_POINT
(
    EXCHANGE_DELIVERY_POINT_ID NVARCHAR(40) NOT NULL,
    EXCHANGE_CONTRACT_ID NVARCHAR(40),
    DELIVERY_POINT_NAME NVARCHAR(255),
    LOCATION NVARCHAR(255),
    IS_RECEIPT_POINT NVARCHAR(255),
    IS_DELIVERY_POINT NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
