raiserror ('CREATING TABLE EXCHANGE_TERMS', 10,1) with nowait

CREATE TABLE EXCHANGE_TERMS
(
    EXCHANGE_TERMS_ID NVARCHAR(40) NOT NULL,
    EXCHANGE_CONTRACT_ID NVARCHAR(40),
    EXCHANGE_RATIO NUMERIC(18,6),
    MINIMUM_VOLUME NUMERIC(18,2),
    MAXIMUM_VOLUME NUMERIC(18,2),
    QUALITY_SPECIFICATIONS NVARCHAR(40),
    NOTICE_PERIOD_DAYS INT,
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
