raiserror ('CREATING TABLE GL_ACCOUNT', 10,1) with nowait

CREATE TABLE GL_ACCOUNT
(
    GL_ACCOUNT_ID NVARCHAR(40) NOT NULL,
    ACCOUNT_NUMBER NVARCHAR(255),
    ACCOUNT_NAME NVARCHAR(255),
    ACCOUNT_TYPE NVARCHAR(50),
    PARENT_ACCOUNT_ID NVARCHAR(40),
    NORMAL_BALANCE NVARCHAR(255),
    OPENING_BALANCE NUMERIC(18,2),
    CURRENT_BALANCE NUMERIC(18,2),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
