raiserror ('CREATING TABLE GL_ENTRY', 10,1) with nowait

CREATE TABLE GL_ENTRY
(
    GL_ENTRY_ID NVARCHAR(40) NOT NULL,
    JOURNAL_ENTRY_ID NVARCHAR(40),
    GL_ACCOUNT_ID NVARCHAR(40),
    ENTRY_DATE DATETIME,
    DEBIT_AMOUNT NUMERIC(18,2),
    CREDIT_AMOUNT NUMERIC(18,2),
    DESCRIPTION NVARCHAR(2000),
    REFERENCE_NUMBER NVARCHAR(255),
    SOURCE_MODULE NVARCHAR(40),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
