ALTER TABLE GL_ENTRY
ADD CONSTRAINT FK_GL_ENTRY_JOURNAL_ENTRY FOREIGN KEY (JOURNAL_ENTRY_ID) REFERENCES JOURNAL_ENTRY(JOURNAL_ENTRY_ID);

ALTER TABLE GL_ENTRY
ADD CONSTRAINT FK_GL_ENTRY_GL_ACCOUNT FOREIGN KEY (GL_ACCOUNT_ID) REFERENCES GL_ACCOUNT(GL_ACCOUNT_ID);
