raiserror ('CREATING TABLE GOVERNMENTAL_REPORT', 10,1) with nowait

CREATE TABLE GOVERNMENTAL_REPORT
(
    GOVERNMENTAL_REPORT_ID NVARCHAR(40) NOT NULL,
    REPORT_TYPE NVARCHAR(50),
    REPORT_PERIOD_START DATETIME,
    REPORT_PERIOD_END DATETIME,
    GENERATION_DATE DATETIME,
    GENERATED_BY NVARCHAR(255),
    REPORTING_AGENCY NVARCHAR(255),
    REPORT_FORMAT NVARCHAR(255),
    GOVERNMENTAL_PRODUCTION_DATA_ID NVARCHAR(40),
    GOVERNMENTAL_ROYALTY_DATA_ID NVARCHAR(40),
    GOVERNMENTAL_TAX_DATA_ID NVARCHAR(40),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
