raiserror ('CREATING TABLE IMBALANCE_STATEMENT', 10,1) with nowait

CREATE TABLE IMBALANCE_STATEMENT
(
    IMBALANCE_STATEMENT_ID NVARCHAR(40) NOT NULL,
    STATEMENT_PERIOD_START DATETIME,
    STATEMENT_PERIOD_END DATETIME,
    IMBALANCE_RECONCILIATION_ID NVARCHAR(40),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
