raiserror ('CREATING TABLE IMBALANCE_SUMMARY', 10,1) with nowait

CREATE TABLE IMBALANCE_SUMMARY
(
    IMBALANCE_SUMMARY_ID NVARCHAR(40) NOT NULL,
    IMBALANCE_STATEMENT_ID NVARCHAR(40),
    SUMMARY_TYPE NVARCHAR(50),
    TOTAL_VOLUME NUMERIC(18,2),
    TRANSACTION_COUNT INT,
    AVERAGE_DAILY_VOLUME NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
