raiserror ('CREATING TABLE IMBALANCE_RECONCILIATION', 10,1) with nowait

CREATE TABLE IMBALANCE_RECONCILIATION
(
    IMBALANCE_RECONCILIATION_ID NVARCHAR(40) NOT NULL,
    RECONCILIATION_DATE DATETIME,
    TOTAL_IMBALANCE_BEFORE NUMERIC(18,2),
    TOTAL_ADJUSTMENTS NUMERIC(18,2),
    TOTAL_IMBALANCE_AFTER NUMERIC(18,2),
    RECONCILED_BY NVARCHAR(255),
    NOTES NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
