raiserror ('CREATING TABLE IMPAIRMENT_RECORD', 10,1) with nowait

CREATE TABLE IMPAIRMENT_RECORD
(
    IMPAIRMENT_RECORD_ID NVARCHAR(40) NOT NULL,
    PROPERTY_ID NVARCHAR(40),
    COST_CENTER_ID NVARCHAR(40),
    IMPAIRMENT_DATE DATETIME,
    IMPAIRMENT_AMOUNT NUMERIC(18,2),
    REASON NVARCHAR(255),
    IMPAIRMENT_TYPE NVARCHAR(50),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
