raiserror ('CREATING TABLE INVENTORY_ADJUSTMENT', 10,1) with nowait

CREATE TABLE INVENTORY_ADJUSTMENT
(
    INVENTORY_ADJUSTMENT_ID NVARCHAR(40) NOT NULL,
    INVENTORY_ITEM_ID NVARCHAR(40),
    ADJUSTMENT_DATE DATETIME,
    ADJUSTMENT_TYPE NVARCHAR(50),
    QUANTITY_ADJUSTMENT NUMERIC(18,2),
    UNIT_COST_ADJUSTMENT NUMERIC(18,2),
    REASON NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
