raiserror ('CREATING TABLE INVENTORY_ITEM', 10,1) with nowait

CREATE TABLE INVENTORY_ITEM
(
    INVENTORY_ITEM_ID NVARCHAR(40) NOT NULL,
    ITEM_NUMBER NVARCHAR(255),
    ITEM_NAME NVARCHAR(255),
    ITEM_TYPE NVARCHAR(50),
    UNIT_OF_MEASURE NVARCHAR(255),
    QUANTITY_ON_HAND NUMERIC(18,2),
    UNIT_COST NUMERIC(18,2),
    TOTAL_VALUE NUMERIC(18,2),
    VALUATION_METHOD NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
