raiserror ('CREATING TABLE INVOICE', 10,1) with nowait

CREATE TABLE INVOICE
(
    INVOICE_ID NVARCHAR(40) NOT NULL,
    INVOICE_NUMBER NVARCHAR(255),
    CUSTOMER_BA_ID NVARCHAR(40),
    INVOICE_DATE DATETIME,
    DUE_DATE DATETIME,
    SUBTOTAL NUMERIC(18,2),
    TAX_AMOUNT NUMERIC(18,2),
    TOTAL_AMOUNT NUMERIC(18,2),
    PAID_AMOUNT NUMERIC(18,2),
    BALANCE_DUE NUMERIC(18,2),
    STATUS NVARCHAR(50),
    CURRENCY_CODE NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
