raiserror ('CREATING TABLE INVOICE_PAYMENT', 10,1) with nowait

CREATE TABLE INVOICE_PAYMENT
(
    INVOICE_PAYMENT_ID NVARCHAR(40) NOT NULL,
    INVOICE_ID NVARCHAR(40),
    PAYMENT_DATE DATETIME,
    PAYMENT_AMOUNT NUMERIC(18,2),
    PAYMENT_METHOD NVARCHAR(255),
    REFERENCE_NUMBER NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
