raiserror ('CREATING TABLE INVOICE_LINE_ITEM', 10,1) with nowait

CREATE TABLE INVOICE_LINE_ITEM
(
    INVOICE_LINE_ITEM_ID NVARCHAR(40) NOT NULL,
    INVOICE_ID NVARCHAR(40),
    LINE_NUMBER INT,
    ITEM_DESCRIPTION NVARCHAR(2000),
    QUANTITY NUMERIC(18,2),
    UNIT_PRICE NUMERIC(18,2),
    LINE_TOTAL NUMERIC(18,2),
    GL_ACCOUNT_ID NVARCHAR(40),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
