raiserror ('CREATING TABLE JIB_PARTICIPANT', 10,1) with nowait

CREATE TABLE JIB_PARTICIPANT
(
    JIB_PARTICIPANT_ID NVARCHAR(40) NOT NULL,
    JOINT_INTEREST_STATEMENT_ID NVARCHAR(40),
    COMPANY_NAME NVARCHAR(255),
    WORKING_INTEREST NUMERIC(18,2),
    NET_REVENUE_INTEREST NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
