raiserror ('CREATING TABLE JIB_COST_ALLOCATION', 10,1) with nowait

CREATE TABLE JIB_COST_ALLOCATION
(
    JIB_COST_ALLOCATION_ID NVARCHAR(40) NOT NULL,
    JIB_ID NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    FINANCE_ID NVARCHAR(40),
    COST_CATEGORY NVARCHAR(255),
    GROSS_COST NUMERIC(18,2) NOT NULL,
    WORKING_INTEREST_SHARE NUMERIC(18,2),
    NET_COST NUMERIC(18,2) NOT NULL,
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
