raiserror ('CREATING TABLE JIB_CREDIT', 10,1) with nowait

CREATE TABLE JIB_CREDIT
(
    JIB_CREDIT_ID NVARCHAR(40) NOT NULL,
    JOINT_INTEREST_STATEMENT_ID NVARCHAR(40),
    DESCRIPTION NVARCHAR(2000),
    AMOUNT NUMERIC(18,2),
    CATEGORY NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
