ALTER TABLE JIB_COST_ALLOCATION
ADD CONSTRAINT FK_JIB_COST_ALLOCATION_JIB FOREIGN KEY (JIB_ID) REFERENCES JIB(JIB_ID);

ALTER TABLE JIB_COST_ALLOCATION
ADD CONSTRAINT FK_JIB_COST_ALLOCATION_FINANCE FOREIGN KEY (FINANCE_ID) REFERENCES FINANCE(FINANCE_ID);
