ALTER TABLE JOA_INTEREST
ADD CONSTRAINT FK_JOA_INTEREST_JOA FOREIGN KEY (JOA_ID) REFERENCES JOA(JOA_ID);

ALTER TABLE JOA_INTEREST
ADD CONSTRAINT FK_JOA_INTEREST_INTEREST_OWNER_BA FOREIGN KEY (INTEREST_OWNER_BA_ID) REFERENCES INTEREST_OWNER_BA(INTEREST_OWNER_BA_ID);
