raiserror ('CREATING TABLE JOIB_LINE_ITEM', 10,1) with nowait

CREATE TABLE JOIB_LINE_ITEM
(
    JOIB_LINE_ITEM_ID NVARCHAR(40) NOT NULL,
    JOINT_INTEREST_BILL_ID NVARCHAR(40),
    LINE_ITEM_NUMBER NVARCHAR(255),
    COST_CATEGORY NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    AMOUNT NUMERIC(18,2),
    PROPERTY_ID NVARCHAR(40),
    WELL_ID NVARCHAR(40),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
