raiserror ('CREATING TABLE JOINT_OPERATING_AGREEMENT', 10,1) with nowait

CREATE TABLE JOINT_OPERATING_AGREEMENT
(
    JOA_ID NVARCHAR(40),
    JOA_NUMBER NVARCHAR(255),
    JOA_NAME NVARCHAR(255),
    FIELD_ID NVARCHAR(40),
    OPERATOR_BA_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    STATUS NVARCHAR(50),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
