raiserror ('CREATING TABLE JOINT_INTEREST_BILL', 10,1) with nowait

CREATE TABLE JOINT_INTEREST_BILL
(
    JIB_ID NVARCHAR(40),
    INTEREST_SET_ID NVARCHAR(40),
    FIELD_ID NVARCHAR(40),
    OPERATOR_ID NVARCHAR(40),
    BILL_PERIOD_START_DATE DATETIME,
    BILL_PERIOD_END_DATE DATETIME,
    TOTAL_BILL_AMOUNT NUMERIC(18,2) NOT NULL,
    WORKING_INTEREST_SHARE NUMERIC(18,2),
    NET_AMOUNT_DUE NUMERIC(18,2),
    BILL_STATUS NVARCHAR(50),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    ROW_ID NVARCHAR(40)
);
