raiserror ('CREATING TABLE JOURNAL_ENTRY', 10,1) with nowait

CREATE TABLE JOURNAL_ENTRY
(
    JOURNAL_ENTRY_ID NVARCHAR(40) NOT NULL,
    ENTRY_NUMBER NVARCHAR(255),
    ENTRY_DATE DATETIME,
    ENTRY_TYPE NVARCHAR(50),
    STATUS NVARCHAR(50),
    DESCRIPTION NVARCHAR(2000),
    REFERENCE_NUMBER NVARCHAR(255),
    SOURCE_MODULE NVARCHAR(40),
    TOTAL_DEBIT NUMERIC(18,2),
    TOTAL_CREDIT NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
