ALTER TABLE JOURNAL_ENTRY_LINE
ADD CONSTRAINT FK_JOURNAL_ENTRY_LINE_JOURNAL_ENTRY FOREIGN KEY (JOURNAL_ENTRY_ID) REFERENCES JOURNAL_ENTRY(JOURNAL_ENTRY_ID);

ALTER TABLE JOURNAL_ENTRY_LINE
ADD CONSTRAINT FK_JOURNAL_ENTRY_LINE_GL_ACCOUNT FOREIGN KEY (GL_ACCOUNT_ID) REFERENCES GL_ACCOUNT(GL_ACCOUNT_ID);
