raiserror ('CREATING TABLE LEASE_REPORT', 10,1) with nowait

CREATE TABLE LEASE_REPORT
(
    LEASE_REPORT_ID NVARCHAR(40) NOT NULL,
    REPORT_TYPE NVARCHAR(50),
    REPORT_PERIOD_START DATETIME,
    REPORT_PERIOD_END DATETIME,
    GENERATION_DATE DATETIME,
    GENERATED_BY NVARCHAR(255),
    LEASE_ID NVARCHAR(40),
    PRODUCTION_VOLUME NUMERIC(18,2),
    REVENUE NUMERIC(18,2),
    COSTS NUMERIC(18,2),
    NET_PROFIT NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
