raiserror ('CREATING TABLE MEASUREMENT_ACCURACY', 10,1) with nowait

CREATE TABLE MEASUREMENT_ACCURACY
(
    MEASUREMENT_ACCURACY_ID NVARCHAR(40) NOT NULL,
    MINIMUM_ACCURACY NUMERIC(18,2),
    MAXIMUM_ERROR NUMERIC(18,2),
    CALIBRATION_REQUIRED NVARCHAR(255),
    CALIBRATION_FREQUENCY_DAYS INT,
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
