raiserror ('CREATING TABLE MEASUREMENT_RECORD', 10,1) with nowait

CREATE TABLE MEASUREMENT_RECORD
(
    MEASUREMENT_ID NVARCHAR(40),
    MEASUREMENT_DATETIME DATETIME,
    MEASUREMENT_METHOD NVARCHAR(255),
    MEASUREMENT_STANDARD NVARCHAR(255),
    GROSS_VOLUME NUMERIC(18,2),
    BSW NUMERIC(18,2),
    NET_VOLUME NUMERIC(18,2),
    TEMPERATURE NUMERIC(18,2),
    PRESSURE NUMERIC(18,2),
    API_GRAVITY NUMERIC(18,2),
    CRUDE_OIL_PROPERTIES_ID NVARCHAR(40),
    ACCURACY NUMERIC(18,2),
    MEASUREMENT_DEVICE NVARCHAR(255),
    OPERATOR NVARCHAR(255),
    NOTES NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
