raiserror ('CREATING TABLE OIL_IMBALANCE', 10,1) with nowait

CREATE TABLE OIL_IMBALANCE
(
    IMBALANCE_ID NVARCHAR(40),
    PERIOD_START DATETIME,
    PERIOD_END DATETIME,
    NOMINATED_VOLUME NUMERIC(18,2),
    ACTUAL_VOLUME NUMERIC(18,2),
    IMBALANCE_AMOUNT NUMERIC(18,2),
    IMBALANCE_PERCENTAGE NUMERIC(18,6),
    STATUS NVARCHAR(50),
    TOLERANCE_PERCENTAGE NUMERIC(18,6),
    IS_WITHIN_TOLERANCE_IND NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
