raiserror ('CREATING TABLE OPERATIONAL_REPORT', 10,1) with nowait

CREATE TABLE OPERATIONAL_REPORT
(
    OPERATIONAL_REPORT_ID NVARCHAR(40) NOT NULL,
    REPORT_TYPE NVARCHAR(50),
    REPORT_PERIOD_START DATETIME,
    REPORT_PERIOD_END DATETIME,
    GENERATION_DATE DATETIME,
    GENERATED_BY NVARCHAR(255),
    PRODUCTION_REPORT_SUMMARY_ID NVARCHAR(40),
    INVENTORY_REPORT_SUMMARY_ID NVARCHAR(40),
    ALLOCATION_REPORT_SUMMARY_ID NVARCHAR(40),
    MEASUREMENT_REPORT_SUMMARY_ID NVARCHAR(40),
    COST_REPORT_SUMMARY_ID NVARCHAR(40),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
