raiserror ('CREATING TABLE OWNER_INFORMATION', 10,1) with nowait

CREATE TABLE OWNER_INFORMATION
(
    OWNER_INFORMATION_ID NVARCHAR(40) NOT NULL,
    OWNER_NAME NVARCHAR(255),
    TAX_ID NVARCHAR(40),
    ADDRESS_ID NVARCHAR(40),
    CONTACT_INFORMATION_ID NVARCHAR(40),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
