raiserror ('CREATING TABLE PO_RECEIPT', 10,1) with nowait

CREATE TABLE PO_RECEIPT
(
    PO_RECEIPT_ID NVARCHAR(40) NOT NULL,
    PURCHASE_ORDER_ID NVARCHAR(40),
    PO_LINE_ITEM_ID NVARCHAR(40),
    RECEIPT_DATE DATETIME,
    RECEIVED_QUANTITY NUMERIC(18,2),
    RECEIVED_BY NVARCHAR(255),
    RECEIPT_STATUS NVARCHAR(50),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
