raiserror ('CREATING TABLE PRICE_INDEX', 10,1) with nowait

CREATE TABLE PRICE_INDEX
(
    PRICE_INDEX_ID NVARCHAR(40) NOT NULL,
    INDEX_NAME NVARCHAR(255),
    COMMODITY_TYPE NVARCHAR(50),
    PRICE_DATE DATETIME,
    PRICE_VALUE NUMERIC(18,2),
    CURRENCY_CODE NVARCHAR(255),
    UNIT_OF_MEASURE NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
