raiserror ('CREATING TABLE PRODUCTION_REPORT_SUMMARY', 10,1) with nowait

CREATE TABLE PRODUCTION_REPORT_SUMMARY
(
    PRODUCTION_REPORT_SUMMARY_ID NVARCHAR(40) NOT NULL,
    TOTAL_PRODUCTION NUMERIC(18,2),
    PRODUCING_DAYS INT,
    AVERAGE_DAILY_PRODUCTION NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
