raiserror ('CREATING TABLE PRODUCTION_AVAILS', 10,1) with nowait

CREATE TABLE PRODUCTION_AVAILS
(
    PRODUCTION_AVAILS_ID NVARCHAR(40) NOT NULL,
    PERIOD_START DATETIME,
    PERIOD_END DATETIME,
    ESTIMATED_PRODUCTION NUMERIC(18,2),
    AVAILABLE_FOR_DELIVERY NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
