raiserror ('CREATING TABLE PRODUCTION_ALLOCATION', 10,1) with nowait

CREATE TABLE PRODUCTION_ALLOCATION
(
    PRODUCTION_ALLOCATION_ID NVARCHAR(40) NOT NULL,
    PDEN_ID NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    FIELD_ID NVARCHAR(40),
    WELL_ID NVARCHAR(40),
    POOL_ID NVARCHAR(40),
    ALLOCATION_DATE DATETIME,
    TOTAL_PRODUCTION NUMERIC(18,2) NOT NULL,
    ALLOCATION_METHOD NVARCHAR(255),
    ALLOCATION_RESULTS_JSON NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
