raiserror ('CREATING TABLE PROVED_RESERVES', 10,1) with nowait

CREATE TABLE PROVED_RESERVES
(
    RESERVES_ID NVARCHAR(40),
    PROPERTY_ID NVARCHAR(40),
    PROVED_DEVELOPED_OIL_RESERVES NUMERIC(18,2),
    PROVED_UNDEVELOPED_OIL_RESERVES NUMERIC(18,2),
    PROVED_DEVELOPED_GAS_RESERVES NUMERIC(18,2),
    PROVED_UNDEVELOPED_GAS_RESERVES NUMERIC(18,2),
    RESERVE_DATE DATETIME,
    OIL_PRICE NUMERIC(18,2),
    GAS_PRICE NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME
);
