raiserror ('CREATING TABLE REVENUE_DEDUCTION', 10,1) with nowait

CREATE TABLE REVENUE_DEDUCTION
(
    REVENUE_DEDUCTION_ID NVARCHAR(40) NOT NULL,
    REVENUE_TRANSACTION_ID NVARCHAR(40),
    DEDUCTION_TYPE NVARCHAR(50),
    AMOUNT NUMERIC(18,2) NOT NULL,
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    ROW_ID NVARCHAR(40)
);
