raiserror ('CREATING TABLE REVENUE_DISTRIBUTION', 10,1) with nowait

CREATE TABLE REVENUE_DISTRIBUTION
(
    REVENUE_DISTRIBUTION_ID NVARCHAR(40) NOT NULL,
    REVENUE_TRANSACTION_ID NVARCHAR(40),
    INT_SET_PARTNER_ID NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    WORKING_INTEREST_PERCENTAGE NUMERIC(18,6),
    NET_REVENUE_INTEREST_PERCENTAGE NUMERIC(18,6),
    REVENUE_AMOUNT NUMERIC(18,2) NOT NULL,
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
