raiserror ('CREATING TABLE REVENUE_TRANSACTION', 10,1) with nowait

CREATE TABLE REVENUE_TRANSACTION
(
    REVENUE_TRANSACTION_ID NVARCHAR(40) NOT NULL,
    PROPERTY_ID NVARCHAR(40),
    WELL_ID NVARCHAR(40),
    FIELD_ID NVARCHAR(40),
    CONTRACT_ID NVARCHAR(40),
    TRANSACTION_DATE DATETIME,
    REVENUE_TYPE NVARCHAR(50),
    GROSS_REVENUE NUMERIC(18,2),
    NET_REVENUE NUMERIC(18,2),
    OIL_VOLUME NUMERIC(18,2),
    GAS_VOLUME NUMERIC(18,2),
    OIL_PRICE NUMERIC(18,2),
    GAS_PRICE NUMERIC(18,2),
    ROYALTY_AMOUNT NUMERIC(18,2),
    TAX_AMOUNT NUMERIC(18,2),
    CURRENCY_CODE NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
