raiserror ('CREATING TABLE REVENUE_SHARING', 10,1) with nowait

CREATE TABLE REVENUE_SHARING
(
    REVENUE_SHARING_ID NVARCHAR(40) NOT NULL,
    UNIT_OPERATING_AGREEMENT_ID NVARCHAR(40),
    BASED_ON_NET_REVENUE_INTEREST NVARCHAR(255),
    BASED_ON_TRACT_PARTICIPATION NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
