raiserror ('CREATING TABLE ROYALTY_PAYMENT_DETAIL', 10,1) with nowait

CREATE TABLE ROYALTY_PAYMENT_DETAIL
(
    ROYALTY_PAYMENT_DETAIL_ID NVARCHAR(40) NOT NULL,
    ROYALTY_PAYMENT_ID NVARCHAR(40),
    REVENUE_TRANSACTION_ID NVARCHAR(40),
    OIL_VOLUME NUMERIC(18,2),
    GAS_VOLUME NUMERIC(18,2),
    OIL_REVENUE NUMERIC(18,2),
    GAS_REVENUE NUMERIC(18,2),
    ROYALTY_AMOUNT NUMERIC(18,2),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
