raiserror ('CREATING TABLE ROYALTY_INTEREST', 10,1) with nowait

CREATE TABLE ROYALTY_INTEREST
(
    ROYALTY_INTEREST_ID NVARCHAR(40) NOT NULL,
    ROYALTY_OWNER_ID NVARCHAR(40),
    PROPERTY_OR_LEASE_ID NVARCHAR(40),
    INTEREST_PERCENTAGE NUMERIC(18,6),
    ROYALTY_RATE NUMERIC(18,2),
    EFFECTIVE_START_DATE DATETIME,
    EFFECTIVE_END_DATE DATETIME,
    EFFECTIVE_DATE DATETIME,
    EXPIRATION_DATE DATETIME,
    DIVISION_ORDER_ID NVARCHAR(40),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
