raiserror ('CREATING TABLE RUN_TICKET_VALUATION', 10,1) with nowait

CREATE TABLE RUN_TICKET_VALUATION
(
    VALUATION_ID NVARCHAR(40),
    RUN_TICKET_NUMBER NVARCHAR(255),
    VALUATION_DATE DATETIME,
    BASE_PRICE NUMERIC(18,2),
    QUALITY_ADJUSTMENTS_JSON NVARCHAR(40),
    LOCATION_ADJUSTMENTS_JSON NVARCHAR(255),
    TIME_ADJUSTMENTS_JSON NVARCHAR(255),
    TOTAL_ADJUSTMENTS NUMERIC(18,2),
    ADJUSTED_PRICE NUMERIC(18,2),
    NET_VOLUME NUMERIC(18,2),
    TOTAL_VALUE NUMERIC(18,2),
    PRICING_METHOD NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
