raiserror ('CREATING TABLE SALES_CONTRACT', 10,1) with nowait

CREATE TABLE SALES_CONTRACT
(
    SALES_CONTRACT_ID NVARCHAR(40) NOT NULL,
    CONTRACT_NUMBER NVARCHAR(255),
    BUYER_BA_ID NVARCHAR(40),
    SELLER_BA_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    COMMODITY_TYPE NVARCHAR(50),
    BASE_PRICE NUMERIC(18,2),
    PRICING_METHOD NVARCHAR(255),
    CURRENCY_CODE NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
