raiserror ('CREATING TABLE TAX_RETURN', 10,1) with nowait

CREATE TABLE TAX_RETURN
(
    TAX_RETURN_ID NVARCHAR(40) NOT NULL,
    RETURN_NUMBER NVARCHAR(255),
    TAX_TYPE NVARCHAR(50),
    RETURN_PERIOD_START DATETIME,
    RETURN_PERIOD_END DATETIME,
    FILING_DATE DATETIME,
    TOTAL_TAX_LIABILITY NUMERIC(18,2),
    TAX_PAID NUMERIC(18,2),
    TAX_DUE NUMERIC(18,2),
    STATUS NVARCHAR(50),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
