raiserror ('CREATING TABLE TAX_WITHHOLDING', 10,1) with nowait

CREATE TABLE TAX_WITHHOLDING
(
    TAX_WITHHOLDING_ID NVARCHAR(40) NOT NULL,
    ROYALTY_PAYMENT_ID NVARCHAR(40),
    WITHHOLDING_TYPE NVARCHAR(50),
    WITHHOLDING_RATE NUMERIC(18,2),
    AMOUNT NUMERIC(18,2),
    REASON NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
