raiserror ('CREATING TABLE TIME_ADJUSTMENTS', 10,1) with nowait

CREATE TABLE TIME_ADJUSTMENTS
(
    TIME_ADJUSTMENTS_ID NVARCHAR(40) NOT NULL,
    TIME_DIFFERENTIAL NUMERIC(18,2),
    INTEREST_ADJUSTMENT NUMERIC(18,2),
    TOTAL_ADJUSTMENT NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
