raiserror ('CREATING TABLE TRANSFER_ORDER', 10,1) with nowait

CREATE TABLE TRANSFER_ORDER
(
    TRANSFER_ORDER_ID NVARCHAR(40) NOT NULL,
    PROPERTY_OR_LEASE_ID NVARCHAR(40),
    FROM_OWNER_ID NVARCHAR(40),
    TO_OWNER_ID NVARCHAR(40),
    INTEREST_TRANSFERRED NUMERIC(18,2),
    EFFECTIVE_DATE DATETIME,
    IS_APPROVED NVARCHAR(255),
    APPROVAL_DATE DATETIME,
    APPROVED_BY NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
