raiserror ('CREATING TABLE UNIT_OPERATING_AGREEMENT', 10,1) with nowait

CREATE TABLE UNIT_OPERATING_AGREEMENT
(
    UNIT_OPERATING_AGREEMENT_ID NVARCHAR(40) NOT NULL,
    UNIT_ID NVARCHAR(40),
    VOTING_RIGHTS_ID NVARCHAR(40),
    COST_SHARING_ID NVARCHAR(40),
    REVENUE_SHARING_ID NVARCHAR(40),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
