ALTER TABLE UNIT_OPERATING_AGREEMENT
ADD CONSTRAINT FK_UNIT_OPERATING_AGREEMENT_UNIT FOREIGN KEY (UNIT_ID) REFERENCES UNIT(UNIT_ID);

ALTER TABLE UNIT_OPERATING_AGREEMENT
ADD CONSTRAINT FK_UNIT_OPERATING_AGREEMENT_VOTING_RIGHTS FOREIGN KEY (VOTING_RIGHTS_ID) REFERENCES VOTING_RIGHTS(VOTING_RIGHTS_ID);

ALTER TABLE UNIT_OPERATING_AGREEMENT
ADD CONSTRAINT FK_UNIT_OPERATING_AGREEMENT_COST_SHARING FOREIGN KEY (COST_SHARING_ID) REFERENCES COST_SHARING(COST_SHARING_ID);

ALTER TABLE UNIT_OPERATING_AGREEMENT
ADD CONSTRAINT FK_UNIT_OPERATING_AGREEMENT_REVENUE_SHARING FOREIGN KEY (REVENUE_SHARING_ID) REFERENCES REVENUE_SHARING(REVENUE_SHARING_ID);
