raiserror ('CREATING TABLE UNIT_PARTICIPANT', 10,1) with nowait

CREATE TABLE UNIT_PARTICIPANT
(
    UNIT_PARTICIPANT_ID NVARCHAR(40) NOT NULL,
    UNIT_OPERATING_AGREEMENT_ID NVARCHAR(40),
    COMPANY_NAME NVARCHAR(255),
    WORKING_INTEREST NUMERIC(18,2),
    NET_REVENUE_INTEREST NUMERIC(18,2),
    IS_OPERATOR NVARCHAR(255),
    VOTING_PERCENTAGE NUMERIC(18,6),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
