raiserror ('CREATING TABLE VOTING_RIGHTS', 10,1) with nowait

CREATE TABLE VOTING_RIGHTS
(
    VOTING_RIGHTS_ID NVARCHAR(40) NOT NULL,
    UNIT_OPERATING_AGREEMENT_ID NVARCHAR(40),
    BASED_ON_WORKING_INTEREST NVARCHAR(255),
    MINIMUM_VOTING_THRESHOLD NUMERIC(18,2),
    UNANIMOUS_CONSENT_REQUIRED NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
