raiserror ('CREATING TABLE ROLE_PERMISSION', 10,1) with nowait

CREATE TABLE ROLE_PERMISSION
(
    ROLE_PERMISSION_ID NVARCHAR(40) NOT NULL,
    ROLE_ID NVARCHAR(40),
    PERMISSION_ID NVARCHAR(40)
);
