raiserror ('CREATING TABLE SETUP_WIZARD_LOG', 10,1) with nowait

CREATE TABLE SETUP_WIZARD_LOG
(
    SETUP_LOG_ID NVARCHAR(40),
    ORGANIZATION_ID NVARCHAR(40),
    SETUP_STEP NVARCHAR(255),
    SETUP_DATA NVARCHAR(255),
    EXECUTED_BY NVARCHAR(255),
    EXECUTION_DATE DATETIME,
    STATUS NVARCHAR(50),
    ERROR_MESSAGE NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
