ALTER TABLE SETUP_WIZARD_LOG
ADD CONSTRAINT FK_SETUP_WIZARD_LOG_SETUP_LOG FOREIGN KEY (SETUP_LOG_ID) REFERENCES SETUP_LOG(SETUP_LOG_ID);

ALTER TABLE SETUP_WIZARD_LOG
ADD CONSTRAINT FK_SETUP_WIZARD_LOG_ORGANIZATION FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION(ORGANIZATION_ID);
