raiserror ('CREATING TABLE USER', 10,1) with nowait

CREATE TABLE USER
(
    USER_ID NVARCHAR(40) NOT NULL,
    USERNAME NVARCHAR(255),
    EMAIL NVARCHAR(255),
    PASSWORD_HASH NVARCHAR(255),
    IS_ACTIVE BIT NOT NULL,
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    TENANT_ID NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    PPDM_GUID NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    SOURCE NVARCHAR(40),
    REMARK NVARCHAR(2000)
);
