raiserror ('CREATING TABLE USER_ROLE', 10,1) with nowait

CREATE TABLE USER_ROLE
(
    USER_ROLE_ID NVARCHAR(40) NOT NULL,
    USER_ID NVARCHAR(40),
    ROLE_ID NVARCHAR(40),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    ROW_QUALITY NVARCHAR(40),
    PPDM_GUID NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    SOURCE NVARCHAR(40),
    REMARK NVARCHAR(2000)
);
