raiserror ('CREATING TABLE USER_PROFILE', 10,1) with nowait

CREATE TABLE USER_PROFILE
(
    USER_ID NVARCHAR(40),
    PRIMARY_ROLE NVARCHAR(255),
    PREFERRED_LAYOUT NVARCHAR(255),
    USER_PREFERENCES NVARCHAR(255),
    LAST_LOGIN_DATE DATETIME,
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
