using Beep.OilandGas.Diagnostics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using TheTechIdeaWeb.Diagnostics;
using TheTechIdeaWeb.Diagnostics.Log;
using TheTechIdeaWeb.Diagnostics.Records;
using Xunit;

namespace Beep.OilandGas.ApiService.Tests;

/// <summary>
/// DIAG-01 for OilGas (CLIENT-CATCH-01 stage 3): the Web and the API keep their failures in one EF store, on the
/// repository's three engines, configured the way the repository is and refusing to start without it.
/// </summary>
/// <remarks>
/// <para>
/// Before this OilGas had no failure reporter, so the identity server's client library refused to start either host — by
/// design, since a library that reports its failures into nothing hides them. Its API's app-wide handler logged past any
/// store and, in development, answered with the exception's own text.
/// </para>
/// <para>
/// <b>Blind spot:</b> the engines' contexts are built without a server, so what is proved is each context's model,
/// history table and migrations — that the migrations run is proved on SQL Server LocalDB only, when
/// <c>OILGAS_TEST_LOCALDB_MODULE=1</c>; PostgreSQL and Oracle are generated by the same tool from the same model and are not
/// run here. The Web's page and error boundary are the shared library's components, whose own tests drive them.
/// </para>
/// </remarks>
public class OilGasDiagnosticsTests
{
    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("REPLACE_ME")]
    [InlineData("MySql")]
    [InlineData("1")]
    [InlineData("SqlServer,Oracle")]
    public void A_missing_or_unknown_engine_stops_the_host_naming_the_setting(string? provider)
    {
        var configuration = Configuration(provider, "Server=db;Database=failures");

        var refused = Assert.Throws<InvalidOperationException>(() => new ServiceCollection().AddOilGasDiagnostics(configuration));

        Assert.Contains(OilGasDiagnosticsRegistration.ProviderSetting, refused.Message, StringComparison.Ordinal);
    }

    [Theory]
    [InlineData(null)]
    [InlineData(" ")]
    [InlineData("Server=REPLACE_ME;Database=REPLACE_ME")]
    public void A_missing_connection_stops_the_host_naming_the_setting(string? connection)
    {
        var configuration = Configuration("SqlServer", connection);

        var refused = Assert.Throws<InvalidOperationException>(() => new ServiceCollection().AddOilGasDiagnostics(configuration));

        Assert.Contains(OilGasDiagnosticsRegistration.ConnectionSetting, refused.Message, StringComparison.Ordinal);
    }

    [Theory]
    [InlineData("SqlServer", typeof(SqlServerOilGasDiagnosticsDbContext))]
    [InlineData("postgresql", typeof(PostgreSqlOilGasDiagnosticsDbContext))]
    [InlineData("ORACLE", typeof(OracleOilGasDiagnosticsDbContext))]
    public void The_named_engine_s_store_is_the_one_the_reporter_writes_into(string provider, Type engineContext)
    {
        var services = new ServiceCollection().AddLogging();
        services.AddOilGasDiagnostics(Configuration(provider, Connection(engineContext)));

        using var provider_ = services.BuildServiceProvider();
        using var scope = provider_.CreateScope();

        Assert.IsType(engineContext, scope.ServiceProvider.GetRequiredService<OilGasDiagnosticsDbContext>());
        Assert.NotNull(provider_.GetRequiredService<IFailureReporter>());
        Assert.NotNull(scope.ServiceProvider.GetRequiredService<IFailureLog>());
    }

    /// <summary>
    /// Each engine's context holds the failure table, keeps its migrations apart from the repository's, and has a migration
    /// for every change to its model — a model changed without one would start and then fail to store anything.
    /// </summary>
    [Theory]
    [InlineData(typeof(SqlServerOilGasDiagnosticsDbContext))]
    [InlineData(typeof(PostgreSqlOilGasDiagnosticsDbContext))]
    [InlineData(typeof(OracleOilGasDiagnosticsDbContext))]
    public void Every_engine_s_store_has_its_table_its_own_history_and_no_missing_migration(Type engineContext)
    {
        using var context = Build(engineContext);

        Assert.NotNull(context.Model.FindEntityType(typeof(FailureRecord)));
        Assert.Equal(
            OilGasDiagnosticsDbContext.MigrationsHistoryTable,
            RelationalOptionsExtension.Extract(context.GetService<IDbContextOptions>()).MigrationsHistoryTableName);
        Assert.Contains(context.Database.GetMigrations(), migration => migration.EndsWith("_AddFailureRecords", StringComparison.Ordinal));
        Assert.False(context.Database.HasPendingModelChanges(), $"{engineContext.Name} has model changes no migration carries.");
    }

    /// <summary>The store as the hosts use it: migrated by the owner, a failure reported, and read back under its reference.</summary>
    [LocalDbModuleFact]
    public async Task A_reported_failure_is_stored_under_the_reference_the_person_is_given()
    {
        var database = $"BeepOilGas_Diagnostics_{Guid.NewGuid():N}";
        var configuration = Configuration(
            "SqlServer", $"Server=(localdb)\\MSSQLLocalDB;Database={database};Integrated Security=true;TrustServerCertificate=true",
            migrate: true);

        var builder = Microsoft.Extensions.Hosting.Host.CreateApplicationBuilder();
        builder.Logging.SetMinimumLevel(LogLevel.Warning);
        builder.Configuration.AddConfiguration(configuration);
        builder.Services.AddOilGasDiagnostics(builder.Configuration);
        using var host = builder.Build();

        await host.Services.ApplyOilGasDiagnosticsSchemaAsync(host.Services.GetRequiredService<IConfiguration>());

        try
        {
            await host.StartAsync();

            var reference = host.Services.GetRequiredService<IFailureReporter>().ReportHandled(
                new InvalidOperationException("the test's failure"), "proving the store", consequence: "nothing");

            FailureRecord? stored = null;
            for (var attempt = 0; attempt < 50 && stored is null; attempt++)
            {
                await Task.Delay(100);
                using var scope = host.Services.CreateScope();
                stored = await scope.ServiceProvider.GetRequiredService<OilGasDiagnosticsDbContext>()
                    .Set<FailureRecord>().SingleOrDefaultAsync(record => record.Reference == reference);
            }

            await host.StopAsync();

            Assert.NotNull(stored);
            Assert.Equal("proving the store", stored!.Operation);
        }
        finally
        {
            using var scope = host.Services.CreateScope();
            await scope.ServiceProvider.GetRequiredService<OilGasDiagnosticsDbContext>().Database.EnsureDeletedAsync();
        }
    }

    private static IConfiguration Configuration(string? provider, string? connection, bool migrate = false) =>
        new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string, string?>
        {
            [OilGasDiagnosticsRegistration.ProviderSetting] = provider,
            [OilGasDiagnosticsRegistration.ConnectionSetting] = connection,
            [OilGasDiagnosticsRegistration.MigrateOnStartupSetting] = migrate ? "true" : "false",
        }).Build();

    /// <summary>A connection string each engine's provider accepts; nothing here connects.</summary>
    private static string Connection(Type engineContext) =>
        engineContext == typeof(SqlServerOilGasDiagnosticsDbContext) ? "Server=db;Database=failures;TrustServerCertificate=true"
        : engineContext == typeof(PostgreSqlOilGasDiagnosticsDbContext) ? "Host=db;Database=failures"
        : "User Id=oilgas;Data Source=db/FREEPDB1";

    private static OilGasDiagnosticsDbContext Build(Type engineContext) =>
        engineContext == typeof(SqlServerOilGasDiagnosticsDbContext)
            ? new SqlServerOilGasDiagnosticsDbContext((DbContextOptions<SqlServerOilGasDiagnosticsDbContext>)OilGasDiagnosticsEngines
                .UseSqlServer(new DbContextOptionsBuilder<SqlServerOilGasDiagnosticsDbContext>(), Connection(engineContext)).Options)
            : engineContext == typeof(PostgreSqlOilGasDiagnosticsDbContext)
                ? new PostgreSqlOilGasDiagnosticsDbContext((DbContextOptions<PostgreSqlOilGasDiagnosticsDbContext>)OilGasDiagnosticsEngines
                    .UsePostgreSql(new DbContextOptionsBuilder<PostgreSqlOilGasDiagnosticsDbContext>(), Connection(engineContext)).Options)
                : new OracleOilGasDiagnosticsDbContext((DbContextOptions<OracleOilGasDiagnosticsDbContext>)OilGasDiagnosticsEngines
                    .UseOracle(new DbContextOptionsBuilder<OracleOilGasDiagnosticsDbContext>(), Connection(engineContext)).Options);
}
