ALTER TABLE `AFE`
ADD CONSTRAINT FK_AFE_PROPERTY FOREIGN KEY (`PROPERTY_ID`) REFERENCES `PROPERTY`(`PROPERTY_ID`);

ALTER TABLE `AFE`
ADD CONSTRAINT FK_AFE_FIELD FOREIGN KEY (`FIELD_ID`) REFERENCES `FIELD`(`FIELD_ID`);
