ALTER TABLE `AMORTIZATION_RECORD`
ADD CONSTRAINT FK_AMORTIZATION_RECORD_PROPERTY FOREIGN KEY (`PROPERTY_ID`) REFERENCES `PROPERTY`(`PROPERTY_ID`);

ALTER TABLE `AMORTIZATION_RECORD`
ADD CONSTRAINT FK_AMORTIZATION_RECORD_COST_CENTER FOREIGN KEY (`COST_CENTER_ID`) REFERENCES `COST_CENTER`(`COST_CENTER_ID`);
