CREATE TABLE `CEILING_TEST_CALCULATION`
(
    `CEILING_TEST_CALCULATION_ID` VARCHAR(40) NOT NULL,
    `PROPERTY_ID` VARCHAR(40),
    `CALCULATION_DATE` DATETIME,
    `NET_CAPITALIZED_COST` DECIMAL(18,2),
    `DISCOUNTED_FUTURE_NET_CASH_FLOWS` DECIMAL(18,2),
    `CEILING_VALUE` DECIMAL(18,2),
    `IMPAIRMENT_AMOUNT` DECIMAL(18,2),
    `DISCOUNT_RATE` DECIMAL(18,2),
    `DESCRIPTION` VARCHAR(2000),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
