CREATE TABLE `COST_ALLOCATION`
(
    `COST_ALLOCATION_ID` VARCHAR(40) NOT NULL,
    `COST_TRANSACTION_ID` VARCHAR(40),
    `PROPERTY_ID` VARCHAR(40),
    `WELL_ID` VARCHAR(40),
    `COST_CENTER_ID` VARCHAR(40),
    `ALLOCATED_AMOUNT` DECIMAL(18,2),
    `ALLOCATION_PERCENTAGE` DECIMAL(18,6),
    `ALLOCATION_METHOD` VARCHAR(255),
    `DESCRIPTION` VARCHAR(2000),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
