ALTER TABLE `COST_TRANSACTION`
ADD CONSTRAINT FK_COST_TRANSACTION_PROPERTY FOREIGN KEY (`PROPERTY_ID`) REFERENCES `PROPERTY`(`PROPERTY_ID`);

ALTER TABLE `COST_TRANSACTION`
ADD CONSTRAINT FK_COST_TRANSACTION_WELL FOREIGN KEY (`WELL_ID`) REFERENCES `WELL`(`WELL_ID`);

ALTER TABLE `COST_TRANSACTION`
ADD CONSTRAINT FK_COST_TRANSACTION_FIELD FOREIGN KEY (`FIELD_ID`) REFERENCES `FIELD`(`FIELD_ID`);

ALTER TABLE `COST_TRANSACTION`
ADD CONSTRAINT FK_COST_TRANSACTION_AFE FOREIGN KEY (`AFE_ID`) REFERENCES `AFE`(`AFE_ID`);

ALTER TABLE `COST_TRANSACTION`
ADD CONSTRAINT FK_COST_TRANSACTION_COST_CENTER FOREIGN KEY (`COST_CENTER_ID`) REFERENCES `COST_CENTER`(`COST_CENTER_ID`);
