CREATE TABLE `CRUDE_OIL_INVENTORY`
(
    `INVENTORY_ID` VARCHAR(40),
    `PROPERTY_OR_LEASE_ID` VARCHAR(40),
    `TANK_BATTERY_ID` VARCHAR(40),
    `INVENTORY_DATE` DATETIME,
    `VOLUME` DECIMAL(18,2),
    `UNIT_COST` DECIMAL(18,2),
    `VALUATION_METHOD` VARCHAR(255),
    `MARKET_PRICE` DECIMAL(18,2),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
