ALTER TABLE `EXCHANGE_COMMITMENT`
ADD CONSTRAINT FK_EXCHANGE_COMMITMENT_COMMITMENT FOREIGN KEY (`COMMITMENT_ID`) REFERENCES `COMMITMENT`(`COMMITMENT_ID`);

ALTER TABLE `EXCHANGE_COMMITMENT`
ADD CONSTRAINT FK_EXCHANGE_COMMITMENT_CONTRACT FOREIGN KEY (`CONTRACT_ID`) REFERENCES `CONTRACT`(`CONTRACT_ID`);
