CREATE TABLE `GL_ENTRY`
(
    `GL_ENTRY_ID` VARCHAR(40) NOT NULL,
    `JOURNAL_ENTRY_ID` VARCHAR(40),
    `GL_ACCOUNT_ID` VARCHAR(40),
    `ENTRY_DATE` DATETIME,
    `DEBIT_AMOUNT` DECIMAL(18,2),
    `CREDIT_AMOUNT` DECIMAL(18,2),
    `DESCRIPTION` VARCHAR(2000),
    `REFERENCE_NUMBER` VARCHAR(255),
    `SOURCE_MODULE` VARCHAR(40),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
