CREATE TABLE `GOVERNMENTAL_PRODUCTION_DATA`
(
    `GOVERNMENTAL_PRODUCTION_DATA_ID` VARCHAR(40) NOT NULL,
    `OIL_PRODUCTION` DECIMAL(18,2),
    `GAS_PRODUCTION` DECIMAL(18,2),
    `WATER_PRODUCTION` DECIMAL(18,2),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
