CREATE TABLE `IMBALANCE_STATEMENT`
(
    `IMBALANCE_STATEMENT_ID` VARCHAR(40) NOT NULL,
    `STATEMENT_PERIOD_START` DATETIME,
    `STATEMENT_PERIOD_END` DATETIME,
    `IMBALANCE_RECONCILIATION_ID` VARCHAR(40),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
