CREATE TABLE `IMBALANCE_SUMMARY`
(
    `IMBALANCE_SUMMARY_ID` VARCHAR(40) NOT NULL,
    `IMBALANCE_STATEMENT_ID` VARCHAR(40),
    `SUMMARY_TYPE` VARCHAR(50),
    `TOTAL_VOLUME` DECIMAL(18,2),
    `TRANSACTION_COUNT` INT,
    `AVERAGE_DAILY_VOLUME` DECIMAL(18,2),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
