ALTER TABLE `IMPAIRMENT_RECORD`
ADD CONSTRAINT FK_IMPAIRMENT_RECORD_PROPERTY FOREIGN KEY (`PROPERTY_ID`) REFERENCES `PROPERTY`(`PROPERTY_ID`);

ALTER TABLE `IMPAIRMENT_RECORD`
ADD CONSTRAINT FK_IMPAIRMENT_RECORD_COST_CENTER FOREIGN KEY (`COST_CENTER_ID`) REFERENCES `COST_CENTER`(`COST_CENTER_ID`);
