CREATE TABLE `INVENTORY_TRANSACTION`
(
    `INVENTORY_TRANSACTION_ID` VARCHAR(40) NOT NULL,
    `INVENTORY_ITEM_ID` VARCHAR(40),
    `TRANSACTION_TYPE` VARCHAR(50),
    `TRANSACTION_DATE` DATETIME,
    `QUANTITY` DECIMAL(18,2),
    `UNIT_COST` DECIMAL(18,2),
    `TOTAL_COST` DECIMAL(18,2),
    `REFERENCE_NUMBER` VARCHAR(255),
    `DESCRIPTION` VARCHAR(2000),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
