CREATE TABLE `INVENTORY_VALUATION`
(
    `INVENTORY_VALUATION_ID` VARCHAR(40) NOT NULL,
    `INVENTORY_ITEM_ID` VARCHAR(40),
    `VALUATION_DATE` DATETIME,
    `VALUATION_METHOD` VARCHAR(255),
    `QUANTITY` DECIMAL(18,2),
    `UNIT_COST` DECIMAL(18,2),
    `TOTAL_VALUE` DECIMAL(18,2),
    `DESCRIPTION` VARCHAR(2000),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
