CREATE TABLE `INVOICE_LINE_ITEM`
(
    `INVOICE_LINE_ITEM_ID` VARCHAR(40) NOT NULL,
    `INVOICE_ID` VARCHAR(40),
    `LINE_NUMBER` INT,
    `ITEM_DESCRIPTION` VARCHAR(2000),
    `QUANTITY` DECIMAL(18,2),
    `UNIT_PRICE` DECIMAL(18,2),
    `LINE_TOTAL` DECIMAL(18,2),
    `GL_ACCOUNT_ID` VARCHAR(40),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
