ALTER TABLE `INVOICE_LINE_ITEM`
ADD CONSTRAINT FK_INVOICE_LINE_ITEM_INVOICE FOREIGN KEY (`INVOICE_ID`) REFERENCES `INVOICE`(`INVOICE_ID`);

ALTER TABLE `INVOICE_LINE_ITEM`
ADD CONSTRAINT FK_INVOICE_LINE_ITEM_GL_ACCOUNT FOREIGN KEY (`GL_ACCOUNT_ID`) REFERENCES `GL_ACCOUNT`(`GL_ACCOUNT_ID`);
