CREATE TABLE `JIB_COST_ALLOCATION`
(
    `JIB_COST_ALLOCATION_ID` VARCHAR(40) NOT NULL,
    `JIB_ID` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `FINANCE_ID` VARCHAR(40),
    `COST_CATEGORY` VARCHAR(255),
    `GROSS_COST` DECIMAL(18,2) NOT NULL,
    `WORKING_INTEREST_SHARE` DECIMAL(18,2),
    `NET_COST` DECIMAL(18,2) NOT NULL,
    `DESCRIPTION` VARCHAR(2000),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
