CREATE TABLE `JOA_INTEREST`
(
    `JOA_INTEREST_ID` VARCHAR(40) NOT NULL,
    `JOA_ID` VARCHAR(40),
    `INTEREST_OWNER_BA_ID` VARCHAR(40),
    `WORKING_INTEREST_PERCENTAGE` DECIMAL(18,6),
    `REVENUE_INTEREST_PERCENTAGE` DECIMAL(18,6),
    `EFFECTIVE_DATE` DATETIME,
    `EXPIRY_DATE` DATETIME,
    `DESCRIPTION` VARCHAR(2000),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
