CREATE TABLE `JOIB_LINE_ITEM`
(
    `JOIB_LINE_ITEM_ID` VARCHAR(40) NOT NULL,
    `JOINT_INTEREST_BILL_ID` VARCHAR(40),
    `LINE_ITEM_NUMBER` VARCHAR(255),
    `COST_CATEGORY` VARCHAR(255),
    `DESCRIPTION` VARCHAR(2000),
    `AMOUNT` DECIMAL(18,2),
    `PROPERTY_ID` VARCHAR(40),
    `WELL_ID` VARCHAR(40),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
