CREATE TABLE `MEASUREMENT_CORRECTIONS`
(
    `MEASUREMENT_CORRECTIONS_ID` VARCHAR(40) NOT NULL,
    `MEASUREMENT_RECORD_ID` VARCHAR(40),
    `TEMPERATURE_CORRECTION_FACTOR` DECIMAL(18,2),
    `PRESSURE_CORRECTION_FACTOR` DECIMAL(18,2),
    `METER_FACTOR` DECIMAL(18,2),
    `SHRINKAGE_FACTOR` DECIMAL(18,2),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
