ALTER TABLE `OWNER_INFORMATION`
ADD CONSTRAINT FK_OWNER_INFORMATION_TAX FOREIGN KEY (`TAX_ID`) REFERENCES `TAX`(`TAX_ID`);

ALTER TABLE `OWNER_INFORMATION`
ADD CONSTRAINT FK_OWNER_INFORMATION_ADDRESS FOREIGN KEY (`ADDRESS_ID`) REFERENCES `ADDRESS`(`ADDRESS_ID`);

ALTER TABLE `OWNER_INFORMATION`
ADD CONSTRAINT FK_OWNER_INFORMATION_CONTACT_INFORMATION FOREIGN KEY (`CONTACT_INFORMATION_ID`) REFERENCES `CONTACT_INFORMATION`(`CONTACT_INFORMATION_ID`);
