ALTER TABLE `PRODUCTION_ALLOCATION`
ADD CONSTRAINT FK_PRODUCTION_ALLOCATION_PDEN FOREIGN KEY (`PDEN_ID`) REFERENCES `PDEN`(`PDEN_ID`);

ALTER TABLE `PRODUCTION_ALLOCATION`
ADD CONSTRAINT FK_PRODUCTION_ALLOCATION_FIELD FOREIGN KEY (`FIELD_ID`) REFERENCES `FIELD`(`FIELD_ID`);

ALTER TABLE `PRODUCTION_ALLOCATION`
ADD CONSTRAINT FK_PRODUCTION_ALLOCATION_WELL FOREIGN KEY (`WELL_ID`) REFERENCES `WELL`(`WELL_ID`);

ALTER TABLE `PRODUCTION_ALLOCATION`
ADD CONSTRAINT FK_PRODUCTION_ALLOCATION_POOL FOREIGN KEY (`POOL_ID`) REFERENCES `POOL`(`POOL_ID`);
