ALTER TABLE `PROVED_RESERVES`
ADD CONSTRAINT FK_PROVED_RESERVES_RESERVES FOREIGN KEY (`RESERVES_ID`) REFERENCES `RESERVES`(`RESERVES_ID`);

ALTER TABLE `PROVED_RESERVES`
ADD CONSTRAINT FK_PROVED_RESERVES_PROPERTY FOREIGN KEY (`PROPERTY_ID`) REFERENCES `PROPERTY`(`PROPERTY_ID`);
