CREATE TABLE `PURCHASE_ORDER`
(
    `PURCHASE_ORDER_ID` VARCHAR(40) NOT NULL,
    `PO_NUMBER` VARCHAR(255),
    `VENDOR_BA_ID` VARCHAR(40),
    `PO_DATE` DATETIME,
    `EXPECTED_DELIVERY_DATE` DATETIME,
    `TOTAL_AMOUNT` DECIMAL(18,2),
    `STATUS` VARCHAR(50),
    `DESCRIPTION` VARCHAR(2000),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
