CREATE TABLE `REGULATED_PRICE`
(
    `REGULATED_PRICE_ID` VARCHAR(40) NOT NULL,
    `REGULATORY_AUTHORITY` VARCHAR(255),
    `PRICE_FORMULA` VARCHAR(255),
    `EFFECTIVE_START_DATE` DATETIME,
    `EFFECTIVE_END_DATE` DATETIME,
    `PRICE_CAP` DECIMAL(18,2),
    `PRICE_FLOOR` DECIMAL(18,2),
    `BASE_PRICE` DECIMAL(18,2),
    `ADJUSTMENT_FACTORS_JSON` VARCHAR(255),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
