ALTER TABLE `ROYALTY_PAYMENT`
ADD CONSTRAINT FK_ROYALTY_PAYMENT_ROYALTY_INTEREST FOREIGN KEY (`ROYALTY_INTEREST_ID`) REFERENCES `ROYALTY_INTEREST`(`ROYALTY_INTEREST_ID`);

ALTER TABLE `ROYALTY_PAYMENT`
ADD CONSTRAINT FK_ROYALTY_PAYMENT_ROYALTY_OWNER FOREIGN KEY (`ROYALTY_OWNER_ID`) REFERENCES `ROYALTY_OWNER`(`ROYALTY_OWNER_ID`);

ALTER TABLE `ROYALTY_PAYMENT`
ADD CONSTRAINT FK_ROYALTY_PAYMENT_PROPERTY_OR_LEASE FOREIGN KEY (`PROPERTY_OR_LEASE_ID`) REFERENCES `PROPERTY_OR_LEASE`(`PROPERTY_OR_LEASE_ID`);
