ALTER TABLE `ROYALTY_PAYMENT_DETAIL`
ADD CONSTRAINT FK_ROYALTY_PAYMENT_DETAIL_ROYALTY_PAYMENT FOREIGN KEY (`ROYALTY_PAYMENT_ID`) REFERENCES `ROYALTY_PAYMENT`(`ROYALTY_PAYMENT_ID`);

ALTER TABLE `ROYALTY_PAYMENT_DETAIL`
ADD CONSTRAINT FK_ROYALTY_PAYMENT_DETAIL_REVENUE_TRANSACTION FOREIGN KEY (`REVENUE_TRANSACTION_ID`) REFERENCES `REVENUE_TRANSACTION`(`REVENUE_TRANSACTION_ID`);
