ALTER TABLE `TRANSFER_ORDER`
ADD CONSTRAINT FK_TRANSFER_ORDER_PROPERTY_OR_LEASE FOREIGN KEY (`PROPERTY_OR_LEASE_ID`) REFERENCES `PROPERTY_OR_LEASE`(`PROPERTY_OR_LEASE_ID`);

ALTER TABLE `TRANSFER_ORDER`
ADD CONSTRAINT FK_TRANSFER_ORDER_FROM_OWNER FOREIGN KEY (`FROM_OWNER_ID`) REFERENCES `FROM_OWNER`(`FROM_OWNER_ID`);

ALTER TABLE `TRANSFER_ORDER`
ADD CONSTRAINT FK_TRANSFER_ORDER_TO_OWNER FOREIGN KEY (`TO_OWNER_ID`) REFERENCES `TO_OWNER`(`TO_OWNER_ID`);
