CREATE TABLE `VOTING_RIGHTS`
(
    `VOTING_RIGHTS_ID` VARCHAR(40) NOT NULL,
    `UNIT_OPERATING_AGREEMENT_ID` VARCHAR(40),
    `BASED_ON_WORKING_INTEREST` VARCHAR(255),
    `MINIMUM_VOTING_THRESHOLD` DECIMAL(18,2),
    `UNANIMOUS_CONSENT_REQUIRED` VARCHAR(255),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
