CREATE TABLE `WELL_ALLOCATION_DATA`
(
    `WELL_ALLOCATION_DATA_ID` VARCHAR(40) NOT NULL,
    `WELL_ID` VARCHAR(40),
    `LEASE_ID` VARCHAR(40),
    `WORKING_INTEREST` DECIMAL(18,2),
    `NET_REVENUE_INTEREST` DECIMAL(18,2),
    `MEASURED_PRODUCTION` DECIMAL(18,2),
    `ESTIMATED_PRODUCTION` DECIMAL(18,2),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
