ALTER TABLE `PRODUCTION_FORECAST`
ADD CONSTRAINT FK_PRODUCTION_FORECAST_FORECAST FOREIGN KEY (`FORECAST_ID`) REFERENCES `FORECAST`(`FORECAST_ID`);

ALTER TABLE `PRODUCTION_FORECAST`
ADD CONSTRAINT FK_PRODUCTION_FORECAST_FIELD FOREIGN KEY (`FIELD_ID`) REFERENCES `FIELD`(`FIELD_ID`);
