CREATE TABLE GL_ACCOUNT
(
    GL_ACCOUNT_ID VARCHAR2(40) NOT NULL,
    ACCOUNT_NUMBER VARCHAR2(40),
    ACCOUNT_NAME VARCHAR2(255),
    ACCOUNT_TYPE VARCHAR2(40),
    PARENT_ACCOUNT_ID VARCHAR2(40),
    NORMAL_BALANCE VARCHAR2(10),
    OPENING_BALANCE NUMBER(18,2),
    CURRENT_BALANCE NUMBER(18,2),
    DESCRIPTION VARCHAR2(4000),
    ACTIVE_IND VARCHAR2(1),
    PPDM_GUID VARCHAR2(40),
    REMARK VARCHAR2(4000),
    SOURCE VARCHAR2(40),
    ROW_QUALITY VARCHAR2(40),
    ROW_CREATED_BY VARCHAR2(40),
    ROW_CREATED_DATE DATE,
    ROW_CHANGED_BY VARCHAR2(40),
    ROW_CHANGED_DATE DATE,
    ROW_EFFECTIVE_DATE DATE,
    ROW_EXPIRY_DATE DATE,
    ROW_ID VARCHAR2(40)
);

