raiserror ('CREATING TABLE COMPLETION_STRING', 10,1) with nowait

CREATE TABLE COMPLETION_STRING
(
    COMPLETION_ID NVARCHAR(40) NOT NULL,
    WELL_CONSTRUCTION_ID NVARCHAR(40),
    COMPLETION_TYPE NVARCHAR(40),
    TOP_DEPTH NUMERIC(18,2),
    BOTTOM_DEPTH NUMERIC(18,2),
    DIAMETER NUMERIC(18,4),
    DIAMETER_UNIT NVARCHAR(10),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);

