raiserror ('CREATING TABLE DRILLING_REPORT', 10,1) with nowait

CREATE TABLE DRILLING_REPORT
(
    DRILLING_REPORT_ID NVARCHAR(40) NOT NULL,
    DRILLING_OPERATION_ID NVARCHAR(40),
    REPORT_DATE DATETIME,
    DEPTH NUMERIC(18,2),
    ACTIVITY NVARCHAR(255),
    HOURS NUMERIC(18,2),
    REPORTED_BY NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);

