raiserror ('CREATING TABLE DRILLING_OPERATION', 10,1) with nowait

CREATE TABLE DRILLING_OPERATION
(
    DRILLING_OPERATION_ID NVARCHAR(40) NOT NULL,
    WELL_UWI NVARCHAR(40),
    WELL_NAME NVARCHAR(255),
    SPUD_DATE DATETIME,
    COMPLETION_DATE DATETIME,
    STATUS NVARCHAR(40),
    CURRENT_DEPTH NUMERIC(18,2),
    TARGET_DEPTH NUMERIC(18,2),
    DRILLING_CONTRACTOR NVARCHAR(255),
    RIG_NAME NVARCHAR(255),
    DAILY_COST NUMERIC(18,2),
    TOTAL_COST NUMERIC(18,2),
    CURRENCY NVARCHAR(10),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);

