raiserror ('CREATING TABLE PERFORATION', 10,1) with nowait

CREATE TABLE PERFORATION
(
    PERFORATION_ID NVARCHAR(40) NOT NULL,
    COMPLETION_ID NVARCHAR(40),
    TOP_DEPTH NUMERIC(18,2),
    BOTTOM_DEPTH NUMERIC(18,2),
    SHOTS_PER_FOOT INT,
    PERFORATION_TYPE NVARCHAR(40),
    PERFORATION_DATE DATETIME,
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);

