raiserror ('CREATING TABLE WELL_CONSTRUCTION', 10,1) with nowait

CREATE TABLE WELL_CONSTRUCTION
(
    WELL_CONSTRUCTION_ID NVARCHAR(40) NOT NULL,
    WELL_UWI NVARCHAR(40),
    STATUS NVARCHAR(40),
    START_DATE DATETIME,
    COMPLETION_DATE DATETIME,
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);

