using System;
using System.Collections.Generic;
using System.Linq;

namespace Beep.OilandGas.Models.DTOs.ProductionAccounting
{
    /// <summary>
    /// Report type enumeration.
    /// </summary>
    public enum ReportType
    {
        /// <summary>
        /// Internal operational report.
        /// </summary>
        InternalOperational,

        /// <summary>
        /// Internal lease report.
        /// </summary>
        InternalLease,

        /// <summary>
        /// Governmental report (federal, state, local).
        /// </summary>
        Governmental,

        /// <summary>
        /// Joint interest statement.
        /// </summary>
        JointInterest,

        /// <summary>
        /// Royalty owner statement.
        /// </summary>
        RoyaltyOwner
    }

    /// <summary>
    /// Represents a base report (DTO for reporting).
    /// </summary>
    public abstract class ReportDto
    {
        /// <summary>
        /// Gets or sets the report identifier.
        /// </summary>
        public string ReportId { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the report type.
        /// </summary>
        public ReportType ReportType { get; set; }

        /// <summary>
        /// Gets or sets the report period start date.
        /// </summary>
        public DateTime ReportPeriodStart { get; set; }

        /// <summary>
        /// Gets or sets the report period end date.
        /// </summary>
        public DateTime ReportPeriodEnd { get; set; }

        /// <summary>
        /// Gets or sets the generation date.
        /// </summary>
        public DateTime GenerationDate { get; set; } = DateTime.Now;

        /// <summary>
        /// Gets or sets the generated by.
        /// </summary>
        public string GeneratedBy { get; set; } = string.Empty;
    }


    /// <summary>
    /// Represents report summaries.
    /// </summary>
    public class ProductionReportSummaryDto
    {
        public decimal TotalProduction { get; set; }
        public int ProducingDays { get; set; }
        public decimal AverageDailyProduction { get; set; }
    }

    public class InventoryReportSummaryDto
    {
        public decimal OpeningInventory { get; set; }
        public decimal Receipts { get; set; }
        public decimal Deliveries { get; set; }
        public decimal ClosingInventory { get; set; }
    }

    public class AllocationReportSummaryDto
    {
        public int WellsAllocated { get; set; }
        public int LeasesAllocated { get; set; }
        public decimal TotalAllocatedVolume { get; set; }
    }

    public class MeasurementReportSummaryDto
    {
        public int MeasurementCount { get; set; }
        public decimal AverageAccuracy { get; set; }
        public int CalibrationsDue { get; set; }
    }

    public class CostReportSummaryDto
    {
        public decimal TotalLiftingCosts { get; set; }
        public decimal TotalOperatingCosts { get; set; }
        public decimal TotalMarketingCosts { get; set; }
        public decimal TotalCosts => TotalLiftingCosts + TotalOperatingCosts + TotalMarketingCosts;
    }

    public class GovernmentalProductionDataDto
    {
        public decimal OilProduction { get; set; }
        public decimal GasProduction { get; set; }
        public decimal WaterProduction { get; set; }
    }

    public class GovernmentalRoyaltyDataDto
    {
        public decimal RoyaltyVolume { get; set; }
        public decimal RoyaltyValue { get; set; }
        public decimal RoyaltyRate { get; set; }
    }

    public class GovernmentalTaxDataDto
    {
        public decimal SeveranceTax { get; set; }
        public decimal AdValoremTax { get; set; }
        public decimal TotalTaxes => SeveranceTax + AdValoremTax;
    }

    public class JIBParticipantDto
    {
        public string ParticipantId { get; set; } = string.Empty;
        public string CompanyName { get; set; } = string.Empty;
        public decimal WorkingInterest { get; set; }
        public decimal NetRevenueInterest { get; set; }
    }

    public class JIBChargeDto
    {
        public string ChargeId { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public decimal Amount { get; set; }
        public string Category { get; set; } = string.Empty;
    }

    public class JIBCreditDto
    {
        public string CreditId { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public decimal Amount { get; set; }
        public string Category { get; set; } = string.Empty;
    }
}

