ALTER TABLE `FEE_MINERAL_LEASE`
ADD CONSTRAINT FK_FEE_MINERAL_LEASE_LEASE FOREIGN KEY (`LEASE_ID`) REFERENCES `LEASE`(`LEASE_ID`);

ALTER TABLE `FEE_MINERAL_LEASE`
ADD CONSTRAINT FK_FEE_MINERAL_LEASE_PROPERTY FOREIGN KEY (`PROPERTY_ID`) REFERENCES `PROPERTY`(`PROPERTY_ID`);

ALTER TABLE `FEE_MINERAL_LEASE`
ADD CONSTRAINT FK_FEE_MINERAL_LEASE_MINERAL_OWNER_BA FOREIGN KEY (`MINERAL_OWNER_BA_ID`) REFERENCES `MINERAL_OWNER_BA`(`MINERAL_OWNER_BA_ID`);

ALTER TABLE `FEE_MINERAL_LEASE`
ADD CONSTRAINT FK_FEE_MINERAL_LEASE_SURFACE_OWNER_BA FOREIGN KEY (`SURFACE_OWNER_BA_ID`) REFERENCES `SURFACE_OWNER_BA`(`SURFACE_OWNER_BA_ID`);
