ALTER TABLE `GOVERNMENT_LEASE`
ADD CONSTRAINT FK_GOVERNMENT_LEASE_LEASE FOREIGN KEY (`LEASE_ID`) REFERENCES `LEASE`(`LEASE_ID`);

ALTER TABLE `GOVERNMENT_LEASE`
ADD CONSTRAINT FK_GOVERNMENT_LEASE_PROPERTY FOREIGN KEY (`PROPERTY_ID`) REFERENCES `PROPERTY`(`PROPERTY_ID`);
