ALTER TABLE "SALES_TRANSACTION"
ADD CONSTRAINT FK_SALES_TRANSACTION_RUN_TICKET FOREIGN KEY ("RUN_TICKET_ID") REFERENCES "RUN_TICKET"("RUN_TICKET_ID");

ALTER TABLE "SALES_TRANSACTION"
ADD CONSTRAINT FK_SALES_TRANSACTION_SALES_AGREEMENT FOREIGN KEY ("SALES_AGREEMENT_ID") REFERENCES "SALES_AGREEMENT"("SALES_AGREEMENT_ID");

ALTER TABLE "SALES_TRANSACTION"
ADD CONSTRAINT FK_SALES_TRANSACTION_CUSTOMER_BA FOREIGN KEY ("CUSTOMER_BA_ID") REFERENCES "CUSTOMER_BA"("CUSTOMER_BA_ID");
