ALTER TABLE `EXPLORATION_PROGRAM`
ADD CONSTRAINT FK_EXPLORATION_PROGRAM_PROGRAM FOREIGN KEY (`PROGRAM_ID`) REFERENCES `PROGRAM`(`PROGRAM_ID`);

ALTER TABLE `EXPLORATION_PROGRAM`
ADD CONSTRAINT FK_EXPLORATION_PROGRAM_FIELD FOREIGN KEY (`FIELD_ID`) REFERENCES `FIELD`(`FIELD_ID`);
