ALTER TABLE `PROSPECT_ECONOMIC`
ADD CONSTRAINT FK_PROSPECT_ECONOMIC_PROSPECT FOREIGN KEY (`PROSPECT_ID`) REFERENCES `PROSPECT`(`PROSPECT_ID`);

ALTER TABLE `PROSPECT_ECONOMIC`
ADD CONSTRAINT FK_PROSPECT_ECONOMIC_ECONOMIC FOREIGN KEY (`ECONOMIC_ID`) REFERENCES `ECONOMIC`(`ECONOMIC_ID`);
