ALTER TABLE `PROSPECT_RANKING`
ADD CONSTRAINT FK_PROSPECT_RANKING_PROSPECT FOREIGN KEY (`PROSPECT_ID`) REFERENCES `PROSPECT`(`PROSPECT_ID`);

ALTER TABLE `PROSPECT_RANKING`
ADD CONSTRAINT FK_PROSPECT_RANKING_RANKING FOREIGN KEY (`RANKING_ID`) REFERENCES `RANKING`(`RANKING_ID`);
