ALTER TABLE `PROSPECT`
ADD CONSTRAINT FK_PROSPECT_PRIMARY_FIELD FOREIGN KEY (`PRIMARY_FIELD_ID`) REFERENCES `PRIMARY_FIELD`(`PRIMARY_FIELD_ID`);

ALTER TABLE `PROSPECT`
ADD CONSTRAINT FK_PROSPECT_PLAY FOREIGN KEY (`PLAY_ID`) REFERENCES `PLAY`(`PLAY_ID`);

ALTER TABLE `PROSPECT`
ADD CONSTRAINT FK_PROSPECT_STRAT_UNIT FOREIGN KEY (`STRAT_UNIT_ID`) REFERENCES `STRAT_UNIT`(`STRAT_UNIT_ID`);

ALTER TABLE `PROSPECT`
ADD CONSTRAINT FK_PROSPECT_COORD_SYSTEM FOREIGN KEY (`COORD_SYSTEM_ID`) REFERENCES `COORD_SYSTEM`(`COORD_SYSTEM_ID`);

ALTER TABLE `PROSPECT`
ADD CONSTRAINT FK_PROSPECT_LOCAL_COORD_SYSTEM FOREIGN KEY (`LOCAL_COORD_SYSTEM_ID`) REFERENCES `LOCAL_COORD_SYSTEM`(`LOCAL_COORD_SYSTEM_ID`);

ALTER TABLE `PROSPECT`
ADD CONSTRAINT FK_PROSPECT_COORD_ACQUISITION FOREIGN KEY (`COORD_ACQUISITION_ID`) REFERENCES `COORD_ACQUISITION`(`COORD_ACQUISITION_ID`);

ALTER TABLE `PROSPECT`
ADD CONSTRAINT FK_PROSPECT_FIELD FOREIGN KEY (`FIELD_ID`) REFERENCES `FIELD`(`FIELD_ID`);
