ALTER TABLE `PROSPECT_PLAY`
ADD CONSTRAINT FK_PROSPECT_PLAY_PROSPECT FOREIGN KEY (`PROSPECT_ID`) REFERENCES `PROSPECT`(`PROSPECT_ID`);

ALTER TABLE `PROSPECT_PLAY`
ADD CONSTRAINT FK_PROSPECT_PLAY_PLAY FOREIGN KEY (`PLAY_ID`) REFERENCES `PLAY`(`PLAY_ID`);
