CREATE TABLE `PROSPECT_BA`
(
    `PROSPECT_ID` VARCHAR(40),
    `BUSINESS_ASSOCIATE_ID` VARCHAR(40),
    `ROLE_TYPE` VARCHAR(50),
    `WORKING_INTEREST` DECIMAL(18,2),
    `CARRIED_INTEREST` DECIMAL(18,2),
    `DESCRIPTION` VARCHAR(2000),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `EFFECTIVE_DATE` DATETIME,
    `EXPIRY_DATE` DATETIME,
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_QUALITY` VARCHAR(40)
);
