raiserror ('CREATING TABLE HEAT_MAP_DATA_POINT', 10,1) with nowait

CREATE TABLE HEAT_MAP_DATA_POINT
(
    HEAT_MAP_DATA_POINT_ID NVARCHAR(40) NOT NULL,
    HEAT_MAP_ID NVARCHAR(40),
    X NUMERIC(18,2),
    Y NUMERIC(18,2),
    ORIGINAL_X NUMERIC(18,2),
    ORIGINAL_Y NUMERIC(18,2),
    VALUE NUMERIC(18,2),
    LABEL NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
