raiserror ('CREATING TABLE HEAT_MAP_CONFIGURATION', 10,1) with nowait

CREATE TABLE HEAT_MAP_CONFIGURATION
(
    HEAT_MAP_ID NVARCHAR(40),
    CONFIGURATION_NAME NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30)
);
