CREATE TABLE "ORGANIZATION_HIERARCHY_CONFIG"
(
    "ORGANIZATION_ID" VARCHAR(40),
    "HIERARCHY_LEVEL" INTEGER NOT NULL,
    "LEVEL_NAME" VARCHAR(255),
    "ASSET_TYPE" VARCHAR(50),
    "PARENT_LEVEL" INTEGER,
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "EFFECTIVE_DATE" TIMESTAMP,
    "EXPIRY_DATE" TIMESTAMP,
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_QUALITY" VARCHAR(40)
);
