CREATE TABLE "SETUP_WIZARD_LOG"
(
    "SETUP_LOG_ID" VARCHAR(40),
    "ORGANIZATION_ID" VARCHAR(40),
    "SETUP_STEP" VARCHAR(255),
    "SETUP_DATA" VARCHAR(255),
    "EXECUTED_BY" VARCHAR(255),
    "EXECUTION_DATE" TIMESTAMP,
    "STATUS" VARCHAR(50),
    "ERROR_MESSAGE" VARCHAR(255),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_QUALITY" VARCHAR(40)
);
