ALTER TABLE "USER_ASSET_ACCESS"
ADD CONSTRAINT FK_USER_ASSET_ACCESS_USER FOREIGN KEY ("USER_ID") REFERENCES "USER"("USER_ID");

ALTER TABLE "USER_ASSET_ACCESS"
ADD CONSTRAINT FK_USER_ASSET_ACCESS_ASSET FOREIGN KEY ("ASSET_ID") REFERENCES "ASSET"("ASSET_ID");

ALTER TABLE "USER_ASSET_ACCESS"
ADD CONSTRAINT FK_USER_ASSET_ACCESS_ORGANIZATION FOREIGN KEY ("ORGANIZATION_ID") REFERENCES "ORGANIZATION"("ORGANIZATION_ID");
