ALTER TABLE "USER"
ADD CONSTRAINT FK_USER_TENANT FOREIGN KEY ("TENANT_ID") REFERENCES "TENANT"("TENANT_ID");

ALTER TABLE "USER"
ADD CONSTRAINT FK_USER_AREA FOREIGN KEY ("AREA_ID") REFERENCES "AREA"("AREA_ID");

ALTER TABLE "USER"
ADD CONSTRAINT FK_USER_BUSINESS_ASSOCIATE FOREIGN KEY ("BUSINESS_ASSOCIATE_ID") REFERENCES "BUSINESS_ASSOCIATE"("BUSINESS_ASSOCIATE_ID");
