ALTER TABLE "USER_ROLE"
ADD CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY ("USER_ID") REFERENCES "USER"("USER_ID");

ALTER TABLE "USER_ROLE"
ADD CONSTRAINT FK_USER_ROLE_ROLE FOREIGN KEY ("ROLE_ID") REFERENCES "ROLE"("ROLE_ID");

ALTER TABLE "USER_ROLE"
ADD CONSTRAINT FK_USER_ROLE_AREA FOREIGN KEY ("AREA_ID") REFERENCES "AREA"("AREA_ID");

ALTER TABLE "USER_ROLE"
ADD CONSTRAINT FK_USER_ROLE_BUSINESS_ASSOCIATE FOREIGN KEY ("BUSINESS_ASSOCIATE_ID") REFERENCES "BUSINESS_ASSOCIATE"("BUSINESS_ASSOCIATE_ID");
