CREATE TABLE ACTUAL_DELIVERY
(
    ACTUAL_DELIVERY_ID TEXT NOT NULL,
    NOMINATION_ID TEXT,
    DELIVERY_DATE DATETIME,
    ACTUAL_VOLUME REAL,
    DELIVERY_POINT TEXT,
    ALLOCATION_METHOD TEXT,
    RUN_TICKET_NUMBER TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
