CREATE TABLE IMBALANCE
(
    IMBALANCE_ID TEXT NOT NULL,
    NOMINATION_ID TEXT,
    PERIOD_START DATETIME,
    PERIOD_END DATETIME,
    NOMINATED_VOLUME REAL,
    ACTUAL_VOLUME REAL,
    IMBALANCE_AMOUNT REAL,
    TOLERANCE_PERCENTAGE REAL,
    STATUS TEXT,
    SETTLEMENT_DATE DATETIME,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
