CREATE TABLE PRODUCTION_AVAIL
(
    PRODUCTION_AVAIL_ID TEXT NOT NULL,
    PROPERTY_ID TEXT,
    AVAIL_DATE DATETIME,
    ESTIMATED_VOLUME REAL,
    AVAILABLE_FOR_DELIVERY REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
