CREATE TABLE ROD_SECTION
(
    ROD_SECTION_ID TEXT NOT NULL,
    SUCKER_ROD_STRING_ID TEXT,
    DIAMETER REAL,
    LENGTH REAL,
    DENSITY REAL,
    WEIGHT REAL,
    SECTION_ORDER INTEGER,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT
);
