ALTER TABLE DATA_VERSION_SNAPSHOT
ADD CONSTRAINT FK_DATA_VERSION_SNAPSHOT_VERSION_SNAPSHOT FOREIGN KEY (VERSION_SNAPSHOT_ID) REFERENCES VERSION_SNAPSHOT(VERSION_SNAPSHOT_ID);

ALTER TABLE DATA_VERSION_SNAPSHOT
ADD CONSTRAINT FK_DATA_VERSION_SNAPSHOT_ENTITY FOREIGN KEY (ENTITY_ID) REFERENCES ENTITY(ENTITY_ID);

ALTER TABLE DATA_VERSION_SNAPSHOT
ADD CONSTRAINT FK_DATA_VERSION_SNAPSHOT_AREA FOREIGN KEY (AREA_ID) REFERENCES AREA(AREA_ID);

ALTER TABLE DATA_VERSION_SNAPSHOT
ADD CONSTRAINT FK_DATA_VERSION_SNAPSHOT_BUSINESS_ASSOCIATE FOREIGN KEY (BUSINESS_ASSOCIATE_ID) REFERENCES BUSINESS_ASSOCIATE(BUSINESS_ASSOCIATE_ID);
