raiserror ('CREATING TABLE DATA_VERSION_SNAPSHOT', 10,1) with nowait

CREATE TABLE DATA_VERSION_SNAPSHOT
(
    VERSION_SNAPSHOT_ID NVARCHAR(40),
    TABLE_NAME NVARCHAR(255),
    ENTITY_ID NVARCHAR(40),
    VERSION_NUMBER INT,
    VERSION_LABEL NVARCHAR(255),
    ENTITY_DATA_JSON NVARCHAR(255),
    CHANGE_DESCRIPTION NVARCHAR(2000),
    CREATED_DATE DATETIME,
    CREATED_BY NVARCHAR(30),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    SOURCE NVARCHAR(40),
    REMARK NVARCHAR(2000),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME
);
