ALTER TABLE DATA_VERSION_COMPARISON
ADD CONSTRAINT FK_DATA_VERSION_COMPARISON_COMPARISON FOREIGN KEY (COMPARISON_ID) REFERENCES COMPARISON(COMPARISON_ID);

ALTER TABLE DATA_VERSION_COMPARISON
ADD CONSTRAINT FK_DATA_VERSION_COMPARISON_ENTITY FOREIGN KEY (ENTITY_ID) REFERENCES ENTITY(ENTITY_ID);

ALTER TABLE DATA_VERSION_COMPARISON
ADD CONSTRAINT FK_DATA_VERSION_COMPARISON_AREA FOREIGN KEY (AREA_ID) REFERENCES AREA(AREA_ID);

ALTER TABLE DATA_VERSION_COMPARISON
ADD CONSTRAINT FK_DATA_VERSION_COMPARISON_BUSINESS_ASSOCIATE FOREIGN KEY (BUSINESS_ASSOCIATE_ID) REFERENCES BUSINESS_ASSOCIATE(BUSINESS_ASSOCIATE_ID);
