raiserror ('CREATING TABLE DATA_QUALITY_TREND', 10,1) with nowait

CREATE TABLE DATA_QUALITY_TREND
(
    TREND_ID NVARCHAR(40),
    TABLE_NAME NVARCHAR(255),
    TREND_DATE DATETIME,
    QUALITY_SCORE NUMERIC(18,2),
    RECORD_COUNT INT,
    ISSUE_COUNT INT,
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    SOURCE NVARCHAR(40),
    REMARK NVARCHAR(2000),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME
);
