ALTER TABLE DATA_ACCESS_AUDIT
ADD CONSTRAINT FK_DATA_ACCESS_AUDIT_ACCESS_AUDIT FOREIGN KEY (ACCESS_AUDIT_ID) REFERENCES ACCESS_AUDIT(ACCESS_AUDIT_ID);

ALTER TABLE DATA_ACCESS_AUDIT
ADD CONSTRAINT FK_DATA_ACCESS_AUDIT_USER FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);

ALTER TABLE DATA_ACCESS_AUDIT
ADD CONSTRAINT FK_DATA_ACCESS_AUDIT_ENTITY FOREIGN KEY (ENTITY_ID) REFERENCES ENTITY(ENTITY_ID);

ALTER TABLE DATA_ACCESS_AUDIT
ADD CONSTRAINT FK_DATA_ACCESS_AUDIT_SESSION FOREIGN KEY (SESSION_ID) REFERENCES SESSION(SESSION_ID);

ALTER TABLE DATA_ACCESS_AUDIT
ADD CONSTRAINT FK_DATA_ACCESS_AUDIT_AREA FOREIGN KEY (AREA_ID) REFERENCES AREA(AREA_ID);

ALTER TABLE DATA_ACCESS_AUDIT
ADD CONSTRAINT FK_DATA_ACCESS_AUDIT_BUSINESS_ASSOCIATE FOREIGN KEY (BUSINESS_ASSOCIATE_ID) REFERENCES BUSINESS_ASSOCIATE(BUSINESS_ASSOCIATE_ID);
