ALTER TABLE DATA_QUALITY_TREND
ADD CONSTRAINT FK_DATA_QUALITY_TREND_TREND FOREIGN KEY (TREND_ID) REFERENCES TREND(TREND_ID);

ALTER TABLE DATA_QUALITY_TREND
ADD CONSTRAINT FK_DATA_QUALITY_TREND_AREA FOREIGN KEY (AREA_ID) REFERENCES AREA(AREA_ID);

ALTER TABLE DATA_QUALITY_TREND
ADD CONSTRAINT FK_DATA_QUALITY_TREND_BUSINESS_ASSOCIATE FOREIGN KEY (BUSINESS_ASSOCIATE_ID) REFERENCES BUSINESS_ASSOCIATE(BUSINESS_ASSOCIATE_ID);
