raiserror ('CREATING TABLE DATA_ACCESS_AUDIT', 10,1) with nowait

CREATE TABLE DATA_ACCESS_AUDIT
(
    ACCESS_AUDIT_ID NVARCHAR(40),
    USER_ID NVARCHAR(40),
    TABLE_NAME NVARCHAR(255),
    ENTITY_ID NVARCHAR(40),
    ACCESS_TYPE NVARCHAR(50),
    ACCESS_DATE DATETIME,
    IP_ADDRESS NVARCHAR(255),
    SESSION_ID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME
);
