raiserror ('CREATING TABLE DATA_VALIDATION_RULE', 10,1) with nowait

CREATE TABLE DATA_VALIDATION_RULE
(
    VALIDATION_RULE_ID NVARCHAR(40),
    TABLE_NAME NVARCHAR(255),
    FIELD_NAME NVARCHAR(255),
    RULE_NAME NVARCHAR(255),
    RULE_TYPE NVARCHAR(50),
    RULE_VALUE NVARCHAR(255),
    ERROR_MESSAGE NVARCHAR(255),
    SEVERITY NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    SOURCE NVARCHAR(40),
    REMARK NVARCHAR(2000),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME
);
