raiserror ('CREATING TABLE DATA_QUALITY_METRICS', 10,1) with nowait

CREATE TABLE DATA_QUALITY_METRICS
(
    METRICS_ID NVARCHAR(40),
    TABLE_NAME NVARCHAR(255),
    TOTAL_RECORDS INT,
    COMPLETE_RECORDS INT,
    INCOMPLETE_RECORDS INT,
    COMPLETENESS_SCORE NUMERIC(18,2),
    ACCURACY_SCORE NUMERIC(18,2),
    CONSISTENCY_SCORE NUMERIC(18,2),
    OVERALL_QUALITY_SCORE NUMERIC(18,2),
    METRICS_DATE DATETIME,
    FIELD_METRICS_JSON NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    SOURCE NVARCHAR(40),
    REMARK NVARCHAR(2000),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME
);
