ALTER TABLE DATA_QUALITY_ALERT
ADD CONSTRAINT FK_DATA_QUALITY_ALERT_ALERT FOREIGN KEY (ALERT_ID) REFERENCES ALERT(ALERT_ID);

ALTER TABLE DATA_QUALITY_ALERT
ADD CONSTRAINT FK_DATA_QUALITY_ALERT_AREA FOREIGN KEY (AREA_ID) REFERENCES AREA(AREA_ID);

ALTER TABLE DATA_QUALITY_ALERT
ADD CONSTRAINT FK_DATA_QUALITY_ALERT_BUSINESS_ASSOCIATE FOREIGN KEY (BUSINESS_ASSOCIATE_ID) REFERENCES BUSINESS_ASSOCIATE(BUSINESS_ASSOCIATE_ID);
