raiserror ('CREATING TABLE DEVELOPMENT_COSTS', 10,1) with nowait

CREATE TABLE DEVELOPMENT_COSTS
(
    DEVELOPMENT_COST_ID NVARCHAR(40),
    PROPERTY_ID NVARCHAR(40),
    DEVELOPMENT_WELL_DRILLING_COSTS NUMERIC(18,2),
    DEVELOPMENT_WELL_EQUIPMENT NUMERIC(18,2),
    SUPPORT_EQUIPMENT_AND_FACILITIES NUMERIC(18,2),
    SERVICE_WELL_COSTS NUMERIC(18,2),
    TOTAL_DEVELOPMENT_COSTS NUMERIC(18,2),
    COST_DATE DATETIME,
    COST_CENTER_ID NVARCHAR(40),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
