CREATE TABLE "EXPORT_HISTORY"
(
    "EXPORT_HISTORY_ID" VARCHAR2(40) NOT NULL,
    "EXPORT_TYPE" VARCHAR2(50),
    "EXPORT_FORMAT" VARCHAR2(255),
    "EXPORT_DATE" DATE,
    "EXPORTED_BY" VARCHAR2(255),
    "FILE_PATH" VARCHAR2(255),
    "RECORD_COUNT" NUMBER(10),
    "STATUS" VARCHAR2(50),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE
);
