raiserror ('CREATING TABLE ABANDONMENT_STATUS', 10,1) with nowait

CREATE TABLE ABANDONMENT_STATUS
(
    ABANDONMENT_STATUS_ID NVARCHAR(40) NOT NULL,
    WELL_ABANDONMENT_ID NVARCHAR(40),
    STATUS NVARCHAR(50),
    STATUS_DATE DATETIME,
    STATUS_CHANGED_BY NVARCHAR(50),
    NOTES NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
