ALTER TABLE `WELL_TEST_DATA`
ADD CONSTRAINT FK_WELL_TEST_DATA_AREA FOREIGN KEY (`AREA_ID`) REFERENCES `AREA`(`AREA_ID`);

ALTER TABLE `WELL_TEST_DATA`
ADD CONSTRAINT FK_WELL_TEST_DATA_BUSINESS_ASSOCIATE FOREIGN KEY (`BUSINESS_ASSOCIATE_ID`) REFERENCES `BUSINESS_ASSOCIATE`(`BUSINESS_ASSOCIATE_ID`);
