CREATE TABLE EXCHANGE_TRANSACTION
(
    EXCHANGE_TRANSACTION_ID TEXT NOT NULL,
    EXCHANGE_CONTRACT_ID TEXT,
    TRANSACTION_DATE DATETIME,
    RECEIPT_VOLUME REAL,
    RECEIPT_PRICE REAL,
    RECEIPT_LOCATION TEXT,
    DELIVERY_VOLUME REAL,
    DELIVERY_PRICE REAL,
    DELIVERY_LOCATION TEXT,
    STATUS TEXT,
    DESCRIPTION TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
