CREATE TABLE EXCHANGE_COMMITMENT
(
    EXCHANGE_COMMITMENT_ID TEXT NOT NULL,
    EXCHANGE_CONTRACT_ID TEXT,
    COMMITMENT_TYPE TEXT,
    COMMITTED_VOLUME REAL,
    ACTUAL_VOLUME_DELIVERED REAL,
    DELIVERY_PERIOD_START DATETIME,
    DELIVERY_PERIOD_END DATETIME,
    STATUS TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
