ALTER TABLE "EXPLORATION_COSTS"
ADD CONSTRAINT FK_EXPLORATION_COSTS_EXPLORATION_COST FOREIGN KEY ("EXPLORATION_COST_ID") REFERENCES "EXPLORATION_COST"("EXPLORATION_COST_ID");

ALTER TABLE "EXPLORATION_COSTS"
ADD CONSTRAINT FK_EXPLORATION_COSTS_PROPERTY FOREIGN KEY ("PROPERTY_ID") REFERENCES "PROPERTY"("PROPERTY_ID");

ALTER TABLE "EXPLORATION_COSTS"
ADD CONSTRAINT FK_EXPLORATION_COSTS_WELL FOREIGN KEY ("WELL_ID") REFERENCES "WELL"("WELL_ID");

ALTER TABLE "EXPLORATION_COSTS"
ADD CONSTRAINT FK_EXPLORATION_COSTS_COST_CENTER FOREIGN KEY ("COST_CENTER_ID") REFERENCES "COST_CENTER"("COST_CENTER_ID");
