CREATE TABLE "EXPLORATION_BUDGET"
(
    "PROGRAM_ID" VARCHAR2(40),
    "BUDGET_YEAR" NUMBER(18,2) NOT NULL,
    "BUDGET_AMOUNT" NUMBER(18,2),
    "BUDGET_CURRENCY" VARCHAR2(255),
    "BUDGET_CATEGORY" VARCHAR2(255),
    "ACTUAL_AMOUNT" NUMBER(18,2),
    "VARIANCE" NUMBER(18,2),
    "DESCRIPTION" VARCHAR2(2000),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "EFFECTIVE_DATE" DATE,
    "EXPIRY_DATE" DATE,
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_QUALITY" VARCHAR2(40)
);
