ALTER TABLE "PROSPECT_DISCOVERY"
ADD CONSTRAINT FK_PROSPECT_DISCOVERY_PROSPECT FOREIGN KEY ("PROSPECT_ID") REFERENCES "PROSPECT"("PROSPECT_ID");

ALTER TABLE "PROSPECT_DISCOVERY"
ADD CONSTRAINT FK_PROSPECT_DISCOVERY_DISCOVERY FOREIGN KEY ("DISCOVERY_ID") REFERENCES "DISCOVERY"("DISCOVERY_ID");
