ALTER TABLE "PROSPECT_RESERVOIR"
ADD CONSTRAINT FK_PROSPECT_RESERVOIR_PROSPECT FOREIGN KEY ("PROSPECT_ID") REFERENCES "PROSPECT"("PROSPECT_ID");

ALTER TABLE "PROSPECT_RESERVOIR"
ADD CONSTRAINT FK_PROSPECT_RESERVOIR_RESERVOIR FOREIGN KEY ("RESERVOIR_ID") REFERENCES "RESERVOIR"("RESERVOIR_ID");

ALTER TABLE "PROSPECT_RESERVOIR"
ADD CONSTRAINT FK_PROSPECT_RESERVOIR_STRAT_UNIT FOREIGN KEY ("STRAT_UNIT_ID") REFERENCES "STRAT_UNIT"("STRAT_UNIT_ID");
