ALTER TABLE "PROSPECT_FIELD"
ADD CONSTRAINT FK_PROSPECT_FIELD_PROSPECT FOREIGN KEY ("PROSPECT_ID") REFERENCES "PROSPECT"("PROSPECT_ID");

ALTER TABLE "PROSPECT_FIELD"
ADD CONSTRAINT FK_PROSPECT_FIELD_FIELD FOREIGN KEY ("FIELD_ID") REFERENCES "FIELD"("FIELD_ID");
