ALTER TABLE "PROSPECT_RISK_ASSESSMENT"
ADD CONSTRAINT FK_PROSPECT_RISK_ASSESSMENT_PROSPECT FOREIGN KEY ("PROSPECT_ID") REFERENCES "PROSPECT"("PROSPECT_ID");

ALTER TABLE "PROSPECT_RISK_ASSESSMENT"
ADD CONSTRAINT FK_PROSPECT_RISK_ASSESSMENT_ASSESSMENT FOREIGN KEY ("ASSESSMENT_ID") REFERENCES "ASSESSMENT"("ASSESSMENT_ID");
