CREATE TABLE "PROSPECT_PORTFOLIO"
(
    "PORTFOLIO_ID" VARCHAR2(40),
    "PORTFOLIO_NAME" VARCHAR2(255),
    "DESCRIPTION" VARCHAR2(2000),
    "STRATEGIC_OBJECTIVES" VARCHAR2(255),
    "CREATION_DATE" DATE,
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "EFFECTIVE_DATE" DATE,
    "EXPIRY_DATE" DATE,
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_QUALITY" VARCHAR2(40)
);
