CREATE TABLE `EXCHANGE_CONTRACT`
(
    `EXCHANGE_CONTRACT_ID` VARCHAR(40) NOT NULL,
    `CONTRACT_NUMBER` VARCHAR(255),
    `COUNTERPARTY_BA_ID` VARCHAR(40),
    `CONTRACT_TYPE` VARCHAR(50),
    `COMMODITY_TYPE` VARCHAR(50),
    `CONTRACT_DATE` DATETIME,
    `EFFECTIVE_DATE` DATETIME,
    `EXPIRY_DATE` DATETIME,
    `STATUS` VARCHAR(50),
    `DESCRIPTION` VARCHAR(2000),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME
);
