CREATE TABLE `EXCHANGE_TRANSACTION`
(
    `EXCHANGE_TRANSACTION_ID` VARCHAR(40) NOT NULL,
    `EXCHANGE_CONTRACT_ID` VARCHAR(40),
    `TRANSACTION_DATE` DATETIME,
    `RECEIPT_VOLUME` DECIMAL(18,2),
    `RECEIPT_PRICE` DECIMAL(18,2),
    `RECEIPT_LOCATION` VARCHAR(255),
    `DELIVERY_VOLUME` DECIMAL(18,2),
    `DELIVERY_PRICE` DECIMAL(18,2),
    `DELIVERY_LOCATION` VARCHAR(255),
    `STATUS` VARCHAR(50),
    `DESCRIPTION` VARCHAR(2000),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME
);
