CREATE TABLE GAS_PIPELINE_FLOW_PROPERTIES
(
    GAS_PIPELINE_FLOW_PROPERTIES_ID TEXT NOT NULL,
    PIPELINE_PROPERTIES_ID TEXT,
    GAS_FLOW_RATE REAL,
    GAS_SPECIFIC_GRAVITY REAL,
    GAS_MOLECULAR_WEIGHT REAL,
    BASE_PRESSURE REAL,
    BASE_TEMPERATURE REAL,
    Z_FACTOR REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT
);
