CREATE TABLE LIQUID_PIPELINE_FLOW_PROPERTIES
(
    LIQUID_PIPELINE_FLOW_PROPERTIES_ID TEXT NOT NULL,
    PIPELINE_PROPERTIES_ID TEXT,
    LIQUID_FLOW_RATE REAL,
    LIQUID_SPECIFIC_GRAVITY REAL,
    LIQUID_VISCOSITY REAL,
    LIQUID_DENSITY REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT
);
