CREATE TABLE PIPELINE_MAINTENANCE_SCHEDULE
(
    PIPELINE_ID TEXT,
    SCHEDULE_ID TEXT,
    SCHEDULE_TYPE TEXT,
    FREQUENCY TEXT,
    NEXT_DUE_DATE DATETIME,
    DESCRIPTION TEXT,
    ACTIVE_IND TEXT,
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT
);
