CREATE TABLE PIPELINE_RISK_ASSESSMENT
(
    PIPELINE_ID TEXT,
    RISK_ASSESSMENT_ID TEXT,
    ASSESSMENT_DATE DATETIME,
    RISK_SCORE REAL NOT NULL,
    ASSESSMENT_METHOD TEXT,
    RISK_FACTORS TEXT,
    SEGMENT_ID TEXT,
    DESCRIPTION TEXT,
    ACTIVE_IND TEXT,
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT
);
