CREATE TABLE R_PIPELINE_TYPE
(
    PIPELINE_TYPE TEXT,
    ABBREVIATION TEXT,
    ACTIVE_IND TEXT,
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    LONG_NAME TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SHORT_NAME TEXT,
    SOURCE TEXT,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT
);
