CREATE TABLE `PRICE_INDEX`
(
    `PRICE_INDEX_ID` VARCHAR(40) NOT NULL,
    `INDEX_NAME` VARCHAR(255),
    `COMMODITY_TYPE` VARCHAR(50),
    `PRICE_DATE` DATETIME,
    `PRICE_VALUE` DECIMAL(18,2),
    `CURRENCY_CODE` VARCHAR(255),
    `PRICING_POINT` VARCHAR(255),
    `UNIT` VARCHAR(255),
    `SOURCE` VARCHAR(40),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME
);
