CREATE TABLE GAS_LIFT_DESIGN
(
    DESIGN_ID TEXT,
    WELL_UWI TEXT,
    DESIGN_DATE DATETIME,
    NUMBER_OF_VALVES TEXT(255),
    TOTAL_GAS_INJECTION_RATE TEXT(255),
    EXPECTED_PRODUCTION_RATE TEXT(255),
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT
);
