CREATE TABLE GAS_LIFT_PERFORMANCE
(
    PERFORMANCE_ID TEXT,
    WELL_UWI TEXT,
    PERFORMANCE_DATE DATETIME,
    GAS_INJECTION_RATE TEXT(255),
    PRODUCTION_RATE TEXT(255),
    GAS_LIQUID_RATIO TEXT(255),
    EFFICIENCY TEXT(255),
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT
);
