-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: ACCESS_CONTROL_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY UAA_PK
ALTER TABLE USER_ASSET_ACCESS ADD CONSTRAINT UAA_PK PRIMARY KEY
(
	USER_ID,
	ASSET_TYPE,
	ASSET_ID
);

-- CREATING PRIMARY KEY RP_PK
ALTER TABLE ROLE_PERMISSION ADD CONSTRAINT RP_PK PRIMARY KEY
(
	ROLE_ID,
	PERMISSION_ID
);

-- CREATING PRIMARY KEY OHC_PK
ALTER TABLE ORGANIZATION_HIERARCHY_CONFIG ADD CONSTRAINT OHC_PK PRIMARY KEY
(
	ORGANIZATION_ID,
	HIERARCHY_LEVEL
);

-- CREATING PRIMARY KEY UP_PK
ALTER TABLE USER_PROFILE ADD CONSTRAINT UP_PK PRIMARY KEY
(
	USER_ID
);

-- CREATING PRIMARY KEY SWL_PK
ALTER TABLE SETUP_WIZARD_LOG ADD CONSTRAINT SWL_PK PRIMARY KEY
(
	SETUP_LOG_ID
);
