-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: EXPLORATION_PERMIT_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE EXPLORATION_PERMIT
CREATE TABLE exploration_permit
(
	PERMIT_ID VARCHAR(40) NOT NULL,
	PERMIT_NUMBER VARCHAR(40),
	FIELD_ID VARCHAR(40),
	PERMIT_HOLDER VARCHAR(40),
	PERMIT_START_DATE DATE,
	PERMIT_END_DATE DATE,
	PERMIT_AREA NUMERIC(18,5),
	PERMIT_AREA_OUOM VARCHAR(40),
	PERMIT_TERMS VARCHAR(2000),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);
