CREATE TABLE GL_ACCOUNT
(
    GL_ACCOUNT_ID VARCHAR(40) NOT NULL,
    ACCOUNT_NUMBER VARCHAR(40),
    ACCOUNT_NAME VARCHAR(255),
    ACCOUNT_TYPE VARCHAR(40),
    PARENT_ACCOUNT_ID VARCHAR(40),
    NORMAL_BALANCE VARCHAR(10),
    OPENING_BALANCE NUMERIC(18,2),
    CURRENT_BALANCE NUMERIC(18,2),
    DESCRIPTION VARCHAR(4000),
    ACTIVE_IND VARCHAR(1),
    PPDM_GUID VARCHAR(40),
    REMARK VARCHAR(4000),
    SOURCE VARCHAR(40),
    ROW_QUALITY VARCHAR(40),
    ROW_CREATED_BY VARCHAR(40),
    ROW_CREATED_DATE TIMESTAMP,
    ROW_CHANGED_BY VARCHAR(40),
    ROW_CHANGED_DATE TIMESTAMP,
    ROW_EFFECTIVE_DATE TIMESTAMP,
    ROW_EXPIRY_DATE TIMESTAMP,
    ROW_ID VARCHAR(40)
);

