-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PIPELINE_CONSTRUCTION_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_CONSTRUCTION
CREATE TABLE pipeline_construction
(
	PIPELINE_ID VARCHAR(40) NOT NULL,
	CONSTRUCTION_PHASE_NO VARCHAR(40) NOT NULL,
	PHASE_TYPE VARCHAR(40),
	PHASE_NAME VARCHAR(255),
	START_DATE DATE,
	END_DATE DATE,
	CONTRACTOR VARCHAR(40),
	INSPECTION_RECORDS VARCHAR(2000),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);

