-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PIPELINE_MAINTENANCE_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PIPELINE_MAINTENANCE_PK
ALTER TABLE PIPELINE_MAINTENANCE ADD CONSTRAINT PIPELINE_MAINTENANCE_PK PRIMARY KEY
(
	PIPELINE_ID,
	MAINTENANCE_ID
);

