-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PIPELINE_OPERATION_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PIPELINE_OPERATION_PK
ALTER TABLE PIPELINE_OPERATION ADD CONSTRAINT PIPELINE_OPERATION_PK PRIMARY KEY
(
	PIPELINE_ID,
	OPERATION_ID
);

