-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PIPELINE_STATION_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PIPELINE_STATION_PK
ALTER TABLE PIPELINE_STATION ADD CONSTRAINT PIPELINE_STATION_PK PRIMARY KEY
(
	PIPELINE_ID,
	STATION_ID
);
