-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PIPELINE_TEST_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PIPELINE_TEST_PK
ALTER TABLE PIPELINE_TEST ADD CONSTRAINT PIPELINE_TEST_PK PRIMARY KEY
(
	PIPELINE_ID,
	TEST_ID
);

