-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PIPELINE_INSPECTION_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_INSPECTION
CREATE TABLE pipeline_inspection
(
	PIPELINE_ID VARCHAR(40) NOT NULL,
	INSPECTION_ID VARCHAR(40) NOT NULL,
	INSPECTION_TYPE VARCHAR(40),
	INSPECTION_DATE DATE,
	INSPECTOR VARCHAR(40),
	TOOL_MODEL VARCHAR(255),
	TOOL_MANUFACTURER VARCHAR(40),
	SEGMENT_ID VARCHAR(40),
	STATION_MILEPOST NUMERIC(10,2),
	STATION_MILEPOST_OUOM VARCHAR(40),
	INSPECTION_RESULT VARCHAR(40),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);

