-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PIPELINE_FIELD_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_FIELD_PIPELINE_FK
ALTER TABLE PIPELINE_FIELD ADD CONSTRAINT PIPELINE_FIELD_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_FIELD_FIELD_FK
ALTER TABLE PIPELINE_FIELD ADD CONSTRAINT PIPELINE_FIELD_FIELD_FK FOREIGN KEY 
(
	FIELD_ID
)
REFERENCES FIELD
(
	FIELD_ID
);
