-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PIPELINE_STATION_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_STATION_PIPELINE_FK
ALTER TABLE PIPELINE_STATION ADD CONSTRAINT PIPELINE_STATION_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_STATION_FACILITY_FK
ALTER TABLE PIPELINE_STATION ADD CONSTRAINT PIPELINE_STATION_FACILITY_FK FOREIGN KEY 
(
	FACILITY_ID,
	FACILITY_TYPE
)
REFERENCES FACILITY
(
	FACILITY_ID,
	FACILITY_TYPE
);
