-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PIPELINE_INCIDENT_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_INCIDENT_PIPELINE_FK
ALTER TABLE PIPELINE_INCIDENT ADD CONSTRAINT PIPELINE_INCIDENT_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

