-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PIPELINE_OPERATION_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_OPERATION
CREATE TABLE pipeline_operation
(
	PIPELINE_ID VARCHAR(40) NOT NULL,
	OPERATION_ID VARCHAR(40) NOT NULL,
	OPERATION_DATE DATE,
	FLOW_RATE NUMERIC(10,2),
	FLOW_RATE_OUOM VARCHAR(40),
	PRESSURE NUMERIC(10,2),
	PRESSURE_OUOM VARCHAR(40),
	TEMPERATURE NUMERIC(10,2),
	TEMPERATURE_OUOM VARCHAR(40),
	THROUGHPUT NUMERIC(10,2),
	THROUGHPUT_OUOM VARCHAR(40),
	STATION_ID VARCHAR(40),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);

