-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PIPELINE_MAINTENANCE_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_MAINTENANCE
CREATE TABLE pipeline_maintenance
(
	PIPELINE_ID VARCHAR(40) NOT NULL,
	MAINTENANCE_ID VARCHAR(40) NOT NULL,
	MAINTENANCE_TYPE VARCHAR(40),
	SCHEDULE_DATE DATE,
	COMPLETION_DATE DATE,
	CREW VARCHAR(40),
	MAINTENANCE_COST NUMERIC(15,2),
	MAINTENANCE_COST_OUOM VARCHAR(40),
	SEGMENT_ID VARCHAR(40),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);

