-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PIPELINE_FIELD_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_FIELD
CREATE TABLE pipeline_field
(
	PIPELINE_ID VARCHAR(40) NOT NULL,
	FIELD_ID VARCHAR(40) NOT NULL,
	ASSOCIATION_TYPE VARCHAR(40),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);
