-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PIPELINE_RISK_ASSESSMENT_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PIPELINE_RISK_ASSESSMENT_PK
ALTER TABLE PIPELINE_RISK_ASSESSMENT ADD CONSTRAINT PIPELINE_RISK_ASSESSMENT_PK PRIMARY KEY
(
	PIPELINE_ID,
	RISK_ASSESSMENT_ID
);

