-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PIPELINE_COMPONENT_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_COMPONENT
CREATE TABLE pipeline_component
(
	PIPELINE_ID VARCHAR(40) NOT NULL,
	COMPONENT_ID VARCHAR(40) NOT NULL,
	COMPONENT_TYPE VARCHAR(40),
	PART_NUMBER VARCHAR(40),
	SEGMENT_ID VARCHAR(40),
	MATERIAL_TYPE VARCHAR(40),
	MATERIAL_GRADE VARCHAR(40),
	MANUFACTURER VARCHAR(40),
	INSTALLATION_DATE DATE,
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);

