-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PIPELINE_DESIGN_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_DESIGN_PIPELINE_FK
ALTER TABLE PIPELINE_DESIGN ADD CONSTRAINT PIPELINE_DESIGN_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

