-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PIPELINE_STATION_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_STATION
CREATE TABLE pipeline_station
(
	PIPELINE_ID VARCHAR(40) NOT NULL,
	STATION_ID VARCHAR(40) NOT NULL,
	STATION_NAME VARCHAR(255),
	STATION_SHORT_NAME VARCHAR(30),
	STATION_TYPE VARCHAR(40),
	FACILITY_ID VARCHAR(40),
	FACILITY_TYPE VARCHAR(40),
	STATION_FUNCTION VARCHAR(40),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);
