-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PIPELINE_ANOMALY_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PIPELINE_ANOMALY_PK
ALTER TABLE PIPELINE_ANOMALY ADD CONSTRAINT PIPELINE_ANOMALY_PK PRIMARY KEY
(
	PIPELINE_ID,
	ANOMALY_ID
);

