-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PIPELINE_MATERIAL_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_MATERIAL_PIPELINE_FK
ALTER TABLE PIPELINE_MATERIAL ADD CONSTRAINT PIPELINE_MATERIAL_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

