-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PIPELINE_CONSTRUCTION_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PIPELINE_CONSTRUCTION_PK
ALTER TABLE PIPELINE_CONSTRUCTION ADD CONSTRAINT PIPELINE_CONSTRUCTION_PK PRIMARY KEY
(
	PIPELINE_ID,
	CONSTRUCTION_PHASE_NO
);

