-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PIPELINE_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_FIELD_FK
ALTER TABLE PIPELINE ADD CONSTRAINT PIPELINE_FIELD_FK FOREIGN KEY 
(
	PRIMARY_FIELD_ID
)
REFERENCES FIELD
(
	FIELD_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_BA_FK
ALTER TABLE PIPELINE ADD CONSTRAINT PIPELINE_BA_FK FOREIGN KEY 
(
	CURRENT_OPERATOR
)
REFERENCES BUSINESS_ASSOCIATE
(
	BUSINESS_ASSOCIATE_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_CS_FK
ALTER TABLE PIPELINE ADD CONSTRAINT PIPELINE_CS_FK FOREIGN KEY 
(
	COORD_SYSTEM_ID
)
REFERENCES CS_COORDINATE_SYSTEM
(
	COORD_SYSTEM_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_LOCAL_CS_FK
ALTER TABLE PIPELINE ADD CONSTRAINT PIPELINE_LOCAL_CS_FK FOREIGN KEY 
(
	LOCAL_COORD_SYSTEM_ID
)
REFERENCES CS_COORDINATE_SYSTEM
(
	COORD_SYSTEM_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_CA_FK
ALTER TABLE PIPELINE ADD CONSTRAINT PIPELINE_CA_FK FOREIGN KEY 
(
	COORD_ACQUISITION_ID
)
REFERENCES CS_COORD_ACQUISITION
(
	ACQUISITION_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_TYPE_FK
ALTER TABLE PIPELINE ADD CONSTRAINT PIPELINE_TYPE_FK FOREIGN KEY 
(
	PIPELINE_TYPE
)
REFERENCES R_PIPELINE_TYPE
(
	PIPELINE_TYPE
);

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_STATUS_FK
ALTER TABLE PIPELINE ADD CONSTRAINT PIPELINE_STATUS_FK FOREIGN KEY 
(
	PIPELINE_STATUS
)
REFERENCES R_PIPELINE_STATUS
(
	PIPELINE_STATUS
);
