-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PLAY_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PLAY_FIELD_FK
ALTER TABLE PLAY ADD CONSTRAINT PLAY_FIELD_FK FOREIGN KEY
(
	FIELD_ID
)
REFERENCES FIELD
(
	FIELD_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PLAY_TYPE_FK
ALTER TABLE PLAY ADD CONSTRAINT PLAY_TYPE_FK FOREIGN KEY
(
	PLAY_TYPE
)
REFERENCES R_PLAY_TYPE
(
	PLAY_TYPE
);

