-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PLAY_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PLAY
CREATE TABLE play
(
	PLAY_ID VARCHAR(40) NOT NULL,
	PLAY_NAME VARCHAR(255),
	PLAY_SHORT_NAME VARCHAR(30),
	FIELD_ID VARCHAR(40),
	PLAY_TYPE VARCHAR(40),
	DESCRIPTION VARCHAR(240),
	GEOLOGICAL_SETTING VARCHAR(240),
	GEOLOGICAL_AGE VARCHAR(40),
	PLAY_EXTENT_AREA NUMERIC(18,5),
	PLAY_EXTENT_AREA_OUOM VARCHAR(40),
	PROVEN_RESERVES_OIL NUMERIC(18,5),
	PROVEN_RESERVES_GAS NUMERIC(18,5),
	PROVEN_RESERVES_OUOM VARCHAR(40),
	LATITUDE NUMERIC(14,9),
	LONGITUDE NUMERIC(14,9),
	ELEVATION NUMERIC(10,5),
	ELEVATION_OUOM VARCHAR(40),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);

