-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PROSPECT_MIGRATION_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PROSPECT_MIGRATION
CREATE TABLE prospect_migration
(
	PROSPECT_ID VARCHAR(40) NOT NULL,
	MIGRATION_ID VARCHAR(40) NOT NULL,
	MIGRATION_PATHWAY VARCHAR(240),
	MIGRATION_DISTANCE NUMERIC(10,5),
	MIGRATION_DISTANCE_OUOM VARCHAR(40),
	MIGRATION_EFFICIENCY NUMERIC(5,4),
	MIGRATION_TIMING VARCHAR(40),
	CARRIER_BED VARCHAR(40),
	SEAL_BREACH_RISK NUMERIC(5,4),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);
