-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PROSPECT_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PROSPECT_PK
ALTER TABLE PROSPECT ADD CONSTRAINT PROSPECT_PK PRIMARY KEY
(
	PROSPECT_ID
);

