-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PROSPECT_VOLUME_ESTIMATE_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_VOLUME_ESTIMATE_PROSPECT_FK
ALTER TABLE PROSPECT_VOLUME_ESTIMATE ADD CONSTRAINT PROSPECT_VOLUME_ESTIMATE_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);
