-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PROSPECT_SEIS_SURVEY_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PROSPECT_SEIS_SURVEY
CREATE TABLE prospect_seis_survey
(
	PROSPECT_ID VARCHAR(40) NOT NULL,
	SEIS_SET_ID VARCHAR(40) NOT NULL,
	ASSOCIATION_TYPE VARCHAR(40),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);
