-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PROSPECT_HISTORY_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PROSPECT_HISTORY
CREATE TABLE prospect_history
(
	PROSPECT_ID VARCHAR(40) NOT NULL,
	HISTORY_SEQ_NO NUMERIC(10,0) NOT NULL,
	FIELD_NAME VARCHAR(40),
	OLD_VALUE VARCHAR(2000),
	NEW_VALUE VARCHAR(2000),
	CHANGE_REASON VARCHAR(240),
	CHANGED_BY VARCHAR(40),
	CHANGE_DATE DATE,
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);
