-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PROSPECT_RESERVOIR_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PROSPECT_RESERVOIR
CREATE TABLE prospect_reservoir
(
	PROSPECT_ID VARCHAR(40) NOT NULL,
	RESERVOIR_ID VARCHAR(40) NOT NULL,
	STRAT_UNIT_ID VARCHAR(40),
	POROSITY NUMERIC(10,5),
	PERMEABILITY NUMERIC(10,5),
	NET_PAY NUMERIC(10,5),
	NET_PAY_OUOM VARCHAR(40),
	GROSS_PAY NUMERIC(10,5),
	GROSS_PAY_OUOM VARCHAR(40),
	NET_TO_GROSS_RATIO NUMERIC(5,4),
	OWC NUMERIC(10,5),
	OWC_OUOM VARCHAR(40),
	GOC NUMERIC(10,5),
	GOC_OUOM VARCHAR(40),
	FWL NUMERIC(10,5),
	FWL_OUOM VARCHAR(40),
	FACIES VARCHAR(40),
	LITHOLOGY VARCHAR(40),
	DIAGENESIS VARCHAR(40),
	RESERVOIR_AREA NUMERIC(18,5),
	RESERVOIR_AREA_OUOM VARCHAR(40),
	RESERVOIR_THICKNESS NUMERIC(10,5),
	RESERVOIR_THICKNESS_OUOM VARCHAR(40),
	RESERVOIR_VOLUME NUMERIC(18,5),
	RESERVOIR_VOLUME_OUOM VARCHAR(40),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);
