-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PROSPECT_PORTFOLIO_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PROSPECT_PORTFOLIO_PK
ALTER TABLE PROSPECT_PORTFOLIO ADD CONSTRAINT PROSPECT_PORTFOLIO_PK PRIMARY KEY
(
	PORTFOLIO_ID
);
