-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PROSPECT_RANKING_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PROSPECT_RANKING
CREATE TABLE prospect_ranking
(
	PROSPECT_ID VARCHAR(40) NOT NULL,
	RANKING_ID VARCHAR(40) NOT NULL,
	RANKING_SCORE NUMERIC(10,5),
	PRIORITY_ORDER NUMERIC(10,0),
	RANKING_CRITERIA VARCHAR(2000),
	RANKING_DATE DATE,
	RANKER VARCHAR(40),
	METHODOLOGY VARCHAR(240),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);
