-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PROSPECT_TRAP_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PROSPECT_TRAP_PK
ALTER TABLE PROSPECT_TRAP ADD CONSTRAINT PROSPECT_TRAP_PK PRIMARY KEY
(
	PROSPECT_ID,
	TRAP_ID
);
