-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PROSPECT_DISCOVERY_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PROSPECT_DISCOVERY_PK
ALTER TABLE PROSPECT_DISCOVERY ADD CONSTRAINT PROSPECT_DISCOVERY_PK PRIMARY KEY
(
	PROSPECT_ID,
	DISCOVERY_ID
);
