-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: PROSPECT_WORKFLOW_STAGE_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_WORKFLOW_STAGE_PROSPECT_FK
ALTER TABLE PROSPECT_WORKFLOW_STAGE ADD CONSTRAINT PROSPECT_WORKFLOW_STAGE_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_WORKFLOW_STAGE_STAGE_FK
ALTER TABLE PROSPECT_WORKFLOW_STAGE ADD CONSTRAINT PROSPECT_WORKFLOW_STAGE_STAGE_FK FOREIGN KEY
(
	WORKFLOW_STAGE
)
REFERENCES R_WORKFLOW_STAGE
(
	WORKFLOW_STAGE
);
