-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: R_LEAD_STATUS_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY R_LEAD_STATUS_PK
ALTER TABLE R_LEAD_STATUS ADD CONSTRAINT R_LEAD_STATUS_PK PRIMARY KEY
(
	LEAD_STATUS
);
