-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: R_PIPELINE_TYPE_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY R_PIPELINE_TYPE_PK
ALTER TABLE R_PIPELINE_TYPE ADD CONSTRAINT R_PIPELINE_TYPE_PK PRIMARY KEY
(
	PIPELINE_TYPE
);
