-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: R_PROSPECT_TYPE_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY R_PROSPECT_TYPE_PK
ALTER TABLE R_PROSPECT_TYPE ADD CONSTRAINT R_PROSPECT_TYPE_PK PRIMARY KEY
(
	PROSPECT_TYPE
);
