-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: R_TRAP_TYPE_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE R_TRAP_TYPE
CREATE TABLE r_trap_type
(
	TRAP_TYPE VARCHAR(40) NOT NULL,
	ABBREVIATION VARCHAR(12),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	LONG_NAME VARCHAR(255),
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SHORT_NAME VARCHAR(30),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);
