-- PPDM39 POSTGRESQL DDL Script
-- Converted from SQL Server script: R_WORKFLOW_STAGE_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY R_WORKFLOW_STAGE_PK
ALTER TABLE R_WORKFLOW_STAGE ADD CONSTRAINT R_WORKFLOW_STAGE_PK PRIMARY KEY
(
	WORKFLOW_STAGE
);
