raiserror ('CREATING TABLE EXPORT_HISTORY', 10,1) with nowait

CREATE TABLE EXPORT_HISTORY
(
    EXPORT_HISTORY_ID NVARCHAR(40) NOT NULL,
    EXPORT_TYPE NVARCHAR(50),
    EXPORT_FORMAT NVARCHAR(255),
    EXPORT_DATE DATETIME,
    EXPORTED_BY NVARCHAR(255),
    FILE_PATH NVARCHAR(255),
    RECORD_COUNT INT,
    STATUS NVARCHAR(50),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
