raiserror ('CREATING TABLE MEASUREMENT_RECORD', 10,1) with nowait

CREATE TABLE MEASUREMENT_RECORD
(
    MEASUREMENT_RECORD_ID NVARCHAR(40) NOT NULL,
    WELL_ID NVARCHAR(40),
    LEASE_ID NVARCHAR(40),
    MEASUREMENT_DATE_TIME DATETIME,
    MEASUREMENT_METHOD NVARCHAR(255),
    MEASUREMENT_STANDARD NVARCHAR(255),
    GROSS_VOLUME NUMERIC(18,2),
    BSW_PERCENTAGE NUMERIC(18,6),
    NET_VOLUME NUMERIC(18,2),
    TEMPERATURE NUMERIC(18,2),
    PRESSURE NUMERIC(18,2),
    API_GRAVITY NUMERIC(18,2),
    SULFUR_CONTENT NUMERIC(18,2),
    ACCURACY NUMERIC(18,2),
    MEASUREMENT_DEVICE NVARCHAR(255),
    OPERATOR NVARCHAR(255),
    VALIDATION_STATUS NVARCHAR(50),
    NOTES NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
