ALTER TABLE "ACCOUNTING_AMORTIZATION"
ADD CONSTRAINT FK_ACCOUNTING_AMORTIZATION_PROPERTY FOREIGN KEY ("PROPERTY_ID") REFERENCES "PROPERTY"("PROPERTY_ID");

ALTER TABLE "ACCOUNTING_AMORTIZATION"
ADD CONSTRAINT FK_ACCOUNTING_AMORTIZATION_WELL FOREIGN KEY ("WELL_ID") REFERENCES "WELL"("WELL_ID");

ALTER TABLE "ACCOUNTING_AMORTIZATION"
ADD CONSTRAINT FK_ACCOUNTING_AMORTIZATION_POOL FOREIGN KEY ("POOL_ID") REFERENCES "POOL"("POOL_ID");

ALTER TABLE "ACCOUNTING_AMORTIZATION"
ADD CONSTRAINT FK_ACCOUNTING_AMORTIZATION_FIELD FOREIGN KEY ("FIELD_ID") REFERENCES "FIELD"("FIELD_ID");
