CREATE TABLE "ACCOUNTING_METHOD"
(
    "ACCOUNTING_METHOD_ID" VARCHAR2(40) NOT NULL,
    "ROW_QUALITY" VARCHAR2(40),
    "FIELD_ID" VARCHAR2(40),
    "COST_CENTER_ID" VARCHAR2(40),
    "METHOD_TYPE" VARCHAR2(50),
    "EFFECTIVE_DATE" DATE,
    "EXPIRY_DATE" DATE,
    "DESCRIPTION" VARCHAR2(2000),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
