CREATE TABLE "ALLOCATION_DETAIL"
(
    "ALLOCATION_DETAIL_ID" VARCHAR2(40) NOT NULL,
    "ALLOCATION_RESULT_ID" VARCHAR2(40),
    "ENTITY_ID" VARCHAR2(40),
    "ENTITY_TYPE" VARCHAR2(50),
    "ENTITY_NAME" VARCHAR2(255),
    "ALLOCATED_VOLUME" NUMBER(18,2),
    "ALLOCATION_PERCENTAGE" NUMBER(18,6),
    "ALLOCATION_BASIS" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40),
    "AllocationRequest_ID" VARCHAR2(40)
);
