CREATE TABLE "AP_PAYMENT"
(
    "AP_PAYMENT_ID" VARCHAR2(40) NOT NULL,
    "AP_INVOICE_ID" VARCHAR2(40),
    "PAYMENT_NUMBER" VARCHAR2(255),
    "PAYMENT_DATE" DATE,
    "PAYMENT_AMOUNT" NUMBER(18,2),
    "PAYMENT_METHOD" VARCHAR2(255),
    "CHECK_NUMBER" VARCHAR2(255),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40),
    "PAYMENT_STATUS" VARCHAR2(50)
);
