CREATE TABLE "AR_CREDIT_MEMO"
(
    "AR_CREDIT_MEMO_ID" VARCHAR2(40) NOT NULL,
    "AR_INVOICE_ID" VARCHAR2(40),
    "CREDIT_MEMO_NUMBER" VARCHAR2(255),
    "CREDIT_MEMO_DATE" DATE,
    "CREDIT_AMOUNT" NUMBER(18,2),
    "REASON" VARCHAR2(255),
    "STATUS" VARCHAR2(50),
    "DESCRIPTION" VARCHAR2(2000),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
