ALTER TABLE "AVAILS_ALLOCATION"
ADD CONSTRAINT FK_AVAILS_ALLOCATION_PRODUCTION_AVAILS FOREIGN KEY ("PRODUCTION_AVAILS_ID") REFERENCES "PRODUCTION_AVAILS"("PRODUCTION_AVAILS_ID");

ALTER TABLE "AVAILS_ALLOCATION"
ADD CONSTRAINT FK_AVAILS_ALLOCATION_ENTITY FOREIGN KEY ("ENTITY_ID") REFERENCES "ENTITY"("ENTITY_ID");
