CREATE TABLE "CEILING_TEST_CALCULATION"
(
    "CEILING_TEST_CALCULATION_ID" VARCHAR2(40) NOT NULL,
    "PROPERTY_ID" VARCHAR2(40),
    "CALCULATION_DATE" DATE,
    "NET_CAPITALIZED_COST" NUMBER(18,2),
    "DISCOUNTED_FUTURE_NET_CASH_FLOWS" NUMBER(18,2),
    "CEILING_VALUE" NUMBER(18,2),
    "IMPAIRMENT_AMOUNT" NUMBER(18,2),
    "DISCOUNT_RATE" NUMBER(18,2),
    "DESCRIPTION" VARCHAR2(2000),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
