CREATE TABLE "CONTACT_INFORMATION"
(
    "CONTACT_INFORMATION_ID" VARCHAR2(40) NOT NULL,
    "OWNER_INFORMATION_ID" VARCHAR2(40),
    "PHONE_NUMBER" VARCHAR2(255),
    "EMAIL_ADDRESS" VARCHAR2(255),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
