CREATE TABLE "COST_ALLOCATION"
(
    "COST_ALLOCATION_ID" VARCHAR2(40) NOT NULL,
    "COST_TRANSACTION_ID" VARCHAR2(40),
    "PROPERTY_ID" VARCHAR2(40),
    "WELL_ID" VARCHAR2(40),
    "COST_CENTER_ID" VARCHAR2(40),
    "ALLOCATED_AMOUNT" NUMBER(18,2),
    "ALLOCATION_PERCENTAGE" NUMBER(18,6),
    "ALLOCATION_METHOD" VARCHAR2(255),
    "DESCRIPTION" VARCHAR2(2000),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
