CREATE TABLE "CRUDE_OIL_INVENTORY_TRANSACTION"
(
    "TRANSACTION_ID" VARCHAR2(40),
    "INVENTORY_ID" VARCHAR2(40),
    "TRANSACTION_DATE" DATE,
    "TRANSACTION_TYPE" VARCHAR2(50),
    "VOLUME" NUMBER(18,2),
    "UNIT_COST" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
