ALTER TABLE "CRUDE_OIL_SPECIFICATIONS"
ADD CONSTRAINT FK_CRUDE_OIL_SPECIFICATIONS_SPECIFICATIONS FOREIGN KEY ("SPECIFICATIONS_ID") REFERENCES "SPECIFICATIONS"("SPECIFICATIONS_ID");

ALTER TABLE "CRUDE_OIL_SPECIFICATIONS"
ADD CONSTRAINT FK_CRUDE_OIL_SPECIFICATIONS_AGREEMENT FOREIGN KEY ("AGREEMENT_ID") REFERENCES "AGREEMENT"("AGREEMENT_ID");
