CREATE TABLE "CRUDE_OIL_INVENTORY"
(
    "INVENTORY_ID" VARCHAR2(40),
    "PROPERTY_OR_LEASE_ID" VARCHAR2(40),
    "TANK_BATTERY_ID" VARCHAR2(40),
    "INVENTORY_DATE" DATE,
    "VOLUME" NUMBER(18,2),
    "UNIT_COST" NUMBER(18,2),
    "VALUATION_METHOD" VARCHAR2(255),
    "MARKET_PRICE" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
