ALTER TABLE "CRUDE_OIL_INVENTORY"
ADD CONSTRAINT FK_CRUDE_OIL_INVENTORY_INVENTORY FOREIGN KEY ("INVENTORY_ID") REFERENCES "INVENTORY"("INVENTORY_ID");

ALTER TABLE "CRUDE_OIL_INVENTORY"
ADD CONSTRAINT FK_CRUDE_OIL_INVENTORY_PROPERTY_OR_LEASE FOREIGN KEY ("PROPERTY_OR_LEASE_ID") REFERENCES "PROPERTY_OR_LEASE"("PROPERTY_OR_LEASE_ID");

ALTER TABLE "CRUDE_OIL_INVENTORY"
ADD CONSTRAINT FK_CRUDE_OIL_INVENTORY_TANK_BATTERY FOREIGN KEY ("TANK_BATTERY_ID") REFERENCES "TANK_BATTERY"("TANK_BATTERY_ID");
