CREATE TABLE "EXCHANGE_CONTRACT"
(
    "CONTRACT_ID" VARCHAR2(40),
    "CONTRACT_NAME" VARCHAR2(255),
    "CONTRACT_TYPE" VARCHAR2(50),
    "PARTIES_JSON" VARCHAR2(255),
    "EFFECTIVE_DATE" DATE,
    "EXPIRATION_DATE" DATE,
    "EXCHANGE_TERMS_JSON" VARCHAR2(255),
    "DELIVERY_POINTS_JSON" VARCHAR2(255),
    "PRICING_TERMS_JSON" VARCHAR2(255),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
