CREATE TABLE "EXCHANGE_PRICING_TERMS"
(
    "EXCHANGE_PRICING_TERMS_ID" VARCHAR2(40) NOT NULL,
    "EXCHANGE_CONTRACT_ID" VARCHAR2(40),
    "BASE_PRICE_INDEX" VARCHAR2(255),
    "LOCATION_DIFFERENTIAL" NUMBER(18,2),
    "QUALITY_DIFFERENTIAL" NUMBER(18,2),
    "TIME_DIFFERENTIAL" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
