CREATE TABLE "EXCHANGE_TERMS"
(
    "EXCHANGE_TERMS_ID" VARCHAR2(40) NOT NULL,
    "EXCHANGE_CONTRACT_ID" VARCHAR2(40),
    "EXCHANGE_RATIO" NUMBER(18,6),
    "MINIMUM_VOLUME" NUMBER(18,2),
    "MAXIMUM_VOLUME" NUMBER(18,2),
    "QUALITY_SPECIFICATIONS" VARCHAR2(40),
    "NOTICE_PERIOD_DAYS" NUMBER(10),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
