CREATE TABLE "IMBALANCE_RECONCILIATION"
(
    "IMBALANCE_RECONCILIATION_ID" VARCHAR2(40) NOT NULL,
    "RECONCILIATION_DATE" DATE,
    "TOTAL_IMBALANCE_BEFORE" NUMBER(18,2),
    "TOTAL_ADJUSTMENTS" NUMBER(18,2),
    "TOTAL_IMBALANCE_AFTER" NUMBER(18,2),
    "RECONCILED_BY" VARCHAR2(255),
    "NOTES" VARCHAR2(2000),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
