CREATE TABLE "IMBALANCE_STATEMENT"
(
    "IMBALANCE_STATEMENT_ID" VARCHAR2(40) NOT NULL,
    "STATEMENT_PERIOD_START" DATE,
    "STATEMENT_PERIOD_END" DATE,
    "IMBALANCE_RECONCILIATION_ID" VARCHAR2(40),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
