CREATE TABLE "INVENTORY_TRANSACTION"
(
    "INVENTORY_TRANSACTION_ID" VARCHAR2(40) NOT NULL,
    "INVENTORY_ITEM_ID" VARCHAR2(40),
    "TRANSACTION_TYPE" VARCHAR2(50),
    "TRANSACTION_DATE" DATE,
    "QUANTITY" NUMBER(18,2),
    "UNIT_COST" NUMBER(18,2),
    "TOTAL_COST" NUMBER(18,2),
    "REFERENCE_NUMBER" VARCHAR2(255),
    "DESCRIPTION" VARCHAR2(2000),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
