CREATE TABLE "JIB_COST_ALLOCATION"
(
    "JIB_COST_ALLOCATION_ID" VARCHAR2(40) NOT NULL,
    "JIB_ID" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "FINANCE_ID" VARCHAR2(40),
    "COST_CATEGORY" VARCHAR2(255),
    "GROSS_COST" NUMBER(18,2) NOT NULL,
    "WORKING_INTEREST_SHARE" NUMBER(18,2),
    "NET_COST" NUMBER(18,2) NOT NULL,
    "DESCRIPTION" VARCHAR2(2000),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
