CREATE TABLE "JIB_PARTICIPANT"
(
    "JIB_PARTICIPANT_ID" VARCHAR2(40) NOT NULL,
    "JOINT_INTEREST_STATEMENT_ID" VARCHAR2(40),
    "COMPANY_NAME" VARCHAR2(255),
    "WORKING_INTEREST" NUMBER(18,2),
    "NET_REVENUE_INTEREST" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
