CREATE TABLE "JOA_INTEREST"
(
    "JOA_INTEREST_ID" VARCHAR2(40) NOT NULL,
    "JOA_ID" VARCHAR2(40),
    "INTEREST_OWNER_BA_ID" VARCHAR2(40),
    "WORKING_INTEREST_PERCENTAGE" NUMBER(18,6),
    "REVENUE_INTEREST_PERCENTAGE" NUMBER(18,6),
    "EFFECTIVE_DATE" DATE,
    "EXPIRY_DATE" DATE,
    "DESCRIPTION" VARCHAR2(2000),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
