CREATE TABLE "JOIB_LINE_ITEM"
(
    "JOIB_LINE_ITEM_ID" VARCHAR2(40) NOT NULL,
    "JOINT_INTEREST_BILL_ID" VARCHAR2(40),
    "LINE_ITEM_NUMBER" VARCHAR2(255),
    "COST_CATEGORY" VARCHAR2(255),
    "DESCRIPTION" VARCHAR2(2000),
    "AMOUNT" NUMBER(18,2),
    "PROPERTY_ID" VARCHAR2(40),
    "WELL_ID" VARCHAR2(40),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
