CREATE TABLE "JOURNAL_ENTRY_LINE"
(
    "JOURNAL_ENTRY_LINE_ID" VARCHAR2(40) NOT NULL,
    "JOURNAL_ENTRY_ID" VARCHAR2(40),
    "GL_ACCOUNT_ID" VARCHAR2(40),
    "LINE_NUMBER" NUMBER(10),
    "DEBIT_AMOUNT" NUMBER(18,2),
    "CREDIT_AMOUNT" NUMBER(18,2),
    "DESCRIPTION" VARCHAR2(2000),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
