CREATE TABLE "MEASUREMENT_ACCURACY"
(
    "MEASUREMENT_ACCURACY_ID" VARCHAR2(40) NOT NULL,
    "MINIMUM_ACCURACY" NUMBER(18,2),
    "MAXIMUM_ERROR" NUMBER(18,2),
    "CALIBRATION_REQUIRED" VARCHAR2(255),
    "CALIBRATION_FREQUENCY_DAYS" NUMBER(10),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
