ALTER TABLE "MEASUREMENT_RECORD"
ADD CONSTRAINT FK_MEASUREMENT_RECORD_MEASUREMENT FOREIGN KEY ("MEASUREMENT_ID") REFERENCES "MEASUREMENT"("MEASUREMENT_ID");

ALTER TABLE "MEASUREMENT_RECORD"
ADD CONSTRAINT FK_MEASUREMENT_RECORD_CRUDE_OIL_PROPERTIES FOREIGN KEY ("CRUDE_OIL_PROPERTIES_ID") REFERENCES "CRUDE_OIL_PROPERTIES"("CRUDE_OIL_PROPERTIES_ID");
