CREATE TABLE "MEASUREMENT_REPORT_SUMMARY"
(
    "MEASUREMENT_REPORT_SUMMARY_ID" VARCHAR2(40) NOT NULL,
    "MEASUREMENT_COUNT" NUMBER(10),
    "AVERAGE_ACCURACY" NUMBER(18,2),
    "CALIBRATIONS_DUE" NUMBER(10),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
