CREATE TABLE "NOMINATION"
(
    "NOMINATION_ID" VARCHAR2(40) NOT NULL,
    "PERIOD_START" DATE,
    "PERIOD_END" DATE,
    "NOMINATED_VOLUME" NUMBER(18,2),
    "DELIVERY_POINTS_JSON" VARCHAR2(255),
    "STATUS" VARCHAR2(50),
    "SUBMISSION_DATE" DATE,
    "APPROVAL_DATE" DATE,
    "APPROVED_BY" VARCHAR2(255),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
