ALTER TABLE "OWNERSHIP_INTEREST"
ADD CONSTRAINT FK_OWNERSHIP_INTEREST_OWNERSHIP FOREIGN KEY ("OWNERSHIP_ID") REFERENCES "OWNERSHIP"("OWNERSHIP_ID");

ALTER TABLE "OWNERSHIP_INTEREST"
ADD CONSTRAINT FK_OWNERSHIP_INTEREST_OWNER FOREIGN KEY ("OWNER_ID") REFERENCES "OWNER"("OWNER_ID");

ALTER TABLE "OWNERSHIP_INTEREST"
ADD CONSTRAINT FK_OWNERSHIP_INTEREST_PROPERTY_OR_LEASE FOREIGN KEY ("PROPERTY_OR_LEASE_ID") REFERENCES "PROPERTY_OR_LEASE"("PROPERTY_OR_LEASE_ID");

ALTER TABLE "OWNERSHIP_INTEREST"
ADD CONSTRAINT FK_OWNERSHIP_INTEREST_DIVISION_ORDER FOREIGN KEY ("DIVISION_ORDER_ID") REFERENCES "DIVISION_ORDER"("DIVISION_ORDER_ID");
