CREATE TABLE "PO_LINE_ITEM"
(
    "PO_LINE_ITEM_ID" VARCHAR2(40) NOT NULL,
    "PURCHASE_ORDER_ID" VARCHAR2(40),
    "LINE_NUMBER" NUMBER(10),
    "ITEM_DESCRIPTION" VARCHAR2(2000),
    "QUANTITY" NUMBER(18,2),
    "UNIT_PRICE" NUMBER(18,2),
    "LINE_TOTAL" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
