CREATE TABLE "PRODUCTION_REPORT_SUMMARY"
(
    "PRODUCTION_REPORT_SUMMARY_ID" VARCHAR2(40) NOT NULL,
    "TOTAL_PRODUCTION" NUMBER(18,2),
    "PRODUCING_DAYS" NUMBER(10),
    "AVERAGE_DAILY_PRODUCTION" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
