CREATE TABLE "RECEIVABLE"
(
    "RECEIVABLE_ID" VARCHAR2(40) NOT NULL,
    "TRANSACTION_ID" VARCHAR2(40),
    "CUSTOMER" VARCHAR2(255),
    "INVOICE_NUMBER" VARCHAR2(255),
    "INVOICE_DATE" DATE,
    "DUE_DATE" DATE,
    "ORIGINAL_AMOUNT" NUMBER(18,2),
    "AMOUNT_PAID" NUMBER(18,2),
    "STATUS" VARCHAR2(50),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
