CREATE TABLE "REVENUE_DEDUCTION"
(
    "REVENUE_DEDUCTION_ID" VARCHAR2(40) NOT NULL,
    "REVENUE_TRANSACTION_ID" VARCHAR2(40),
    "DEDUCTION_TYPE" VARCHAR2(50),
    "AMOUNT" NUMBER(18,2) NOT NULL,
    "DESCRIPTION" VARCHAR2(2000),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_ID" VARCHAR2(40)
);
