CREATE TABLE "ROYALTY_OWNER"
(
    "ROYALTY_OWNER_ID" VARCHAR2(40) NOT NULL,
    "ROYALTY_OWNER_BA_ID" VARCHAR2(40),
    "ROYALTY_OWNER_NAME" VARCHAR2(255),
    "CONTACT_INFO" VARCHAR2(255),
    "PAYMENT_METHOD" VARCHAR2(255),
    "DESCRIPTION" VARCHAR2(2000),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
