CREATE TABLE "ROYALTY_PAYMENT_DETAIL"
(
    "ROYALTY_PAYMENT_DETAIL_ID" VARCHAR2(40) NOT NULL,
    "ROYALTY_PAYMENT_ID" VARCHAR2(40),
    "REVENUE_TRANSACTION_ID" VARCHAR2(40),
    "OIL_VOLUME" NUMBER(18,2),
    "GAS_VOLUME" NUMBER(18,2),
    "OIL_REVENUE" NUMBER(18,2),
    "GAS_REVENUE" NUMBER(18,2),
    "ROYALTY_AMOUNT" NUMBER(18,2),
    "DESCRIPTION" VARCHAR2(2000),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
