CREATE TABLE "ROYALTY_CALCULATION"
(
    "ROYALTY_CALCULATION_ID" VARCHAR2(40) NOT NULL,
    "CALCULATION_DATE" DATE,
    "PROPERTY_OR_LEASE_ID" VARCHAR2(40),
    "GROSS_REVENUE" NUMBER(18,2),
    "ROYALTY_DEDUCTIONS_ID" VARCHAR2(40),
    "NET_REVENUE" NUMBER(18,2),
    "ROYALTY_INTEREST" NUMBER(18,2),
    "ROYALTY_AMOUNT" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
