ALTER TABLE "TRACT_ALLOCATION_DATA"
ADD CONSTRAINT FK_TRACT_ALLOCATION_DATA_TRACT FOREIGN KEY ("TRACT_ID") REFERENCES "TRACT"("TRACT_ID");

ALTER TABLE "TRACT_ALLOCATION_DATA"
ADD CONSTRAINT FK_TRACT_ALLOCATION_DATA_UNIT FOREIGN KEY ("UNIT_ID") REFERENCES "UNIT"("UNIT_ID");
