ALTER TABLE "TRACT_PARTICIPATION"
ADD CONSTRAINT FK_TRACT_PARTICIPATION_TRACT FOREIGN KEY ("TRACT_ID") REFERENCES "TRACT"("TRACT_ID");

ALTER TABLE "TRACT_PARTICIPATION"
ADD CONSTRAINT FK_TRACT_PARTICIPATION_UNIT FOREIGN KEY ("UNIT_ID") REFERENCES "UNIT"("UNIT_ID");

ALTER TABLE "TRACT_PARTICIPATION"
ADD CONSTRAINT FK_TRACT_PARTICIPATION_PARTICIPATING_AREA FOREIGN KEY ("PARTICIPATING_AREA_ID") REFERENCES "PARTICIPATING_AREA"("PARTICIPATING_AREA_ID");
