CREATE TABLE "TRANSFER_ORDER"
(
    "TRANSFER_ORDER_ID" VARCHAR2(40) NOT NULL,
    "PROPERTY_OR_LEASE_ID" VARCHAR2(40),
    "FROM_OWNER_ID" VARCHAR2(40),
    "TO_OWNER_ID" VARCHAR2(40),
    "INTEREST_TRANSFERRED" NUMBER(18,2),
    "EFFECTIVE_DATE" DATE,
    "IS_APPROVED" VARCHAR2(255),
    "APPROVAL_DATE" DATE,
    "APPROVED_BY" VARCHAR2(255),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
