CREATE TABLE "UNIT_AGREEMENT"
(
    "UNIT_ID" VARCHAR2(40),
    "UNIT_NAME" VARCHAR2(255),
    "EFFECTIVE_DATE" DATE,
    "EXPIRATION_DATE" DATE,
    "UNIT_OPERATOR" VARCHAR2(255),
    "TERMS_AND_CONDITIONS" VARCHAR2(255),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
