CREATE TABLE "UNIT_OPERATING_AGREEMENT"
(
    "UNIT_OPERATING_AGREEMENT_ID" VARCHAR2(40) NOT NULL,
    "UNIT_ID" VARCHAR2(40),
    "VOTING_RIGHTS_ID" VARCHAR2(40),
    "COST_SHARING_ID" VARCHAR2(40),
    "REVENUE_SHARING_ID" VARCHAR2(40),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
