CREATE TABLE `GAS_CHOKE_PROPERTIES`
(
    `GAS_CHOKE_PROPERTIES_ID` VARCHAR(40) NOT NULL,
    `GAS_SPECIFIC_GRAVITY` DECIMAL(18,2),
    `UPSTREAM_PRESSURE` DECIMAL(18,2),
    `DOWNSTREAM_PRESSURE` DECIMAL(18,2),
    `TEMPERATURE` DECIMAL(18,2),
    `Z_FACTOR` DECIMAL(18,2),
    `FLOW_RATE` DECIMAL(18,2),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_QUALITY` VARCHAR(40)
);
