CREATE TABLE "GAS_COMPOSITION_COMPONENT"
(
    "GAS_COMPONENT_ID" VARCHAR2(40),
    "GAS_COMPOSITION_ID" VARCHAR2(40),
    "COMPONENT_NAME" VARCHAR2(255),
    "MOLE_FRACTION" NUMBER(18,2),
    "MOLECULAR_WEIGHT" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE
);
