CREATE TABLE "PPDM_DEFAULT_VALUE"
(
    "DEFAULT_VALUE_ID" VARCHAR2(40),
    "DEFAULT_KEY" VARCHAR2(255),
    "DEFAULT_VALUE" VARCHAR2(255),
    "DEFAULT_CATEGORY" VARCHAR2(255),
    "VALUE_TYPE" VARCHAR2(50),
    "USER_ID" VARCHAR2(40),
    "DATABASE_ID" VARCHAR2(40),
    "DESCRIPTION" VARCHAR2(2000),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" NUMBER(19)
);
