CREATE TABLE "PROVED_PROPERTY"
(
    "PROPERTY_ID" VARCHAR2(40),
    "ACQUISITION_COST" NUMBER(18,2),
    "EXPLORATION_COSTS" NUMBER(18,6),
    "DEVELOPMENT_COSTS" NUMBER(18,2),
    "ACCUMULATED_AMORTIZATION" NUMBER(18,2),
    "PROVED_DATE" DATE,
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40),
    "PROVED_RESERVES_GAS" NUMBER(18,2) NOT NULL,
    "PROVED_RESERVES_OIL" NUMBER(18,2) NOT NULL,
    "PROVED_RESERVES_BOE" VARCHAR2(255) NOT NULL
);
