CREATE TABLE "RESERVOIR_STATUS"
(
    "RESERVOIR_STATUS_ID" VARCHAR2(40) NOT NULL,
    "RESERVE_ENTITY_ID" VARCHAR2(40),
    "POOL_ID" VARCHAR2(40),
    "STATUS" VARCHAR2(50),
    "STATUS_DATE" DATE,
    "STATUS_CHANGED_BY" VARCHAR2(50),
    "NOTES" VARCHAR2(2000),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_QUALITY" VARCHAR2(40)
);
