CREATE TABLE "PRODUCTION_FORECAST_POINT"
(
    "FORECAST_POINT_ID" VARCHAR(40),
    "FORECAST_ID" VARCHAR(40),
    "FORECAST_DATE" TIMESTAMP,
    "OIL_RATE" VARCHAR(255),
    "GAS_RATE" VARCHAR(255),
    "WATER_RATE" VARCHAR(255),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30)
);
