ALTER TABLE "RESERVOIR_FORECAST_PROPERTIES"
ADD CONSTRAINT FK_RESERVOIR_FORECAST_PROPERTIES_AREA FOREIGN KEY ("AREA_ID") REFERENCES "AREA"("AREA_ID");

ALTER TABLE "RESERVOIR_FORECAST_PROPERTIES"
ADD CONSTRAINT FK_RESERVOIR_FORECAST_PROPERTIES_BUSINESS_ASSOCIATE FOREIGN KEY ("BUSINESS_ASSOCIATE_ID") REFERENCES "BUSINESS_ASSOCIATE"("BUSINESS_ASSOCIATE_ID");
