CREATE TABLE `GAS_LIFT_VALVE`
(
    `GAS_LIFT_VALVE_ID` VARCHAR(40) NOT NULL,
    `GAS_LIFT_DESIGN_ID` VARCHAR(40),
    `DEPTH` DECIMAL(18,2),
    `PORT_SIZE` DECIMAL(18,2),
    `OPENING_PRESSURE` DECIMAL(18,2),
    `CLOSING_PRESSURE` DECIMAL(18,2),
    `VALVE_TYPE` VARCHAR(50),
    `TEMPERATURE` DECIMAL(18,2),
    `GAS_INJECTION_RATE` DECIMAL(18,2),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_QUALITY` VARCHAR(40)
);
