CREATE TABLE "PRODUCTION_FORECAST_POINT"
(
    "FORECAST_POINT_ID" VARCHAR2(40),
    "FORECAST_ID" VARCHAR2(40),
    "FORECAST_DATE" DATE,
    "OIL_RATE" VARCHAR2(255),
    "GAS_RATE" VARCHAR2(255),
    "WATER_RATE" VARCHAR2(255),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30)
);
