CREATE TABLE "PRODUCTION_FORECAST"
(
    "FORECAST_ID" VARCHAR2(40),
    "WELL_UWI" VARCHAR2(255),
    "FIELD_ID" VARCHAR2(40),
    "FORECAST_NAME" VARCHAR2(255),
    "FORECAST_TYPE" VARCHAR2(50),
    "FORECAST_START_DATE" DATE,
    "FORECAST_END_DATE" DATE,
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30)
);
