-- DEVELOPMENT_COSTS Table Creation Script
-- SQL Server Version

CREATE TABLE DEVELOPMENT_COSTS
(
    DEVELOPMENT_COST_ID NVARCHAR(40) NOT NULL,
    PROPERTY_ID NVARCHAR(40),
    DEVELOPMENT_WELL_DRILLING_COSTS NUMERIC(18,2),
    DEVELOPMENT_WELL_EQUIPMENT NUMERIC(18,2),
    SUPPORT_EQUIPMENT_AND_FACILITIES NUMERIC(18,2),
    SERVICE_WELL_COSTS NUMERIC(18,2),
    TOTAL_DEVELOPMENT_COSTS NUMERIC(18,2),
    COST_DATE DATETIME,
    COST_CENTER_ID NVARCHAR(40),
    ACTIVE_IND NVARCHAR(1),
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(4000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(40),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);

-- Primary Key
ALTER TABLE DEVELOPMENT_COSTS
ADD CONSTRAINT PK_DEVELOPMENT_COSTS PRIMARY KEY (DEVELOPMENT_COST_ID);

-- Foreign Keys
ALTER TABLE DEVELOPMENT_COSTS
ADD CONSTRAINT FK_DEVELOPMENT_COSTS_PROPERTY FOREIGN KEY (PROPERTY_ID) REFERENCES UNPROVED_PROPERTY(PROPERTY_ID);

ALTER TABLE DEVELOPMENT_COSTS
ADD CONSTRAINT FK_DEVELOPMENT_COSTS_COST_CENTER FOREIGN KEY (COST_CENTER_ID) REFERENCES COST_CENTER(COST_CENTER_ID);

-- Indexes
CREATE INDEX IX_DEVELOPMENT_COSTS_PROPERTY ON DEVELOPMENT_COSTS(PROPERTY_ID);
CREATE INDEX IX_DEVELOPMENT_COSTS_COST_CENTER ON DEVELOPMENT_COSTS(COST_CENTER_ID);
CREATE INDEX IX_DEVELOPMENT_COSTS_COST_DATE ON DEVELOPMENT_COSTS(COST_DATE);

