CREATE TABLE NPV_PROFILE_POINT
(
    NPV_PROFILE_POINT_ID TEXT NOT NULL,
    ECONOMIC_ANALYSIS_RESULT_ID TEXT,
    RATE REAL,
    NPV REAL,
    POINT_ORDER INTEGER,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT,
    AREA_ID TEXT,
    AREA_TYPE TEXT,
    BUSINESS_ASSOCIATE_ID TEXT,
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME
);
