CREATE TABLE GAS_COMPOSITION
(
    GAS_COMPOSITION_ID TEXT NOT NULL,
    COMPOSITION_NAME TEXT,
    COMPOSITION_DATE DATETIME,
    TOTAL_MOLE_FRACTION REAL,
    MOLECULAR_WEIGHT REAL,
    SPECIFIC_GRAVITY REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
