CREATE TABLE OIL_COMPOSITION
(
    OIL_COMPOSITION_ID TEXT NOT NULL,
    COMPOSITION_NAME TEXT,
    COMPOSITION_DATE DATETIME,
    OIL_GRAVITY TEXT(255),
    GAS_OIL_RATIO TEXT(255),
    WATER_CUT TEXT(255),
    BUBBLE_POINT_PRESSURE TEXT(255),
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
