CREATE TABLE PPDM_DEFAULT_VALUE
(
    DEFAULT_VALUE_ID TEXT,
    DEFAULT_KEY TEXT,
    DEFAULT_VALUE TEXT,
    DEFAULT_CATEGORY TEXT,
    VALUE_TYPE TEXT,
    USER_ID TEXT,
    DATABASE_ID TEXT,
    DESCRIPTION TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID INTEGER
);
