-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: EXPLORATION_BUDGET_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY EXPLORATION_BUDGET_PK
ALTER TABLE EXPLORATION_BUDGET ADD CONSTRAINT EXPLORATION_BUDGET_PK PRIMARY KEY
(
	PROGRAM_ID,
	BUDGET_YEAR
);
