-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: EXPLORATION_PROGRAM_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY EXPLORATION_PROGRAM_PK
ALTER TABLE EXPLORATION_PROGRAM ADD CONSTRAINT EXPLORATION_PROGRAM_PK PRIMARY KEY
(
	PROGRAM_ID
);
