-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: EXPLORATION_PERMIT_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY EXPLORATION_PERMIT_PK
ALTER TABLE EXPLORATION_PERMIT ADD CONSTRAINT EXPLORATION_PERMIT_PK PRIMARY KEY
(
	PERMIT_ID
);
