-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PIPELINE_ANOMALY_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_ANOMALY_PIPELINE_FK
ALTER TABLE PIPELINE_ANOMALY ADD CONSTRAINT PIPELINE_ANOMALY_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_ANOMALY_INSPECTION_FK
ALTER TABLE PIPELINE_ANOMALY ADD CONSTRAINT PIPELINE_ANOMALY_INSPECTION_FK FOREIGN KEY 
(
	PIPELINE_ID,
	INSPECTION_ID
)
REFERENCES PIPELINE_INSPECTION
(
	PIPELINE_ID,
	INSPECTION_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_ANOMALY_TYPE_FK
ALTER TABLE PIPELINE_ANOMALY ADD CONSTRAINT PIPELINE_ANOMALY_TYPE_FK FOREIGN KEY 
(
	ANOMALY_TYPE
)
REFERENCES R_ANOMALY_TYPE
(
	ANOMALY_TYPE
);

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_ANOMALY_SEGMENT_FK
ALTER TABLE PIPELINE_ANOMALY ADD CONSTRAINT PIPELINE_ANOMALY_SEGMENT_FK FOREIGN KEY 
(
	PIPELINE_ID,
	SEGMENT_ID
)
REFERENCES PIPELINE_SEGMENT
(
	PIPELINE_ID,
	SEGMENT_ID
);

