-- CREATING TABLE PIPELINE_WELL
CREATE TABLE pipeline_well
(
	PIPELINE_ID VARCHAR(40) NOT NULL,
	UWI VARCHAR(40) NOT NULL,
	CONNECTION_SEQ_NO NUMERIC(8,0) NOT NULL,
	CONNECTION_TYPE VARCHAR(40),
	CONNECTION_DATE DATE,
	FLOW_DIRECTION VARCHAR(40),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);
