-- CREATING TABLE PIPELINE_TEST
CREATE TABLE pipeline_test
(
	PIPELINE_ID VARCHAR(40) NOT NULL,
	TEST_ID VARCHAR(40) NOT NULL,
	TEST_TYPE VARCHAR(40),
	TEST_DATE DATE,
	TEST_PRESSURE NUMERIC(10,5),
	TEST_PRESSURE_OUOM VARCHAR(40),
	TEST_RESULT VARCHAR(40),
	TEST_DURATION NUMERIC(10,2),
	TEST_DURATION_OUOM VARCHAR(40),
	SEGMENT_ID VARCHAR(40),
	TEST_METHOD VARCHAR(40),
	INSPECTOR VARCHAR(40),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);

