-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_COMPONENT_PIPELINE_FK
ALTER TABLE PIPELINE_COMPONENT ADD CONSTRAINT PIPELINE_COMPONENT_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_COMPONENT_SEGMENT_FK
ALTER TABLE PIPELINE_COMPONENT ADD CONSTRAINT PIPELINE_COMPONENT_SEGMENT_FK FOREIGN KEY 
(
	PIPELINE_ID,
	SEGMENT_ID
)
REFERENCES PIPELINE_SEGMENT
(
	PIPELINE_ID,
	SEGMENT_ID
);

