-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PIPELINE_MAINTENANCE_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_MAINTENANCE_PIPELINE_FK
ALTER TABLE PIPELINE_MAINTENANCE ADD CONSTRAINT PIPELINE_MAINTENANCE_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_MAINTENANCE_SEGMENT_FK
ALTER TABLE PIPELINE_MAINTENANCE ADD CONSTRAINT PIPELINE_MAINTENANCE_SEGMENT_FK FOREIGN KEY 
(
	PIPELINE_ID,
	SEGMENT_ID
)
REFERENCES PIPELINE_SEGMENT
(
	PIPELINE_ID,
	SEGMENT_ID
);

