-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PROSPECT_DISCOVERY_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_DISCOVERY_PROSPECT_FK
ALTER TABLE PROSPECT_DISCOVERY ADD CONSTRAINT PROSPECT_DISCOVERY_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_DISCOVERY_TYPE_FK
ALTER TABLE PROSPECT_DISCOVERY ADD CONSTRAINT PROSPECT_DISCOVERY_TYPE_FK FOREIGN KEY
(
	DISCOVERY_TYPE
)
REFERENCES R_DISCOVERY_TYPE
(
	DISCOVERY_TYPE
);

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_DISCOVERY_WELL_FK
ALTER TABLE PROSPECT_DISCOVERY ADD CONSTRAINT PROSPECT_DISCOVERY_WELL_FK FOREIGN KEY
(
	DISCOVERY_WELL
)
REFERENCES WELL
(
	UWI
);
