-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PROSPECT_WORKFLOW_STAGE_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PROSPECT_WORKFLOW_STAGE_PK
ALTER TABLE PROSPECT_WORKFLOW_STAGE ADD CONSTRAINT PROSPECT_WORKFLOW_STAGE_PK PRIMARY KEY
(
	PROSPECT_ID,
	STAGE_SEQ_NO
);
