-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PROSPECT_ECONOMIC_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PROSPECT_ECONOMIC_PK
ALTER TABLE PROSPECT_ECONOMIC ADD CONSTRAINT PROSPECT_ECONOMIC_PK PRIMARY KEY
(
	PROSPECT_ID,
	ECONOMIC_ID
);
