-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PROSPECT_BA_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PROSPECT_BA
CREATE TABLE prospect_ba
(
	PROSPECT_ID VARCHAR(40) NOT NULL,
	BUSINESS_ASSOCIATE_ID VARCHAR(40) NOT NULL,
	ROLE_TYPE VARCHAR(40) NOT NULL,
	WORKING_INTEREST DECIMAL(5,4),
	CARRIED_INTEREST DECIMAL(5,4),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);
