-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PROSPECT_SOURCE_ROCK_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PROSPECT_SOURCE_ROCK
CREATE TABLE prospect_source_rock
(
	PROSPECT_ID VARCHAR(40) NOT NULL,
	SOURCE_ID VARCHAR(40) NOT NULL,
	STRAT_UNIT_ID VARCHAR(40),
	TOC DECIMAL(10,5),
	HI DECIMAL(10,5),
	KEROGEN_TYPE VARCHAR(40),
	VITRINITE_REFLECTANCE DECIMAL(5,3),
	TMAX DECIMAL(10,5),
	MATURITY_STAGE VARCHAR(40),
	GENERATION_POTENTIAL DECIMAL(10,5),
	EXPULSION_EFFICIENCY DECIMAL(5,4),
	MIGRATION_DISTANCE DECIMAL(10,5),
	MIGRATION_DISTANCE_OUOM VARCHAR(40),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);
