-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PROSPECT_TRAP_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_TRAP_PROSPECT_FK
ALTER TABLE PROSPECT_TRAP ADD CONSTRAINT PROSPECT_TRAP_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_TRAP_TYPE_FK
ALTER TABLE PROSPECT_TRAP ADD CONSTRAINT PROSPECT_TRAP_TYPE_FK FOREIGN KEY
(
	TRAP_TYPE
)
REFERENCES R_TRAP_TYPE
(
	TRAP_TYPE
);
