-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PROSPECT_ECONOMIC_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PROSPECT_ECONOMIC
CREATE TABLE prospect_economic
(
	PROSPECT_ID VARCHAR(40) NOT NULL,
	ECONOMIC_ID VARCHAR(40) NOT NULL,
	NPV DECIMAL(18,5),
	EMV DECIMAL(18,5),
	IRR DECIMAL(10,5),
	PAYBACK_PERIOD DECIMAL(10,2),
	PAYBACK_PERIOD_OUOM VARCHAR(40),
	DEVELOPMENT_COST DECIMAL(18,5),
	OPERATING_COST DECIMAL(18,5),
	ABANDONMENT_COST DECIMAL(18,5),
	OIL_PRICE DECIMAL(10,2),
	GAS_PRICE DECIMAL(10,2),
	DISCOUNT_RATE DECIMAL(5,4),
	INFLATION_RATE DECIMAL(5,4),
	ECONOMIC_SCENARIO VARCHAR(40),
	EVALUATION_DATE DATE,
	EVALUATOR VARCHAR(40),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);
