-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PROSPECT_TRAP_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PROSPECT_TRAP
CREATE TABLE prospect_trap
(
	PROSPECT_ID VARCHAR(40) NOT NULL,
	TRAP_ID VARCHAR(40) NOT NULL,
	TRAP_TYPE VARCHAR(40),
	TRAP_GEOMETRY VARCHAR(40),
	CLOSURE_AREA DECIMAL(18,5),
	CLOSURE_AREA_OUOM VARCHAR(40),
	CLOSURE_HEIGHT DECIMAL(10,5),
	CLOSURE_HEIGHT_OUOM VARCHAR(40),
	SEAL_QUALITY VARCHAR(40),
	SEAL_THICKNESS DECIMAL(10,5),
	SEAL_THICKNESS_OUOM VARCHAR(40),
	TRAP_EFFECTIVENESS DECIMAL(5,2),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);
