-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PROSPECT_ECONOMIC_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_ECONOMIC_PROSPECT_FK
ALTER TABLE PROSPECT_ECONOMIC ADD CONSTRAINT PROSPECT_ECONOMIC_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);
