-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PROSPECT_ANALOG_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_ANALOG_PROSPECT_FK
ALTER TABLE PROSPECT_ANALOG ADD CONSTRAINT PROSPECT_ANALOG_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_ANALOG_ANALOG_PROSPECT_FK
ALTER TABLE PROSPECT_ANALOG ADD CONSTRAINT PROSPECT_ANALOG_ANALOG_PROSPECT_FK FOREIGN KEY
(
	ANALOG_PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_ANALOG_ANALOG_FIELD_FK
ALTER TABLE PROSPECT_ANALOG ADD CONSTRAINT PROSPECT_ANALOG_ANALOG_FIELD_FK FOREIGN KEY
(
	ANALOG_FIELD_ID
)
REFERENCES FIELD
(
	FIELD_ID
);
