-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PROSPECT_WELL_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_WELL_PROSPECT_FK
ALTER TABLE PROSPECT_WELL ADD CONSTRAINT PROSPECT_WELL_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_WELL_WELL_FK
ALTER TABLE PROSPECT_WELL ADD CONSTRAINT PROSPECT_WELL_WELL_FK FOREIGN KEY
(
	UWI
)
REFERENCES WELL
(
	UWI
);

