-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PROSPECT_PLAY_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_PLAY_PROSPECT_FK
ALTER TABLE PROSPECT_PLAY ADD CONSTRAINT PROSPECT_PLAY_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_PLAY_PLAY_FK
ALTER TABLE PROSPECT_PLAY ADD CONSTRAINT PROSPECT_PLAY_PLAY_FK FOREIGN KEY
(
	PLAY_ID
)
REFERENCES PLAY
(
	PLAY_ID
);

