-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PROSPECT_VOLUME_ESTIMATE_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PROSPECT_VOLUME_ESTIMATE_PK
ALTER TABLE PROSPECT_VOLUME_ESTIMATE ADD CONSTRAINT PROSPECT_VOLUME_ESTIMATE_PK PRIMARY KEY
(
	PROSPECT_ID,
	ESTIMATE_ID
);
