-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: R_DISCOVERY_TYPE_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY R_DISCOVERY_TYPE_PK
ALTER TABLE R_DISCOVERY_TYPE ADD CONSTRAINT R_DISCOVERY_TYPE_PK PRIMARY KEY
(
	DISCOVERY_TYPE
);
