-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: R_INSPECTION_TYPE_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY R_INSPECTION_TYPE_PK
ALTER TABLE R_INSPECTION_TYPE ADD CONSTRAINT R_INSPECTION_TYPE_PK PRIMARY KEY
(
	INSPECTION_TYPE
);

