CREATE TABLE `GAS_PIPELINE_FLOW_PROPERTIES`
(
    `GAS_PIPELINE_FLOW_PROPERTIES_ID` VARCHAR(40) NOT NULL,
    `PIPELINE_PROPERTIES_ID` VARCHAR(40),
    `GAS_FLOW_RATE` DECIMAL(18,2),
    `GAS_SPECIFIC_GRAVITY` DECIMAL(18,2),
    `GAS_MOLECULAR_WEIGHT` DECIMAL(18,2),
    `BASE_PRESSURE` DECIMAL(18,2),
    `BASE_TEMPERATURE` DECIMAL(18,2),
    `Z_FACTOR` DECIMAL(18,2),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_QUALITY` VARCHAR(40)
);
