CREATE TABLE `LIQUID_PIPELINE_FLOW_PROPERTIES`
(
    `LIQUID_PIPELINE_FLOW_PROPERTIES_ID` VARCHAR(40) NOT NULL,
    `PIPELINE_PROPERTIES_ID` VARCHAR(40),
    `LIQUID_FLOW_RATE` DECIMAL(18,2),
    `LIQUID_SPECIFIC_GRAVITY` DECIMAL(18,2),
    `LIQUID_VISCOSITY` DECIMAL(18,2),
    `LIQUID_DENSITY` DECIMAL(18,2),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_QUALITY` VARCHAR(40)
);
