ALTER TABLE `PIPELINE_INCIDENT`
ADD CONSTRAINT FK_PIPELINE_INCIDENT_PIPELINE FOREIGN KEY (`PIPELINE_ID`) REFERENCES `PIPELINE`(`PIPELINE_ID`);

ALTER TABLE `PIPELINE_INCIDENT`
ADD CONSTRAINT FK_PIPELINE_INCIDENT_INCIDENT FOREIGN KEY (`INCIDENT_ID`) REFERENCES `INCIDENT`(`INCIDENT_ID`);
