ALTER TABLE `PIPELINE_TEST`
ADD CONSTRAINT FK_PIPELINE_TEST_PIPELINE FOREIGN KEY (`PIPELINE_ID`) REFERENCES `PIPELINE`(`PIPELINE_ID`);

ALTER TABLE `PIPELINE_TEST`
ADD CONSTRAINT FK_PIPELINE_TEST_TEST FOREIGN KEY (`TEST_ID`) REFERENCES `TEST`(`TEST_ID`);

ALTER TABLE `PIPELINE_TEST`
ADD CONSTRAINT FK_PIPELINE_TEST_SEGMENT FOREIGN KEY (`SEGMENT_ID`) REFERENCES `SEGMENT`(`SEGMENT_ID`);
