ALTER TABLE `PIPELINE_FACILITY`
ADD CONSTRAINT FK_PIPELINE_FACILITY_PIPELINE FOREIGN KEY (`PIPELINE_ID`) REFERENCES `PIPELINE`(`PIPELINE_ID`);

ALTER TABLE `PIPELINE_FACILITY`
ADD CONSTRAINT FK_PIPELINE_FACILITY_FACILITY FOREIGN KEY (`FACILITY_ID`) REFERENCES `FACILITY`(`FACILITY_ID`);
