CREATE TABLE `PIPELINE_WELL`
(
    `PIPELINE_ID` VARCHAR(40),
    `UWI` VARCHAR(255),
    `CONNECTION_SEQ_NO` DECIMAL(18,2) NOT NULL,
    `CONNECTION_TYPE` VARCHAR(50),
    `CONNECTION_DATE` DATETIME,
    `FLOW_DIRECTION` VARCHAR(255),
    `DESCRIPTION` VARCHAR(2000),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `EFFECTIVE_DATE` DATETIME,
    `EXPIRY_DATE` DATETIME,
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_QUALITY` VARCHAR(40)
);
