CREATE TABLE `PIPELINE_PROPERTIES`
(
    `PIPELINE_PROPERTIES_ID` VARCHAR(40) NOT NULL,
    `DIAMETER` DECIMAL(18,2),
    `LENGTH` DECIMAL(18,2),
    `ROUGHNESS` DECIMAL(18,2),
    `ELEVATION_CHANGE` DECIMAL(18,2),
    `INLET_PRESSURE` DECIMAL(18,2),
    `OUTLET_PRESSURE` DECIMAL(18,2),
    `AVERAGE_TEMPERATURE` DECIMAL(18,2),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_QUALITY` VARCHAR(40)
);
