ALTER TABLE `PIPELINE_COMPONENT`
ADD CONSTRAINT FK_PIPELINE_COMPONENT_PIPELINE FOREIGN KEY (`PIPELINE_ID`) REFERENCES `PIPELINE`(`PIPELINE_ID`);

ALTER TABLE `PIPELINE_COMPONENT`
ADD CONSTRAINT FK_PIPELINE_COMPONENT_COMPONENT FOREIGN KEY (`COMPONENT_ID`) REFERENCES `COMPONENT`(`COMPONENT_ID`);

ALTER TABLE `PIPELINE_COMPONENT`
ADD CONSTRAINT FK_PIPELINE_COMPONENT_SEGMENT FOREIGN KEY (`SEGMENT_ID`) REFERENCES `SEGMENT`(`SEGMENT_ID`);
