raiserror ('CREATING TABLE ROD_SECTION', 10,1) with nowait

CREATE TABLE ROD_SECTION
(
    ROD_SECTION_ID NVARCHAR(40) NOT NULL,
    SUCKER_ROD_STRING_ID NVARCHAR(40),
    DIAMETER NUMERIC(18,2),
    LENGTH NUMERIC(18,2),
    DENSITY NUMERIC(18,2),
    WEIGHT NUMERIC(18,2),
    SECTION_ORDER INT,
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
