raiserror ('CREATING TABLE SUCKER_ROD_SYSTEM_PROPERTIES', 10,1) with nowait

CREATE TABLE SUCKER_ROD_SYSTEM_PROPERTIES
(
    SUCKER_ROD_SYSTEM_PROPERTIES_ID NVARCHAR(40) NOT NULL,
    WELL_DEPTH NUMERIC(18,2),
    TUBING_DIAMETER NUMERIC(18,2),
    ROD_DIAMETER NUMERIC(18,2),
    PUMP_DIAMETER NUMERIC(18,2),
    STROKE_LENGTH NUMERIC(18,2),
    STROKES_PER_MINUTE NUMERIC(18,2),
    WELLHEAD_PRESSURE NUMERIC(18,2),
    BOTTOM_HOLE_PRESSURE NUMERIC(18,2),
    OIL_GRAVITY NUMERIC(18,2),
    WATER_CUT NUMERIC(18,2),
    GAS_OIL_RATIO NUMERIC(18,6),
    GAS_SPECIFIC_GRAVITY NUMERIC(18,2),
    ROD_DENSITY NUMERIC(18,2),
    PUMP_EFFICIENCY NUMERIC(18,2),
    FLUID_LEVEL NUMERIC(18,2),
    FLUID_DENSITY NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
