raiserror ('CREATING TABLE GAS_COMPOSITION_COMPONENT', 10,1) with nowait

CREATE TABLE GAS_COMPOSITION_COMPONENT
(
    GAS_COMPONENT_ID NVARCHAR(40),
    GAS_COMPOSITION_ID NVARCHAR(40),
    COMPONENT_NAME NVARCHAR(255),
    MOLE_FRACTION NUMERIC(18,2),
    MOLECULAR_WEIGHT NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
