raiserror ('CREATING TABLE LIST_OF_VALUE', 10,1) with nowait

CREATE TABLE LIST_OF_VALUE
(
    LIST_OF_VALUE_ID NVARCHAR(40) NOT NULL,
    VALUE_TYPE NVARCHAR(50),
    VALUE_CODE NVARCHAR(255),
    VALUE_NAME NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    CATEGORY NVARCHAR(255),
    MODULE NVARCHAR(255),
    SORT_ORDER INT,
    PARENT_VALUE_ID NVARCHAR(40),
    IS_DEFAULT NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID BIGINT
);
