raiserror ('CREATING TABLE OIL_COMPOSITION', 10,1) with nowait

CREATE TABLE OIL_COMPOSITION
(
    OIL_COMPOSITION_ID NVARCHAR(40) NOT NULL,
    COMPOSITION_NAME NVARCHAR(255),
    COMPOSITION_DATE DATETIME,
    OIL_GRAVITY NVARCHAR(255),
    GAS_OIL_RATIO NVARCHAR(255),
    WATER_CUT NVARCHAR(255),
    BUBBLE_POINT_PRESSURE NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
