raiserror ('CREATING TABLE PPDM_DEFAULT_VALUE', 10,1) with nowait

CREATE TABLE PPDM_DEFAULT_VALUE
(
    DEFAULT_VALUE_ID NVARCHAR(40),
    DEFAULT_KEY NVARCHAR(255),
    DEFAULT_VALUE NVARCHAR(255),
    DEFAULT_CATEGORY NVARCHAR(255),
    VALUE_TYPE NVARCHAR(50),
    USER_ID NVARCHAR(40),
    DATABASE_ID NVARCHAR(40),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID BIGINT
);
