raiserror ('CREATING TABLE PROVED_PROPERTY', 10,1) with nowait

CREATE TABLE PROVED_PROPERTY
(
    PROPERTY_ID NVARCHAR(40),
    ACQUISITION_COST NUMERIC(18,2),
    EXPLORATION_COSTS NUMERIC(18,6),
    DEVELOPMENT_COSTS NUMERIC(18,2),
    ACCUMULATED_AMORTIZATION NUMERIC(18,2),
    PROVED_DATE DATETIME,
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40),
    PROVED_RESERVES_GAS NUMERIC(18,2) NOT NULL,
    PROVED_RESERVES_OIL NUMERIC(18,2) NOT NULL,
    PROVED_RESERVES_BOE NVARCHAR(255) NOT NULL
);
