raiserror ('CREATING TABLE R_ECONOMIC_METRIC', 10,1) with nowait

CREATE TABLE R_ECONOMIC_METRIC
(
    ECONOMIC_METRIC NVARCHAR(255),
    ABBREVIATION NVARCHAR(255),
    LONG_NAME NVARCHAR(255),
    SHORT_NAME NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
