raiserror ('CREATING TABLE R_RISK_LEVEL', 10,1) with nowait

CREATE TABLE R_RISK_LEVEL
(
    RISK_LEVEL NVARCHAR(255),
    ABBREVIATION NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    LONG_NAME NVARCHAR(255),
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SHORT_NAME NVARCHAR(255),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
