ALTER TABLE RESERVOIR_STATUS
ADD CONSTRAINT FK_RESERVOIR_STATUS_RESERVE_ENTITY FOREIGN KEY (RESERVE_ENTITY_ID) REFERENCES RESERVE_ENTITY(RESERVE_ENTITY_ID);

ALTER TABLE RESERVOIR_STATUS
ADD CONSTRAINT FK_RESERVOIR_STATUS_POOL FOREIGN KEY (POOL_ID) REFERENCES POOL(POOL_ID);
