raiserror ('CREATING TABLE UNPROVED_PROPERTY', 10,1) with nowait

CREATE TABLE UNPROVED_PROPERTY
(
    PROPERTY_ID NVARCHAR(40),
    PROPERTY_NAME NVARCHAR(255),
    ACQUISITION_COST NUMERIC(18,2),
    ACQUISITION_DATE DATETIME,
    PROPERTY_TYPE NVARCHAR(50),
    WORKING_INTEREST NUMERIC(18,2),
    NET_REVENUE_INTEREST NUMERIC(18,2),
    ACCUMULATED_IMPAIRMENT NUMERIC(18,2),
    IS_PROVED NVARCHAR(255),
    PROVED_DATE DATETIME,
    COST_CENTER_ID NVARCHAR(40),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
