CREATE TABLE `PLUNGER_LIFT_CYCLE_POINT`
(
    `PLUNGER_LIFT_CYCLE_POINT_ID` VARCHAR(40) NOT NULL,
    `PLUNGER_LIFT_CYCLE_RESULT_ID` VARCHAR(40),
    `TIME` DECIMAL(18,2),
    `PHASE` VARCHAR(255),
    `PLUNGER_DEPTH` DECIMAL(18,2),
    `CASING_PRESSURE` DECIMAL(18,2),
    `TUBING_PRESSURE` DECIMAL(18,2),
    `PRODUCTION_RATE` DECIMAL(18,2),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_QUALITY` VARCHAR(40)
);
