ALTER TABLE "OIL_PROPERTY_CONDITIONS"
ADD CONSTRAINT FK_OIL_PROPERTY_CONDITIONS_AREA FOREIGN KEY ("AREA_ID") REFERENCES "AREA"("AREA_ID");

ALTER TABLE "OIL_PROPERTY_CONDITIONS"
ADD CONSTRAINT FK_OIL_PROPERTY_CONDITIONS_BUSINESS_ASSOCIATE FOREIGN KEY ("BUSINESS_ASSOCIATE_ID") REFERENCES "BUSINESS_ASSOCIATE"("BUSINESS_ASSOCIATE_ID");
