CREATE TABLE RECEIVABLE
(
    RECEIVABLE_ID TEXT NOT NULL,
    SALES_TRANSACTION_ID TEXT,
    CUSTOMER_BA_ID TEXT,
    INVOICE_NUMBER TEXT,
    INVOICE_DATE DATETIME,
    DUE_DATE DATETIME,
    ORIGINAL_AMOUNT REAL,
    AMOUNT_PAID REAL,
    OUTSTANDING_BALANCE REAL,
    STATUS TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT
);
