CREATE TABLE ALLOCATION_DETAIL
(
    ALLOCATION_DETAIL_ID VARCHAR(40) NOT NULL,
    ALLOCATION_RESULT_ID VARCHAR(40) NOT NULL,
    ENTITY_ID VARCHAR(40),
    ENTITY_TYPE VARCHAR(100),
    ENTITY_NAME VARCHAR(255),
    ALLOCATED_VOLUME NUMERIC(18,2),
    ALLOCATION_PERCENTAGE NUMERIC(18,6),
    ALLOCATION_BASIS NUMERIC(18,6),
    ACTIVE_IND VARCHAR(1),
    PPDM_GUID VARCHAR(40),
    REMARK VARCHAR(4000),
    SOURCE VARCHAR(40),
    ROW_QUALITY VARCHAR(40),
    ROW_CREATED_BY VARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY VARCHAR(40),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID BIGINT
);

