CREATE TABLE ORGANIZATION_HIERARCHY_CONFIG
(
    ORGANIZATION_ID TEXT,
    HIERARCHY_LEVEL INTEGER NOT NULL,
    LEVEL_NAME TEXT,
    ASSET_TYPE TEXT,
    PARENT_LEVEL INTEGER,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT
);
