CREATE TABLE SETUP_WIZARD_LOG
(
    SETUP_LOG_ID TEXT,
    ORGANIZATION_ID TEXT,
    SETUP_STEP TEXT,
    SETUP_DATA TEXT,
    EXECUTED_BY TEXT,
    EXECUTION_DATE DATETIME,
    STATUS TEXT,
    ERROR_MESSAGE TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT
);
