CREATE TABLE USER_PROFILE
(
    USER_ID TEXT,
    PRIMARY_ROLE TEXT,
    PREFERRED_LAYOUT TEXT,
    USER_PREFERENCES TEXT,
    LAST_LOGIN_DATE DATETIME,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT
);
