CREATE TABLE USER_ROLE
(
    USER_ROLE_ID TEXT NOT NULL,
    USER_ID TEXT,
    ROLE_ID TEXT,
    ACTIVE_IND TEXT,
    ROW_QUALITY TEXT,
    PPDM_GUID TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    AREA_ID TEXT,
    AREA_TYPE TEXT,
    BUSINESS_ASSOCIATE_ID TEXT,
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    SOURCE TEXT,
    REMARK TEXT
);
