CREATE TABLE USER_ASSET_ACCESS
(
    USER_ID TEXT,
    ASSET_TYPE TEXT,
    ASSET_ID TEXT,
    ACCESS_LEVEL TEXT,
    INHERIT_IND TEXT,
    ORGANIZATION_ID TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT
);
