CREATE TABLE `ACCOUNTING_METHOD`
(
    `ACCOUNTING_METHOD_ID` VARCHAR(40) NOT NULL,
    `ROW_QUALITY` VARCHAR(40),
    `FIELD_ID` VARCHAR(40),
    `COST_CENTER_ID` VARCHAR(40),
    `METHOD_TYPE` VARCHAR(50),
    `EFFECTIVE_DATE` DATETIME,
    `EXPIRY_DATE` DATETIME,
    `DESCRIPTION` VARCHAR(2000),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
