CREATE TABLE `ACTUAL_DELIVERY`
(
    `ACTUAL_DELIVERY_ID` VARCHAR(40) NOT NULL,
    `DELIVERY_DATE` DATETIME,
    `ACTUAL_VOLUME` DECIMAL(18,2),
    `DELIVERY_POINT` VARCHAR(255),
    `ALLOCATION_METHOD` VARCHAR(255),
    `RUN_TICKET_NUMBER` VARCHAR(255),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
