CREATE TABLE `ALLOCATION_DETAIL`
(
    `ALLOCATION_DETAIL_ID` VARCHAR(40) NOT NULL,
    `ALLOCATION_RESULT_ID` VARCHAR(40),
    `ENTITY_ID` VARCHAR(40),
    `ENTITY_TYPE` VARCHAR(50),
    `ENTITY_NAME` VARCHAR(255),
    `ALLOCATED_VOLUME` DECIMAL(18,2),
    `ALLOCATION_PERCENTAGE` DECIMAL(18,6),
    `ALLOCATION_BASIS` DECIMAL(18,2),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40),
    `AllocationRequest_ID` VARCHAR(40)
);
