CREATE TABLE `AR_CREDIT_MEMO`
(
    `AR_CREDIT_MEMO_ID` VARCHAR(40) NOT NULL,
    `AR_INVOICE_ID` VARCHAR(40),
    `CREDIT_MEMO_NUMBER` VARCHAR(255),
    `CREDIT_MEMO_DATE` DATETIME,
    `CREDIT_AMOUNT` DECIMAL(18,2),
    `REASON` VARCHAR(255),
    `STATUS` VARCHAR(50),
    `DESCRIPTION` VARCHAR(2000),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
