-- CRUDE_OIL_INVENTORY_TRANSACTION Table Creation Script
-- SQL Server Version

CREATE TABLE CRUDE_OIL_INVENTORY_TRANSACTION
(
    TRANSACTION_ID NVARCHAR(40) NOT NULL,
    INVENTORY_ID NVARCHAR(40) NOT NULL,
    TRANSACTION_DATE DATETIME,
    TRANSACTION_TYPE NVARCHAR(40),
    VOLUME NUMERIC(18,2),
    UNIT_COST NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1),
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(4000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(40),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);

-- Primary Key
ALTER TABLE CRUDE_OIL_INVENTORY_TRANSACTION
ADD CONSTRAINT PK_CRUDE_OIL_INVENTORY_TRANSACTION PRIMARY KEY (TRANSACTION_ID);

-- Foreign Keys
ALTER TABLE CRUDE_OIL_INVENTORY_TRANSACTION
ADD CONSTRAINT FK_INVENTORY_TRANSACTION_INVENTORY FOREIGN KEY (INVENTORY_ID) REFERENCES CRUDE_OIL_INVENTORY(INVENTORY_ID);

-- Indexes
CREATE INDEX IX_INVENTORY_TRANSACTION_INVENTORY ON CRUDE_OIL_INVENTORY_TRANSACTION(INVENTORY_ID);
CREATE INDEX IX_INVENTORY_TRANSACTION_DATE ON CRUDE_OIL_INVENTORY_TRANSACTION(TRANSACTION_DATE);
CREATE INDEX IX_INVENTORY_TRANSACTION_TYPE ON CRUDE_OIL_INVENTORY_TRANSACTION(TRANSACTION_TYPE);

