-- CRUDE_OIL_INVENTORY Table Creation Script
-- SQL Server Version

CREATE TABLE CRUDE_OIL_INVENTORY
(
    INVENTORY_ID NVARCHAR(40) NOT NULL,
    PROPERTY_OR_LEASE_ID NVARCHAR(40),
    TANK_BATTERY_ID NVARCHAR(40),
    INVENTORY_DATE DATETIME,
    VOLUME NUMERIC(18,2),
    UNIT_COST NUMERIC(18,2),
    VALUATION_METHOD NVARCHAR(40),
    MARKET_PRICE NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1),
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(4000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(40),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);

-- Primary Key
ALTER TABLE CRUDE_OIL_INVENTORY
ADD CONSTRAINT PK_CRUDE_OIL_INVENTORY PRIMARY KEY (INVENTORY_ID);

-- Indexes
CREATE INDEX IX_CRUDE_OIL_INVENTORY_PROPERTY ON CRUDE_OIL_INVENTORY(PROPERTY_OR_LEASE_ID);
CREATE INDEX IX_CRUDE_OIL_INVENTORY_TANK_BATTERY ON CRUDE_OIL_INVENTORY(TANK_BATTERY_ID);
CREATE INDEX IX_CRUDE_OIL_INVENTORY_DATE ON CRUDE_OIL_INVENTORY(INVENTORY_DATE);

