CREATE TABLE `EXCHANGE_DELIVERY_POINT`
(
    `EXCHANGE_DELIVERY_POINT_ID` VARCHAR(40) NOT NULL,
    `EXCHANGE_CONTRACT_ID` VARCHAR(40),
    `DELIVERY_POINT_NAME` VARCHAR(255),
    `LOCATION` VARCHAR(255),
    `IS_RECEIPT_POINT` VARCHAR(255),
    `IS_DELIVERY_POINT` VARCHAR(255),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
