CREATE TABLE `EXCHANGE_PRICING_TERMS`
(
    `EXCHANGE_PRICING_TERMS_ID` VARCHAR(40) NOT NULL,
    `EXCHANGE_CONTRACT_ID` VARCHAR(40),
    `BASE_PRICE_INDEX` VARCHAR(255),
    `LOCATION_DIFFERENTIAL` DECIMAL(18,2),
    `QUALITY_DIFFERENTIAL` DECIMAL(18,2),
    `TIME_DIFFERENTIAL` DECIMAL(18,2),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
