CREATE TABLE `JOIB_ALLOCATION`
(
    `JOIB_ALLOCATION_ID` VARCHAR(40) NOT NULL,
    `JOINT_INTEREST_BILL_ID` VARCHAR(40),
    `JOIB_LINE_ITEM_ID` VARCHAR(40),
    `INTEREST_OWNER_BA_ID` VARCHAR(40),
    `ALLOCATED_AMOUNT` DECIMAL(18,2),
    `ALLOCATION_PERCENTAGE` DECIMAL(18,6),
    `ALLOCATION_METHOD` VARCHAR(255),
    `DESCRIPTION` VARCHAR(2000),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
