ALTER TABLE `JOINT_OPERATING_AGREEMENT`
ADD CONSTRAINT FK_JOINT_OPERATING_AGREEMENT_JOA FOREIGN KEY (`JOA_ID`) REFERENCES `JOA`(`JOA_ID`);

ALTER TABLE `JOINT_OPERATING_AGREEMENT`
ADD CONSTRAINT FK_JOINT_OPERATING_AGREEMENT_FIELD FOREIGN KEY (`FIELD_ID`) REFERENCES `FIELD`(`FIELD_ID`);

ALTER TABLE `JOINT_OPERATING_AGREEMENT`
ADD CONSTRAINT FK_JOINT_OPERATING_AGREEMENT_OPERATOR_BA FOREIGN KEY (`OPERATOR_BA_ID`) REFERENCES `OPERATOR_BA`(`OPERATOR_BA_ID`);
