ALTER TABLE `JOINT_INTEREST_BILL`
ADD CONSTRAINT FK_JOINT_INTEREST_BILL_JIB FOREIGN KEY (`JIB_ID`) REFERENCES `JIB`(`JIB_ID`);

ALTER TABLE `JOINT_INTEREST_BILL`
ADD CONSTRAINT FK_JOINT_INTEREST_BILL_INTEREST_SET FOREIGN KEY (`INTEREST_SET_ID`) REFERENCES `INTEREST_SET`(`INTEREST_SET_ID`);

ALTER TABLE `JOINT_INTEREST_BILL`
ADD CONSTRAINT FK_JOINT_INTEREST_BILL_FIELD FOREIGN KEY (`FIELD_ID`) REFERENCES `FIELD`(`FIELD_ID`);

ALTER TABLE `JOINT_INTEREST_BILL`
ADD CONSTRAINT FK_JOINT_INTEREST_BILL_OPERATOR FOREIGN KEY (`OPERATOR_ID`) REFERENCES `OPERATOR`(`OPERATOR_ID`);
