CREATE TABLE `NOMINATION`
(
    `NOMINATION_ID` VARCHAR(40) NOT NULL,
    `PERIOD_START` DATETIME,
    `PERIOD_END` DATETIME,
    `NOMINATED_VOLUME` DECIMAL(18,2),
    `DELIVERY_POINTS_JSON` VARCHAR(255),
    `STATUS` VARCHAR(50),
    `SUBMISSION_DATE` DATETIME,
    `APPROVAL_DATE` DATETIME,
    `APPROVED_BY` VARCHAR(255),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
