ALTER TABLE `OPERATIONAL_REPORT`
ADD CONSTRAINT FK_OPERATIONAL_REPORT_PRODUCTION_REPORT_SUMMARY FOREIGN KEY (`PRODUCTION_REPORT_SUMMARY_ID`) REFERENCES `PRODUCTION_REPORT_SUMMARY`(`PRODUCTION_REPORT_SUMMARY_ID`);

ALTER TABLE `OPERATIONAL_REPORT`
ADD CONSTRAINT FK_OPERATIONAL_REPORT_INVENTORY_REPORT_SUMMARY FOREIGN KEY (`INVENTORY_REPORT_SUMMARY_ID`) REFERENCES `INVENTORY_REPORT_SUMMARY`(`INVENTORY_REPORT_SUMMARY_ID`);

ALTER TABLE `OPERATIONAL_REPORT`
ADD CONSTRAINT FK_OPERATIONAL_REPORT_ALLOCATION_REPORT_SUMMARY FOREIGN KEY (`ALLOCATION_REPORT_SUMMARY_ID`) REFERENCES `ALLOCATION_REPORT_SUMMARY`(`ALLOCATION_REPORT_SUMMARY_ID`);

ALTER TABLE `OPERATIONAL_REPORT`
ADD CONSTRAINT FK_OPERATIONAL_REPORT_MEASUREMENT_REPORT_SUMMARY FOREIGN KEY (`MEASUREMENT_REPORT_SUMMARY_ID`) REFERENCES `MEASUREMENT_REPORT_SUMMARY`(`MEASUREMENT_REPORT_SUMMARY_ID`);

ALTER TABLE `OPERATIONAL_REPORT`
ADD CONSTRAINT FK_OPERATIONAL_REPORT_COST_REPORT_SUMMARY FOREIGN KEY (`COST_REPORT_SUMMARY_ID`) REFERENCES `COST_REPORT_SUMMARY`(`COST_REPORT_SUMMARY_ID`);
