ALTER TABLE `PO_RECEIPT`
ADD CONSTRAINT FK_PO_RECEIPT_PURCHASE_ORDER FOREIGN KEY (`PURCHASE_ORDER_ID`) REFERENCES `PURCHASE_ORDER`(`PURCHASE_ORDER_ID`);

ALTER TABLE `PO_RECEIPT`
ADD CONSTRAINT FK_PO_RECEIPT_PO_LINE_ITEM FOREIGN KEY (`PO_LINE_ITEM_ID`) REFERENCES `PO_LINE_ITEM`(`PO_LINE_ITEM_ID`);
