CREATE TABLE `PO_RECEIPT`
(
    `PO_RECEIPT_ID` VARCHAR(40) NOT NULL,
    `PURCHASE_ORDER_ID` VARCHAR(40),
    `PO_LINE_ITEM_ID` VARCHAR(40),
    `RECEIPT_DATE` DATETIME,
    `RECEIVED_QUANTITY` DECIMAL(18,2),
    `RECEIVED_BY` VARCHAR(255),
    `RECEIPT_STATUS` VARCHAR(50),
    `DESCRIPTION` VARCHAR(2000),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
