CREATE TABLE `REVENUE_DEDUCTION`
(
    `REVENUE_DEDUCTION_ID` VARCHAR(40) NOT NULL,
    `REVENUE_TRANSACTION_ID` VARCHAR(40),
    `DEDUCTION_TYPE` VARCHAR(50),
    `AMOUNT` DECIMAL(18,2) NOT NULL,
    `DESCRIPTION` VARCHAR(2000),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_QUALITY` VARCHAR(40),
    `ROW_ID` VARCHAR(40)
);
