ALTER TABLE `ROYALTY_INTEREST`
ADD CONSTRAINT FK_ROYALTY_INTEREST_ROYALTY_OWNER FOREIGN KEY (`ROYALTY_OWNER_ID`) REFERENCES `ROYALTY_OWNER`(`ROYALTY_OWNER_ID`);

ALTER TABLE `ROYALTY_INTEREST`
ADD CONSTRAINT FK_ROYALTY_INTEREST_PROPERTY_OR_LEASE FOREIGN KEY (`PROPERTY_OR_LEASE_ID`) REFERENCES `PROPERTY_OR_LEASE`(`PROPERTY_OR_LEASE_ID`);

ALTER TABLE `ROYALTY_INTEREST`
ADD CONSTRAINT FK_ROYALTY_INTEREST_DIVISION_ORDER FOREIGN KEY (`DIVISION_ORDER_ID`) REFERENCES `DIVISION_ORDER`(`DIVISION_ORDER_ID`);
