CREATE TABLE `ROYALTY_CALCULATION`
(
    `ROYALTY_CALCULATION_ID` VARCHAR(40) NOT NULL,
    `CALCULATION_DATE` DATETIME,
    `PROPERTY_OR_LEASE_ID` VARCHAR(40),
    `GROSS_REVENUE` DECIMAL(18,2),
    `ROYALTY_DEDUCTIONS_ID` VARCHAR(40),
    `NET_REVENUE` DECIMAL(18,2),
    `ROYALTY_INTEREST` DECIMAL(18,2),
    `ROYALTY_AMOUNT` DECIMAL(18,2),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
