ALTER TABLE `RUN_TICKET`
ADD CONSTRAINT FK_RUN_TICKET_LEASE FOREIGN KEY (`LEASE_ID`) REFERENCES `LEASE`(`LEASE_ID`);

ALTER TABLE `RUN_TICKET`
ADD CONSTRAINT FK_RUN_TICKET_WELL FOREIGN KEY (`WELL_ID`) REFERENCES `WELL`(`WELL_ID`);

ALTER TABLE `RUN_TICKET`
ADD CONSTRAINT FK_RUN_TICKET_TANK_BATTERY FOREIGN KEY (`TANK_BATTERY_ID`) REFERENCES `TANK_BATTERY`(`TANK_BATTERY_ID`);

ALTER TABLE `RUN_TICKET`
ADD CONSTRAINT FK_RUN_TICKET_MEASUREMENT_RECORD FOREIGN KEY (`MEASUREMENT_RECORD_ID`) REFERENCES `MEASUREMENT_RECORD`(`MEASUREMENT_RECORD_ID`);
