ALTER TABLE `SALES_CONTRACT`
ADD CONSTRAINT FK_SALES_CONTRACT_BUYER_BA FOREIGN KEY (`BUYER_BA_ID`) REFERENCES `BUYER_BA`(`BUYER_BA_ID`);

ALTER TABLE `SALES_CONTRACT`
ADD CONSTRAINT FK_SALES_CONTRACT_SELLER_BA FOREIGN KEY (`SELLER_BA_ID`) REFERENCES `SELLER_BA`(`SELLER_BA_ID`);
