CREATE TABLE `TAX_TRANSACTION`
(
    `TAX_TRANSACTION_ID` VARCHAR(40) NOT NULL,
    `PROPERTY_ID` VARCHAR(40),
    `TAX_TYPE` VARCHAR(50),
    `TAX_DATE` DATETIME,
    `TAX_AMOUNT` DECIMAL(18,2),
    `TAX_JURISDICTION` VARCHAR(255),
    `DESCRIPTION` VARCHAR(2000),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
