CREATE TABLE `PARTICIPATING_AREA`
(
    `PARTICIPATING_AREA_ID` VARCHAR(40) NOT NULL,
    `UNIT_AGREEMENT_ID` VARCHAR(40),
    `AREA_NAME` VARCHAR(255),
    `EFFECTIVE_DATE` DATETIME,
    `EXPIRY_DATE` DATETIME,
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME
);
