CREATE TABLE `UNIT_AGREEMENT`
(
    `UNIT_AGREEMENT_ID` VARCHAR(40) NOT NULL,
    `UNIT_NAME` VARCHAR(255),
    `UNIT_NUMBER` VARCHAR(255),
    `UNIT_OPERATOR_BA_ID` VARCHAR(40),
    `EFFECTIVE_DATE` DATETIME,
    `EXPIRY_DATE` DATETIME,
    `STATUS` VARCHAR(50),
    `TERMS_AND_CONDITIONS` VARCHAR(255),
    `APPROVAL_DATE` DATETIME,
    `APPROVED_BY` VARCHAR(255),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME
);
