raiserror ('CREATING TABLE ESP_DESIGN_PROPERTIES', 10,1) with nowait

CREATE TABLE ESP_DESIGN_PROPERTIES
(
    ESP_DESIGN_PROPERTIES_ID NVARCHAR(40) NOT NULL,
    DESIRED_FLOW_RATE NUMERIC(18,2),
    TOTAL_DYNAMIC_HEAD NUMERIC(18,2),
    WELL_DEPTH NUMERIC(18,2),
    CASING_DIAMETER NUMERIC(18,2),
    TUBING_DIAMETER NUMERIC(18,2),
    OIL_GRAVITY NUMERIC(18,2),
    WATER_CUT NUMERIC(18,2),
    GAS_OIL_RATIO NUMERIC(18,6),
    WELLHEAD_PRESSURE NUMERIC(18,2),
    BOTTOM_HOLE_TEMPERATURE NUMERIC(18,2),
    GAS_SPECIFIC_GRAVITY NUMERIC(18,2),
    PUMP_SETTING_DEPTH NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME
);
