CREATE TABLE "COMPRESSOR_OPERATING_CONDITIONS"
(
    "COMPRESSOR_OPERATING_CONDITIONS_ID" VARCHAR(40) NOT NULL,
    "SUCTION_PRESSURE" NUMERIC(18,2),
    "DISCHARGE_PRESSURE" NUMERIC(18,2),
    "SUCTION_TEMPERATURE" NUMERIC(18,2),
    "DISCHARGE_TEMPERATURE" NUMERIC(18,2),
    "GAS_FLOW_RATE" NUMERIC(18,2),
    "GAS_SPECIFIC_GRAVITY" NUMERIC(18,2),
    "GAS_MOLECULAR_WEIGHT" NUMERIC(18,2),
    "COMPRESSOR_EFFICIENCY" NUMERIC(18,2),
    "MECHANICAL_EFFICIENCY" NUMERIC(18,2),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_QUALITY" VARCHAR(40)
);
