CREATE TABLE "RECIPROCATING_COMPRESSOR_PROPERTIES"
(
    "RECIPROCATING_COMPRESSOR_PROPERTIES_ID" VARCHAR(40) NOT NULL,
    "COMPRESSOR_OPERATING_CONDITIONS_ID" VARCHAR(40),
    "CYLINDER_DIAMETER" NUMERIC(18,2),
    "STROKE_LENGTH" NUMERIC(18,2),
    "ROTATIONAL_SPEED" NUMERIC(18,2),
    "NUMBER_OF_CYLINDERS" INTEGER,
    "VOLUMETRIC_EFFICIENCY" NUMERIC(18,2),
    "CLEARANCE_FACTOR" NUMERIC(18,2),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_QUALITY" VARCHAR(40)
);
