raiserror ('CREATING TABLE GAS_PIPELINE_FLOW_PROPERTIES', 10,1) with nowait

CREATE TABLE GAS_PIPELINE_FLOW_PROPERTIES
(
    GAS_PIPELINE_FLOW_PROPERTIES_ID NVARCHAR(40) NOT NULL,
    PIPELINE_PROPERTIES_ID NVARCHAR(40),
    GAS_FLOW_RATE NUMERIC(18,2),
    GAS_SPECIFIC_GRAVITY NUMERIC(18,2),
    GAS_MOLECULAR_WEIGHT NUMERIC(18,2),
    BASE_PRESSURE NUMERIC(18,2),
    BASE_TEMPERATURE NUMERIC(18,2),
    Z_FACTOR NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
