raiserror ('CREATING TABLE LIQUID_PIPELINE_FLOW_PROPERTIES', 10,1) with nowait

CREATE TABLE LIQUID_PIPELINE_FLOW_PROPERTIES
(
    LIQUID_PIPELINE_FLOW_PROPERTIES_ID NVARCHAR(40) NOT NULL,
    PIPELINE_PROPERTIES_ID NVARCHAR(40),
    LIQUID_FLOW_RATE NUMERIC(18,2),
    LIQUID_SPECIFIC_GRAVITY NUMERIC(18,2),
    LIQUID_VISCOSITY NUMERIC(18,2),
    LIQUID_DENSITY NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
