ALTER TABLE PIPELINE_ROUTE
ADD CONSTRAINT FK_PIPELINE_ROUTE_PIPELINE FOREIGN KEY (PIPELINE_ID) REFERENCES PIPELINE(PIPELINE_ID);

ALTER TABLE PIPELINE_ROUTE
ADD CONSTRAINT FK_PIPELINE_ROUTE_COORD_SYSTEM FOREIGN KEY (COORD_SYSTEM_ID) REFERENCES COORD_SYSTEM(COORD_SYSTEM_ID);

ALTER TABLE PIPELINE_ROUTE
ADD CONSTRAINT FK_PIPELINE_ROUTE_LOCAL_COORD_SYSTEM FOREIGN KEY (LOCAL_COORD_SYSTEM_ID) REFERENCES LOCAL_COORD_SYSTEM(LOCAL_COORD_SYSTEM_ID);

ALTER TABLE PIPELINE_ROUTE
ADD CONSTRAINT FK_PIPELINE_ROUTE_COORD_ACQUISITION FOREIGN KEY (COORD_ACQUISITION_ID) REFERENCES COORD_ACQUISITION(COORD_ACQUISITION_ID);
