raiserror ('CREATING TABLE PIPELINE_COMPONENT', 10,1) with nowait

CREATE TABLE PIPELINE_COMPONENT
(
    PIPELINE_ID NVARCHAR(40),
    COMPONENT_ID NVARCHAR(40),
    COMPONENT_TYPE NVARCHAR(50),
    PART_NUMBER NVARCHAR(255),
    SEGMENT_ID NVARCHAR(40),
    MATERIAL_TYPE NVARCHAR(50),
    MATERIAL_GRADE NVARCHAR(255),
    MANUFACTURER NVARCHAR(255),
    INSTALLATION_DATE DATETIME,
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
