raiserror ('CREATING TABLE PIPELINE_PROPERTIES', 10,1) with nowait

CREATE TABLE PIPELINE_PROPERTIES
(
    PIPELINE_PROPERTIES_ID NVARCHAR(40) NOT NULL,
    DIAMETER NUMERIC(18,2),
    LENGTH NUMERIC(18,2),
    ROUGHNESS NUMERIC(18,2),
    ELEVATION_CHANGE NUMERIC(18,2),
    INLET_PRESSURE NUMERIC(18,2),
    OUTLET_PRESSURE NUMERIC(18,2),
    AVERAGE_TEMPERATURE NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
