ALTER TABLE PIPELINE_ANOMALY
ADD CONSTRAINT FK_PIPELINE_ANOMALY_PIPELINE FOREIGN KEY (PIPELINE_ID) REFERENCES PIPELINE(PIPELINE_ID);

ALTER TABLE PIPELINE_ANOMALY
ADD CONSTRAINT FK_PIPELINE_ANOMALY_ANOMALY FOREIGN KEY (ANOMALY_ID) REFERENCES ANOMALY(ANOMALY_ID);

ALTER TABLE PIPELINE_ANOMALY
ADD CONSTRAINT FK_PIPELINE_ANOMALY_INSPECTION FOREIGN KEY (INSPECTION_ID) REFERENCES INSPECTION(INSPECTION_ID);

ALTER TABLE PIPELINE_ANOMALY
ADD CONSTRAINT FK_PIPELINE_ANOMALY_SEGMENT FOREIGN KEY (SEGMENT_ID) REFERENCES SEGMENT(SEGMENT_ID);
