raiserror ('CREATING TABLE PIPELINE_ANOMALY', 10,1) with nowait

CREATE TABLE PIPELINE_ANOMALY
(
    PIPELINE_ID NVARCHAR(40),
    ANOMALY_ID NVARCHAR(40),
    ANOMALY_TYPE NVARCHAR(50),
    INSPECTION_ID NVARCHAR(40),
    LOCATION_STATION_MILEPOST NUMERIC(18,2) NOT NULL,
    LOCATION_STATION_MILEPOST_OUOM NVARCHAR(255),
    SEVERITY NVARCHAR(255),
    ANOMALY_LENGTH NUMERIC(18,2) NOT NULL,
    ANOMALY_LENGTH_OUOM NVARCHAR(255),
    ANOMALY_DEPTH NUMERIC(18,2) NOT NULL,
    ANOMALY_DEPTH_OUOM NVARCHAR(255),
    ANOMALY_WIDTH NUMERIC(18,2) NOT NULL,
    ANOMALY_WIDTH_OUOM NVARCHAR(255),
    SEGMENT_ID NVARCHAR(40),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
