raiserror ('CREATING TABLE PIPELINE_MAINTENANCE', 10,1) with nowait

CREATE TABLE PIPELINE_MAINTENANCE
(
    PIPELINE_ID NVARCHAR(40),
    MAINTENANCE_ID NVARCHAR(40),
    MAINTENANCE_TYPE NVARCHAR(50),
    SCHEDULE_DATE DATETIME,
    COMPLETION_DATE DATETIME,
    CREW NVARCHAR(255),
    MAINTENANCE_COST NUMERIC(18,2) NOT NULL,
    MAINTENANCE_COST_OUOM NVARCHAR(255),
    SEGMENT_ID NVARCHAR(40),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
