raiserror ('CREATING TABLE PIPELINE_ROUTE', 10,1) with nowait

CREATE TABLE PIPELINE_ROUTE
(
    PIPELINE_ID NVARCHAR(40),
    ROUTE_SEQ_NO NUMERIC(18,2) NOT NULL,
    LATITUDE NUMERIC(18,2) NOT NULL,
    LONGITUDE NUMERIC(18,2) NOT NULL,
    ELEVATION NUMERIC(18,2) NOT NULL,
    ELEVATION_OUOM NVARCHAR(255),
    STATION_MILEPOST NUMERIC(18,2) NOT NULL,
    STATION_MILEPOST_OUOM NVARCHAR(255),
    LINEAR_REFERENCE NUMERIC(18,2) NOT NULL,
    COORD_SYSTEM_ID NVARCHAR(40),
    LOCAL_COORD_SYSTEM_ID NVARCHAR(40),
    COORD_ACQUISITION_ID NVARCHAR(40),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
