raiserror ('CREATING TABLE PIPELINE_RISK_ASSESSMENT', 10,1) with nowait

CREATE TABLE PIPELINE_RISK_ASSESSMENT
(
    PIPELINE_ID NVARCHAR(40),
    RISK_ASSESSMENT_ID NVARCHAR(40),
    ASSESSMENT_DATE DATETIME,
    RISK_SCORE NUMERIC(18,2) NOT NULL,
    ASSESSMENT_METHOD NVARCHAR(255),
    RISK_FACTORS NVARCHAR(255),
    SEGMENT_ID NVARCHAR(40),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
