raiserror ('CREATING TABLE PIPELINE_CONSTRUCTION', 10,1) with nowait

CREATE TABLE PIPELINE_CONSTRUCTION
(
    PIPELINE_ID NVARCHAR(40),
    CONSTRUCTION_PHASE_NO NVARCHAR(255),
    PHASE_TYPE NVARCHAR(50),
    PHASE_NAME NVARCHAR(255),
    START_DATE DATETIME,
    END_DATE DATETIME,
    CONTRACTOR NVARCHAR(255),
    INSPECTION_RECORDS NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
