raiserror ('CREATING TABLE PIPELINE_TEST', 10,1) with nowait

CREATE TABLE PIPELINE_TEST
(
    PIPELINE_ID NVARCHAR(40),
    TEST_ID NVARCHAR(40),
    TEST_TYPE NVARCHAR(50),
    TEST_DATE DATETIME,
    TEST_PRESSURE NUMERIC(18,2) NOT NULL,
    TEST_PRESSURE_OUOM NVARCHAR(255),
    TEST_RESULT NVARCHAR(255),
    TEST_DURATION NUMERIC(18,6) NOT NULL,
    TEST_DURATION_OUOM NVARCHAR(255),
    SEGMENT_ID NVARCHAR(40),
    TEST_METHOD NVARCHAR(255),
    INSPECTOR NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
