raiserror ('CREATING TABLE PIPELINE_DESIGN', 10,1) with nowait

CREATE TABLE PIPELINE_DESIGN
(
    PIPELINE_ID NVARCHAR(40),
    DESIGN_VERSION_NO NVARCHAR(255),
    DESIGN_PRESSURE NUMERIC(18,2) NOT NULL,
    DESIGN_PRESSURE_OUOM NVARCHAR(255),
    DESIGN_TEMPERATURE NUMERIC(18,2) NOT NULL,
    DESIGN_TEMPERATURE_OUOM NVARCHAR(255),
    MATERIAL_GRADE NVARCHAR(255),
    COATING_TYPE NVARCHAR(50),
    CATHODIC_PROTECTION_TYPE NVARCHAR(50),
    CP_SYSTEM_TYPE NVARCHAR(50),
    DESIGN_SPECIFICATION NVARCHAR(255),
    DESIGN_STANDARD NVARCHAR(255),
    DESIGN_DATE DATETIME,
    DESIGNER NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
