raiserror ('CREATING TABLE PIPELINE_OPERATION', 10,1) with nowait

CREATE TABLE PIPELINE_OPERATION
(
    PIPELINE_ID NVARCHAR(40),
    OPERATION_ID NVARCHAR(40),
    OPERATION_DATE DATETIME,
    FLOW_RATE NUMERIC(18,2) NOT NULL,
    FLOW_RATE_OUOM NVARCHAR(255),
    PRESSURE NUMERIC(18,2) NOT NULL,
    PRESSURE_OUOM NVARCHAR(255),
    TEMPERATURE NUMERIC(18,2) NOT NULL,
    TEMPERATURE_OUOM NVARCHAR(255),
    THROUGHPUT NUMERIC(18,2) NOT NULL,
    THROUGHPUT_OUOM NVARCHAR(255),
    STATION_ID NVARCHAR(40),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
