raiserror ('CREATING TABLE PIPELINE_INSPECTION', 10,1) with nowait

CREATE TABLE PIPELINE_INSPECTION
(
    PIPELINE_ID NVARCHAR(40),
    INSPECTION_ID NVARCHAR(40),
    INSPECTION_TYPE NVARCHAR(50),
    INSPECTION_DATE DATETIME,
    INSPECTOR NVARCHAR(255),
    TOOL_MODEL NVARCHAR(255),
    TOOL_MANUFACTURER NVARCHAR(255),
    SEGMENT_ID NVARCHAR(40),
    STATION_MILEPOST NUMERIC(18,2) NOT NULL,
    STATION_MILEPOST_OUOM NVARCHAR(255),
    INSPECTION_RESULT NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
