ALTER TABLE PIPELINE_OPERATION
ADD CONSTRAINT FK_PIPELINE_OPERATION_PIPELINE FOREIGN KEY (PIPELINE_ID) REFERENCES PIPELINE(PIPELINE_ID);

ALTER TABLE PIPELINE_OPERATION
ADD CONSTRAINT FK_PIPELINE_OPERATION_OPERATION FOREIGN KEY (OPERATION_ID) REFERENCES OPERATION(OPERATION_ID);

ALTER TABLE PIPELINE_OPERATION
ADD CONSTRAINT FK_PIPELINE_OPERATION_STATION FOREIGN KEY (STATION_ID) REFERENCES STATION(STATION_ID);
