raiserror ('CREATING TABLE PIPELINE_STATION', 10,1) with nowait

CREATE TABLE PIPELINE_STATION
(
    PIPELINE_ID NVARCHAR(40),
    STATION_ID NVARCHAR(40),
    STATION_NAME NVARCHAR(255),
    STATION_SHORT_NAME NVARCHAR(255),
    STATION_TYPE NVARCHAR(50),
    FACILITY_ID NVARCHAR(40),
    FACILITY_TYPE NVARCHAR(50),
    STATION_FUNCTION NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
