CREATE TABLE "FLASH_COMPONENT"
(
    "FLASH_COMPONENT_ID" VARCHAR2(40) NOT NULL,
    "FLASH_CALCULATION_ID" VARCHAR2(40),
    "COMPONENT_NAME" VARCHAR2(255),
    "MOLE_FRACTION" NUMBER(18,2),
    "CRITICAL_TEMPERATURE" NUMBER(18,2),
    "CRITICAL_PRESSURE" NUMBER(18,2),
    "ACENTRIC_FACTOR" NUMBER(18,2),
    "MOLECULAR_WEIGHT" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_QUALITY" VARCHAR2(40)
);
