ALTER TABLE "PROCESSING_AGREEMENT"
ADD CONSTRAINT FK_PROCESSING_AGREEMENT_AGREEMENT FOREIGN KEY ("AGREEMENT_ID") REFERENCES "AGREEMENT"("AGREEMENT_ID");

ALTER TABLE "PROCESSING_AGREEMENT"
ADD CONSTRAINT FK_PROCESSING_AGREEMENT_PROCESSOR_BA FOREIGN KEY ("PROCESSOR_BA_ID") REFERENCES "PROCESSOR_BA"("PROCESSOR_BA_ID");
