CREATE TABLE "SALES_AGREEMENT"
(
    "AGREEMENT_ID" VARCHAR2(40),
    "AGREEMENT_NAME" VARCHAR2(255),
    "SELLER_BA_ID" VARCHAR2(40),
    "PURCHASER_BA_ID" VARCHAR2(40),
    "EFFECTIVE_DATE" DATE,
    "EXPIRATION_DATE" DATE,
    "PRICING_METHOD" VARCHAR2(255),
    "BASE_PRICE" NUMBER(18,2),
    "PRICE_INDEX" VARCHAR2(255),
    "DIFFERENTIAL" NUMBER(18,2),
    "PAYMENT_TERMS_DAYS" NUMBER(10),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE
);
