ALTER TABLE "SALES_AGREEMENT"
ADD CONSTRAINT FK_SALES_AGREEMENT_AGREEMENT FOREIGN KEY ("AGREEMENT_ID") REFERENCES "AGREEMENT"("AGREEMENT_ID");

ALTER TABLE "SALES_AGREEMENT"
ADD CONSTRAINT FK_SALES_AGREEMENT_SELLER_BA FOREIGN KEY ("SELLER_BA_ID") REFERENCES "SELLER_BA"("SELLER_BA_ID");

ALTER TABLE "SALES_AGREEMENT"
ADD CONSTRAINT FK_SALES_AGREEMENT_PURCHASER_BA FOREIGN KEY ("PURCHASER_BA_ID") REFERENCES "PURCHASER_BA"("PURCHASER_BA_ID");
