CREATE TABLE "STORAGE_AGREEMENT"
(
    "AGREEMENT_ID" VARCHAR2(40),
    "STORAGE_FACILITY_ID" VARCHAR2(40),
    "EFFECTIVE_DATE" DATE,
    "EXPIRATION_DATE" DATE,
    "STORAGE_FEE" NUMBER(18,2),
    "RESERVED_CAPACITY" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_QUALITY" VARCHAR2(40),
    "AREA_ID" VARCHAR2(40),
    "AREA_TYPE" VARCHAR2(50),
    "BUSINESS_ASSOCIATE_ID" VARCHAR2(40),
    "EXPIRY_DATE" DATE
);
