CREATE TABLE "TRANSPORTATION_AGREEMENT"
(
    "AGREEMENT_ID" VARCHAR2(40),
    "CARRIER_BA_ID" VARCHAR2(40),
    "ORIGIN_POINT" VARCHAR2(255),
    "DESTINATION_POINT" VARCHAR2(255),
    "EFFECTIVE_DATE" DATE,
    "EXPIRATION_DATE" DATE,
    "TARIFF_RATE" NUMBER(18,2),
    "MINIMUM_VOLUME_COMMITMENT" NUMBER(18,2),
    "MAXIMUM_CAPACITY" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE
);
