ALTER TABLE `GAS_COMPOSITION_COMPONENT`
ADD CONSTRAINT FK_GAS_COMPOSITION_COMPONENT_GAS_COMPONENT FOREIGN KEY (`GAS_COMPONENT_ID`) REFERENCES `GAS_COMPONENT`(`GAS_COMPONENT_ID`);

ALTER TABLE `GAS_COMPOSITION_COMPONENT`
ADD CONSTRAINT FK_GAS_COMPOSITION_COMPONENT_GAS_COMPOSITION FOREIGN KEY (`GAS_COMPOSITION_ID`) REFERENCES `GAS_COMPOSITION`(`GAS_COMPOSITION_ID`);
