CREATE TABLE `PROVED_PROPERTY`
(
    `PROPERTY_ID` VARCHAR(40),
    `ACQUISITION_COST` DECIMAL(18,2),
    `EXPLORATION_COSTS` DECIMAL(18,6),
    `DEVELOPMENT_COSTS` DECIMAL(18,2),
    `ACCUMULATED_AMORTIZATION` DECIMAL(18,2),
    `PROVED_DATE` DATETIME,
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40),
    `PROVED_RESERVES_GAS` DECIMAL(18,2) NOT NULL,
    `PROVED_RESERVES_OIL` DECIMAL(18,2) NOT NULL,
    `PROVED_RESERVES_BOE` VARCHAR(255) NOT NULL
);
