CREATE TABLE `RESERVOIR_STATUS`
(
    `RESERVOIR_STATUS_ID` VARCHAR(40) NOT NULL,
    `RESERVE_ENTITY_ID` VARCHAR(40),
    `POOL_ID` VARCHAR(40),
    `STATUS` VARCHAR(50),
    `STATUS_DATE` DATETIME,
    `STATUS_CHANGED_BY` VARCHAR(50),
    `NOTES` VARCHAR(2000),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_QUALITY` VARCHAR(40)
);
