ALTER TABLE `UNPROVED_PROPERTY`
ADD CONSTRAINT FK_UNPROVED_PROPERTY_PROPERTY FOREIGN KEY (`PROPERTY_ID`) REFERENCES `PROPERTY`(`PROPERTY_ID`);

ALTER TABLE `UNPROVED_PROPERTY`
ADD CONSTRAINT FK_UNPROVED_PROPERTY_COST_CENTER FOREIGN KEY (`COST_CENTER_ID`) REFERENCES `COST_CENTER`(`COST_CENTER_ID`);
