CREATE TABLE LACT_UNIT
(
    LACT_UNIT_ID TEXT NOT NULL,
    LACT_NAME TEXT,
    SERVICE_UNIT_ID TEXT,
    METER_TYPE TEXT,
    MAXIMUM_FLOW_RATE REAL,
    METER_FACTOR REAL,
    LAST_CALIBRATION_DATE DATETIME,
    NEXT_CALIBRATION_DATE DATETIME,
    IS_ACTIVE TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
