CREATE TABLE SERVICE_UNIT
(
    SERVICE_UNIT_ID TEXT NOT NULL,
    UNIT_NAME TEXT,
    UNIT_TYPE TEXT,
    LEASE_ID TEXT,
    TANK_BATTERY_ID TEXT,
    OPERATOR_BA_ID TEXT,
    EFFECTIVE_DATE DATETIME,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
