CREATE TABLE STORAGE_FACILITY
(
    STORAGE_FACILITY_ID TEXT NOT NULL,
    FACILITY_NAME TEXT,
    FACILITY_TYPE TEXT,
    LOCATION TEXT,
    CAPACITY REAL,
    CURRENT_INVENTORY REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
