CREATE TABLE TANK_BATTERY
(
    TANK_BATTERY_ID TEXT NOT NULL,
    BATTERY_NAME TEXT,
    STORAGE_FACILITY_ID TEXT,
    LEASE_ID TEXT,
    CURRENT_INVENTORY REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
