ALTER TABLE PRESSURE_TIME_POINT
ADD CONSTRAINT FK_PRESSURE_TIME_POINT_WELL_TEST_DATA FOREIGN KEY (WELL_TEST_DATA_ID) REFERENCES WELL_TEST_DATA(WELL_TEST_DATA_ID);

ALTER TABLE PRESSURE_TIME_POINT
ADD CONSTRAINT FK_PRESSURE_TIME_POINT_AREA FOREIGN KEY (AREA_ID) REFERENCES AREA(AREA_ID);

ALTER TABLE PRESSURE_TIME_POINT
ADD CONSTRAINT FK_PRESSURE_TIME_POINT_BUSINESS_ASSOCIATE FOREIGN KEY (BUSINESS_ASSOCIATE_ID) REFERENCES BUSINESS_ASSOCIATE(BUSINESS_ASSOCIATE_ID);
