raiserror ('CREATING TABLE PRESSURE_TIME_POINT', 10,1) with nowait

CREATE TABLE PRESSURE_TIME_POINT
(
    PRESSURE_TIME_POINT_ID NVARCHAR(40) NOT NULL,
    WELL_TEST_DATA_ID NVARCHAR(40),
    TIME NUMERIC(18,2),
    PRESSURE NUMERIC(18,2),
    PRESSURE_DERIVATIVE NUMERIC(18,2),
    POINT_ORDER INT,
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME
);
