CREATE TABLE `RECEIVABLE`
(
    `RECEIVABLE_ID` VARCHAR(40) NOT NULL,
    `SALES_TRANSACTION_ID` VARCHAR(40),
    `CUSTOMER_BA_ID` VARCHAR(40),
    `INVOICE_NUMBER` VARCHAR(255),
    `INVOICE_DATE` DATETIME,
    `DUE_DATE` DATETIME,
    `ORIGINAL_AMOUNT` DECIMAL(18,2),
    `AMOUNT_PAID` DECIMAL(18,2),
    `OUTSTANDING_BALANCE` DECIMAL(18,2),
    `STATUS` VARCHAR(50),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_QUALITY` VARCHAR(40)
);
