CREATE TABLE "CHART_CONFIGURATION"
(
    "CHART_CONFIGURATION_ID" VARCHAR2(40) NOT NULL,
    "CHART_TYPE" VARCHAR2(50),
    "CONFIGURATION_NAME" VARCHAR2(255),
    "CONFIGURATION_DATA" VARCHAR2(255),
    "CREATED_BY" VARCHAR2(30),
    "IS_DEFAULT" VARCHAR2(255),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE
);
