raiserror ('CREATING TABLE LACT_UNIT', 10,1) with nowait

CREATE TABLE LACT_UNIT
(
    LACT_UNIT_ID NVARCHAR(40) NOT NULL,
    LACT_NAME NVARCHAR(255),
    SERVICE_UNIT_ID NVARCHAR(40),
    METER_TYPE NVARCHAR(50),
    MAXIMUM_FLOW_RATE NUMERIC(18,2),
    METER_FACTOR NUMERIC(18,2),
    LAST_CALIBRATION_DATE DATETIME,
    NEXT_CALIBRATION_DATE DATETIME,
    IS_ACTIVE NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
