ALTER TABLE SERVICE_UNIT
ADD CONSTRAINT FK_SERVICE_UNIT_LEASE FOREIGN KEY (LEASE_ID) REFERENCES LEASE(LEASE_ID);

ALTER TABLE SERVICE_UNIT
ADD CONSTRAINT FK_SERVICE_UNIT_TANK_BATTERY FOREIGN KEY (TANK_BATTERY_ID) REFERENCES TANK_BATTERY(TANK_BATTERY_ID);

ALTER TABLE SERVICE_UNIT
ADD CONSTRAINT FK_SERVICE_UNIT_OPERATOR_BA FOREIGN KEY (OPERATOR_BA_ID) REFERENCES OPERATOR_BA(OPERATOR_BA_ID);
