raiserror ('CREATING TABLE SERVICE_UNIT', 10,1) with nowait

CREATE TABLE SERVICE_UNIT
(
    SERVICE_UNIT_ID NVARCHAR(40) NOT NULL,
    UNIT_NAME NVARCHAR(255),
    UNIT_TYPE NVARCHAR(50),
    LEASE_ID NVARCHAR(40),
    TANK_BATTERY_ID NVARCHAR(40),
    OPERATOR_BA_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
