raiserror ('CREATING TABLE STORAGE_FACILITY', 10,1) with nowait

CREATE TABLE STORAGE_FACILITY
(
    STORAGE_FACILITY_ID NVARCHAR(40) NOT NULL,
    FACILITY_NAME NVARCHAR(255),
    FACILITY_TYPE NVARCHAR(50),
    LOCATION NVARCHAR(255),
    CAPACITY NUMERIC(18,2),
    CURRENT_INVENTORY NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
