raiserror ('CREATING TABLE TANK_BATTERY', 10,1) with nowait

CREATE TABLE TANK_BATTERY
(
    TANK_BATTERY_ID NVARCHAR(40) NOT NULL,
    BATTERY_NAME NVARCHAR(255),
    STORAGE_FACILITY_ID NVARCHAR(40),
    LEASE_ID NVARCHAR(40),
    CURRENT_INVENTORY NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
