raiserror ('CREATING TABLE GAS_LIFT_PERFORMANCE', 10,1) with nowait

CREATE TABLE GAS_LIFT_PERFORMANCE
(
    PERFORMANCE_ID NVARCHAR(40),
    WELL_UWI NVARCHAR(255),
    PERFORMANCE_DATE DATETIME,
    GAS_INJECTION_RATE NVARCHAR(255),
    PRODUCTION_RATE NVARCHAR(255),
    GAS_LIQUID_RATIO NVARCHAR(255),
    EFFICIENCY NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30)
);
