raiserror ('CREATING TABLE GAS_LIFT_VALVE', 10,1) with nowait

CREATE TABLE GAS_LIFT_VALVE
(
    GAS_LIFT_VALVE_ID NVARCHAR(40) NOT NULL,
    GAS_LIFT_DESIGN_ID NVARCHAR(40),
    DEPTH NUMERIC(18,2),
    PORT_SIZE NUMERIC(18,2),
    OPENING_PRESSURE NUMERIC(18,2),
    CLOSING_PRESSURE NUMERIC(18,2),
    VALVE_TYPE NVARCHAR(50),
    TEMPERATURE NUMERIC(18,2),
    GAS_INJECTION_RATE NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
