raiserror ('CREATING TABLE GAS_LIFT_DESIGN', 10,1) with nowait

CREATE TABLE GAS_LIFT_DESIGN
(
    DESIGN_ID NVARCHAR(40),
    WELL_UWI NVARCHAR(255),
    DESIGN_DATE DATETIME,
    NUMBER_OF_VALVES NVARCHAR(255),
    TOTAL_GAS_INJECTION_RATE NVARCHAR(255),
    EXPECTED_PRODUCTION_RATE NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30)
);
