CREATE TABLE `STORAGE_FACILITY`
(
    `STORAGE_FACILITY_ID` VARCHAR(40) NOT NULL,
    `FACILITY_NAME` VARCHAR(255),
    `FACILITY_TYPE` VARCHAR(50),
    `LOCATION` VARCHAR(255),
    `CAPACITY` DECIMAL(18,2),
    `CURRENT_INVENTORY` DECIMAL(18,2),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME
);
