ALTER TABLE `TANK_BATTERY`
ADD CONSTRAINT FK_TANK_BATTERY_STORAGE_FACILITY FOREIGN KEY (`STORAGE_FACILITY_ID`) REFERENCES `STORAGE_FACILITY`(`STORAGE_FACILITY_ID`);

ALTER TABLE `TANK_BATTERY`
ADD CONSTRAINT FK_TANK_BATTERY_LEASE FOREIGN KEY (`LEASE_ID`) REFERENCES `LEASE`(`LEASE_ID`);
