raiserror ('CREATING TABLE EXCHANGE_COMMITMENT', 10,1) with nowait

CREATE TABLE EXCHANGE_COMMITMENT
(
    EXCHANGE_COMMITMENT_ID NVARCHAR(40) NOT NULL,
    EXCHANGE_CONTRACT_ID NVARCHAR(40),
    COMMITMENT_TYPE NVARCHAR(50),
    COMMITTED_VOLUME NUMERIC(18,2),
    ACTUAL_VOLUME_DELIVERED NUMERIC(18,2),
    DELIVERY_PERIOD_START DATETIME,
    DELIVERY_PERIOD_END DATETIME,
    STATUS NVARCHAR(50),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
