raiserror ('CREATING TABLE EXCHANGE_TRANSACTION', 10,1) with nowait

CREATE TABLE EXCHANGE_TRANSACTION
(
    EXCHANGE_TRANSACTION_ID NVARCHAR(40) NOT NULL,
    EXCHANGE_CONTRACT_ID NVARCHAR(40),
    TRANSACTION_DATE DATETIME,
    RECEIPT_VOLUME NUMERIC(18,2),
    RECEIPT_PRICE NUMERIC(18,2),
    RECEIPT_LOCATION NVARCHAR(255),
    DELIVERY_VOLUME NUMERIC(18,2),
    DELIVERY_PRICE NUMERIC(18,2),
    DELIVERY_LOCATION NVARCHAR(255),
    STATUS NVARCHAR(50),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
