raiserror ('CREATING TABLE EXCHANGE_CONTRACT', 10,1) with nowait

CREATE TABLE EXCHANGE_CONTRACT
(
    EXCHANGE_CONTRACT_ID NVARCHAR(40) NOT NULL,
    CONTRACT_NUMBER NVARCHAR(255),
    COUNTERPARTY_BA_ID NVARCHAR(40),
    CONTRACT_TYPE NVARCHAR(50),
    COMMODITY_TYPE NVARCHAR(50),
    CONTRACT_DATE DATETIME,
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    STATUS NVARCHAR(50),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
