CREATE TABLE "PRODUCTION_COSTS"
(
    "PRODUCTION_COST_ID" VARCHAR2(40),
    "PROPERTY_ID" VARCHAR2(40),
    "OPERATING_COSTS" NUMBER(18,2),
    "WORKOVER_COSTS" NUMBER(18,2),
    "MAINTENANCE_COSTS" NUMBER(18,2),
    "TOTAL_PRODUCTION_COSTS" NUMBER(18,2),
    "COST_PERIOD" DATE,
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
