raiserror ('CREATING TABLE DIVISION_ORDER', 10,1) with nowait

CREATE TABLE DIVISION_ORDER
(
    DIVISION_ORDER_ID NVARCHAR(40) NOT NULL,
    PROPERTY_ID NVARCHAR(40),
    OWNER_BA_ID NVARCHAR(40),
    WORKING_INTEREST NUMERIC(18,2),
    NET_REVENUE_INTEREST NUMERIC(18,2),
    ROYALTY_INTEREST NUMERIC(18,2),
    OVERRIDING_ROYALTY_INTEREST NUMERIC(18,2),
    EFFECTIVE_DATE DATETIME,
    EXPIRATION_DATE DATETIME,
    STATUS NVARCHAR(50),
    APPROVAL_DATE DATETIME,
    APPROVED_BY NVARCHAR(255),
    NOTES NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
