ALTER TABLE TRANSFER_ORDER
ADD CONSTRAINT FK_TRANSFER_ORDER_PROPERTY FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID);

ALTER TABLE TRANSFER_ORDER
ADD CONSTRAINT FK_TRANSFER_ORDER_FROM_OWNER_BA FOREIGN KEY (FROM_OWNER_BA_ID) REFERENCES FROM_OWNER_BA(FROM_OWNER_BA_ID);

ALTER TABLE TRANSFER_ORDER
ADD CONSTRAINT FK_TRANSFER_ORDER_TO_OWNER_BA FOREIGN KEY (TO_OWNER_BA_ID) REFERENCES TO_OWNER_BA(TO_OWNER_BA_ID);
