raiserror ('CREATING TABLE ROYALTY_INTEREST', 10,1) with nowait

CREATE TABLE ROYALTY_INTEREST
(
    ROYALTY_INTEREST_ID NVARCHAR(40) NOT NULL,
    PROPERTY_ID NVARCHAR(40),
    ROYALTY_OWNER_BA_ID NVARCHAR(40),
    INTEREST_TYPE NVARCHAR(50),
    INTEREST_PERCENTAGE NUMERIC(18,6),
    ROYALTY_RATE NUMERIC(18,2),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    DIVISION_ORDER_ID NVARCHAR(40),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
