raiserror ('CREATING TABLE ROYALTY_CALCULATION', 10,1) with nowait

CREATE TABLE ROYALTY_CALCULATION
(
    ROYALTY_CALCULATION_ID NVARCHAR(40) NOT NULL,
    PROPERTY_ID NVARCHAR(40),
    REVENUE_TRANSACTION_ID NVARCHAR(40),
    CALCULATION_DATE DATETIME,
    GROSS_REVENUE NUMERIC(18,2),
    PRODUCTION_TAXES NUMERIC(18,2),
    TRANSPORTATION_COSTS NUMERIC(18,2),
    PROCESSING_COSTS NUMERIC(18,2),
    MARKETING_COSTS NUMERIC(18,2),
    OTHER_DEDUCTIONS NUMERIC(18,2),
    TOTAL_DEDUCTIONS NUMERIC(18,2),
    NET_REVENUE NUMERIC(18,2),
    ROYALTY_INTEREST NUMERIC(18,2),
    ROYALTY_AMOUNT NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
