raiserror ('CREATING TABLE ROYALTY_PAYMENT', 10,1) with nowait

CREATE TABLE ROYALTY_PAYMENT
(
    ROYALTY_PAYMENT_ID NVARCHAR(40) NOT NULL,
    ROYALTY_INTEREST_ID NVARCHAR(40),
    REVENUE_TRANSACTION_ID NVARCHAR(40),
    ROYALTY_OWNER_BA_ID NVARCHAR(40),
    PROPERTY_ID NVARCHAR(40),
    PAYMENT_PERIOD_START DATETIME,
    PAYMENT_PERIOD_END DATETIME,
    ROYALTY_AMOUNT NUMERIC(18,2),
    NET_PAYMENT_AMOUNT NUMERIC(18,2),
    PAYMENT_DATE DATETIME,
    PAYMENT_METHOD NVARCHAR(255),
    CHECK_NUMBER NVARCHAR(255),
    PAYMENT_STATUS NVARCHAR(50),
    APPROVED_BY NVARCHAR(255),
    APPROVAL_DATE DATETIME,
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
