ALTER TABLE ROYALTY_STATEMENT
ADD CONSTRAINT FK_ROYALTY_STATEMENT_ROYALTY_OWNER_BA FOREIGN KEY (ROYALTY_OWNER_BA_ID) REFERENCES ROYALTY_OWNER_BA(ROYALTY_OWNER_BA_ID);

ALTER TABLE ROYALTY_STATEMENT
ADD CONSTRAINT FK_ROYALTY_STATEMENT_PROPERTY FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID);
