raiserror ('CREATING TABLE ROYALTY_STATEMENT', 10,1) with nowait

CREATE TABLE ROYALTY_STATEMENT
(
    ROYALTY_STATEMENT_ID NVARCHAR(40) NOT NULL,
    ROYALTY_OWNER_BA_ID NVARCHAR(40),
    PROPERTY_ID NVARCHAR(40),
    STATEMENT_PERIOD_START DATETIME,
    STATEMENT_PERIOD_END DATETIME,
    TOTAL_ROYALTY_AMOUNT NUMERIC(18,2),
    TOTAL_DEDUCTIONS NUMERIC(18,2),
    NET_PAYMENT_AMOUNT NUMERIC(18,2),
    STATEMENT_DATE DATETIME,
    STATUS NVARCHAR(50),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
