-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: ACCESS_CONTROL_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE USER_ASSET_ACCESS
CREATE TABLE user_asset_access
(
	USER_ID TEXT(40) NOT NULL,
	ASSET_TYPE TEXT(40) NOT NULL,
	ASSET_ID TEXT(40) NOT NULL,
	ACCESS_LEVEL TEXT(40),
	INHERIT_IND TEXT(1),
	ORGANIZATION_ID TEXT(40),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);

-- CREATING TABLE ROLE_PERMISSION
CREATE TABLE role_permission
(
	ROLE_ID TEXT(40) NOT NULL,
	PERMISSION_ID TEXT(40) NOT NULL,
	ORGANIZATION_ID TEXT(40),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);

-- CREATING TABLE ORGANIZATION_HIERARCHY_CONFIG
CREATE TABLE organization_hierarchy_config
(
	ORGANIZATION_ID TEXT(40) NOT NULL,
	HIERARCHY_LEVEL NUMERIC(8,0) NOT NULL,
	LEVEL_NAME TEXT(255),
	ASSET_TYPE TEXT(40),
	PARENT_LEVEL NUMERIC(8,0),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);

-- CREATING TABLE USER_PROFILE
CREATE TABLE user_profile
(
	USER_ID TEXT(40) NOT NULL,
	PRIMARY_ROLE TEXT(40),
	PREFERRED_LAYOUT TEXT(40),
	USER_PREFERENCES TEXT(MAX),
	LAST_LOGIN_DATE TEXT,
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);

-- CREATING TABLE SETUP_WIZARD_LOG
CREATE TABLE setup_wizard_log
(
	SETUP_LOG_ID TEXT(40) NOT NULL,
	ORGANIZATION_ID TEXT(40),
	SETUP_STEP TEXT(255),
	SETUP_DATA TEXT(MAX),
	EXECUTED_BY TEXT(40),
	EXECUTION_DATE TEXT,
	STATUS TEXT(40),
	ERROR_MESSAGE TEXT(MAX),
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);
