-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: ACCESS_CONTROL_IX.sql
-- This script is for the PPDM39 model

-- CREATING INDEX UAA_USER_ID_IX
CREATE INDEX UAA_USER_ID_IX ON USER_ASSET_ACCESS
(
	USER_ID
);

-- CREATING INDEX UAA_ORG_IX
CREATE INDEX UAA_ORG_IX ON USER_ASSET_ACCESS
(
	ORGANIZATION_ID
);

-- CREATING INDEX UAA_ASSET_IX
CREATE INDEX UAA_ASSET_IX ON USER_ASSET_ACCESS
(
	ASSET_TYPE,
	ASSET_ID
);

-- CREATING INDEX RP_ROLE_IX
CREATE INDEX RP_ROLE_IX ON ROLE_PERMISSION
(
	ROLE_ID
);

-- CREATING INDEX RP_ORG_IX
CREATE INDEX RP_ORG_IX ON ROLE_PERMISSION
(
	ORGANIZATION_ID
);

-- CREATING INDEX OHC_ORG_IX
CREATE INDEX OHC_ORG_IX ON ORGANIZATION_HIERARCHY_CONFIG
(
	ORGANIZATION_ID
);

-- CREATING INDEX OHC_LEVEL_IX
CREATE INDEX OHC_LEVEL_IX ON ORGANIZATION_HIERARCHY_CONFIG
(
	ORGANIZATION_ID,
	HIERARCHY_LEVEL
);

-- CREATING INDEX SWL_ORG_IX
CREATE INDEX SWL_ORG_IX ON SETUP_WIZARD_LOG
(
	ORGANIZATION_ID
);

-- CREATING INDEX SWL_DATE_IX
CREATE INDEX SWL_DATE_IX ON SETUP_WIZARD_LOG
(
	EXECUTION_DATE
);
