-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: EXPLORATION_PERMIT_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT EXPLORATION_PERMIT_FIELD_FK
ALTER TABLE EXPLORATION_PERMIT ADD CONSTRAINT EXPLORATION_PERMIT_FIELD_FK FOREIGN KEY
(
	FIELD_ID
)
REFERENCES FIELD
(
	FIELD_ID
);

-- CREATING FOREIGN KEY CONSTRAINT EXPLORATION_PERMIT_HOLDER_FK
ALTER TABLE EXPLORATION_PERMIT ADD CONSTRAINT EXPLORATION_PERMIT_HOLDER_FK FOREIGN KEY
(
	PERMIT_HOLDER
)
REFERENCES BUSINESS_ASSOCIATE
(
	BUSINESS_ASSOCIATE_ID
);
