-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: EXPLORATION_PROGRAM_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE EXPLORATION_PROGRAM
CREATE TABLE exploration_program
(
	PROGRAM_ID TEXT(40) NOT NULL,
	PROGRAM_NAME TEXT(255),
	FIELD_ID TEXT(40),
	OPERATOR TEXT(40),
	OBJECTIVES TEXT(2000),
	PROGRAM_START_DATE TEXT,
	PROGRAM_END_DATE TEXT,
	BUDGET NUMERIC(18,5),
	BUDGET_CURRENCY TEXT(40),
	DESCRIPTION TEXT(240),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);
