-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: EXPLORATION_PERMIT_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE EXPLORATION_PERMIT
CREATE TABLE exploration_permit
(
	PERMIT_ID TEXT(40) NOT NULL,
	PERMIT_NUMBER TEXT(40),
	FIELD_ID TEXT(40),
	PERMIT_HOLDER TEXT(40),
	PERMIT_START_DATE TEXT,
	PERMIT_END_DATE TEXT,
	PERMIT_AREA NUMERIC(18,5),
	PERMIT_AREA_OUOM TEXT(40),
	PERMIT_TERMS TEXT(2000),
	DESCRIPTION TEXT(240),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);
