-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: EXPLORATION_BUDGET_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE EXPLORATION_BUDGET
CREATE TABLE exploration_budget
(
	PROGRAM_ID TEXT(40) NOT NULL,
	BUDGET_YEAR NUMERIC(4,0) NOT NULL,
	BUDGET_AMOUNT NUMERIC(18,5),
	BUDGET_CURRENCY TEXT(40),
	BUDGET_CATEGORY TEXT(40),
	ACTUAL_AMOUNT NUMERIC(18,5),
	VARIANCE NUMERIC(18,5),
	DESCRIPTION TEXT(240),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);
