-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: EXPLORATION_PROGRAM_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT EXPLORATION_PROGRAM_FIELD_FK
ALTER TABLE EXPLORATION_PROGRAM ADD CONSTRAINT EXPLORATION_PROGRAM_FIELD_FK FOREIGN KEY
(
	FIELD_ID
)
REFERENCES FIELD
(
	FIELD_ID
);

-- CREATING FOREIGN KEY CONSTRAINT EXPLORATION_PROGRAM_OPERATOR_FK
ALTER TABLE EXPLORATION_PROGRAM ADD CONSTRAINT EXPLORATION_PROGRAM_OPERATOR_FK FOREIGN KEY
(
	OPERATOR
)
REFERENCES BUSINESS_ASSOCIATE
(
	BUSINESS_ASSOCIATE_ID
);
