CREATE TABLE GL_ACCOUNT
(
    GL_ACCOUNT_ID TEXT(40) NOT NULL,
    ACCOUNT_NUMBER TEXT(40),
    ACCOUNT_NAME TEXT(255),
    ACCOUNT_TYPE TEXT(40),
    PARENT_ACCOUNT_ID TEXT(40),
    NORMAL_BALANCE TEXT(10),
    OPENING_BALANCE NUMERIC(18,2),
    CURRENT_BALANCE NUMERIC(18,2),
    DESCRIPTION TEXT(4000),
    ACTIVE_IND TEXT(1),
    PPDM_GUID TEXT(40),
    REMARK TEXT(4000),
    SOURCE TEXT(40),
    ROW_QUALITY TEXT(40),
    ROW_CREATED_BY TEXT(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT(40),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT(40)
);

