-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: LEAD_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT LEAD_FIELD_FK
ALTER TABLE LEAD ADD CONSTRAINT LEAD_FIELD_FK FOREIGN KEY
(
	FIELD_ID
)
REFERENCES FIELD
(
	FIELD_ID
);

-- CREATING FOREIGN KEY CONSTRAINT LEAD_PLAY_FK
ALTER TABLE LEAD ADD CONSTRAINT LEAD_PLAY_FK FOREIGN KEY
(
	PLAY_ID
)
REFERENCES PLAY
(
	PLAY_ID
);

-- CREATING FOREIGN KEY CONSTRAINT LEAD_STATUS_FK
ALTER TABLE LEAD ADD CONSTRAINT LEAD_STATUS_FK FOREIGN KEY
(
	LEAD_STATUS
)
REFERENCES R_LEAD_STATUS
(
	LEAD_STATUS
);

-- CREATING FOREIGN KEY CONSTRAINT LEAD_PROSPECT_FK
ALTER TABLE LEAD ADD CONSTRAINT LEAD_PROSPECT_FK FOREIGN KEY
(
	PROMOTED_TO_PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);

