-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: LEAD_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE LEAD
CREATE TABLE lead
(
	LEAD_ID TEXT(40) NOT NULL,
	LEAD_NAME TEXT(255),
	LEAD_SHORT_NAME TEXT(30),
	FIELD_ID TEXT(40),
	PLAY_ID TEXT(40),
	LEAD_STATUS TEXT(40),
	DESCRIPTION TEXT(240),
	LEAD_SOURCE TEXT(40),
	INITIAL_ASSESSMENT_DATE TEXT,
	PROMOTED_TO_PROSPECT_DATE TEXT,
	REJECTED_DATE TEXT,
	REJECTION_REASON TEXT(2000),
	LATITUDE NUMERIC(14,9),
	LONGITUDE NUMERIC(14,9),
	ELEVATION NUMERIC(10,5),
	ELEVATION_OUOM TEXT(40),
	LOCATION_DESCRIPTION TEXT(240),
	INITIAL_RISK_ASSESSMENT TEXT(40),
	INITIAL_VOLUME_ESTIMATE_OIL NUMERIC(18,5),
	INITIAL_VOLUME_ESTIMATE_GAS NUMERIC(18,5),
	INITIAL_VOLUME_ESTIMATE_OUOM TEXT(40),
	PROMOTED_TO_PROSPECT_ID TEXT(40),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);

