-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_DESIGN_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PIPELINE_DESIGN_PK
ALTER TABLE PIPELINE_DESIGN ADD CONSTRAINT PIPELINE_DESIGN_PK PRIMARY KEY
(
	PIPELINE_ID,
	DESIGN_VERSION_NO
);

