-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_MAINTENANCE_SCHEDULE_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PIPELINE_MAINTENANCE_SCHEDULE_PK
ALTER TABLE PIPELINE_MAINTENANCE_SCHEDULE ADD CONSTRAINT PIPELINE_MAINTENANCE_SCHEDULE_PK PRIMARY KEY
(
	PIPELINE_ID,
	SCHEDULE_ID
);

