-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_MAINTENANCE_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_MAINTENANCE
CREATE TABLE pipeline_maintenance
(
	PIPELINE_ID TEXT(40) NOT NULL,
	MAINTENANCE_ID TEXT(40) NOT NULL,
	MAINTENANCE_TYPE TEXT(40),
	SCHEDULE_DATE TEXT,
	COMPLETION_DATE TEXT,
	CREW TEXT(40),
	MAINTENANCE_COST NUMERIC(15,2),
	MAINTENANCE_COST_OUOM TEXT(40),
	SEGMENT_ID TEXT(40),
	DESCRIPTION TEXT(240),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);

