-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_INSPECTION_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_INSPECTION
CREATE TABLE pipeline_inspection
(
	PIPELINE_ID TEXT(40) NOT NULL,
	INSPECTION_ID TEXT(40) NOT NULL,
	INSPECTION_TYPE TEXT(40),
	INSPECTION_DATE TEXT,
	INSPECTOR TEXT(40),
	TOOL_MODEL TEXT(255),
	TOOL_MANUFACTURER TEXT(40),
	SEGMENT_ID TEXT(40),
	STATION_MILEPOST NUMERIC(10,2),
	STATION_MILEPOST_OUOM TEXT(40),
	INSPECTION_RESULT TEXT(40),
	DESCRIPTION TEXT(240),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);

