-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_SEGMENT_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PIPELINE_SEGMENT_PK
ALTER TABLE PIPELINE_SEGMENT ADD CONSTRAINT PIPELINE_SEGMENT_PK PRIMARY KEY
(
	PIPELINE_ID,
	SEGMENT_ID
);
