-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_OPERATION_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_OPERATION_PIPELINE_FK
ALTER TABLE PIPELINE_OPERATION ADD CONSTRAINT PIPELINE_OPERATION_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_OPERATION_STATION_FK
ALTER TABLE PIPELINE_OPERATION ADD CONSTRAINT PIPELINE_OPERATION_STATION_FK FOREIGN KEY 
(
	PIPELINE_ID,
	STATION_ID
)
REFERENCES PIPELINE_STATION
(
	PIPELINE_ID,
	STATION_ID
);

