-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_INSPECTION_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_INSPECTION_PIPELINE_FK
ALTER TABLE PIPELINE_INSPECTION ADD CONSTRAINT PIPELINE_INSPECTION_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_INSPECTION_SEGMENT_FK
ALTER TABLE PIPELINE_INSPECTION ADD CONSTRAINT PIPELINE_INSPECTION_SEGMENT_FK FOREIGN KEY 
(
	PIPELINE_ID,
	SEGMENT_ID
)
REFERENCES PIPELINE_SEGMENT
(
	PIPELINE_ID,
	SEGMENT_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_INSPECTION_TYPE_FK
ALTER TABLE PIPELINE_INSPECTION ADD CONSTRAINT PIPELINE_INSPECTION_TYPE_FK FOREIGN KEY 
(
	INSPECTION_TYPE
)
REFERENCES R_INSPECTION_TYPE
(
	INSPECTION_TYPE
);

