-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_SEGMENT_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_SEGMENT
CREATE TABLE pipeline_segment
(
	PIPELINE_ID TEXT(40) NOT NULL,
	SEGMENT_ID TEXT(40) NOT NULL,
	SEGMENT_NAME TEXT(255),
	SEGMENT_SHORT_NAME TEXT(30),
	START_STATION_ID TEXT(40),
	START_STATION_TYPE TEXT(40),
	END_STATION_ID TEXT(40),
	END_STATION_TYPE TEXT(40),
	SEGMENT_LENGTH NUMERIC(15,5),
	SEGMENT_LENGTH_OUOM TEXT(40),
	SEGMENT_DIAMETER NUMERIC(10,5),
	SEGMENT_DIAMETER_OUOM TEXT(40),
	WALL_THICKNESS NUMERIC(10,5),
	WALL_THICKNESS_OUOM TEXT(40),
	MATERIAL_TYPE TEXT(40),
	MATERIAL_GRADE TEXT(40),
	DESCRIPTION TEXT(240),
	INSTALLATION_DATE TEXT,
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);
