-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_RISK_ASSESSMENT_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_RISK_ASSESSMENT_PIPELINE_FK
ALTER TABLE PIPELINE_RISK_ASSESSMENT ADD CONSTRAINT PIPELINE_RISK_ASSESSMENT_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_RISK_ASSESSMENT_SEGMENT_FK
ALTER TABLE PIPELINE_RISK_ASSESSMENT ADD CONSTRAINT PIPELINE_RISK_ASSESSMENT_SEGMENT_FK FOREIGN KEY 
(
	PIPELINE_ID,
	SEGMENT_ID
)
REFERENCES PIPELINE_SEGMENT
(
	PIPELINE_ID,
	SEGMENT_ID
);

