-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_FIELD_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PIPELINE_FIELD_PK
ALTER TABLE PIPELINE_FIELD ADD CONSTRAINT PIPELINE_FIELD_PK PRIMARY KEY
(
	PIPELINE_ID,
	FIELD_ID
);
