-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_ROUTE_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_ROUTE
CREATE TABLE pipeline_route
(
	PIPELINE_ID TEXT(40) NOT NULL,
	ROUTE_SEQ_NO NUMERIC(8,0) NOT NULL,
	LATITUDE NUMERIC(14,9),
	LONGITUDE NUMERIC(14,9),
	ELEVATION NUMERIC(10,5),
	ELEVATION_OUOM TEXT(40),
	STATION_MILEPOST NUMERIC(15,5),
	STATION_MILEPOST_OUOM TEXT(40),
	LINEAR_REFERENCE NUMERIC(15,5),
	COORD_SYSTEM_ID TEXT(40),
	LOCAL_COORD_SYSTEM_ID TEXT(40),
	COORD_ACQUISITION_ID TEXT(40),
	DESCRIPTION TEXT(240),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);
