-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_MATERIAL_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_MATERIAL
CREATE TABLE pipeline_material
(
	PIPELINE_ID TEXT(40) NOT NULL,
	MATERIAL_SEQ_NO TEXT(40) NOT NULL,
	MATERIAL_TYPE TEXT(40),
	MATERIAL_GRADE TEXT(40),
	MATERIAL_SPECIFICATION TEXT(255),
	MATERIAL_STANDARD TEXT(40),
	MANUFACTURER TEXT(40),
	HEAT_NUMBER TEXT(40),
	BATCH_NUMBER TEXT(40),
	DESCRIPTION TEXT(240),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);

