-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_FACILITY_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_FACILITY
CREATE TABLE pipeline_facility
(
	PIPELINE_ID TEXT(40) NOT NULL,
	FACILITY_ID TEXT(40) NOT NULL,
	FACILITY_TYPE TEXT(40) NOT NULL,
	CONNECTION_SEQ_NO NUMERIC(8,0) NOT NULL,
	CONNECTION_TYPE TEXT(40),
	CONNECTION_DATE TEXT,
	STATION_FUNCTION TEXT(40),
	DESCRIPTION TEXT(240),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);
