-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_WELL_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_WELL_PIPELINE_FK
ALTER TABLE PIPELINE_WELL ADD CONSTRAINT PIPELINE_WELL_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_WELL_WELL_FK
ALTER TABLE PIPELINE_WELL ADD CONSTRAINT PIPELINE_WELL_WELL_FK FOREIGN KEY 
(
	UWI
)
REFERENCES WELL
(
	UWI
);
