-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_OPERATION_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_OPERATION
CREATE TABLE pipeline_operation
(
	PIPELINE_ID TEXT(40) NOT NULL,
	OPERATION_ID TEXT(40) NOT NULL,
	OPERATION_DATE TEXT,
	FLOW_RATE NUMERIC(10,2),
	FLOW_RATE_OUOM TEXT(40),
	PRESSURE NUMERIC(10,2),
	PRESSURE_OUOM TEXT(40),
	TEMPERATURE NUMERIC(10,2),
	TEMPERATURE_OUOM TEXT(40),
	THROUGHPUT NUMERIC(10,2),
	THROUGHPUT_OUOM TEXT(40),
	STATION_ID TEXT(40),
	DESCRIPTION TEXT(240),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);

