-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_ROUTE_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PIPELINE_ROUTE_PK
ALTER TABLE PIPELINE_ROUTE ADD CONSTRAINT PIPELINE_ROUTE_PK PRIMARY KEY
(
	PIPELINE_ID,
	ROUTE_SEQ_NO
);
