-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_STATION_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_STATION
CREATE TABLE pipeline_station
(
	PIPELINE_ID TEXT(40) NOT NULL,
	STATION_ID TEXT(40) NOT NULL,
	STATION_NAME TEXT(255),
	STATION_SHORT_NAME TEXT(30),
	STATION_TYPE TEXT(40),
	FACILITY_ID TEXT(40),
	FACILITY_TYPE TEXT(40),
	STATION_FUNCTION TEXT(40),
	DESCRIPTION TEXT(240),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);
