-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PIPELINE_PK
ALTER TABLE PIPELINE ADD CONSTRAINT PIPELINE_PK PRIMARY KEY
(
	PIPELINE_ID
);
