-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_ANOMALY_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_ANOMALY
CREATE TABLE pipeline_anomaly
(
	PIPELINE_ID TEXT(40) NOT NULL,
	ANOMALY_ID TEXT(40) NOT NULL,
	ANOMALY_TYPE TEXT(40),
	INSPECTION_ID TEXT(40),
	LOCATION_STATION_MILEPOST NUMERIC(10,2),
	LOCATION_STATION_MILEPOST_OUOM TEXT(40),
	SEVERITY TEXT(40),
	ANOMALY_LENGTH NUMERIC(10,2),
	ANOMALY_LENGTH_OUOM TEXT(40),
	ANOMALY_DEPTH NUMERIC(10,2),
	ANOMALY_DEPTH_OUOM TEXT(40),
	ANOMALY_WIDTH NUMERIC(10,2),
	ANOMALY_WIDTH_OUOM TEXT(40),
	SEGMENT_ID TEXT(40),
	DESCRIPTION TEXT(240),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);

