-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_COMPONENT_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PIPELINE_COMPONENT_PK
ALTER TABLE PIPELINE_COMPONENT ADD CONSTRAINT PIPELINE_COMPONENT_PK PRIMARY KEY
(
	PIPELINE_ID,
	COMPONENT_ID
);

