-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_FACILITY_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PIPELINE_FACILITY_PK
ALTER TABLE PIPELINE_FACILITY ADD CONSTRAINT PIPELINE_FACILITY_PK PRIMARY KEY
(
	PIPELINE_ID,
	FACILITY_ID,
	FACILITY_TYPE,
	CONNECTION_SEQ_NO
);
