-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_DESIGN_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_DESIGN
CREATE TABLE pipeline_design
(
	PIPELINE_ID TEXT(40) NOT NULL,
	DESIGN_VERSION_NO TEXT(40) NOT NULL,
	DESIGN_PRESSURE NUMERIC(10,5),
	DESIGN_PRESSURE_OUOM TEXT(40),
	DESIGN_TEMPERATURE NUMERIC(10,5),
	DESIGN_TEMPERATURE_OUOM TEXT(40),
	MATERIAL_GRADE TEXT(40),
	COATING_TYPE TEXT(40),
	CATHODIC_PROTECTION_TYPE TEXT(40),
	CP_SYSTEM_TYPE TEXT(40),
	DESIGN_SPECIFICATION TEXT(255),
	DESIGN_STANDARD TEXT(40),
	DESIGN_DATE TEXT,
	DESIGNER TEXT(40),
	DESCRIPTION TEXT(240),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);

