-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_CONSTRUCTION_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_CONSTRUCTION_PIPELINE_FK
ALTER TABLE PIPELINE_CONSTRUCTION ADD CONSTRAINT PIPELINE_CONSTRUCTION_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_CONSTRUCTION_CONTRACTOR_FK
ALTER TABLE PIPELINE_CONSTRUCTION ADD CONSTRAINT PIPELINE_CONSTRUCTION_CONTRACTOR_FK FOREIGN KEY 
(
	CONTRACTOR
)
REFERENCES BUSINESS_ASSOCIATE
(
	BUSINESS_ASSOCIATE_ID
);

