-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE
CREATE TABLE pipeline
(
	PIPELINE_ID TEXT(40) NOT NULL,
	PIPELINE_NAME TEXT(255),
	PIPELINE_SHORT_NAME TEXT(30),
	PIPELINE_TYPE TEXT(40),
	PIPELINE_STATUS TEXT(40),
	REGULATORY_ID TEXT(40),
	PRIMARY_FIELD_ID TEXT(40),
	CURRENT_OPERATOR TEXT(40),
	DESCRIPTION TEXT(240),
	INSTALLATION_DATE TEXT,
	COMMISSIONING_DATE TEXT,
	DECOMMISSIONING_DATE TEXT,
	ABANDONED_DATE TEXT,
	ACTIVE_DATE TEXT,
	INACTIVE_DATE TEXT,
	DESIGN_PRESSURE NUMERIC(10,5),
	DESIGN_PRESSURE_OUOM TEXT(40),
	DESIGN_TEMPERATURE NUMERIC(10,5),
	DESIGN_TEMPERATURE_OUOM TEXT(40),
	COORD_SYSTEM_ID TEXT(40),
	LOCAL_COORD_SYSTEM_ID TEXT(40),
	COORD_ACQUISITION_ID TEXT(40),
	LATITUDE NUMERIC(14,9),
	LONGITUDE NUMERIC(14,9),
	ELEVATION NUMERIC(10,5),
	ELEVATION_OUOM TEXT(40),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);
