-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_CONSTRUCTION_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_CONSTRUCTION
CREATE TABLE pipeline_construction
(
	PIPELINE_ID TEXT(40) NOT NULL,
	CONSTRUCTION_PHASE_NO TEXT(40) NOT NULL,
	PHASE_TYPE TEXT(40),
	PHASE_NAME TEXT(255),
	START_DATE TEXT,
	END_DATE TEXT,
	CONTRACTOR TEXT(40),
	INSPECTION_RECORDS TEXT(2000),
	DESCRIPTION TEXT(240),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);

