-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PIPELINE_INCIDENT_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PIPELINE_INCIDENT_PK
ALTER TABLE PIPELINE_INCIDENT ADD CONSTRAINT PIPELINE_INCIDENT_PK PRIMARY KEY
(
	PIPELINE_ID,
	INCIDENT_ID
);

