-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PLAY_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PLAY
CREATE TABLE play
(
	PLAY_ID TEXT(40) NOT NULL,
	PLAY_NAME TEXT(255),
	PLAY_SHORT_NAME TEXT(30),
	FIELD_ID TEXT(40),
	PLAY_TYPE TEXT(40),
	DESCRIPTION TEXT(240),
	GEOLOGICAL_SETTING TEXT(240),
	GEOLOGICAL_AGE TEXT(40),
	PLAY_EXTENT_AREA NUMERIC(18,5),
	PLAY_EXTENT_AREA_OUOM TEXT(40),
	PROVEN_RESERVES_OIL NUMERIC(18,5),
	PROVEN_RESERVES_GAS NUMERIC(18,5),
	PROVEN_RESERVES_OUOM TEXT(40),
	LATITUDE NUMERIC(14,9),
	LONGITUDE NUMERIC(14,9),
	ELEVATION NUMERIC(10,5),
	ELEVATION_OUOM TEXT(40),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);

