-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PROSPECT_SOURCE_ROCK_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PROSPECT_SOURCE_ROCK_PK
ALTER TABLE PROSPECT_SOURCE_ROCK ADD CONSTRAINT PROSPECT_SOURCE_ROCK_PK PRIMARY KEY
(
	PROSPECT_ID,
	SOURCE_ID
);
