-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PROSPECT_RESERVOIR_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PROSPECT_RESERVOIR
CREATE TABLE prospect_reservoir
(
	PROSPECT_ID TEXT(40) NOT NULL,
	RESERVOIR_ID TEXT(40) NOT NULL,
	STRAT_UNIT_ID TEXT(40),
	POROSITY NUMERIC(10,5),
	PERMEABILITY NUMERIC(10,5),
	NET_PAY NUMERIC(10,5),
	NET_PAY_OUOM TEXT(40),
	GROSS_PAY NUMERIC(10,5),
	GROSS_PAY_OUOM TEXT(40),
	NET_TO_GROSS_RATIO NUMERIC(5,4),
	OWC NUMERIC(10,5),
	OWC_OUOM TEXT(40),
	GOC NUMERIC(10,5),
	GOC_OUOM TEXT(40),
	FWL NUMERIC(10,5),
	FWL_OUOM TEXT(40),
	FACIES TEXT(40),
	LITHOLOGY TEXT(40),
	DIAGENESIS TEXT(40),
	RESERVOIR_AREA NUMERIC(18,5),
	RESERVOIR_AREA_OUOM TEXT(40),
	RESERVOIR_THICKNESS NUMERIC(10,5),
	RESERVOIR_THICKNESS_OUOM TEXT(40),
	RESERVOIR_VOLUME NUMERIC(18,5),
	RESERVOIR_VOLUME_OUOM TEXT(40),
	DESCRIPTION TEXT(240),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);
