-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PROSPECT_PORTFOLIO_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PROSPECT_PORTFOLIO
CREATE TABLE prospect_portfolio
(
	PORTFOLIO_ID TEXT(40) NOT NULL,
	PORTFOLIO_NAME TEXT(255),
	DESCRIPTION TEXT(240),
	STRATEGIC_OBJECTIVES TEXT(2000),
	CREATION_DATE TEXT,
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);
