-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PROSPECT_MIGRATION_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PROSPECT_MIGRATION
CREATE TABLE prospect_migration
(
	PROSPECT_ID TEXT(40) NOT NULL,
	MIGRATION_ID TEXT(40) NOT NULL,
	MIGRATION_PATHWAY TEXT(240),
	MIGRATION_DISTANCE NUMERIC(10,5),
	MIGRATION_DISTANCE_OUOM TEXT(40),
	MIGRATION_EFFICIENCY NUMERIC(5,4),
	MIGRATION_TIMING TEXT(40),
	CARRIER_BED TEXT(40),
	SEAL_BREACH_RISK NUMERIC(5,4),
	DESCRIPTION TEXT(240),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);
