-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PROSPECT_WELL_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PROSPECT_WELL_PK
ALTER TABLE PROSPECT_WELL ADD CONSTRAINT PROSPECT_WELL_PK PRIMARY KEY
(
	PROSPECT_ID,
	UWI
);
