-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PROSPECT_SEIS_SURVEY_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PROSPECT_SEIS_SURVEY_PK
ALTER TABLE PROSPECT_SEIS_SURVEY ADD CONSTRAINT PROSPECT_SEIS_SURVEY_PK PRIMARY KEY
(
	PROSPECT_ID,
	SEIS_SET_ID
);
