-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PROSPECT_SOURCE_ROCK_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PROSPECT_SOURCE_ROCK
CREATE TABLE prospect_source_rock
(
	PROSPECT_ID TEXT(40) NOT NULL,
	SOURCE_ID TEXT(40) NOT NULL,
	STRAT_UNIT_ID TEXT(40),
	TOC NUMERIC(10,5),
	HI NUMERIC(10,5),
	KEROGEN_TYPE TEXT(40),
	VITRINITE_REFLECTANCE NUMERIC(5,3),
	TMAX NUMERIC(10,5),
	MATURITY_STAGE TEXT(40),
	GENERATION_POTENTIAL NUMERIC(10,5),
	EXPULSION_EFFICIENCY NUMERIC(5,4),
	MIGRATION_DISTANCE NUMERIC(10,5),
	MIGRATION_DISTANCE_OUOM TEXT(40),
	DESCRIPTION TEXT(240),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);
