-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PROSPECT_RISK_ASSESSMENT_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PROSPECT_RISK_ASSESSMENT_PK
ALTER TABLE PROSPECT_RISK_ASSESSMENT ADD CONSTRAINT PROSPECT_RISK_ASSESSMENT_PK PRIMARY KEY
(
	PROSPECT_ID,
	ASSESSMENT_ID
);
