-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PROSPECT_HISTORY_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PROSPECT_HISTORY
CREATE TABLE prospect_history
(
	PROSPECT_ID TEXT(40) NOT NULL,
	HISTORY_SEQ_NO NUMERIC(10,0) NOT NULL,
	FIELD_NAME TEXT(40),
	OLD_VALUE TEXT(2000),
	NEW_VALUE TEXT(2000),
	CHANGE_REASON TEXT(240),
	CHANGED_BY TEXT(40),
	CHANGE_DATE TEXT,
	DESCRIPTION TEXT(240),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);
