-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PROSPECT_FIELD_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PROSPECT_FIELD_PK
ALTER TABLE PROSPECT_FIELD ADD CONSTRAINT PROSPECT_FIELD_PK PRIMARY KEY
(
	PROSPECT_ID,
	FIELD_ID
);
