-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PROSPECT_RANKING_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PROSPECT_RANKING
CREATE TABLE prospect_ranking
(
	PROSPECT_ID TEXT(40) NOT NULL,
	RANKING_ID TEXT(40) NOT NULL,
	RANKING_SCORE NUMERIC(10,5),
	PRIORITY_ORDER NUMERIC(10,0),
	RANKING_CRITERIA TEXT(2000),
	RANKING_DATE TEXT,
	RANKER TEXT(40),
	METHODOLOGY TEXT(240),
	DESCRIPTION TEXT(240),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);
