-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PROSPECT_SEIS_SURVEY_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_SEIS_SURVEY_PROSPECT_FK
ALTER TABLE PROSPECT_SEIS_SURVEY ADD CONSTRAINT PROSPECT_SEIS_SURVEY_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_SEIS_SURVEY_SEIS_SET_FK
ALTER TABLE PROSPECT_SEIS_SURVEY ADD CONSTRAINT PROSPECT_SEIS_SURVEY_SEIS_SET_FK FOREIGN KEY
(
	SEIS_SET_ID
)
REFERENCES SEIS_SET
(
	SEIS_SET_ID
);

