-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PROSPECT_BA_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_BA_PROSPECT_FK
ALTER TABLE PROSPECT_BA ADD CONSTRAINT PROSPECT_BA_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_BA_BA_FK
ALTER TABLE PROSPECT_BA ADD CONSTRAINT PROSPECT_BA_BA_FK FOREIGN KEY
(
	BUSINESS_ASSOCIATE_ID
)
REFERENCES BUSINESS_ASSOCIATE
(
	BUSINESS_ASSOCIATE_ID
);
