-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PROSPECT_WORKFLOW_STAGE_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PROSPECT_WORKFLOW_STAGE
CREATE TABLE prospect_workflow_stage
(
	PROSPECT_ID TEXT(40) NOT NULL,
	STAGE_SEQ_NO NUMERIC(10,0) NOT NULL,
	WORKFLOW_STAGE TEXT(40),
	STAGE_START_DATE TEXT,
	STAGE_END_DATE TEXT,
	STAGE_OUTCOME TEXT(40),
	NEXT_STAGE TEXT(40),
	APPROVALS_REQUIRED TEXT(2000),
	DESCRIPTION TEXT(240),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);
