-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PROSPECT_VOLUME_ESTIMATE_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PROSPECT_VOLUME_ESTIMATE
CREATE TABLE prospect_volume_estimate
(
	PROSPECT_ID TEXT(40) NOT NULL,
	ESTIMATE_ID TEXT(40) NOT NULL,
	OIL_VOLUME_P10 NUMERIC(18,5),
	OIL_VOLUME_P50 NUMERIC(18,5),
	OIL_VOLUME_P90 NUMERIC(18,5),
	GAS_VOLUME_P10 NUMERIC(18,5),
	GAS_VOLUME_P50 NUMERIC(18,5),
	GAS_VOLUME_P90 NUMERIC(18,5),
	VOLUME_OUOM TEXT(40),
	UNRISKED_OIL_VOLUME NUMERIC(18,5),
	UNRISKED_GAS_VOLUME NUMERIC(18,5),
	RISKED_OIL_VOLUME NUMERIC(18,5),
	RISKED_GAS_VOLUME NUMERIC(18,5),
	RECOVERY_FACTOR NUMERIC(5,4),
	FORMATION_VOLUME_FACTOR NUMERIC(10,5),
	ESTIMATE_METHOD TEXT(40),
	ESTIMATE_DATE TEXT,
	ESTIMATOR TEXT(40),
	DESCRIPTION TEXT(240),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);
