-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PROSPECT_SOURCE_ROCK_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_SOURCE_ROCK_PROSPECT_FK
ALTER TABLE PROSPECT_SOURCE_ROCK ADD CONSTRAINT PROSPECT_SOURCE_ROCK_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_SOURCE_ROCK_STRAT_UNIT_FK
ALTER TABLE PROSPECT_SOURCE_ROCK ADD CONSTRAINT PROSPECT_SOURCE_ROCK_STRAT_UNIT_FK FOREIGN KEY
(
	STRAT_UNIT_ID
)
REFERENCES STRAT_UNIT
(
	STRAT_UNIT_ID
);
