-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PROSPECT_ANALOG_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PROSPECT_ANALOG_PK
ALTER TABLE PROSPECT_ANALOG ADD CONSTRAINT PROSPECT_ANALOG_PK PRIMARY KEY
(
	PROSPECT_ID,
	ANALOG_ID
);
