-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PROSPECT_RANKING_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_RANKING_PROSPECT_FK
ALTER TABLE PROSPECT_RANKING ADD CONSTRAINT PROSPECT_RANKING_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);
