-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PROSPECT_DISCOVERY_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PROSPECT_DISCOVERY
CREATE TABLE prospect_discovery
(
	PROSPECT_ID TEXT(40) NOT NULL,
	DISCOVERY_ID TEXT(40) NOT NULL,
	DISCOVERY_TYPE TEXT(40),
	DISCOVERY_DATE TEXT,
	DISCOVERY_WELL TEXT(40),
	VOLUMES_DISCOVERED_OIL NUMERIC(18,5),
	VOLUMES_DISCOVERED_GAS NUMERIC(18,5),
	VOLUMES_DISCOVERED_OUOM TEXT(40),
	SIGNIFICANCE TEXT(40),
	DESCRIPTION TEXT(240),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);
