-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PROSPECT_MIGRATION_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PROSPECT_MIGRATION_PK
ALTER TABLE PROSPECT_MIGRATION ADD CONSTRAINT PROSPECT_MIGRATION_PK PRIMARY KEY
(
	PROSPECT_ID,
	MIGRATION_ID
);
