-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PROSPECT_TRAP_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PROSPECT_TRAP
CREATE TABLE prospect_trap
(
	PROSPECT_ID TEXT(40) NOT NULL,
	TRAP_ID TEXT(40) NOT NULL,
	TRAP_TYPE TEXT(40),
	TRAP_GEOMETRY TEXT(40),
	CLOSURE_AREA NUMERIC(18,5),
	CLOSURE_AREA_OUOM TEXT(40),
	CLOSURE_HEIGHT NUMERIC(10,5),
	CLOSURE_HEIGHT_OUOM TEXT(40),
	SEAL_QUALITY TEXT(40),
	SEAL_THICKNESS NUMERIC(10,5),
	SEAL_THICKNESS_OUOM TEXT(40),
	TRAP_EFFECTIVENESS NUMERIC(5,2),
	DESCRIPTION TEXT(240),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);
