-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PROSPECT_PLAY_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PROSPECT_PLAY_PK
ALTER TABLE PROSPECT_PLAY ADD CONSTRAINT PROSPECT_PLAY_PK PRIMARY KEY
(
	PROSPECT_ID,
	PLAY_ID
);
