-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: PROSPECT_ECONOMIC_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PROSPECT_ECONOMIC
CREATE TABLE prospect_economic
(
	PROSPECT_ID TEXT(40) NOT NULL,
	ECONOMIC_ID TEXT(40) NOT NULL,
	NPV NUMERIC(18,5),
	EMV NUMERIC(18,5),
	IRR NUMERIC(10,5),
	PAYBACK_PERIOD NUMERIC(10,2),
	PAYBACK_PERIOD_OUOM TEXT(40),
	DEVELOPMENT_COST NUMERIC(18,5),
	OPERATING_COST NUMERIC(18,5),
	ABANDONMENT_COST NUMERIC(18,5),
	OIL_PRICE NUMERIC(10,2),
	GAS_PRICE NUMERIC(10,2),
	DISCOUNT_RATE NUMERIC(5,4),
	INFLATION_RATE NUMERIC(5,4),
	ECONOMIC_SCENARIO TEXT(40),
	EVALUATION_DATE TEXT,
	EVALUATOR TEXT(40),
	DESCRIPTION TEXT(240),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);
