-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: R_ANOMALY_TYPE_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY R_ANOMALY_TYPE_PK
ALTER TABLE R_ANOMALY_TYPE ADD CONSTRAINT R_ANOMALY_TYPE_PK PRIMARY KEY
(
	ANOMALY_TYPE
);

