-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: R_ECONOMIC_METRIC_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY R_ECONOMIC_METRIC_PK
ALTER TABLE R_ECONOMIC_METRIC ADD CONSTRAINT R_ECONOMIC_METRIC_PK PRIMARY KEY
(
	ECONOMIC_METRIC
);
