-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: R_ECONOMIC_METRIC_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE R_ECONOMIC_METRIC
CREATE TABLE r_economic_metric
(
	ECONOMIC_METRIC TEXT(40) NOT NULL,
	ABBREVIATION TEXT(12),
	ACTIVE_IND TEXT(1),
	EFFECTIVE_DATE TEXT,
	EXPIRY_DATE TEXT,
	LONG_NAME TEXT(255),
	PPDM_GUID TEXT(38),
	REMARK TEXT(2000),
	SHORT_NAME TEXT(30),
	SOURCE TEXT(40),
	ROW_CHANGED_BY TEXT(30),
	ROW_CHANGED_DATE TEXT,
	ROW_CREATED_BY TEXT(30),
	ROW_CREATED_DATE TEXT,
	ROW_EFFECTIVE_DATE TEXT,
	ROW_EXPIRY_DATE TEXT,
	ROW_QUALITY TEXT(40)
);
