-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: R_PIPELINE_STATUS_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY R_PIPELINE_STATUS_PK
ALTER TABLE R_PIPELINE_STATUS ADD CONSTRAINT R_PIPELINE_STATUS_PK PRIMARY KEY
(
	PIPELINE_STATUS
);
