-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: R_PLAY_TYPE_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY R_PLAY_TYPE_PK
ALTER TABLE R_PLAY_TYPE ADD CONSTRAINT R_PLAY_TYPE_PK PRIMARY KEY
(
	PLAY_TYPE
);
