-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: R_PROSPECT_STATUS_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY R_PROSPECT_STATUS_PK
ALTER TABLE R_PROSPECT_STATUS ADD CONSTRAINT R_PROSPECT_STATUS_PK PRIMARY KEY
(
	PROSPECT_STATUS
);
