-- PPDM39 SQLITE DDL Script
-- Converted from SQL Server script: R_RISK_LEVEL_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY R_RISK_LEVEL_PK
ALTER TABLE R_RISK_LEVEL ADD CONSTRAINT R_RISK_LEVEL_PK PRIMARY KEY
(
	RISK_LEVEL
);
