CREATE TABLE "SETUP_WIZARD_LOG"
(
    "SETUP_LOG_ID" VARCHAR2(40),
    "ORGANIZATION_ID" VARCHAR2(40),
    "SETUP_STEP" VARCHAR2(255),
    "SETUP_DATA" VARCHAR2(255),
    "EXECUTED_BY" VARCHAR2(255),
    "EXECUTION_DATE" DATE,
    "STATUS" VARCHAR2(50),
    "ERROR_MESSAGE" VARCHAR2(255),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_QUALITY" VARCHAR2(40)
);
