CREATE TABLE "USER_PROFILE"
(
    "USER_ID" VARCHAR2(40),
    "PRIMARY_ROLE" VARCHAR2(255),
    "PREFERRED_LAYOUT" VARCHAR2(255),
    "USER_PREFERENCES" VARCHAR2(255),
    "LAST_LOGIN_DATE" DATE,
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "EFFECTIVE_DATE" DATE,
    "EXPIRY_DATE" DATE,
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_QUALITY" VARCHAR2(40)
);
