CREATE TABLE "USER_ASSET_ACCESS"
(
    "USER_ID" VARCHAR2(40),
    "ASSET_TYPE" VARCHAR2(50),
    "ASSET_ID" VARCHAR2(40),
    "ACCESS_LEVEL" VARCHAR2(255),
    "INHERIT_IND" VARCHAR2(255),
    "ORGANIZATION_ID" VARCHAR2(40),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "EFFECTIVE_DATE" DATE,
    "EXPIRY_DATE" DATE,
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_QUALITY" VARCHAR2(40)
);
