CREATE TABLE "USER_ROLE"
(
    "USER_ROLE_ID" VARCHAR2(40) NOT NULL,
    "USER_ID" VARCHAR2(40),
    "ROLE_ID" VARCHAR2(40),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "ROW_QUALITY" VARCHAR2(40),
    "PPDM_GUID" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "AREA_ID" VARCHAR2(40),
    "AREA_TYPE" VARCHAR2(50),
    "BUSINESS_ASSOCIATE_ID" VARCHAR2(40),
    "EFFECTIVE_DATE" DATE,
    "EXPIRY_DATE" DATE,
    "SOURCE" VARCHAR2(40),
    "REMARK" VARCHAR2(2000)
);
