CREATE TABLE "LACT_UNIT"
(
    "LACT_UNIT_ID" VARCHAR2(40) NOT NULL,
    "LACT_NAME" VARCHAR2(255),
    "SERVICE_UNIT_ID" VARCHAR2(40),
    "METER_TYPE" VARCHAR2(50),
    "MAXIMUM_FLOW_RATE" NUMBER(18,2),
    "METER_FACTOR" NUMBER(18,2),
    "LAST_CALIBRATION_DATE" DATE,
    "NEXT_CALIBRATION_DATE" DATE,
    "IS_ACTIVE" VARCHAR2(255),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE
);
