CREATE TABLE "STORAGE_FACILITY"
(
    "STORAGE_FACILITY_ID" VARCHAR2(40) NOT NULL,
    "FACILITY_NAME" VARCHAR2(255),
    "FACILITY_TYPE" VARCHAR2(50),
    "LOCATION" VARCHAR2(255),
    "CAPACITY" NUMBER(18,2),
    "CURRENT_INVENTORY" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE
);
