CREATE TABLE "TANK_BATTERY"
(
    "TANK_BATTERY_ID" VARCHAR2(40) NOT NULL,
    "BATTERY_NAME" VARCHAR2(255),
    "STORAGE_FACILITY_ID" VARCHAR2(40),
    "LEASE_ID" VARCHAR2(40),
    "CURRENT_INVENTORY" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE
);
