CREATE TABLE "OIL_COMPOSITION"
(
    "OIL_COMPOSITION_ID" VARCHAR(40) NOT NULL,
    "COMPOSITION_NAME" VARCHAR(255),
    "COMPOSITION_DATE" TIMESTAMP,
    "OIL_GRAVITY" VARCHAR(255),
    "GAS_OIL_RATIO" VARCHAR(255),
    "WATER_CUT" VARCHAR(255),
    "BUBBLE_POINT_PRESSURE" VARCHAR(255),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP
);
