CREATE TABLE "PROVED_PROPERTY"
(
    "PROPERTY_ID" VARCHAR(40),
    "ACQUISITION_COST" NUMERIC(18,2),
    "EXPLORATION_COSTS" NUMERIC(18,6),
    "DEVELOPMENT_COSTS" NUMERIC(18,2),
    "ACCUMULATED_AMORTIZATION" NUMERIC(18,2),
    "PROVED_DATE" TIMESTAMP,
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40),
    "PROVED_RESERVES_GAS" NUMERIC(18,2) NOT NULL,
    "PROVED_RESERVES_OIL" NUMERIC(18,2) NOT NULL,
    "PROVED_RESERVES_BOE" VARCHAR(255) NOT NULL
);
