-- PROVED_PROPERTY Table Creation Script
-- SQL Server Version

CREATE TABLE PROVED_PROPERTY
(
    PROPERTY_ID NVARCHAR(40) NOT NULL,
    ACQUISITION_COST NUMERIC(18,2),
    EXPLORATION_COSTS NUMERIC(18,2),
    DEVELOPMENT_COSTS NUMERIC(18,2),
    ACCUMULATED_AMORTIZATION NUMERIC(18,2),
    PROVED_DATE DATETIME,
    ACTIVE_IND NVARCHAR(1),
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(4000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(40),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);

-- Primary Key
ALTER TABLE PROVED_PROPERTY
ADD CONSTRAINT PK_PROVED_PROPERTY PRIMARY KEY (PROPERTY_ID);

-- Foreign Keys (if PROPERTY_ID references UNPROVED_PROPERTY)
-- ALTER TABLE PROVED_PROPERTY
-- ADD CONSTRAINT FK_PROVED_PROPERTY_UNPROVED FOREIGN KEY (PROPERTY_ID) REFERENCES UNPROVED_PROPERTY(PROPERTY_ID);

-- Indexes
CREATE INDEX IX_PROVED_PROPERTY_PROVED_DATE ON PROVED_PROPERTY(PROVED_DATE);

