CREATE TABLE `PRODUCTION_COSTS`
(
    `PRODUCTION_COST_ID` VARCHAR(40),
    `PROPERTY_ID` VARCHAR(40),
    `OPERATING_COSTS` DECIMAL(18,2),
    `WORKOVER_COSTS` DECIMAL(18,2),
    `MAINTENANCE_COSTS` DECIMAL(18,2),
    `TOTAL_PRODUCTION_COSTS` DECIMAL(18,2),
    `COST_PERIOD` DATETIME,
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` VARCHAR(40)
);
