-- PRODUCTION_COSTS Table Creation Script
-- SQL Server Version

CREATE TABLE PRODUCTION_COSTS
(
    PRODUCTION_COST_ID NVARCHAR(40) NOT NULL,
    PROPERTY_ID NVARCHAR(40),
    OPERATING_COSTS NUMERIC(18,2),
    WORKOVER_COSTS NUMERIC(18,2),
    MAINTENANCE_COSTS NUMERIC(18,2),
    TOTAL_PRODUCTION_COSTS NUMERIC(18,2),
    COST_PERIOD DATETIME,
    ACTIVE_IND NVARCHAR(1),
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(4000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(40),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);

-- Primary Key
ALTER TABLE PRODUCTION_COSTS
ADD CONSTRAINT PK_PRODUCTION_COSTS PRIMARY KEY (PRODUCTION_COST_ID);

-- Foreign Keys
ALTER TABLE PRODUCTION_COSTS
ADD CONSTRAINT FK_PRODUCTION_COSTS_PROPERTY FOREIGN KEY (PROPERTY_ID) REFERENCES UNPROVED_PROPERTY(PROPERTY_ID);

-- Indexes
CREATE INDEX IX_PRODUCTION_COSTS_PROPERTY ON PRODUCTION_COSTS(PROPERTY_ID);
CREATE INDEX IX_PRODUCTION_COSTS_COST_PERIOD ON PRODUCTION_COSTS(COST_PERIOD);

