raiserror ('CREATING TABLE GAS_PROPERTIES', 10,1) with nowait

CREATE TABLE GAS_PROPERTIES
(
    GAS_PROPERTIES_ID NVARCHAR(40) NOT NULL,
    GAS_COMPOSITION_ID NVARCHAR(40),
    PRESSURE NUMERIC(18,2),
    TEMPERATURE NUMERIC(18,2),
    Z_FACTOR NUMERIC(18,2),
    VISCOSITY NUMERIC(18,2),
    DENSITY NUMERIC(18,2),
    SPECIFIC_GRAVITY NUMERIC(18,2),
    MOLECULAR_WEIGHT NUMERIC(18,2),
    PSEUDO_REDUCED_PRESSURE NUMERIC(18,2),
    PSEUDO_REDUCED_TEMPERATURE NUMERIC(18,2),
    PSEUDO_CRITICAL_PRESSURE NUMERIC(18,2),
    PSEUDO_CRITICAL_TEMPERATURE NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME
);
