ALTER TABLE GAS_PROPERTIES
ADD CONSTRAINT FK_GAS_PROPERTIES_GAS_COMPOSITION FOREIGN KEY (GAS_COMPOSITION_ID) REFERENCES GAS_COMPOSITION(GAS_COMPOSITION_ID);

ALTER TABLE GAS_PROPERTIES
ADD CONSTRAINT FK_GAS_PROPERTIES_AREA FOREIGN KEY (AREA_ID) REFERENCES AREA(AREA_ID);

ALTER TABLE GAS_PROPERTIES
ADD CONSTRAINT FK_GAS_PROPERTIES_BUSINESS_ASSOCIATE FOREIGN KEY (BUSINESS_ASSOCIATE_ID) REFERENCES BUSINESS_ASSOCIATE(BUSINESS_ASSOCIATE_ID);
