CREATE TABLE DEVELOPMENT_COSTS
(
    DEVELOPMENT_COST_ID TEXT,
    PROPERTY_ID TEXT,
    DEVELOPMENT_WELL_DRILLING_COSTS REAL,
    DEVELOPMENT_WELL_EQUIPMENT REAL,
    SUPPORT_EQUIPMENT_AND_FACILITIES REAL,
    SERVICE_WELL_COSTS REAL,
    TOTAL_DEVELOPMENT_COSTS REAL,
    COST_DATE DATETIME,
    COST_CENTER_ID TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
