CREATE TABLE "GAS_LIFT_DESIGN"
(
    "DESIGN_ID" VARCHAR(40),
    "WELL_UWI" VARCHAR(255),
    "DESIGN_DATE" TIMESTAMP,
    "NUMBER_OF_VALVES" VARCHAR(255),
    "TOTAL_GAS_INJECTION_RATE" VARCHAR(255),
    "EXPECTED_PRODUCTION_RATE" VARCHAR(255),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30)
);
