CREATE TABLE "GAS_LIFT_PERFORMANCE"
(
    "PERFORMANCE_ID" VARCHAR(40),
    "WELL_UWI" VARCHAR(255),
    "PERFORMANCE_DATE" TIMESTAMP,
    "GAS_INJECTION_RATE" VARCHAR(255),
    "PRODUCTION_RATE" VARCHAR(255),
    "GAS_LIQUID_RATIO" VARCHAR(255),
    "EFFICIENCY" VARCHAR(255),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30)
);
