ALTER TABLE "GAS_LIFT_PERFORMANCE_POINT"
ADD CONSTRAINT FK_GAS_LIFT_PERFORMANCE_POINT_GAS_LIFT_POTENTIAL_RESULT FOREIGN KEY ("GAS_LIFT_POTENTIAL_RESULT_ID") REFERENCES "GAS_LIFT_POTENTIAL_RESULT"("GAS_LIFT_POTENTIAL_RESULT_ID");

ALTER TABLE "GAS_LIFT_PERFORMANCE_POINT"
ADD CONSTRAINT FK_GAS_LIFT_PERFORMANCE_POINT_AREA FOREIGN KEY ("AREA_ID") REFERENCES "AREA"("AREA_ID");

ALTER TABLE "GAS_LIFT_PERFORMANCE_POINT"
ADD CONSTRAINT FK_GAS_LIFT_PERFORMANCE_POINT_BUSINESS_ASSOCIATE FOREIGN KEY ("BUSINESS_ASSOCIATE_ID") REFERENCES "BUSINESS_ASSOCIATE"("BUSINESS_ASSOCIATE_ID");
