raiserror ('CREATING TABLE HYDRAULIC_PISTON_PUMP_PROPERTIES', 10,1) with nowait

CREATE TABLE HYDRAULIC_PISTON_PUMP_PROPERTIES
(
    HYDRAULIC_PISTON_PUMP_PROPERTIES_ID NVARCHAR(40) NOT NULL,
    HYDRAULIC_PUMP_WELL_PROPERTIES_ID NVARCHAR(40),
    PISTON_DIAMETER NUMERIC(18,2),
    ROD_DIAMETER NUMERIC(18,2),
    STROKE_LENGTH NUMERIC(18,2),
    STROKES_PER_MINUTE NUMERIC(18,2),
    POWER_FLUID_PRESSURE NUMERIC(18,2),
    POWER_FLUID_RATE NUMERIC(18,2),
    POWER_FLUID_SPECIFIC_GRAVITY NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME
);
