CREATE TABLE "PARTICIPATING_AREA"
(
    "PARTICIPATING_AREA_ID" VARCHAR2(40) NOT NULL,
    "UNIT_AGREEMENT_ID" VARCHAR2(40),
    "AREA_NAME" VARCHAR2(255),
    "EFFECTIVE_DATE" DATE,
    "EXPIRY_DATE" DATE,
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE
);
