CREATE TABLE "TRACT_PARTICIPATION"
(
    "TRACT_PARTICIPATION_ID" VARCHAR2(40) NOT NULL,
    "PARTICIPATING_AREA_ID" VARCHAR2(40),
    "UNIT_AGREEMENT_ID" VARCHAR2(40),
    "TRACT_ID" VARCHAR2(40),
    "PARTICIPATION_PERCENTAGE" NUMBER(18,6),
    "WORKING_INTEREST" NUMBER(18,2),
    "NET_REVENUE_INTEREST" NUMBER(18,2),
    "TRACT_ACREAGE" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE
);
