CREATE TABLE "UNIT_AGREEMENT"
(
    "UNIT_AGREEMENT_ID" VARCHAR2(40) NOT NULL,
    "UNIT_NAME" VARCHAR2(255),
    "UNIT_NUMBER" VARCHAR2(255),
    "UNIT_OPERATOR_BA_ID" VARCHAR2(40),
    "EFFECTIVE_DATE" DATE,
    "EXPIRY_DATE" DATE,
    "STATUS" VARCHAR2(50),
    "TERMS_AND_CONDITIONS" VARCHAR2(255),
    "APPROVAL_DATE" DATE,
    "APPROVED_BY" VARCHAR2(255),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE
);
