ALTER TABLE `PPDM_DEFAULT_VALUE`
ADD CONSTRAINT FK_PPDM_DEFAULT_VALUE_DEFAULT_VALUE FOREIGN KEY (`DEFAULT_VALUE_ID`) REFERENCES `DEFAULT_VALUE`(`DEFAULT_VALUE_ID`);

ALTER TABLE `PPDM_DEFAULT_VALUE`
ADD CONSTRAINT FK_PPDM_DEFAULT_VALUE_USER FOREIGN KEY (`USER_ID`) REFERENCES `USER`(`USER_ID`);

ALTER TABLE `PPDM_DEFAULT_VALUE`
ADD CONSTRAINT FK_PPDM_DEFAULT_VALUE_DATABASE FOREIGN KEY (`DATABASE_ID`) REFERENCES `DATABASE`(`DATABASE_ID`);
