CREATE TABLE `PPDM_DEFAULT_VALUE`
(
    `DEFAULT_VALUE_ID` VARCHAR(40),
    `DEFAULT_KEY` VARCHAR(255),
    `DEFAULT_VALUE` VARCHAR(255),
    `DEFAULT_CATEGORY` VARCHAR(255),
    `VALUE_TYPE` VARCHAR(50),
    `USER_ID` VARCHAR(40),
    `DATABASE_ID` VARCHAR(40),
    `DESCRIPTION` VARCHAR(2000),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_QUALITY` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_ID` BIGINT
);
