ALTER TABLE FLASH_CONDITIONS
ADD CONSTRAINT FK_FLASH_CONDITIONS_FLASH_CALCULATION_RESULT FOREIGN KEY (FLASH_CALCULATION_RESULT_ID) REFERENCES FLASH_CALCULATION_RESULT(FLASH_CALCULATION_RESULT_ID);

ALTER TABLE FLASH_CONDITIONS
ADD CONSTRAINT FK_FLASH_CONDITIONS_AREA FOREIGN KEY (AREA_ID) REFERENCES AREA(AREA_ID);

ALTER TABLE FLASH_CONDITIONS
ADD CONSTRAINT FK_FLASH_CONDITIONS_BUSINESS_ASSOCIATE FOREIGN KEY (BUSINESS_ASSOCIATE_ID) REFERENCES BUSINESS_ASSOCIATE(BUSINESS_ASSOCIATE_ID);
