CREATE TABLE "PLUNGER_LIFT_GAS_REQUIREMENTS"
(
    "PLUNGER_LIFT_GAS_REQUIREMENTS_ID" VARCHAR2(40) NOT NULL,
    "PLUNGER_LIFT_WELL_PROPERTIES_ID" VARCHAR2(40),
    "REQUIRED_GAS_INJECTION_RATE" NUMBER(18,2),
    "AVAILABLE_GAS" NUMBER(18,2),
    "ADDITIONAL_GAS_REQUIRED" NUMBER(18,2),
    "REQUIRED_GAS_LIQUID_RATIO" NUMBER(18,6),
    "MINIMUM_CASING_PRESSURE" NUMBER(18,2),
    "MAXIMUM_CASING_PRESSURE" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_QUALITY" VARCHAR2(40)
);
