CREATE TABLE "PLUNGER_LIFT_CYCLE_POINT"
(
    "PLUNGER_LIFT_CYCLE_POINT_ID" VARCHAR2(40) NOT NULL,
    "PLUNGER_LIFT_CYCLE_RESULT_ID" VARCHAR2(40),
    "TIME" NUMBER(18,2),
    "PHASE" VARCHAR2(255),
    "PLUNGER_DEPTH" NUMBER(18,2),
    "CASING_PRESSURE" NUMBER(18,2),
    "TUBING_PRESSURE" NUMBER(18,2),
    "PRODUCTION_RATE" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_QUALITY" VARCHAR2(40)
);
