CREATE TABLE FIELD_PHASE
(
    FIELD_PHASE_ID TEXT NOT NULL,
    FIELD_ID TEXT,
    PHASE TEXT,
    PHASE_START_DATE DATETIME,
    PHASE_END_DATE DATETIME,
    PHASE_STATUS TEXT,
    TRANSITION_REASON TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT
);
