ALTER TABLE "GAS_PIPELINE_FLOW_PROPERTIES"
ADD CONSTRAINT FK_GAS_PIPELINE_FLOW_PROPERTIES_PIPELINE_PROPERTIES FOREIGN KEY ("PIPELINE_PROPERTIES_ID") REFERENCES "PIPELINE_PROPERTIES"("PIPELINE_PROPERTIES_ID");
