CREATE TABLE "LIQUID_PIPELINE_FLOW_PROPERTIES"
(
    "LIQUID_PIPELINE_FLOW_PROPERTIES_ID" VARCHAR(40) NOT NULL,
    "PIPELINE_PROPERTIES_ID" VARCHAR(40),
    "LIQUID_FLOW_RATE" NUMERIC(18,2),
    "LIQUID_SPECIFIC_GRAVITY" NUMERIC(18,2),
    "LIQUID_VISCOSITY" NUMERIC(18,2),
    "LIQUID_DENSITY" NUMERIC(18,2),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_QUALITY" VARCHAR(40)
);
