ALTER TABLE "PIPELINE_INSPECTION"
ADD CONSTRAINT FK_PIPELINE_INSPECTION_PIPELINE FOREIGN KEY ("PIPELINE_ID") REFERENCES "PIPELINE"("PIPELINE_ID");

ALTER TABLE "PIPELINE_INSPECTION"
ADD CONSTRAINT FK_PIPELINE_INSPECTION_INSPECTION FOREIGN KEY ("INSPECTION_ID") REFERENCES "INSPECTION"("INSPECTION_ID");

ALTER TABLE "PIPELINE_INSPECTION"
ADD CONSTRAINT FK_PIPELINE_INSPECTION_SEGMENT FOREIGN KEY ("SEGMENT_ID") REFERENCES "SEGMENT"("SEGMENT_ID");
