CREATE TABLE "PIPELINE_PROPERTIES"
(
    "PIPELINE_PROPERTIES_ID" VARCHAR(40) NOT NULL,
    "DIAMETER" NUMERIC(18,2),
    "LENGTH" NUMERIC(18,2),
    "ROUGHNESS" NUMERIC(18,2),
    "ELEVATION_CHANGE" NUMERIC(18,2),
    "INLET_PRESSURE" NUMERIC(18,2),
    "OUTLET_PRESSURE" NUMERIC(18,2),
    "AVERAGE_TEMPERATURE" NUMERIC(18,2),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_QUALITY" VARCHAR(40)
);
