CREATE TABLE "PIPELINE_WELL"
(
    "PIPELINE_ID" VARCHAR(40),
    "UWI" VARCHAR(255),
    "CONNECTION_SEQ_NO" NUMERIC(18,2) NOT NULL,
    "CONNECTION_TYPE" VARCHAR(50),
    "CONNECTION_DATE" TIMESTAMP,
    "FLOW_DIRECTION" VARCHAR(255),
    "DESCRIPTION" VARCHAR(2000),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "EFFECTIVE_DATE" TIMESTAMP,
    "EXPIRY_DATE" TIMESTAMP,
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_QUALITY" VARCHAR(40)
);
