CREATE TABLE "R_PIPELINE_STATUS"
(
    "PIPELINE_STATUS" VARCHAR(50),
    "ABBREVIATION" VARCHAR(255),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "EFFECTIVE_DATE" TIMESTAMP,
    "EXPIRY_DATE" TIMESTAMP,
    "LONG_NAME" VARCHAR(255),
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SHORT_NAME" VARCHAR(255),
    "SOURCE" VARCHAR(40),
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_QUALITY" VARCHAR(40)
);
