CREATE TABLE "FLASH_COMPONENT"
(
    "FLASH_COMPONENT_ID" VARCHAR(40) NOT NULL,
    "FLASH_CALCULATION_ID" VARCHAR(40),
    "COMPONENT_NAME" VARCHAR(255),
    "MOLE_FRACTION" NUMERIC(18,2),
    "CRITICAL_TEMPERATURE" NUMERIC(18,2),
    "CRITICAL_PRESSURE" NUMERIC(18,2),
    "ACENTRIC_FACTOR" NUMERIC(18,2),
    "MOLECULAR_WEIGHT" NUMERIC(18,2),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_QUALITY" VARCHAR(40)
);
