CREATE TABLE PRODUCTION_FORECAST
(
    FORECAST_ID TEXT,
    WELL_UWI TEXT,
    FIELD_ID TEXT,
    FORECAST_NAME TEXT,
    FORECAST_TYPE TEXT,
    FORECAST_START_DATE DATETIME,
    FORECAST_END_DATE DATETIME,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT
);
