CREATE TABLE PRODUCTION_FORECAST_POINT
(
    FORECAST_POINT_ID TEXT,
    FORECAST_ID TEXT,
    FORECAST_DATE DATETIME,
    OIL_RATE TEXT(255),
    GAS_RATE TEXT(255),
    WATER_RATE TEXT(255),
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT
);
