CREATE TABLE "ROYALTY_STATEMENT"
(
    "ROYALTY_STATEMENT_ID" VARCHAR2(40) NOT NULL,
    "ROYALTY_OWNER_BA_ID" VARCHAR2(40),
    "PROPERTY_ID" VARCHAR2(40),
    "STATEMENT_PERIOD_START" DATE,
    "STATEMENT_PERIOD_END" DATE,
    "TOTAL_ROYALTY_AMOUNT" NUMBER(18,2),
    "TOTAL_DEDUCTIONS" NUMBER(18,2),
    "NET_PAYMENT_AMOUNT" NUMBER(18,2),
    "STATEMENT_DATE" DATE,
    "STATUS" VARCHAR2(50),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE
);
