CREATE TABLE "ROYALTY_INTEREST"
(
    "ROYALTY_INTEREST_ID" VARCHAR2(40) NOT NULL,
    "PROPERTY_ID" VARCHAR2(40),
    "ROYALTY_OWNER_BA_ID" VARCHAR2(40),
    "INTEREST_TYPE" VARCHAR2(50),
    "INTEREST_PERCENTAGE" NUMBER(18,6),
    "ROYALTY_RATE" NUMBER(18,2),
    "EFFECTIVE_DATE" DATE,
    "EXPIRY_DATE" DATE,
    "DIVISION_ORDER_ID" VARCHAR2(40),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_QUALITY" VARCHAR2(40)
);
