using System;
using System.Collections.Generic;
using System.Linq;
using Beep.OilandGas.Models.Data;

namespace Beep.OilandGas.Models.Data.ProductionAccounting
{
    public abstract class Report : ModelEntityBase
    {
        /// <summary>
        /// Gets or sets the report identifier.
        /// </summary>
        private string ReportIdValue = string.Empty;

        public string ReportId

        {

            get { return this.ReportIdValue; }

            set { SetProperty(ref ReportIdValue, value); }

        }

        /// <summary>
        /// Gets or sets the report type.
        /// </summary>
        private ReportType ReportTypeValue;

        public ReportType ReportType

        {

            get { return this.ReportTypeValue; }

            set { SetProperty(ref ReportTypeValue, value); }

        }

        /// <summary>
        /// Gets or sets the report period start date.
        /// </summary>
        private DateTime ReportPeriodStartValue;

        public DateTime ReportPeriodStart

        {

            get { return this.ReportPeriodStartValue; }

            set { SetProperty(ref ReportPeriodStartValue, value); }

        }

        /// <summary>
        /// Gets or sets the report period end date.
        /// </summary>
        private DateTime ReportPeriodEndValue;

        public DateTime ReportPeriodEnd

        {

            get { return this.ReportPeriodEndValue; }

            set { SetProperty(ref ReportPeriodEndValue, value); }

        }

        /// <summary>
        /// Gets or sets the generation date.
        /// </summary>
        private DateTime GenerationDateValue = DateTime.Now;

        public DateTime GenerationDate

        {

            get { return this.GenerationDateValue; }

            set { SetProperty(ref GenerationDateValue, value); }

        }

        /// <summary>
        /// Gets or sets the generated by.
        /// </summary>
        private string GeneratedByValue = string.Empty;

        public string GeneratedBy

        {

            get { return this.GeneratedByValue; }

            set { SetProperty(ref GeneratedByValue, value); }

        }
    }
}
