using System;
using System.Collections.Generic;
using System.Linq;

using Beep.OilandGas.Models.Data;
namespace Beep.OilandGas.Models.Data.ProductionAccounting
{
    /// <summary>
    /// Report type enumeration.
    /// </summary>


    /// <summary>
    /// Represents a base report (DTO for reporting).
    /// </summary>
    public abstract class Report : ModelEntityBase
    {
        /// <summary>
        /// Gets or sets the report identifier.
        /// </summary>
        private string ReportIdValue = string.Empty;

        public string ReportId

        {

            get { return this.ReportIdValue; }

            set { SetProperty(ref ReportIdValue, value); }

        }

        /// <summary>
        /// Gets or sets the report type.
        /// </summary>
        private ReportType ReportTypeValue;

        public ReportType ReportType

        {

            get { return this.ReportTypeValue; }

            set { SetProperty(ref ReportTypeValue, value); }

        }

        /// <summary>
        /// Gets or sets the report period start date.
        /// </summary>
        private DateTime ReportPeriodStartValue;

        public DateTime ReportPeriodStart

        {

            get { return this.ReportPeriodStartValue; }

            set { SetProperty(ref ReportPeriodStartValue, value); }

        }

        /// <summary>
        /// Gets or sets the report period end date.
        /// </summary>
        private DateTime ReportPeriodEndValue;

        public DateTime ReportPeriodEnd

        {

            get { return this.ReportPeriodEndValue; }

            set { SetProperty(ref ReportPeriodEndValue, value); }

        }

        /// <summary>
        /// Gets or sets the generation date.
        /// </summary>
        private DateTime GenerationDateValue = DateTime.Now;

        public DateTime GenerationDate

        {

            get { return this.GenerationDateValue; }

            set { SetProperty(ref GenerationDateValue, value); }

        }

        /// <summary>
        /// Gets or sets the generated by.
        /// </summary>
        private string GeneratedByValue = string.Empty;

        public string GeneratedBy

        {

            get { return this.GeneratedByValue; }

            set { SetProperty(ref GeneratedByValue, value); }

        }
    }


    /// <summary>
    /// Represents report summaries.
    /// </summary>
    public class ProductionReportSummary : ModelEntityBase
    {
        private decimal TotalProductionValue;

        public decimal TotalProduction

        {

            get { return this.TotalProductionValue; }

            set { SetProperty(ref TotalProductionValue, value); }

        }
        private int ProducingDaysValue;

        public int ProducingDays

        {

            get { return this.ProducingDaysValue; }

            set { SetProperty(ref ProducingDaysValue, value); }

        }
        private decimal AverageDailyProductionValue;

        public decimal AverageDailyProduction

        {

            get { return this.AverageDailyProductionValue; }

            set { SetProperty(ref AverageDailyProductionValue, value); }

        }
    }

    public class InventoryReportSummary : ModelEntityBase
    {
        private decimal OpeningInventoryValue;

        public decimal OpeningInventory

        {

            get { return this.OpeningInventoryValue; }

            set { SetProperty(ref OpeningInventoryValue, value); }

        }
        private decimal ReceiptsValue;

        public decimal Receipts

        {

            get { return this.ReceiptsValue; }

            set { SetProperty(ref ReceiptsValue, value); }

        }
        private decimal DeliveriesValue;

        public decimal Deliveries

        {

            get { return this.DeliveriesValue; }

            set { SetProperty(ref DeliveriesValue, value); }

        }
        private decimal ClosingInventoryValue;

        public decimal ClosingInventory

        {

            get { return this.ClosingInventoryValue; }

            set { SetProperty(ref ClosingInventoryValue, value); }

        }
    }

    public class AllocationReportSummary : ModelEntityBase
    {
        private int WellsAllocatedValue;

        public int WellsAllocated

        {

            get { return this.WellsAllocatedValue; }

            set { SetProperty(ref WellsAllocatedValue, value); }

        }
        private int LeasesAllocatedValue;

        public int LeasesAllocated

        {

            get { return this.LeasesAllocatedValue; }

            set { SetProperty(ref LeasesAllocatedValue, value); }

        }
        private decimal TotalAllocatedVolumeValue;

        public decimal TotalAllocatedVolume

        {

            get { return this.TotalAllocatedVolumeValue; }

            set { SetProperty(ref TotalAllocatedVolumeValue, value); }

        }
    }

    public class MeasurementReportSummary : ModelEntityBase
    {
        private int MeasurementCountValue;

        public int MeasurementCount

        {

            get { return this.MeasurementCountValue; }

            set { SetProperty(ref MeasurementCountValue, value); }

        }
        private decimal AverageAccuracyValue;

        public decimal AverageAccuracy

        {

            get { return this.AverageAccuracyValue; }

            set { SetProperty(ref AverageAccuracyValue, value); }

        }
        private int CalibrationsDueValue;

        public int CalibrationsDue

        {

            get { return this.CalibrationsDueValue; }

            set { SetProperty(ref CalibrationsDueValue, value); }

        }
    }

    public class CostReportSummary : ModelEntityBase
    {
        private decimal TotalLiftingCostsValue;

        public decimal TotalLiftingCosts

        {

            get { return this.TotalLiftingCostsValue; }

            set { SetProperty(ref TotalLiftingCostsValue, value); }

        }
        private decimal TotalOperatingCostsValue;

        public decimal TotalOperatingCosts

        {

            get { return this.TotalOperatingCostsValue; }

            set { SetProperty(ref TotalOperatingCostsValue, value); }

        }
        private decimal TotalMarketingCostsValue;

        public decimal TotalMarketingCosts

        {

            get { return this.TotalMarketingCostsValue; }

            set { SetProperty(ref TotalMarketingCostsValue, value); }

        }
        public decimal TotalCosts => TotalLiftingCosts + TotalOperatingCosts + TotalMarketingCosts;
    }

    public class GovernmentalProductionData : ModelEntityBase
    {
        private decimal OilProductionValue;

        public decimal OilProduction

        {

            get { return this.OilProductionValue; }

            set { SetProperty(ref OilProductionValue, value); }

        }
        private decimal GasProductionValue;

        public decimal GasProduction

        {

            get { return this.GasProductionValue; }

            set { SetProperty(ref GasProductionValue, value); }

        }
        private decimal WaterProductionValue;

        public decimal WaterProduction

        {

            get { return this.WaterProductionValue; }

            set { SetProperty(ref WaterProductionValue, value); }

        }
    }

    public class GovernmentalRoyaltyData : ModelEntityBase
    {
        private decimal RoyaltyVolumeValue;

        public decimal RoyaltyVolume

        {

            get { return this.RoyaltyVolumeValue; }

            set { SetProperty(ref RoyaltyVolumeValue, value); }

        }
        private decimal RoyaltyValueValue;

        public decimal RoyaltyValue

        {

            get { return this.RoyaltyValueValue; }

            set { SetProperty(ref RoyaltyValueValue, value); }

        }
        private decimal RoyaltyRateValue;

        public decimal RoyaltyRate

        {

            get { return this.RoyaltyRateValue; }

            set { SetProperty(ref RoyaltyRateValue, value); }

        }
    }

    public class GovernmentalTaxData : ModelEntityBase
    {
        private decimal SeveranceTaxValue;

        public decimal SeveranceTax

        {

            get { return this.SeveranceTaxValue; }

            set { SetProperty(ref SeveranceTaxValue, value); }

        }
        private decimal AdValoremTaxValue;

        public decimal AdValoremTax

        {

            get { return this.AdValoremTaxValue; }

            set { SetProperty(ref AdValoremTaxValue, value); }

        }
        public decimal TotalTaxes => SeveranceTax + AdValoremTax;
    }

    public class JIBParticipant : ModelEntityBase
    {
        private string ParticipantIdValue = string.Empty;

        public string ParticipantId

        {

            get { return this.ParticipantIdValue; }

            set { SetProperty(ref ParticipantIdValue, value); }

        }
        private string CompanyNameValue = string.Empty;

        public string CompanyName

        {

            get { return this.CompanyNameValue; }

            set { SetProperty(ref CompanyNameValue, value); }

        }
        private decimal WorkingInterestValue;

        public decimal WorkingInterest

        {

            get { return this.WorkingInterestValue; }

            set { SetProperty(ref WorkingInterestValue, value); }

        }
        private decimal NetRevenueInterestValue;

        public decimal NetRevenueInterest

        {

            get { return this.NetRevenueInterestValue; }

            set { SetProperty(ref NetRevenueInterestValue, value); }

        }
    }

    public class JIBCharge : ModelEntityBase
    {
        private string ChargeIdValue = string.Empty;

        public string ChargeId

        {

            get { return this.ChargeIdValue; }

            set { SetProperty(ref ChargeIdValue, value); }

        }
        private string DescriptionValue = string.Empty;

        public string Description

        {

            get { return this.DescriptionValue; }

            set { SetProperty(ref DescriptionValue, value); }

        }
        private decimal AmountValue;

        public decimal Amount

        {

            get { return this.AmountValue; }

            set { SetProperty(ref AmountValue, value); }

        }
        private string CategoryValue = string.Empty;

        public string Category

        {

            get { return this.CategoryValue; }

            set { SetProperty(ref CategoryValue, value); }

        }
    }

    public class JIBCredit : ModelEntityBase
    {
        private string CreditIdValue = string.Empty;

        public string CreditId

        {

            get { return this.CreditIdValue; }

            set { SetProperty(ref CreditIdValue, value); }

        }
        private string DescriptionValue = string.Empty;

        public string Description

        {

            get { return this.DescriptionValue; }

            set { SetProperty(ref DescriptionValue, value); }

        }
        private decimal AmountValue;

        public decimal Amount

        {

            get { return this.AmountValue; }

            set { SetProperty(ref AmountValue, value); }

        }
        private string CategoryValue = string.Empty;

        public string Category

        {

            get { return this.CategoryValue; }

            set { SetProperty(ref CategoryValue, value); }

        }
    }
}








