CREATE TABLE ALLOCATION_DETAIL
(
    ALLOCATION_DETAIL_ID TEXT NOT NULL PRIMARY KEY,
    ALLOCATION_RESULT_ID TEXT NOT NULL,
    ENTITY_ID TEXT,
    ENTITY_TYPE TEXT,
    ENTITY_NAME TEXT,
    ALLOCATED_VOLUME NUMERIC(18,2),
    ALLOCATION_PERCENTAGE NUMERIC(18,6),
    ALLOCATION_BASIS NUMERIC(18,6),
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE TEXT,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE TEXT,
    ROW_EFFECTIVE_DATE TEXT,
    ROW_EXPIRY_DATE TEXT,
    ROW_ID INTEGER
);

