CREATE TABLE LIST_OF_VALUE
(
    LIST_OF_VALUE_ID TEXT NOT NULL PRIMARY KEY,
    VALUE_TYPE TEXT NOT NULL,
    VALUE_CODE TEXT NOT NULL,
    VALUE_NAME TEXT,
    DESCRIPTION TEXT,
    CATEGORY TEXT,
    MODULE TEXT,
    SORT_ORDER INTEGER,
    PARENT_VALUE_ID TEXT,
    IS_DEFAULT TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE TEXT,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE TEXT,
    ROW_EFFECTIVE_DATE TEXT,
    ROW_EXPIRY_DATE TEXT,
    ROW_ID INTEGER
);

