CREATE TABLE TANK_INVENTORY
(
    TANK_INVENTORY_ID TEXT NOT NULL PRIMARY KEY,
    INVENTORY_DATE TEXT,
    TANK_BATTERY_ID TEXT,
    OPENING_INVENTORY NUMERIC(18,2),
    RECEIPTS NUMERIC(18,2),
    DELIVERIES NUMERIC(18,2),
    ADJUSTMENTS NUMERIC(18,2),
    SHRINKAGE NUMERIC(18,2),
    THEFT_LOSS NUMERIC(18,2),
    ACTUAL_CLOSING_INVENTORY NUMERIC(18,2),
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE TEXT,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE TEXT,
    ROW_EFFECTIVE_DATE TEXT,
    ROW_EXPIRY_DATE TEXT,
    ROW_ID INTEGER
);

