raiserror ('CREATING TABLE SALES_AGREEMENT', 10,1) with nowait

CREATE TABLE SALES_AGREEMENT
(
    AGREEMENT_ID NVARCHAR(40),
    AGREEMENT_NAME NVARCHAR(255),
    SELLER_BA_ID NVARCHAR(40),
    PURCHASER_BA_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRATION_DATE DATETIME,
    PRICING_METHOD NVARCHAR(255),
    BASE_PRICE NUMERIC(18,2),
    PRICE_INDEX NVARCHAR(255),
    DIFFERENTIAL NUMERIC(18,2),
    PAYMENT_TERMS_DAYS INT,
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
