raiserror ('CREATING TABLE STORAGE_AGREEMENT', 10,1) with nowait

CREATE TABLE STORAGE_AGREEMENT
(
    AGREEMENT_ID NVARCHAR(40),
    STORAGE_FACILITY_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRATION_DATE DATETIME,
    STORAGE_FEE NUMERIC(18,2),
    RESERVED_CAPACITY NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EXPIRY_DATE DATETIME
);
