ALTER TABLE TRANSPORTATION_AGREEMENT
ADD CONSTRAINT FK_TRANSPORTATION_AGREEMENT_AGREEMENT FOREIGN KEY (AGREEMENT_ID) REFERENCES AGREEMENT(AGREEMENT_ID);

ALTER TABLE TRANSPORTATION_AGREEMENT
ADD CONSTRAINT FK_TRANSPORTATION_AGREEMENT_CARRIER_BA FOREIGN KEY (CARRIER_BA_ID) REFERENCES CARRIER_BA(CARRIER_BA_ID);
