raiserror ('CREATING TABLE TRANSPORTATION_AGREEMENT', 10,1) with nowait

CREATE TABLE TRANSPORTATION_AGREEMENT
(
    AGREEMENT_ID NVARCHAR(40),
    CARRIER_BA_ID NVARCHAR(40),
    ORIGIN_POINT NVARCHAR(255),
    DESTINATION_POINT NVARCHAR(255),
    EFFECTIVE_DATE DATETIME,
    EXPIRATION_DATE DATETIME,
    TARIFF_RATE NUMERIC(18,2),
    MINIMUM_VOLUME_COMMITMENT NUMERIC(18,2),
    MAXIMUM_CAPACITY NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
