CREATE TABLE `EXPLORATION_BUDGET`
(
    `PROGRAM_ID` VARCHAR(40),
    `BUDGET_YEAR` DECIMAL(18,2) NOT NULL,
    `BUDGET_AMOUNT` DECIMAL(18,2),
    `BUDGET_CURRENCY` VARCHAR(255),
    `BUDGET_CATEGORY` VARCHAR(255),
    `ACTUAL_AMOUNT` DECIMAL(18,2),
    `VARIANCE` DECIMAL(18,2),
    `DESCRIPTION` VARCHAR(2000),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `EFFECTIVE_DATE` DATETIME,
    `EXPIRY_DATE` DATETIME,
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_QUALITY` VARCHAR(40)
);
