-- EXPLORATION_COSTS Table Creation Script
-- SQL Server Version

CREATE TABLE EXPLORATION_COSTS
(
    EXPLORATION_COST_ID NVARCHAR(40) NOT NULL,
    PROPERTY_ID NVARCHAR(40),
    GEOLOGICAL_GEOPHYSICAL_COSTS NUMERIC(18,2),
    EXPLORATORY_DRILLING_COSTS NUMERIC(18,2),
    EXPLORATORY_WELL_EQUIPMENT NUMERIC(18,2),
    TOTAL_EXPLORATION_COSTS NUMERIC(18,2),
    COST_DATE DATETIME,
    WELL_ID NVARCHAR(40),
    IS_DRY_HOLE NVARCHAR(1),
    FOUND_PROVED_RESERVES NVARCHAR(1),
    IS_DEFERRED_CLASSIFICATION NVARCHAR(1),
    COST_CENTER_ID NVARCHAR(40),
    ACTIVE_IND NVARCHAR(1),
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(4000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(40),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);

-- Primary Key
ALTER TABLE EXPLORATION_COSTS
ADD CONSTRAINT PK_EXPLORATION_COSTS PRIMARY KEY (EXPLORATION_COST_ID);

-- Foreign Keys
ALTER TABLE EXPLORATION_COSTS
ADD CONSTRAINT FK_EXPLORATION_COSTS_PROPERTY FOREIGN KEY (PROPERTY_ID) REFERENCES UNPROVED_PROPERTY(PROPERTY_ID);

ALTER TABLE EXPLORATION_COSTS
ADD CONSTRAINT FK_EXPLORATION_COSTS_COST_CENTER FOREIGN KEY (COST_CENTER_ID) REFERENCES COST_CENTER(COST_CENTER_ID);

-- Indexes
CREATE INDEX IX_EXPLORATION_COSTS_PROPERTY ON EXPLORATION_COSTS(PROPERTY_ID);
CREATE INDEX IX_EXPLORATION_COSTS_COST_CENTER ON EXPLORATION_COSTS(COST_CENTER_ID);
CREATE INDEX IX_EXPLORATION_COSTS_COST_DATE ON EXPLORATION_COSTS(COST_DATE);
CREATE INDEX IX_EXPLORATION_COSTS_WELL ON EXPLORATION_COSTS(WELL_ID);

