ALTER TABLE `PROSPECT_ANALOG`
ADD CONSTRAINT FK_PROSPECT_ANALOG_PROSPECT FOREIGN KEY (`PROSPECT_ID`) REFERENCES `PROSPECT`(`PROSPECT_ID`);

ALTER TABLE `PROSPECT_ANALOG`
ADD CONSTRAINT FK_PROSPECT_ANALOG_ANALOG FOREIGN KEY (`ANALOG_ID`) REFERENCES `ANALOG`(`ANALOG_ID`);

ALTER TABLE `PROSPECT_ANALOG`
ADD CONSTRAINT FK_PROSPECT_ANALOG_ANALOG_PROSPECT FOREIGN KEY (`ANALOG_PROSPECT_ID`) REFERENCES `ANALOG_PROSPECT`(`ANALOG_PROSPECT_ID`);

ALTER TABLE `PROSPECT_ANALOG`
ADD CONSTRAINT FK_PROSPECT_ANALOG_ANALOG_FIELD FOREIGN KEY (`ANALOG_FIELD_ID`) REFERENCES `ANALOG_FIELD`(`ANALOG_FIELD_ID`);
