ALTER TABLE `PROSPECT_SOURCE_ROCK`
ADD CONSTRAINT FK_PROSPECT_SOURCE_ROCK_PROSPECT FOREIGN KEY (`PROSPECT_ID`) REFERENCES `PROSPECT`(`PROSPECT_ID`);

ALTER TABLE `PROSPECT_SOURCE_ROCK`
ADD CONSTRAINT FK_PROSPECT_SOURCE_ROCK_SOURCE FOREIGN KEY (`SOURCE_ID`) REFERENCES `SOURCE`(`SOURCE_ID`);

ALTER TABLE `PROSPECT_SOURCE_ROCK`
ADD CONSTRAINT FK_PROSPECT_SOURCE_ROCK_STRAT_UNIT FOREIGN KEY (`STRAT_UNIT_ID`) REFERENCES `STRAT_UNIT`(`STRAT_UNIT_ID`);
