raiserror ('CREATING TABLE PLUNGER_LIFT_CYCLE_POINT', 10,1) with nowait

CREATE TABLE PLUNGER_LIFT_CYCLE_POINT
(
    PLUNGER_LIFT_CYCLE_POINT_ID NVARCHAR(40) NOT NULL,
    PLUNGER_LIFT_CYCLE_RESULT_ID NVARCHAR(40),
    TIME NUMERIC(18,2),
    PHASE NVARCHAR(255),
    PLUNGER_DEPTH NUMERIC(18,2),
    CASING_PRESSURE NUMERIC(18,2),
    TUBING_PRESSURE NUMERIC(18,2),
    PRODUCTION_RATE NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
