raiserror ('CREATING TABLE PLUNGER_LIFT_GAS_REQUIREMENTS', 10,1) with nowait

CREATE TABLE PLUNGER_LIFT_GAS_REQUIREMENTS
(
    PLUNGER_LIFT_GAS_REQUIREMENTS_ID NVARCHAR(40) NOT NULL,
    PLUNGER_LIFT_WELL_PROPERTIES_ID NVARCHAR(40),
    REQUIRED_GAS_INJECTION_RATE NUMERIC(18,2),
    AVAILABLE_GAS NUMERIC(18,2),
    ADDITIONAL_GAS_REQUIRED NUMERIC(18,2),
    REQUIRED_GAS_LIQUID_RATIO NUMERIC(18,6),
    MINIMUM_CASING_PRESSURE NUMERIC(18,2),
    MAXIMUM_CASING_PRESSURE NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
