raiserror ('CREATING TABLE PLUNGER_LIFT_WELL_PROPERTIES', 10,1) with nowait

CREATE TABLE PLUNGER_LIFT_WELL_PROPERTIES
(
    PLUNGER_LIFT_WELL_PROPERTIES_ID NVARCHAR(40) NOT NULL,
    WELL_DEPTH NUMERIC(18,2),
    TUBING_DIAMETER NUMERIC(18,2),
    PLUNGER_DIAMETER NUMERIC(18,2),
    WELLHEAD_PRESSURE NUMERIC(18,2),
    CASING_PRESSURE NUMERIC(18,2),
    BOTTOM_HOLE_PRESSURE NUMERIC(18,2),
    WELLHEAD_TEMPERATURE NUMERIC(18,2),
    BOTTOM_HOLE_TEMPERATURE NUMERIC(18,2),
    OIL_GRAVITY NUMERIC(18,2),
    WATER_CUT NUMERIC(18,2),
    GAS_OIL_RATIO NUMERIC(18,6),
    GAS_SPECIFIC_GRAVITY NUMERIC(18,2),
    LIQUID_PRODUCTION_RATE NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
