CREATE TABLE "ADDRESS"
(
    "ADDRESS_ID" VARCHAR(40) NOT NULL,
    "OWNER_INFORMATION_ID" VARCHAR(40),
    "STREET_ADDRESS" VARCHAR(255),
    "CITY" VARCHAR(255),
    "STATE" VARCHAR(255),
    "ZIP_CODE" VARCHAR(255),
    "COUNTRY" VARCHAR(255),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
