CREATE TABLE "AP_PAYMENT"
(
    "AP_PAYMENT_ID" VARCHAR(40) NOT NULL,
    "AP_INVOICE_ID" VARCHAR(40),
    "PAYMENT_NUMBER" VARCHAR(255),
    "PAYMENT_DATE" TIMESTAMP,
    "PAYMENT_AMOUNT" NUMERIC(18,2),
    "PAYMENT_METHOD" VARCHAR(255),
    "CHECK_NUMBER" VARCHAR(255),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40),
    "PAYMENT_STATUS" VARCHAR(50)
);
