CREATE TABLE "AR_INVOICE"
(
    "AR_INVOICE_ID" VARCHAR(40) NOT NULL,
    "INVOICE_NUMBER" VARCHAR(255),
    "CUSTOMER_BA_ID" VARCHAR(40),
    "INVOICE_DATE" TIMESTAMP,
    "DUE_DATE" TIMESTAMP,
    "TOTAL_AMOUNT" NUMERIC(18,2),
    "PAID_AMOUNT" NUMERIC(18,2),
    "BALANCE_DUE" NUMERIC(18,2),
    "STATUS" VARCHAR(50),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
