CREATE TABLE "CEILING_TEST_CALCULATION"
(
    "CEILING_TEST_CALCULATION_ID" VARCHAR(40) NOT NULL,
    "PROPERTY_ID" VARCHAR(40),
    "CALCULATION_DATE" TIMESTAMP,
    "NET_CAPITALIZED_COST" NUMERIC(18,2),
    "DISCOUNTED_FUTURE_NET_CASH_FLOWS" NUMERIC(18,2),
    "CEILING_VALUE" NUMERIC(18,2),
    "IMPAIRMENT_AMOUNT" NUMERIC(18,2),
    "DISCOUNT_RATE" NUMERIC(18,2),
    "DESCRIPTION" VARCHAR(2000),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
