ALTER TABLE "DEPLETION_CALCULATION"
ADD CONSTRAINT FK_DEPLETION_CALCULATION_DEPLETION FOREIGN KEY ("DEPLETION_ID") REFERENCES "DEPLETION"("DEPLETION_ID");

ALTER TABLE "DEPLETION_CALCULATION"
ADD CONSTRAINT FK_DEPLETION_CALCULATION_PROPERTY FOREIGN KEY ("PROPERTY_ID") REFERENCES "PROPERTY"("PROPERTY_ID");

ALTER TABLE "DEPLETION_CALCULATION"
ADD CONSTRAINT FK_DEPLETION_CALCULATION_WELL FOREIGN KEY ("WELL_ID") REFERENCES "WELL"("WELL_ID");

ALTER TABLE "DEPLETION_CALCULATION"
ADD CONSTRAINT FK_DEPLETION_CALCULATION_POOL FOREIGN KEY ("POOL_ID") REFERENCES "POOL"("POOL_ID");

ALTER TABLE "DEPLETION_CALCULATION"
ADD CONSTRAINT FK_DEPLETION_CALCULATION_FIELD FOREIGN KEY ("FIELD_ID") REFERENCES "FIELD"("FIELD_ID");
