CREATE TABLE "EXCHANGE_CONTRACT"
(
    "CONTRACT_ID" VARCHAR(40),
    "CONTRACT_NAME" VARCHAR(255),
    "CONTRACT_TYPE" VARCHAR(50),
    "PARTIES_JSON" VARCHAR(255),
    "EFFECTIVE_DATE" TIMESTAMP,
    "EXPIRATION_DATE" TIMESTAMP,
    "EXCHANGE_TERMS_JSON" VARCHAR(255),
    "DELIVERY_POINTS_JSON" VARCHAR(255),
    "PRICING_TERMS_JSON" VARCHAR(255),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
