CREATE TABLE "EXCHANGE_TERMS"
(
    "EXCHANGE_TERMS_ID" VARCHAR(40) NOT NULL,
    "EXCHANGE_CONTRACT_ID" VARCHAR(40),
    "EXCHANGE_RATIO" NUMERIC(18,6),
    "MINIMUM_VOLUME" NUMERIC(18,2),
    "MAXIMUM_VOLUME" NUMERIC(18,2),
    "QUALITY_SPECIFICATIONS" VARCHAR(40),
    "NOTICE_PERIOD_DAYS" INTEGER,
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
