CREATE TABLE "IMBALANCE_RECONCILIATION"
(
    "IMBALANCE_RECONCILIATION_ID" VARCHAR(40) NOT NULL,
    "RECONCILIATION_DATE" TIMESTAMP,
    "TOTAL_IMBALANCE_BEFORE" NUMERIC(18,2),
    "TOTAL_ADJUSTMENTS" NUMERIC(18,2),
    "TOTAL_IMBALANCE_AFTER" NUMERIC(18,2),
    "RECONCILED_BY" VARCHAR(255),
    "NOTES" VARCHAR(2000),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
