CREATE TABLE "INVENTORY_ITEM"
(
    "INVENTORY_ITEM_ID" VARCHAR(40) NOT NULL,
    "ITEM_NUMBER" VARCHAR(255),
    "ITEM_NAME" VARCHAR(255),
    "ITEM_TYPE" VARCHAR(50),
    "UNIT_OF_MEASURE" VARCHAR(255),
    "QUANTITY_ON_HAND" NUMERIC(18,2),
    "UNIT_COST" NUMERIC(18,2),
    "TOTAL_VALUE" NUMERIC(18,2),
    "VALUATION_METHOD" VARCHAR(255),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
