CREATE TABLE "INVENTORY_VALUATION"
(
    "INVENTORY_VALUATION_ID" VARCHAR(40) NOT NULL,
    "INVENTORY_ITEM_ID" VARCHAR(40),
    "VALUATION_DATE" TIMESTAMP,
    "VALUATION_METHOD" VARCHAR(255),
    "QUANTITY" NUMERIC(18,2),
    "UNIT_COST" NUMERIC(18,2),
    "TOTAL_VALUE" NUMERIC(18,2),
    "DESCRIPTION" VARCHAR(2000),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
