CREATE TABLE "INVOICE_LINE_ITEM"
(
    "INVOICE_LINE_ITEM_ID" VARCHAR(40) NOT NULL,
    "INVOICE_ID" VARCHAR(40),
    "LINE_NUMBER" INTEGER,
    "ITEM_DESCRIPTION" VARCHAR(2000),
    "QUANTITY" NUMERIC(18,2),
    "UNIT_PRICE" NUMERIC(18,2),
    "LINE_TOTAL" NUMERIC(18,2),
    "GL_ACCOUNT_ID" VARCHAR(40),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
