CREATE TABLE "JIB_CREDIT"
(
    "JIB_CREDIT_ID" VARCHAR(40) NOT NULL,
    "JOINT_INTEREST_STATEMENT_ID" VARCHAR(40),
    "DESCRIPTION" VARCHAR(2000),
    "AMOUNT" NUMERIC(18,2),
    "CATEGORY" VARCHAR(255),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
