ALTER TABLE "JOIB_LINE_ITEM"
ADD CONSTRAINT FK_JOIB_LINE_ITEM_JOINT_INTEREST_BILL FOREIGN KEY ("JOINT_INTEREST_BILL_ID") REFERENCES "JOINT_INTEREST_BILL"("JOINT_INTEREST_BILL_ID");

ALTER TABLE "JOIB_LINE_ITEM"
ADD CONSTRAINT FK_JOIB_LINE_ITEM_PROPERTY FOREIGN KEY ("PROPERTY_ID") REFERENCES "PROPERTY"("PROPERTY_ID");

ALTER TABLE "JOIB_LINE_ITEM"
ADD CONSTRAINT FK_JOIB_LINE_ITEM_WELL FOREIGN KEY ("WELL_ID") REFERENCES "WELL"("WELL_ID");
