ALTER TABLE "JOIB_ALLOCATION"
ADD CONSTRAINT FK_JOIB_ALLOCATION_JOINT_INTEREST_BILL FOREIGN KEY ("JOINT_INTEREST_BILL_ID") REFERENCES "JOINT_INTEREST_BILL"("JOINT_INTEREST_BILL_ID");

ALTER TABLE "JOIB_ALLOCATION"
ADD CONSTRAINT FK_JOIB_ALLOCATION_JOIB_LINE_ITEM FOREIGN KEY ("JOIB_LINE_ITEM_ID") REFERENCES "JOIB_LINE_ITEM"("JOIB_LINE_ITEM_ID");

ALTER TABLE "JOIB_ALLOCATION"
ADD CONSTRAINT FK_JOIB_ALLOCATION_INTEREST_OWNER_BA FOREIGN KEY ("INTEREST_OWNER_BA_ID") REFERENCES "INTEREST_OWNER_BA"("INTEREST_OWNER_BA_ID");
