CREATE TABLE "JOURNAL_ENTRY_LINE"
(
    "JOURNAL_ENTRY_LINE_ID" VARCHAR(40) NOT NULL,
    "JOURNAL_ENTRY_ID" VARCHAR(40),
    "GL_ACCOUNT_ID" VARCHAR(40),
    "LINE_NUMBER" INTEGER,
    "DEBIT_AMOUNT" NUMERIC(18,2),
    "CREDIT_AMOUNT" NUMERIC(18,2),
    "DESCRIPTION" VARCHAR(2000),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
