CREATE TABLE "MEASUREMENT_ACCURACY"
(
    "MEASUREMENT_ACCURACY_ID" VARCHAR(40) NOT NULL,
    "MINIMUM_ACCURACY" NUMERIC(18,2),
    "MAXIMUM_ERROR" NUMERIC(18,2),
    "CALIBRATION_REQUIRED" VARCHAR(255),
    "CALIBRATION_FREQUENCY_DAYS" INTEGER,
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
