CREATE TABLE "PRODUCTION_AVAILS"
(
    "PRODUCTION_AVAILS_ID" VARCHAR(40) NOT NULL,
    "PERIOD_START" TIMESTAMP,
    "PERIOD_END" TIMESTAMP,
    "ESTIMATED_PRODUCTION" NUMERIC(18,2),
    "AVAILABLE_FOR_DELIVERY" NUMERIC(18,2),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
