CREATE TABLE "PRODUCTION_REPORT_SUMMARY"
(
    "PRODUCTION_REPORT_SUMMARY_ID" VARCHAR(40) NOT NULL,
    "TOTAL_PRODUCTION" NUMERIC(18,2),
    "PRODUCING_DAYS" INTEGER,
    "AVERAGE_DAILY_PRODUCTION" NUMERIC(18,2),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
