CREATE TABLE "QUALITY_ADJUSTMENTS"
(
    "QUALITY_ADJUSTMENTS_ID" VARCHAR(40) NOT NULL,
    "API_GRAVITY_ADJUSTMENT" NUMERIC(18,2),
    "SULFUR_ADJUSTMENT" NUMERIC(18,2),
    "BSW_ADJUSTMENT" NUMERIC(18,2),
    "OTHER_ADJUSTMENTS" NUMERIC(18,2),
    "TOTAL_ADJUSTMENT" NUMERIC(18,2),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
