CREATE TABLE "RECEIVABLE"
(
    "RECEIVABLE_ID" VARCHAR(40) NOT NULL,
    "TRANSACTION_ID" VARCHAR(40),
    "CUSTOMER" VARCHAR(255),
    "INVOICE_NUMBER" VARCHAR(255),
    "INVOICE_DATE" TIMESTAMP,
    "DUE_DATE" TIMESTAMP,
    "ORIGINAL_AMOUNT" NUMERIC(18,2),
    "AMOUNT_PAID" NUMERIC(18,2),
    "STATUS" VARCHAR(50),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
