-- REGULATED_PRICE Table Creation Script
-- SQL Server Version

CREATE TABLE REGULATED_PRICE
(
    REGULATED_PRICE_ID NVARCHAR(40) NOT NULL,
    REGULATORY_AUTHORITY NVARCHAR(255),
    PRICE_FORMULA NVARCHAR(4000),
    EFFECTIVE_START_DATE DATETIME,
    EFFECTIVE_END_DATE DATETIME,
    PRICE_CAP NUMERIC(18,2),
    PRICE_FLOOR NUMERIC(18,2),
    BASE_PRICE NUMERIC(18,2),
    ADJUSTMENT_FACTORS NVARCHAR(MAX),
    ACTIVE_IND NVARCHAR(1),
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(4000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(40),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);

-- Primary Key
ALTER TABLE REGULATED_PRICE
ADD CONSTRAINT PK_REGULATED_PRICE PRIMARY KEY (REGULATED_PRICE_ID);

-- Indexes
CREATE INDEX IX_REGULATED_PRICE_AUTHORITY ON REGULATED_PRICE(REGULATORY_AUTHORITY);
CREATE INDEX IX_REGULATED_PRICE_EFFECTIVE_START ON REGULATED_PRICE(EFFECTIVE_START_DATE);
CREATE INDEX IX_REGULATED_PRICE_EFFECTIVE_END ON REGULATED_PRICE(EFFECTIVE_END_DATE);

