ALTER TABLE "REVENUE_ALLOCATION"
ADD CONSTRAINT FK_REVENUE_ALLOCATION_REVENUE_TRANSACTION FOREIGN KEY ("REVENUE_TRANSACTION_ID") REFERENCES "REVENUE_TRANSACTION"("REVENUE_TRANSACTION_ID");

ALTER TABLE "REVENUE_ALLOCATION"
ADD CONSTRAINT FK_REVENUE_ALLOCATION_INTEREST_OWNER_BA FOREIGN KEY ("INTEREST_OWNER_BA_ID") REFERENCES "INTEREST_OWNER_BA"("INTEREST_OWNER_BA_ID");
