ALTER TABLE "REVENUE_TRANSACTION"
ADD CONSTRAINT FK_REVENUE_TRANSACTION_PROPERTY FOREIGN KEY ("PROPERTY_ID") REFERENCES "PROPERTY"("PROPERTY_ID");

ALTER TABLE "REVENUE_TRANSACTION"
ADD CONSTRAINT FK_REVENUE_TRANSACTION_WELL FOREIGN KEY ("WELL_ID") REFERENCES "WELL"("WELL_ID");

ALTER TABLE "REVENUE_TRANSACTION"
ADD CONSTRAINT FK_REVENUE_TRANSACTION_FIELD FOREIGN KEY ("FIELD_ID") REFERENCES "FIELD"("FIELD_ID");

ALTER TABLE "REVENUE_TRANSACTION"
ADD CONSTRAINT FK_REVENUE_TRANSACTION_CONTRACT FOREIGN KEY ("CONTRACT_ID") REFERENCES "CONTRACT"("CONTRACT_ID");
