CREATE TABLE "REVENUE_DISTRIBUTION"
(
    "REVENUE_DISTRIBUTION_ID" VARCHAR(40) NOT NULL,
    "REVENUE_TRANSACTION_ID" VARCHAR(40),
    "INT_SET_PARTNER_ID" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "BUSINESS_ASSOCIATE_ID" VARCHAR(40),
    "WORKING_INTEREST_PERCENTAGE" NUMERIC(18,6),
    "NET_REVENUE_INTEREST_PERCENTAGE" NUMERIC(18,6),
    "REVENUE_AMOUNT" NUMERIC(18,2) NOT NULL,
    "DESCRIPTION" VARCHAR(2000),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
