CREATE TABLE "ROYALTY_CALCULATION"
(
    "ROYALTY_CALCULATION_ID" VARCHAR(40) NOT NULL,
    "CALCULATION_DATE" TIMESTAMP,
    "PROPERTY_OR_LEASE_ID" VARCHAR(40),
    "GROSS_REVENUE" NUMERIC(18,2),
    "ROYALTY_DEDUCTIONS_ID" VARCHAR(40),
    "NET_REVENUE" NUMERIC(18,2),
    "ROYALTY_INTEREST" NUMERIC(18,2),
    "ROYALTY_AMOUNT" NUMERIC(18,2),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
