CREATE TABLE "ROYALTY_PAYMENT_DETAIL"
(
    "ROYALTY_PAYMENT_DETAIL_ID" VARCHAR(40) NOT NULL,
    "ROYALTY_PAYMENT_ID" VARCHAR(40),
    "REVENUE_TRANSACTION_ID" VARCHAR(40),
    "OIL_VOLUME" NUMERIC(18,2),
    "GAS_VOLUME" NUMERIC(18,2),
    "OIL_REVENUE" NUMERIC(18,2),
    "GAS_REVENUE" NUMERIC(18,2),
    "ROYALTY_AMOUNT" NUMERIC(18,2),
    "DESCRIPTION" VARCHAR(2000),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
