CREATE TABLE "ROYALTY_DEDUCTIONS"
(
    "ROYALTY_DEDUCTIONS_ID" VARCHAR(40) NOT NULL,
    "PRODUCTION_TAXES" NUMERIC(18,2),
    "TRANSPORTATION_COSTS" NUMERIC(18,2),
    "PROCESSING_COSTS" NUMERIC(18,2),
    "MARKETING_COSTS" NUMERIC(18,2),
    "OTHER_DEDUCTIONS" NUMERIC(18,2),
    "TOTAL_DEDUCTIONS" NUMERIC(18,2),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
