CREATE TABLE "ROYALTY_OWNER"
(
    "ROYALTY_OWNER_ID" VARCHAR(40) NOT NULL,
    "ROYALTY_OWNER_BA_ID" VARCHAR(40),
    "ROYALTY_OWNER_NAME" VARCHAR(255),
    "CONTACT_INFO" VARCHAR(255),
    "PAYMENT_METHOD" VARCHAR(255),
    "DESCRIPTION" VARCHAR(2000),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
