CREATE TABLE "TAX_WITHHOLDING"
(
    "TAX_WITHHOLDING_ID" VARCHAR(40) NOT NULL,
    "ROYALTY_PAYMENT_ID" VARCHAR(40),
    "WITHHOLDING_TYPE" VARCHAR(50),
    "WITHHOLDING_RATE" NUMERIC(18,2),
    "AMOUNT" NUMERIC(18,2),
    "REASON" VARCHAR(255),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
