CREATE TABLE "TRACT_ALLOCATION_DATA"
(
    "TRACT_ALLOCATION_DATA_ID" VARCHAR(40) NOT NULL,
    "TRACT_ID" VARCHAR(40),
    "UNIT_ID" VARCHAR(40),
    "TRACT_PARTICIPATION" NUMERIC(18,2),
    "WORKING_INTEREST" NUMERIC(18,2),
    "NET_REVENUE_INTEREST" NUMERIC(18,2),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
