CREATE TABLE "UNIT_PARTICIPANT"
(
    "UNIT_PARTICIPANT_ID" VARCHAR(40) NOT NULL,
    "UNIT_OPERATING_AGREEMENT_ID" VARCHAR(40),
    "COMPANY_NAME" VARCHAR(255),
    "WORKING_INTEREST" NUMERIC(18,2),
    "NET_REVENUE_INTEREST" NUMERIC(18,2),
    "IS_OPERATOR" VARCHAR(255),
    "VOTING_PERCENTAGE" NUMERIC(18,6),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
