CREATE TABLE "UNIT_OPERATING_AGREEMENT"
(
    "UNIT_OPERATING_AGREEMENT_ID" VARCHAR(40) NOT NULL,
    "UNIT_ID" VARCHAR(40),
    "VOTING_RIGHTS_ID" VARCHAR(40),
    "COST_SHARING_ID" VARCHAR(40),
    "REVENUE_SHARING_ID" VARCHAR(40),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
