ALTER TABLE "WELL_ALLOCATION_DATA"
ADD CONSTRAINT FK_WELL_ALLOCATION_DATA_WELL FOREIGN KEY ("WELL_ID") REFERENCES "WELL"("WELL_ID");

ALTER TABLE "WELL_ALLOCATION_DATA"
ADD CONSTRAINT FK_WELL_ALLOCATION_DATA_LEASE FOREIGN KEY ("LEASE_ID") REFERENCES "LEASE"("LEASE_ID");
