raiserror ('CREATING TABLE PRODUCTION_FORECAST', 10,1) with nowait

CREATE TABLE PRODUCTION_FORECAST
(
    PRODUCTION_FORECAST_ID NVARCHAR(40) NOT NULL,
    RESERVOIR_FORECAST_PROPERTIES_ID NVARCHAR(40),
    FORECAST_TYPE NVARCHAR(50),
    FORECAST_DURATION NUMERIC(18,6),
    INITIAL_PRODUCTION_RATE NUMERIC(18,2),
    FINAL_PRODUCTION_RATE NUMERIC(18,2),
    TOTAL_CUMULATIVE_PRODUCTION NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME
);
