raiserror ('CREATING TABLE PRODUCTION_FORECAST', 10,1) with nowait

CREATE TABLE PRODUCTION_FORECAST
(
    FORECAST_ID NVARCHAR(40),
    WELL_UWI NVARCHAR(255),
    FIELD_ID NVARCHAR(40),
    FORECAST_NAME NVARCHAR(255),
    FORECAST_TYPE NVARCHAR(50),
    FORECAST_START_DATE DATETIME,
    FORECAST_END_DATE DATETIME,
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30)
);
