ALTER TABLE PRODUCTION_FORECAST_POINT
ADD CONSTRAINT FK_PRODUCTION_FORECAST_POINT_FORECAST_POINT FOREIGN KEY (FORECAST_POINT_ID) REFERENCES FORECAST_POINT(FORECAST_POINT_ID);

ALTER TABLE PRODUCTION_FORECAST_POINT
ADD CONSTRAINT FK_PRODUCTION_FORECAST_POINT_FORECAST FOREIGN KEY (FORECAST_ID) REFERENCES FORECAST(FORECAST_ID);
