raiserror ('CREATING TABLE PRODUCTION_FORECAST_POINT', 10,1) with nowait

CREATE TABLE PRODUCTION_FORECAST_POINT
(
    FORECAST_POINT_ID NVARCHAR(40),
    FORECAST_ID NVARCHAR(40),
    FORECAST_DATE DATETIME,
    OIL_RATE NVARCHAR(255),
    GAS_RATE NVARCHAR(255),
    WATER_RATE NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30)
);
