raiserror ('CREATING TABLE RESERVOIR_FORECAST_PROPERTIES', 10,1) with nowait

CREATE TABLE RESERVOIR_FORECAST_PROPERTIES
(
    RESERVOIR_FORECAST_PROPERTIES_ID NVARCHAR(40) NOT NULL,
    INITIAL_PRESSURE NUMERIC(18,2),
    PERMEABILITY NUMERIC(18,2),
    THICKNESS NUMERIC(18,2),
    DRAINAGE_RADIUS NUMERIC(18,2),
    WELLBORE_RADIUS NUMERIC(18,2),
    FORMATION_VOLUME_FACTOR NUMERIC(18,2),
    OIL_VISCOSITY NUMERIC(18,2),
    TOTAL_COMPRESSIBILITY NUMERIC(18,2),
    POROSITY NUMERIC(18,2),
    SKIN_FACTOR NUMERIC(18,2),
    GAS_SPECIFIC_GRAVITY NUMERIC(18,2),
    TEMPERATURE NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME
);
