CREATE TABLE PRODUCTION_COSTS
(
    PRODUCTION_COST_ID TEXT,
    PROPERTY_ID TEXT,
    OPERATING_COSTS REAL,
    WORKOVER_COSTS REAL,
    MAINTENANCE_COSTS REAL,
    TOTAL_PRODUCTION_COSTS REAL,
    COST_PERIOD DATETIME,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
