CREATE TABLE CHART_CONFIGURATION
(
    CHART_CONFIGURATION_ID TEXT NOT NULL,
    CHART_TYPE TEXT,
    CONFIGURATION_NAME TEXT,
    CONFIGURATION_DATA TEXT,
    CREATED_BY TEXT,
    IS_DEFAULT TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
