CREATE TABLE ROYALTY_INTEREST
(
    ROYALTY_INTEREST_ID TEXT NOT NULL,
    PROPERTY_ID TEXT,
    ROYALTY_OWNER_BA_ID TEXT,
    INTEREST_TYPE TEXT,
    INTEREST_PERCENTAGE REAL,
    ROYALTY_RATE REAL,
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    DIVISION_ORDER_ID TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT
);
