CREATE TABLE ROYALTY_STATEMENT
(
    ROYALTY_STATEMENT_ID TEXT NOT NULL,
    ROYALTY_OWNER_BA_ID TEXT,
    PROPERTY_ID TEXT,
    STATEMENT_PERIOD_START DATETIME,
    STATEMENT_PERIOD_END DATETIME,
    TOTAL_ROYALTY_AMOUNT REAL,
    TOTAL_DEDUCTIONS REAL,
    NET_PAYMENT_AMOUNT REAL,
    STATEMENT_DATE DATETIME,
    STATUS TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
