CREATE TABLE EXPLORATION_BUDGET
(
    PROGRAM_ID TEXT,
    BUDGET_YEAR REAL NOT NULL,
    BUDGET_AMOUNT REAL,
    BUDGET_CURRENCY TEXT,
    BUDGET_CATEGORY TEXT,
    ACTUAL_AMOUNT REAL,
    VARIANCE REAL,
    DESCRIPTION TEXT,
    ACTIVE_IND TEXT,
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT
);
