CREATE TABLE PROSPECT_BA
(
    PROSPECT_ID TEXT,
    BUSINESS_ASSOCIATE_ID TEXT,
    ROLE_TYPE TEXT,
    WORKING_INTEREST REAL,
    CARRIED_INTEREST REAL,
    DESCRIPTION TEXT,
    ACTIVE_IND TEXT,
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT
);
