CREATE TABLE `EXPORT_HISTORY`
(
    `EXPORT_HISTORY_ID` VARCHAR(40) NOT NULL,
    `EXPORT_TYPE` VARCHAR(50),
    `EXPORT_FORMAT` VARCHAR(255),
    `EXPORT_DATE` DATETIME,
    `EXPORTED_BY` VARCHAR(255),
    `FILE_PATH` VARCHAR(255),
    `RECORD_COUNT` INT,
    `STATUS` VARCHAR(50),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME
);
