CREATE TABLE OWNERSHIP_INTEREST
(
    OWNERSHIP_INTEREST_ID TEXT NOT NULL,
    PROPERTY_ID TEXT,
    OWNER_BA_ID TEXT,
    WORKING_INTEREST REAL,
    NET_REVENUE_INTEREST REAL,
    ROYALTY_INTEREST REAL,
    OVERRIDING_ROYALTY_INTEREST REAL,
    EFFECTIVE_START_DATE DATETIME,
    EFFECTIVE_END_DATE DATETIME,
    DIVISION_ORDER_ID TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
