CREATE TABLE "EXCHANGE_COMMITMENT"
(
    "EXCHANGE_COMMITMENT_ID" VARCHAR2(40) NOT NULL,
    "EXCHANGE_CONTRACT_ID" VARCHAR2(40),
    "COMMITMENT_TYPE" VARCHAR2(50),
    "COMMITTED_VOLUME" NUMBER(18,2),
    "ACTUAL_VOLUME_DELIVERED" NUMBER(18,2),
    "DELIVERY_PERIOD_START" DATE,
    "DELIVERY_PERIOD_END" DATE,
    "STATUS" VARCHAR2(50),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE
);
