CREATE TABLE "EXCHANGE_CONTRACT"
(
    "EXCHANGE_CONTRACT_ID" VARCHAR2(40) NOT NULL,
    "CONTRACT_NUMBER" VARCHAR2(255),
    "COUNTERPARTY_BA_ID" VARCHAR2(40),
    "CONTRACT_TYPE" VARCHAR2(50),
    "COMMODITY_TYPE" VARCHAR2(50),
    "CONTRACT_DATE" DATE,
    "EFFECTIVE_DATE" DATE,
    "EXPIRY_DATE" DATE,
    "STATUS" VARCHAR2(50),
    "DESCRIPTION" VARCHAR2(2000),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE
);
