CREATE TABLE "EXCHANGE_TRANSACTION"
(
    "EXCHANGE_TRANSACTION_ID" VARCHAR2(40) NOT NULL,
    "EXCHANGE_CONTRACT_ID" VARCHAR2(40),
    "TRANSACTION_DATE" DATE,
    "RECEIPT_VOLUME" NUMBER(18,2),
    "RECEIPT_PRICE" NUMBER(18,2),
    "RECEIPT_LOCATION" VARCHAR2(255),
    "DELIVERY_VOLUME" NUMBER(18,2),
    "DELIVERY_PRICE" NUMBER(18,2),
    "DELIVERY_LOCATION" VARCHAR2(255),
    "STATUS" VARCHAR2(50),
    "DESCRIPTION" VARCHAR2(2000),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE
);
