CREATE TABLE `LACT_UNIT`
(
    `LACT_UNIT_ID` VARCHAR(40) NOT NULL,
    `LACT_NAME` VARCHAR(255),
    `SERVICE_UNIT_ID` VARCHAR(40),
    `METER_TYPE` VARCHAR(50),
    `MAXIMUM_FLOW_RATE` DECIMAL(18,2),
    `METER_FACTOR` DECIMAL(18,2),
    `LAST_CALIBRATION_DATE` DATETIME,
    `NEXT_CALIBRATION_DATE` DATETIME,
    `IS_ACTIVE` VARCHAR(255),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME
);
