CREATE TABLE `SERVICE_UNIT`
(
    `SERVICE_UNIT_ID` VARCHAR(40) NOT NULL,
    `UNIT_NAME` VARCHAR(255),
    `UNIT_TYPE` VARCHAR(50),
    `LEASE_ID` VARCHAR(40),
    `TANK_BATTERY_ID` VARCHAR(40),
    `OPERATOR_BA_ID` VARCHAR(40),
    `EFFECTIVE_DATE` DATETIME,
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME
);
