CREATE TABLE "ECONOMIC_CASH_FLOW"
(
    "ECONOMIC_CASH_FLOW_ID" VARCHAR2(40) NOT NULL,
    "ECONOMIC_ANALYSIS_ID" VARCHAR2(40),
    "PERIOD" NUMBER(10),
    "AMOUNT" NUMBER(18,2),
    "DESCRIPTION" VARCHAR2(2000),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_QUALITY" VARCHAR2(40)
);
