raiserror ('CREATING TABLE REGULATED_PRICE', 10,1) with nowait

CREATE TABLE REGULATED_PRICE
(
    REGULATED_PRICE_ID NVARCHAR(40) NOT NULL,
    REGULATORY_AUTHORITY NVARCHAR(255),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PRICE_VALUE NUMERIC(18,2),
    PRICE_CAP NUMERIC(18,2),
    PRICE_FLOOR NUMERIC(18,2),
    PRICE_FORMULA NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    EFFECTIVE_START_DATE DATETIME NOT NULL,
    EFFECTIVE_END_DATE DATETIME,
    BASE_PRICE NUMERIC(18,2) NOT NULL,
    ADJUSTMENT_FACTORS NVARCHAR(255)
);
