CREATE TABLE "GOVERNMENT_LEASE"
(
    "LEASE_ID" VARCHAR2(40),
    "PROPERTY_ID" VARCHAR2(40),
    "GOVERNMENT_AGENCY" VARCHAR2(255),
    "LEASE_NUMBER" VARCHAR2(255),
    "IS_FEDERAL" VARCHAR2(255),
    "IS_INDIAN" VARCHAR2(255),
    "EFFECTIVE_DATE" DATE,
    "EXPIRATION_DATE" DATE,
    "WORKING_INTEREST" NUMBER(18,2),
    "NET_REVENUE_INTEREST" NUMBER(18,2),
    "ROYALTY_RATE" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE
);
