CREATE TABLE `PERMISSION`
(
    `PERMISSION_ID` VARCHAR(40) NOT NULL,
    `PERMISSION_CODE` VARCHAR(255),
    `DESCRIPTION` VARCHAR(2000),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `ROW_QUALITY` VARCHAR(40),
    `PPDM_GUID` VARCHAR(40),
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `AREA_ID` VARCHAR(40),
    `AREA_TYPE` VARCHAR(50),
    `BUSINESS_ASSOCIATE_ID` VARCHAR(40),
    `EFFECTIVE_DATE` DATETIME,
    `EXPIRY_DATE` DATETIME,
    `SOURCE` VARCHAR(40),
    `REMARK` VARCHAR(2000)
);
