ALTER TABLE `PERMISSION`
ADD CONSTRAINT FK_PERMISSION_AREA FOREIGN KEY (`AREA_ID`) REFERENCES `AREA`(`AREA_ID`);

ALTER TABLE `PERMISSION`
ADD CONSTRAINT FK_PERMISSION_BUSINESS_ASSOCIATE FOREIGN KEY (`BUSINESS_ASSOCIATE_ID`) REFERENCES `BUSINESS_ASSOCIATE`(`BUSINESS_ASSOCIATE_ID`);
