CREATE TABLE `CHART_CONFIGURATION`
(
    `CHART_CONFIGURATION_ID` VARCHAR(40) NOT NULL,
    `CHART_TYPE` VARCHAR(50),
    `CONFIGURATION_NAME` VARCHAR(255),
    `CONFIGURATION_DATA` VARCHAR(255),
    `CREATED_BY` VARCHAR(30),
    `IS_DEFAULT` VARCHAR(255),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME
);
