raiserror ('CREATING TABLE FEE_MINERAL_LEASE', 10,1) with nowait

CREATE TABLE FEE_MINERAL_LEASE
(
    LEASE_ID NVARCHAR(40),
    PROPERTY_ID NVARCHAR(40),
    LEASE_NUMBER NVARCHAR(255),
    LEASE_NAME NVARCHAR(255),
    MINERAL_OWNER_BA_ID NVARCHAR(40),
    SURFACE_OWNER_BA_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRATION_DATE DATETIME,
    PRIMARY_TERM_MONTHS INT,
    WORKING_INTEREST NUMERIC(18,2),
    NET_REVENUE_INTEREST NUMERIC(18,2),
    ROYALTY_RATE NUMERIC(18,2),
    IS_HELD_BY_PRODUCTION NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
