raiserror ('CREATING TABLE GOVERNMENT_LEASE', 10,1) with nowait

CREATE TABLE GOVERNMENT_LEASE
(
    LEASE_ID NVARCHAR(40),
    PROPERTY_ID NVARCHAR(40),
    GOVERNMENT_AGENCY NVARCHAR(255),
    LEASE_NUMBER NVARCHAR(255),
    IS_FEDERAL NVARCHAR(255),
    IS_INDIAN NVARCHAR(255),
    EFFECTIVE_DATE DATETIME,
    EXPIRATION_DATE DATETIME,
    WORKING_INTEREST NUMERIC(18,2),
    NET_REVENUE_INTEREST NUMERIC(18,2),
    ROYALTY_RATE NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
