ALTER TABLE NET_PROFIT_LEASE
ADD CONSTRAINT FK_NET_PROFIT_LEASE_LEASE FOREIGN KEY (LEASE_ID) REFERENCES LEASE(LEASE_ID);

ALTER TABLE NET_PROFIT_LEASE
ADD CONSTRAINT FK_NET_PROFIT_LEASE_PROPERTY FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID);
