raiserror ('CREATING TABLE NET_PROFIT_LEASE', 10,1) with nowait

CREATE TABLE NET_PROFIT_LEASE
(
    LEASE_ID NVARCHAR(40),
    PROPERTY_ID NVARCHAR(40),
    LEASE_NUMBER NVARCHAR(255),
    LEASE_NAME NVARCHAR(255),
    NET_PROFIT_INTEREST NUMERIC(18,2),
    COSTS_RECOVERABLE NVARCHAR(255),
    RECOVERY_PERCENTAGE NUMERIC(18,6),
    EFFECTIVE_DATE DATETIME,
    EXPIRATION_DATE DATETIME,
    PRIMARY_TERM_MONTHS INT,
    WORKING_INTEREST NUMERIC(18,2),
    NET_REVENUE_INTEREST NUMERIC(18,2),
    ROYALTY_RATE NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EXPIRY_DATE DATETIME
);
