CREATE TABLE "ROD_SECTION"
(
    "ROD_SECTION_ID" VARCHAR2(40) NOT NULL,
    "SUCKER_ROD_STRING_ID" VARCHAR2(40),
    "DIAMETER" NUMBER(18,2),
    "LENGTH" NUMBER(18,2),
    "DENSITY" NUMBER(18,2),
    "WEIGHT" NUMBER(18,2),
    "SECTION_ORDER" NUMBER(10),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_QUALITY" VARCHAR2(40)
);
