CREATE TABLE `IMBALANCE`
(
    `IMBALANCE_ID` VARCHAR(40) NOT NULL,
    `NOMINATION_ID` VARCHAR(40),
    `PERIOD_START` DATETIME,
    `PERIOD_END` DATETIME,
    `NOMINATED_VOLUME` DECIMAL(18,2),
    `ACTUAL_VOLUME` DECIMAL(18,2),
    `IMBALANCE_AMOUNT` DECIMAL(18,2),
    `TOLERANCE_PERCENTAGE` DECIMAL(18,6),
    `STATUS` VARCHAR(50),
    `SETTLEMENT_DATE` DATETIME,
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME
);
