ALTER TABLE `MEASUREMENT_RECORD`
ADD CONSTRAINT FK_MEASUREMENT_RECORD_WELL FOREIGN KEY (`WELL_ID`) REFERENCES `WELL`(`WELL_ID`);

ALTER TABLE `MEASUREMENT_RECORD`
ADD CONSTRAINT FK_MEASUREMENT_RECORD_LEASE FOREIGN KEY (`LEASE_ID`) REFERENCES `LEASE`(`LEASE_ID`);
