ALTER TABLE `DECOMMISSIONING_STATUS`
ADD CONSTRAINT FK_DECOMMISSIONING_STATUS_FACILITY_DECOMMISSIONING FOREIGN KEY (`FACILITY_DECOMMISSIONING_ID`) REFERENCES `FACILITY_DECOMMISSIONING`(`FACILITY_DECOMMISSIONING_ID`);
