ALTER TABLE `ROYALTY_INTEREST`
ADD CONSTRAINT FK_ROYALTY_INTEREST_PROPERTY FOREIGN KEY (`PROPERTY_ID`) REFERENCES `PROPERTY`(`PROPERTY_ID`);

ALTER TABLE `ROYALTY_INTEREST`
ADD CONSTRAINT FK_ROYALTY_INTEREST_ROYALTY_OWNER_BA FOREIGN KEY (`ROYALTY_OWNER_BA_ID`) REFERENCES `ROYALTY_OWNER_BA`(`ROYALTY_OWNER_BA_ID`);

ALTER TABLE `ROYALTY_INTEREST`
ADD CONSTRAINT FK_ROYALTY_INTEREST_DIVISION_ORDER FOREIGN KEY (`DIVISION_ORDER_ID`) REFERENCES `DIVISION_ORDER`(`DIVISION_ORDER_ID`);
