ALTER TABLE `ROYALTY_CALCULATION`
ADD CONSTRAINT FK_ROYALTY_CALCULATION_PROPERTY FOREIGN KEY (`PROPERTY_ID`) REFERENCES `PROPERTY`(`PROPERTY_ID`);

ALTER TABLE `ROYALTY_CALCULATION`
ADD CONSTRAINT FK_ROYALTY_CALCULATION_REVENUE_TRANSACTION FOREIGN KEY (`REVENUE_TRANSACTION_ID`) REFERENCES `REVENUE_TRANSACTION`(`REVENUE_TRANSACTION_ID`);
