CREATE TABLE "CENTRIFUGAL_COMPRESSOR_PROPERTIES"
(
    "CENTRIFUGAL_COMPRESSOR_PROPERTIES_ID" VARCHAR2(40) NOT NULL,
    "COMPRESSOR_OPERATING_CONDITIONS_ID" VARCHAR2(40),
    "POLYTROPIC_EFFICIENCY" NUMBER(18,2),
    "SPECIFIC_HEAT_RATIO" NUMBER(18,6),
    "NUMBER_OF_STAGES" NUMBER(10),
    "SPEED" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_QUALITY" VARCHAR2(40)
);
