CREATE TABLE "COMPRESSOR_OPERATING_CONDITIONS"
(
    "COMPRESSOR_OPERATING_CONDITIONS_ID" VARCHAR2(40) NOT NULL,
    "SUCTION_PRESSURE" NUMBER(18,2),
    "DISCHARGE_PRESSURE" NUMBER(18,2),
    "SUCTION_TEMPERATURE" NUMBER(18,2),
    "DISCHARGE_TEMPERATURE" NUMBER(18,2),
    "GAS_FLOW_RATE" NUMBER(18,2),
    "GAS_SPECIFIC_GRAVITY" NUMBER(18,2),
    "GAS_MOLECULAR_WEIGHT" NUMBER(18,2),
    "COMPRESSOR_EFFICIENCY" NUMBER(18,2),
    "MECHANICAL_EFFICIENCY" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_QUALITY" VARCHAR2(40)
);
