CREATE TABLE "RECIPROCATING_COMPRESSOR_PROPERTIES"
(
    "RECIPROCATING_COMPRESSOR_PROPERTIES_ID" VARCHAR2(40) NOT NULL,
    "COMPRESSOR_OPERATING_CONDITIONS_ID" VARCHAR2(40),
    "CYLINDER_DIAMETER" NUMBER(18,2),
    "STROKE_LENGTH" NUMBER(18,2),
    "ROTATIONAL_SPEED" NUMBER(18,2),
    "NUMBER_OF_CYLINDERS" NUMBER(10),
    "VOLUMETRIC_EFFICIENCY" NUMBER(18,2),
    "CLEARANCE_FACTOR" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_QUALITY" VARCHAR2(40)
);
