CREATE TABLE "DEVELOPMENT_COSTS"
(
    "DEVELOPMENT_COST_ID" VARCHAR2(40),
    "PROPERTY_ID" VARCHAR2(40),
    "DEVELOPMENT_WELL_DRILLING_COSTS" NUMBER(18,2),
    "DEVELOPMENT_WELL_EQUIPMENT" NUMBER(18,2),
    "SUPPORT_EQUIPMENT_AND_FACILITIES" NUMBER(18,2),
    "SERVICE_WELL_COSTS" NUMBER(18,2),
    "TOTAL_DEVELOPMENT_COSTS" NUMBER(18,2),
    "COST_DATE" DATE,
    "COST_CENTER_ID" VARCHAR2(40),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_QUALITY" VARCHAR2(40),
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CREATED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_ID" VARCHAR2(40)
);
