ALTER TABLE "DEVELOPMENT_COSTS"
ADD CONSTRAINT FK_DEVELOPMENT_COSTS_DEVELOPMENT_COST FOREIGN KEY ("DEVELOPMENT_COST_ID") REFERENCES "DEVELOPMENT_COST"("DEVELOPMENT_COST_ID");

ALTER TABLE "DEVELOPMENT_COSTS"
ADD CONSTRAINT FK_DEVELOPMENT_COSTS_PROPERTY FOREIGN KEY ("PROPERTY_ID") REFERENCES "PROPERTY"("PROPERTY_ID");

ALTER TABLE "DEVELOPMENT_COSTS"
ADD CONSTRAINT FK_DEVELOPMENT_COSTS_COST_CENTER FOREIGN KEY ("COST_CENTER_ID") REFERENCES "COST_CENTER"("COST_CENTER_ID");
