raiserror ('CREATING TABLE APPLICATION_ATTACHMENT', 10,1) with nowait

CREATE TABLE APPLICATION_ATTACHMENT
(
    APPLICATION_ATTACHMENT_ID NVARCHAR(40) NOT NULL,
    PERMIT_APPLICATION_ID NVARCHAR(40),
    FILE_NAME NVARCHAR(255),
    FILE_TYPE NVARCHAR(50),
    FILE_SIZE BIGINT,
    UPLOAD_DATE DATETIME,
    DESCRIPTION NVARCHAR(2000),
    DOCUMENT_TYPE NVARCHAR(50),
    SEQUENCE_NUMBER INT,
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME
);
