raiserror ('CREATING TABLE DRILLING_PERMIT_APPLICATION', 10,1) with nowait

CREATE TABLE DRILLING_PERMIT_APPLICATION
(
    DRILLING_PERMIT_APPLICATION_ID NVARCHAR(40) NOT NULL,
    PERMIT_APPLICATION_ID NVARCHAR(40),
    WELL_UWI NVARCHAR(255),
    LEGAL_DESCRIPTION NVARCHAR(2000),
    TARGET_FORMATION NVARCHAR(255),
    PROPOSED_DEPTH NUMERIC(18,2),
    DRILLING_METHOD NVARCHAR(255),
    SURFACE_OWNER_NOTIFIED_IND NVARCHAR(255),
    SURFACE_OWNER_NOTIFICATION_DATE DATETIME,
    ENVIRONMENTAL_ASSESSMENT_REQUIRED_IND NVARCHAR(255),
    ENVIRONMENTAL_ASSESSMENT_REFERENCE NVARCHAR(255),
    SPACING_UNIT NVARCHAR(255),
    PERMIT_TYPE NVARCHAR(50),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME
);
