raiserror ('CREATING TABLE ENVIRONMENTAL_PERMIT_APPLICATION', 10,1) with nowait

CREATE TABLE ENVIRONMENTAL_PERMIT_APPLICATION
(
    ENVIRONMENTAL_PERMIT_APPLICATION_ID NVARCHAR(40) NOT NULL,
    PERMIT_APPLICATION_ID NVARCHAR(40),
    ENVIRONMENTAL_PERMIT_TYPE NVARCHAR(50),
    WASTE_TYPE NVARCHAR(50),
    WASTE_VOLUME NUMERIC(18,2),
    WASTE_VOLUME_UNIT NVARCHAR(255),
    DISPOSAL_METHOD NVARCHAR(255),
    ENVIRONMENTAL_IMPACT NVARCHAR(255),
    MONITORING_PLAN NVARCHAR(255),
    NORM_INVOLVED_IND NVARCHAR(255),
    FACILITY_LOCATION NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME
);
