raiserror ('CREATING TABLE INJECTION_PERMIT_APPLICATION', 10,1) with nowait

CREATE TABLE INJECTION_PERMIT_APPLICATION
(
    INJECTION_PERMIT_APPLICATION_ID NVARCHAR(40) NOT NULL,
    PERMIT_APPLICATION_ID NVARCHAR(40),
    INJECTION_TYPE NVARCHAR(50),
    INJECTION_ZONE NVARCHAR(255),
    INJECTION_FLUID NVARCHAR(255),
    MAXIMUM_INJECTION_PRESSURE NUMERIC(18,2),
    MAXIMUM_INJECTION_RATE NUMERIC(18,2),
    INJECTION_RATE_UNIT NVARCHAR(255),
    MONITORING_REQUIREMENTS NVARCHAR(255),
    INJECTION_WELL_UWI NVARCHAR(255),
    IS_CO2_STORAGE_IND NVARCHAR(255),
    IS_GAS_STORAGE_IND NVARCHAR(255),
    IS_BRINE_MINING_IND NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME
);
