ALTER TABLE JURISDICTION_REQUIREMENTS
ADD CONSTRAINT FK_JURISDICTION_REQUIREMENTS_AREA FOREIGN KEY (AREA_ID) REFERENCES AREA(AREA_ID);

ALTER TABLE JURISDICTION_REQUIREMENTS
ADD CONSTRAINT FK_JURISDICTION_REQUIREMENTS_BUSINESS_ASSOCIATE FOREIGN KEY (BUSINESS_ASSOCIATE_ID) REFERENCES BUSINESS_ASSOCIATE(BUSINESS_ASSOCIATE_ID);
