ALTER TABLE PERMIT_APPLICATION
ADD CONSTRAINT FK_PERMIT_APPLICATION_APPLICANT FOREIGN KEY (APPLICANT_ID) REFERENCES APPLICANT(APPLICANT_ID);

ALTER TABLE PERMIT_APPLICATION
ADD CONSTRAINT FK_PERMIT_APPLICATION_OPERATOR FOREIGN KEY (OPERATOR_ID) REFERENCES OPERATOR(OPERATOR_ID);

ALTER TABLE PERMIT_APPLICATION
ADD CONSTRAINT FK_PERMIT_APPLICATION_RELATED_FACILITY FOREIGN KEY (RELATED_FACILITY_ID) REFERENCES RELATED_FACILITY(RELATED_FACILITY_ID);

ALTER TABLE PERMIT_APPLICATION
ADD CONSTRAINT FK_PERMIT_APPLICATION_AREA FOREIGN KEY (AREA_ID) REFERENCES AREA(AREA_ID);

ALTER TABLE PERMIT_APPLICATION
ADD CONSTRAINT FK_PERMIT_APPLICATION_BUSINESS_ASSOCIATE FOREIGN KEY (BUSINESS_ASSOCIATE_ID) REFERENCES BUSINESS_ASSOCIATE(BUSINESS_ASSOCIATE_ID);
