raiserror ('CREATING TABLE REQUIRED_FORM', 10,1) with nowait

CREATE TABLE REQUIRED_FORM
(
    REQUIRED_FORM_ID NVARCHAR(40) NOT NULL,
    JURISDICTION_REQUIREMENTS_ID NVARCHAR(40),
    FORM_ID NVARCHAR(40),
    FORM_NAME NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    FORM_URL NVARCHAR(255),
    ONLINE_FILING_AVAILABLE_IND NVARCHAR(255),
    FORM_TYPE NVARCHAR(50),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME
);
