ALTER TABLE "DATA_QUALITY_DASHBOARD"
ADD CONSTRAINT FK_DATA_QUALITY_DASHBOARD_DASHBOARD FOREIGN KEY ("DASHBOARD_ID") REFERENCES "DASHBOARD"("DASHBOARD_ID");

ALTER TABLE "DATA_QUALITY_DASHBOARD"
ADD CONSTRAINT FK_DATA_QUALITY_DASHBOARD_CURRENT_METRICS FOREIGN KEY ("CURRENT_METRICS_ID") REFERENCES "CURRENT_METRICS"("CURRENT_METRICS_ID");

ALTER TABLE "DATA_QUALITY_DASHBOARD"
ADD CONSTRAINT FK_DATA_QUALITY_DASHBOARD_AREA FOREIGN KEY ("AREA_ID") REFERENCES "AREA"("AREA_ID");

ALTER TABLE "DATA_QUALITY_DASHBOARD"
ADD CONSTRAINT FK_DATA_QUALITY_DASHBOARD_BUSINESS_ASSOCIATE FOREIGN KEY ("BUSINESS_ASSOCIATE_ID") REFERENCES "BUSINESS_ASSOCIATE"("BUSINESS_ASSOCIATE_ID");
