ALTER TABLE "DATA_QUALITY_SCORE"
ADD CONSTRAINT FK_DATA_QUALITY_SCORE_QUALITY_SCORE FOREIGN KEY ("QUALITY_SCORE_ID") REFERENCES "QUALITY_SCORE"("QUALITY_SCORE_ID");

ALTER TABLE "DATA_QUALITY_SCORE"
ADD CONSTRAINT FK_DATA_QUALITY_SCORE_ENTITY FOREIGN KEY ("ENTITY_ID") REFERENCES "ENTITY"("ENTITY_ID");

ALTER TABLE "DATA_QUALITY_SCORE"
ADD CONSTRAINT FK_DATA_QUALITY_SCORE_AREA FOREIGN KEY ("AREA_ID") REFERENCES "AREA"("AREA_ID");

ALTER TABLE "DATA_QUALITY_SCORE"
ADD CONSTRAINT FK_DATA_QUALITY_SCORE_BUSINESS_ASSOCIATE FOREIGN KEY ("BUSINESS_ASSOCIATE_ID") REFERENCES "BUSINESS_ASSOCIATE"("BUSINESS_ASSOCIATE_ID");
