ALTER TABLE "DATA_VALIDATION_RULE"
ADD CONSTRAINT FK_DATA_VALIDATION_RULE_VALIDATION_RULE FOREIGN KEY ("VALIDATION_RULE_ID") REFERENCES "VALIDATION_RULE"("VALIDATION_RULE_ID");

ALTER TABLE "DATA_VALIDATION_RULE"
ADD CONSTRAINT FK_DATA_VALIDATION_RULE_AREA FOREIGN KEY ("AREA_ID") REFERENCES "AREA"("AREA_ID");

ALTER TABLE "DATA_VALIDATION_RULE"
ADD CONSTRAINT FK_DATA_VALIDATION_RULE_BUSINESS_ASSOCIATE FOREIGN KEY ("BUSINESS_ASSOCIATE_ID") REFERENCES "BUSINESS_ASSOCIATE"("BUSINESS_ASSOCIATE_ID");
