raiserror ('CREATING TABLE RECEIVABLE', 10,1) with nowait

CREATE TABLE RECEIVABLE
(
    RECEIVABLE_ID NVARCHAR(40) NOT NULL,
    SALES_TRANSACTION_ID NVARCHAR(40),
    CUSTOMER_BA_ID NVARCHAR(40),
    INVOICE_NUMBER NVARCHAR(255),
    INVOICE_DATE DATETIME,
    DUE_DATE DATETIME,
    ORIGINAL_AMOUNT NUMERIC(18,2),
    AMOUNT_PAID NUMERIC(18,2),
    OUTSTANDING_BALANCE NUMERIC(18,2),
    STATUS NVARCHAR(50),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
