ALTER TABLE RECEIVABLE
ADD CONSTRAINT FK_RECEIVABLE_SALES_TRANSACTION FOREIGN KEY (SALES_TRANSACTION_ID) REFERENCES SALES_TRANSACTION(SALES_TRANSACTION_ID);

ALTER TABLE RECEIVABLE
ADD CONSTRAINT FK_RECEIVABLE_CUSTOMER_BA FOREIGN KEY (CUSTOMER_BA_ID) REFERENCES CUSTOMER_BA(CUSTOMER_BA_ID);
