raiserror ('CREATING TABLE SALES_TRANSACTION', 10,1) with nowait

CREATE TABLE SALES_TRANSACTION
(
    SALES_TRANSACTION_ID NVARCHAR(40) NOT NULL,
    RUN_TICKET_ID NVARCHAR(40),
    SALES_AGREEMENT_ID NVARCHAR(40),
    CUSTOMER_BA_ID NVARCHAR(40),
    SALES_DATE DATETIME,
    NET_VOLUME NUMERIC(18,2),
    PRICE_PER_BARREL NUMERIC(18,2),
    TOTAL_AMOUNT NUMERIC(18,2),
    TOTAL_COSTS NUMERIC(18,2),
    TOTAL_TAXES NUMERIC(18,2),
    NET_REVENUE NUMERIC(18,2),
    STATUS NVARCHAR(50),
    APPROVAL_STATUS NVARCHAR(50),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
