ALTER TABLE `APPLICATION_COMPONENT`
ADD CONSTRAINT FK_APPLICATION_COMPONENT_PERMIT_APPLICATION FOREIGN KEY (`PERMIT_APPLICATION_ID`) REFERENCES `PERMIT_APPLICATION`(`PERMIT_APPLICATION_ID`);

ALTER TABLE `APPLICATION_COMPONENT`
ADD CONSTRAINT FK_APPLICATION_COMPONENT_AREA FOREIGN KEY (`AREA_ID`) REFERENCES `AREA`(`AREA_ID`);

ALTER TABLE `APPLICATION_COMPONENT`
ADD CONSTRAINT FK_APPLICATION_COMPONENT_BUSINESS_ASSOCIATE FOREIGN KEY (`BUSINESS_ASSOCIATE_ID`) REFERENCES `BUSINESS_ASSOCIATE`(`BUSINESS_ASSOCIATE_ID`);
