CREATE TABLE `JURISDICTION_REQUIREMENTS`
(
    `JURISDICTION_REQUIREMENTS_ID` VARCHAR(40) NOT NULL,
    `COUNTRY` VARCHAR(255),
    `STATE_PROVINCE` VARCHAR(255),
    `REGULATORY_AUTHORITY` VARCHAR(255),
    `REQUIREMENTS_DESCRIPTION` VARCHAR(2000),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_QUALITY` VARCHAR(40),
    `AREA_ID` VARCHAR(40),
    `AREA_TYPE` VARCHAR(50),
    `BUSINESS_ASSOCIATE_ID` VARCHAR(40),
    `EFFECTIVE_DATE` DATETIME,
    `EXPIRY_DATE` DATETIME
);
