ALTER TABLE `REQUIRED_FORM`
ADD CONSTRAINT FK_REQUIRED_FORM_JURISDICTION_REQUIREMENTS FOREIGN KEY (`JURISDICTION_REQUIREMENTS_ID`) REFERENCES `JURISDICTION_REQUIREMENTS`(`JURISDICTION_REQUIREMENTS_ID`);

ALTER TABLE `REQUIRED_FORM`
ADD CONSTRAINT FK_REQUIRED_FORM_FORM FOREIGN KEY (`FORM_ID`) REFERENCES `FORM`(`FORM_ID`);

ALTER TABLE `REQUIRED_FORM`
ADD CONSTRAINT FK_REQUIRED_FORM_AREA FOREIGN KEY (`AREA_ID`) REFERENCES `AREA`(`AREA_ID`);

ALTER TABLE `REQUIRED_FORM`
ADD CONSTRAINT FK_REQUIRED_FORM_BUSINESS_ASSOCIATE FOREIGN KEY (`BUSINESS_ASSOCIATE_ID`) REFERENCES `BUSINESS_ASSOCIATE`(`BUSINESS_ASSOCIATE_ID`);
