CREATE TABLE "DEVELOPMENT_COSTS"
(
    "DEVELOPMENT_COST_ID" VARCHAR(40),
    "PROPERTY_ID" VARCHAR(40),
    "DEVELOPMENT_WELL_DRILLING_COSTS" NUMERIC(18,2),
    "DEVELOPMENT_WELL_EQUIPMENT" NUMERIC(18,2),
    "SUPPORT_EQUIPMENT_AND_FACILITIES" NUMERIC(18,2),
    "SERVICE_WELL_COSTS" NUMERIC(18,2),
    "TOTAL_DEVELOPMENT_COSTS" NUMERIC(18,2),
    "COST_DATE" TIMESTAMP,
    "COST_CENTER_ID" VARCHAR(40),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_QUALITY" VARCHAR(40),
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_ID" VARCHAR(40)
);
