ALTER TABLE "NODAL_OPERATING_POINT"
ADD CONSTRAINT FK_NODAL_OPERATING_POINT_NODAL_ANALYSIS_RESULT FOREIGN KEY ("NODAL_ANALYSIS_RESULT_ID") REFERENCES "NODAL_ANALYSIS_RESULT"("NODAL_ANALYSIS_RESULT_ID");

ALTER TABLE "NODAL_OPERATING_POINT"
ADD CONSTRAINT FK_NODAL_OPERATING_POINT_AREA FOREIGN KEY ("AREA_ID") REFERENCES "AREA"("AREA_ID");

ALTER TABLE "NODAL_OPERATING_POINT"
ADD CONSTRAINT FK_NODAL_OPERATING_POINT_BUSINESS_ASSOCIATE FOREIGN KEY ("BUSINESS_ASSOCIATE_ID") REFERENCES "BUSINESS_ASSOCIATE"("BUSINESS_ASSOCIATE_ID");
