CREATE TABLE LIST_OF_VALUE
(
    LIST_OF_VALUE_ID VARCHAR2(40) NOT NULL,
    VALUE_TYPE VARCHAR2(100) NOT NULL,
    VALUE_CODE VARCHAR2(100) NOT NULL,
    VALUE_NAME VARCHAR2(255),
    DESCRIPTION VARCHAR2(2000),
    CATEGORY VARCHAR2(100),
    MODULE VARCHAR2(100),
    SORT_ORDER NUMBER(10),
    PARENT_VALUE_ID VARCHAR2(40),
    IS_DEFAULT VARCHAR2(1),
    ACTIVE_IND VARCHAR2(1),
    PPDM_GUID VARCHAR2(38),
    REMARK VARCHAR2(2000),
    SOURCE VARCHAR2(40),
    ROW_QUALITY VARCHAR2(40),
    ROW_CREATED_BY VARCHAR2(30),
    ROW_CREATED_DATE DATE,
    ROW_CHANGED_BY VARCHAR2(30),
    ROW_CHANGED_DATE DATE,
    ROW_EFFECTIVE_DATE DATE,
    ROW_EXPIRY_DATE DATE,
    ROW_ID NUMBER(19)
);

