raiserror ('CREATING FOREIGN KEY CONSTRAINT ABANDONMENT_STATUS_WELL_ABANDONMENT_FK', 10, 1) with nowait
ALTER TABLE ABANDONMENT_STATUS ADD CONSTRAINT ABANDONMENT_STATUS_WELL_ABANDONMENT_FK FOREIGN KEY
(
	WELL_ABANDONMENT_ID
)
REFERENCES WELL_ABANDONMENT
(
	WELL_ABANDONMENT_ID
);

