raiserror ('CREATING INDEX UAA_USER_ID_IX', 10, 1) with nowait
CREATE INDEX UAA_USER_ID_IX ON USER_ASSET_ACCESS
(
	USER_ID
);

raiserror ('CREATING INDEX UAA_ORG_IX', 10, 1) with nowait
CREATE INDEX UAA_ORG_IX ON USER_ASSET_ACCESS
(
	ORGANIZATION_ID
);

raiserror ('CREATING INDEX UAA_ASSET_IX', 10, 1) with nowait
CREATE INDEX UAA_ASSET_IX ON USER_ASSET_ACCESS
(
	ASSET_TYPE,
	ASSET_ID
);

raiserror ('CREATING INDEX RP_ROLE_IX', 10, 1) with nowait
CREATE INDEX RP_ROLE_IX ON ROLE_PERMISSION
(
	ROLE_ID
);

raiserror ('CREATING INDEX RP_ORG_IX', 10, 1) with nowait
CREATE INDEX RP_ORG_IX ON ROLE_PERMISSION
(
	ORGANIZATION_ID
);

raiserror ('CREATING INDEX OHC_ORG_IX', 10, 1) with nowait
CREATE INDEX OHC_ORG_IX ON ORGANIZATION_HIERARCHY_CONFIG
(
	ORGANIZATION_ID
);

raiserror ('CREATING INDEX OHC_LEVEL_IX', 10, 1) with nowait
CREATE INDEX OHC_LEVEL_IX ON ORGANIZATION_HIERARCHY_CONFIG
(
	ORGANIZATION_ID,
	HIERARCHY_LEVEL
);

raiserror ('CREATING INDEX SWL_ORG_IX', 10, 1) with nowait
CREATE INDEX SWL_ORG_IX ON SETUP_WIZARD_LOG
(
	ORGANIZATION_ID
);

raiserror ('CREATING INDEX SWL_DATE_IX', 10, 1) with nowait
CREATE INDEX SWL_DATE_IX ON SETUP_WIZARD_LOG
(
	EXECUTION_DATE
);
