raiserror ('CREATING FOREIGN KEY CONSTRAINT UAA_BA_FK', 10, 1) with nowait
ALTER TABLE USER_ASSET_ACCESS ADD CONSTRAINT UAA_BA_FK FOREIGN KEY 
(
	USER_ID
)
REFERENCES BUSINESS_ASSOCIATE
(
	BUSINESS_ASSOCIATE_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT UAA_BAO_FK', 10, 1) with nowait
ALTER TABLE USER_ASSET_ACCESS ADD CONSTRAINT UAA_BAO_FK FOREIGN KEY 
(
	ORGANIZATION_ID
)
REFERENCES BA_ORGANIZATION
(
	ORGANIZATION_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT RP_BAO_FK', 10, 1) with nowait
ALTER TABLE ROLE_PERMISSION ADD CONSTRAINT RP_BAO_FK FOREIGN KEY 
(
	ORGANIZATION_ID
)
REFERENCES BA_ORGANIZATION
(
	ORGANIZATION_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT OHC_BAO_FK', 10, 1) with nowait
ALTER TABLE ORGANIZATION_HIERARCHY_CONFIG ADD CONSTRAINT OHC_BAO_FK FOREIGN KEY 
(
	ORGANIZATION_ID
)
REFERENCES BA_ORGANIZATION
(
	ORGANIZATION_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT UP_BA_FK', 10, 1) with nowait
ALTER TABLE USER_PROFILE ADD CONSTRAINT UP_BA_FK FOREIGN KEY 
(
	USER_ID
)
REFERENCES BUSINESS_ASSOCIATE
(
	BUSINESS_ASSOCIATE_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT SWL_BAO_FK', 10, 1) with nowait
ALTER TABLE SETUP_WIZARD_LOG ADD CONSTRAINT SWL_BAO_FK FOREIGN KEY 
(
	ORGANIZATION_ID
)
REFERENCES BA_ORGANIZATION
(
	ORGANIZATION_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT SWL_BA_FK', 10, 1) with nowait
ALTER TABLE SETUP_WIZARD_LOG ADD CONSTRAINT SWL_BA_FK FOREIGN KEY 
(
	EXECUTED_BY
)
REFERENCES BUSINESS_ASSOCIATE
(
	BUSINESS_ASSOCIATE_ID
);
