raiserror ('CREATING PRIMARY KEY UAA_PK', 10, 1) with nowait
ALTER TABLE USER_ASSET_ACCESS ADD CONSTRAINT UAA_PK PRIMARY KEY
(
	USER_ID,
	ASSET_TYPE,
	ASSET_ID
);

raiserror ('CREATING PRIMARY KEY RP_PK', 10, 1) with nowait
ALTER TABLE ROLE_PERMISSION ADD CONSTRAINT RP_PK PRIMARY KEY
(
	ROLE_ID,
	PERMISSION_ID
);

raiserror ('CREATING PRIMARY KEY OHC_PK', 10, 1) with nowait
ALTER TABLE ORGANIZATION_HIERARCHY_CONFIG ADD CONSTRAINT OHC_PK PRIMARY KEY
(
	ORGANIZATION_ID,
	HIERARCHY_LEVEL
);

raiserror ('CREATING PRIMARY KEY UP_PK', 10, 1) with nowait
ALTER TABLE USER_PROFILE ADD CONSTRAINT UP_PK PRIMARY KEY
(
	USER_ID
);

raiserror ('CREATING PRIMARY KEY SWL_PK', 10, 1) with nowait
ALTER TABLE SETUP_WIZARD_LOG ADD CONSTRAINT SWL_PK PRIMARY KEY
(
	SETUP_LOG_ID
);
