raiserror ('CREATING TABLE USER_ASSET_ACCESS', 10,1) with nowait
CREATE TABLE user_asset_access
(
	USER_ID NVARCHAR(40) NOT NULL,
	ASSET_TYPE NVARCHAR(40) NOT NULL,
	ASSET_ID NVARCHAR(40) NOT NULL,
	ACCESS_LEVEL NVARCHAR(40),
	INHERIT_IND NVARCHAR(1),
	ORGANIZATION_ID NVARCHAR(40),
	ACTIVE_IND NVARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);

raiserror ('CREATING TABLE ROLE_PERMISSION', 10,1) with nowait
CREATE TABLE role_permission
(
	ROLE_ID NVARCHAR(40) NOT NULL,
	PERMISSION_ID NVARCHAR(40) NOT NULL,
	ORGANIZATION_ID NVARCHAR(40),
	ACTIVE_IND NVARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);

raiserror ('CREATING TABLE ORGANIZATION_HIERARCHY_CONFIG', 10,1) with nowait
CREATE TABLE organization_hierarchy_config
(
	ORGANIZATION_ID NVARCHAR(40) NOT NULL,
	HIERARCHY_LEVEL NUMERIC(8,0) NOT NULL,
	LEVEL_NAME NVARCHAR(255),
	ASSET_TYPE NVARCHAR(40),
	PARENT_LEVEL NUMERIC(8,0),
	ACTIVE_IND NVARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);

raiserror ('CREATING TABLE USER_PROFILE', 10,1) with nowait
CREATE TABLE user_profile
(
	USER_ID NVARCHAR(40) NOT NULL,
	PRIMARY_ROLE NVARCHAR(40),
	PREFERRED_LAYOUT NVARCHAR(40),
	USER_PREFERENCES NVARCHAR(MAX),
	LAST_LOGIN_DATE DATE,
	ACTIVE_IND NVARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);

raiserror ('CREATING TABLE SETUP_WIZARD_LOG', 10,1) with nowait
CREATE TABLE setup_wizard_log
(
	SETUP_LOG_ID NVARCHAR(40) NOT NULL,
	ORGANIZATION_ID NVARCHAR(40),
	SETUP_STEP NVARCHAR(255),
	SETUP_DATA NVARCHAR(MAX),
	EXECUTED_BY NVARCHAR(40),
	EXECUTION_DATE DATE,
	STATUS NVARCHAR(40),
	ERROR_MESSAGE NVARCHAR(MAX),
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);
