raiserror ('CREATING TABLE ACCOUNTING_AMORTIZATION', 10,1) with nowait
CREATE TABLE accounting_amortization
(
	ACCOUNTING_AMORTIZATION_ID NVARCHAR(40) NOT NULL,
	PROPERTY_ID NVARCHAR(40),
	WELL_ID NVARCHAR(40),
	POOL_ID NVARCHAR(40),
	FIELD_ID NVARCHAR(40),
	PERIOD_START_DATE DATE NOT NULL,
	PERIOD_END_DATE DATE NOT NULL,
	CAPITALIZED_COST NUMERIC(18,2) NOT NULL,
	PRODUCTION_BOE NUMERIC(18,2),
	TOTAL_RESERVES_BOE NUMERIC(18,2),
	AMORTIZATION_AMOUNT NUMERIC(18,2) NOT NULL,
	AMORTIZATION_METHOD NVARCHAR(40),  -- 'UNITS_OF_PRODUCTION'
	DESCRIPTION NVARCHAR(2000),
	ACTIVE_IND NVARCHAR(1),
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_ID NVARCHAR(40) NOT NULL,
	CONSTRAINT accounting_amortization_PK PRIMARY KEY (ACCOUNTING_AMORTIZATION_ID)
)

