raiserror ('CREATING TABLE ACCOUNTING_COST', 10,1) with nowait
CREATE TABLE accounting_cost
(
	ACCOUNTING_COST_ID NVARCHAR(40) NOT NULL,
	FINANCE_ID NVARCHAR(40),  -- Link to parent FINANCE transaction
	PROPERTY_ID NVARCHAR(40),
	WELL_ID NVARCHAR(40),
	FIELD_ID NVARCHAR(40),
	POOL_ID NVARCHAR(40),
	COST_TYPE NVARCHAR(40) NOT NULL,  -- 'EXPLORATION', 'DEVELOPMENT', 'PRODUCTION', 'ACQUISITION'
	COST_CATEGORY NVARCHAR(40),  -- 'G&G', 'DRILLING', 'FACILITY', etc.
	AMOUNT NUMERIC(18,2) NOT NULL,
	COST_DATE DATE,
	IS_CAPITALIZED NVARCHAR(1),
	IS_EXPENSED NVARCHAR(1),
	DRY_HOLE_FLAG NVARCHAR(1),
	DESCRIPTION NVARCHAR(2000),
	ACTIVE_IND NVARCHAR(1),
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_ID NVARCHAR(40) NOT NULL,
	CONSTRAINT accounting_cost_PK PRIMARY KEY (ACCOUNTING_COST_ID)
)

