raiserror ('CREATING TABLE ACCOUNTING_METHOD', 10,1) with nowait
CREATE TABLE accounting_method
(
	ACCOUNTING_METHOD_ID NVARCHAR(40) NOT NULL,
	FIELD_ID NVARCHAR(40),
	COST_CENTER_ID NVARCHAR(40),
	METHOD_TYPE NVARCHAR(40) NOT NULL,  -- 'SUCCESSFUL_EFFORTS' or 'FULL_COST'
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	DESCRIPTION NVARCHAR(2000),
	ACTIVE_IND NVARCHAR(1),
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_ID NVARCHAR(40) NOT NULL,
	CONSTRAINT accounting_method_PK PRIMARY KEY (ACCOUNTING_METHOD_ID)
)

