raiserror ('CREATING TABLE ASSET_RETIREMENT_OBLIGATION', 10,1) with nowait
CREATE TABLE asset_retirement_obligation
(
	ARO_ID NVARCHAR(40) NOT NULL,
	FIELD_ID NVARCHAR(40),
	WELL_ID NVARCHAR(40),
	FACILITY_ID NVARCHAR(40),
	ESTIMATED_COST NUMERIC(18,2) NOT NULL,
	ESTIMATED_RETIREMENT_DATE DATE,
	DISCOUNT_RATE NUMERIC(10,4),
	PRESENT_VALUE NUMERIC(18,2),
	ACCRETION_EXPENSE NUMERIC(18,2),
	STATUS NVARCHAR(40),  -- 'ACTIVE', 'SETTLED', 'CANCELLED'
	DESCRIPTION NVARCHAR(2000),
	ACTIVE_IND NVARCHAR(1),
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_ID NVARCHAR(40) NOT NULL,
	CONSTRAINT asset_retirement_obligation_PK PRIMARY KEY (ARO_ID)
)

