raiserror ('CREATING PRIMARY KEY DECOMMISSIONING_STATUS_PK', 10, 1) with nowait
ALTER TABLE DECOMMISSIONING_STATUS ADD CONSTRAINT DECOMMISSIONING_STATUS_PK PRIMARY KEY
(
	DECOMMISSIONING_STATUS_ID
);

