raiserror ('CREATING FOREIGN KEY CONSTRAINT DECOMMISSIONING_STATUS_FACILITY_DECOMMISSIONING_FK', 10, 1) with nowait
ALTER TABLE DECOMMISSIONING_STATUS ADD CONSTRAINT DECOMMISSIONING_STATUS_FACILITY_DECOMMISSIONING_FK FOREIGN KEY
(
	FACILITY_DECOMMISSIONING_ID
)
REFERENCES FACILITY_DECOMMISSIONING
(
	FACILITY_DECOMMISSIONING_ID
);

