raiserror ('CREATING TABLE DEPLETION_CALCULATION', 10,1) with nowait
CREATE TABLE depletion_calculation
(
	DEPLETION_ID NVARCHAR(40) NOT NULL,
	PROPERTY_ID NVARCHAR(40),
	WELL_ID NVARCHAR(40),
	POOL_ID NVARCHAR(40),
	FIELD_ID NVARCHAR(40),
	DEPLETION_METHOD NVARCHAR(40) NOT NULL,  -- 'COST_DEPLETION', 'PERCENTAGE_DEPLETION'
	COST_BASIS NUMERIC(18,2),
	ESTIMATED_RESERVES NUMERIC(18,2),
	PRODUCTION NUMERIC(18,2),
	DEPLETION_RATE NUMERIC(10,4),
	DEPLETION_AMOUNT NUMERIC(18,2),
	PERCENTAGE_RATE NUMERIC(10,4),  -- For percentage depletion
	PERIOD_START_DATE DATE,
	PERIOD_END_DATE DATE,
	DESCRIPTION NVARCHAR(2000),
	ACTIVE_IND NVARCHAR(1),
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_ID NVARCHAR(40) NOT NULL,
	CONSTRAINT depletion_calculation_PK PRIMARY KEY (DEPLETION_ID)
)

