raiserror ('CREATING TABLE EXPLORATION_PERMIT', 10,1) with nowait
CREATE TABLE exploration_permit
(
	PERMIT_ID NVARCHAR(40) NOT NULL,
	PERMIT_NUMBER NVARCHAR(40),
	FIELD_ID NVARCHAR(40),
	PERMIT_HOLDER NVARCHAR(40),
	PERMIT_START_DATE DATE,
	PERMIT_END_DATE DATE,
	PERMIT_AREA NUMERIC(18,5),
	PERMIT_AREA_OUOM NVARCHAR(40),
	PERMIT_TERMS NVARCHAR(2000),
	DESCRIPTION NVARCHAR(240),
	ACTIVE_IND NVARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);
