raiserror ('CREATING FOREIGN KEY CONSTRAINT EXPLORATION_PROGRAM_FIELD_FK', 10, 1) with nowait
ALTER TABLE EXPLORATION_PROGRAM ADD CONSTRAINT EXPLORATION_PROGRAM_FIELD_FK FOREIGN KEY
(
	FIELD_ID
)
REFERENCES FIELD
(
	FIELD_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT EXPLORATION_PROGRAM_OPERATOR_FK', 10, 1) with nowait
ALTER TABLE EXPLORATION_PROGRAM ADD CONSTRAINT EXPLORATION_PROGRAM_OPERATOR_FK FOREIGN KEY
(
	OPERATOR
)
REFERENCES BUSINESS_ASSOCIATE
(
	BUSINESS_ASSOCIATE_ID
);
