raiserror ('CREATING FOREIGN KEY CONSTRAINT EXPLORATION_PERMIT_FIELD_FK', 10, 1) with nowait
ALTER TABLE EXPLORATION_PERMIT ADD CONSTRAINT EXPLORATION_PERMIT_FIELD_FK FOREIGN KEY
(
	FIELD_ID
)
REFERENCES FIELD
(
	FIELD_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT EXPLORATION_PERMIT_HOLDER_FK', 10, 1) with nowait
ALTER TABLE EXPLORATION_PERMIT ADD CONSTRAINT EXPLORATION_PERMIT_HOLDER_FK FOREIGN KEY
(
	PERMIT_HOLDER
)
REFERENCES BUSINESS_ASSOCIATE
(
	BUSINESS_ASSOCIATE_ID
);
