raiserror ('CREATING TABLE EXPLORATION_BUDGET', 10,1) with nowait
CREATE TABLE exploration_budget
(
	PROGRAM_ID NVARCHAR(40) NOT NULL,
	BUDGET_YEAR NUMERIC(4,0) NOT NULL,
	BUDGET_AMOUNT NUMERIC(18,5),
	BUDGET_CURRENCY NVARCHAR(40),
	BUDGET_CATEGORY NVARCHAR(40),
	ACTUAL_AMOUNT NUMERIC(18,5),
	VARIANCE NUMERIC(18,5),
	DESCRIPTION NVARCHAR(240),
	ACTIVE_IND NVARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);
