raiserror ('CREATING TABLE EXPLORATION_PROGRAM', 10,1) with nowait
CREATE TABLE exploration_program
(
	PROGRAM_ID NVARCHAR(40) NOT NULL,
	PROGRAM_NAME NVARCHAR(255),
	FIELD_ID NVARCHAR(40),
	OPERATOR NVARCHAR(40),
	OBJECTIVES NVARCHAR(2000),
	PROGRAM_START_DATE DATE,
	PROGRAM_END_DATE DATE,
	BUDGET NUMERIC(18,5),
	BUDGET_CURRENCY NVARCHAR(40),
	DESCRIPTION NVARCHAR(240),
	ACTIVE_IND NVARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);
