raiserror ('CREATING FOREIGN KEY CONSTRAINT EXPLORATION_BUDGET_PROGRAM_FK', 10, 1) with nowait
ALTER TABLE EXPLORATION_BUDGET ADD CONSTRAINT EXPLORATION_BUDGET_PROGRAM_FK FOREIGN KEY
(
	PROGRAM_ID
)
REFERENCES EXPLORATION_PROGRAM
(
	PROGRAM_ID
);
