raiserror ('CREATING TABLE FIELD_PHASE', 10,1) with nowait
CREATE TABLE FIELD_PHASE
(
	FIELD_PHASE_ID NVARCHAR(50) NOT NULL,
	FIELD_ID NVARCHAR(40) NOT NULL,
	PHASE NVARCHAR(50) NOT NULL, -- EXPLORATION, DEVELOPMENT, PRODUCTION, DECLINE, DECOMMISSIONING, DECOMMISSIONED
	PHASE_START_DATE DATETIME NOT NULL,
	PHASE_END_DATE DATETIME,
	PHASE_STATUS NVARCHAR(50), -- ACTIVE, COMPLETED, REJECTED
	TRANSITION_REASON NVARCHAR(2000),
	ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATETIME,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATETIME,
	ROW_EFFECTIVE_DATE DATETIME,
	ROW_EXPIRY_DATE DATETIME,
	ROW_QUALITY NVARCHAR(40)
);

