raiserror ('CREATING FOREIGN KEY CONSTRAINT FIELD_PHASE_FIELD_FK', 10, 1) with nowait
ALTER TABLE FIELD_PHASE ADD CONSTRAINT FIELD_PHASE_FIELD_FK FOREIGN KEY
(
	FIELD_ID
)
REFERENCES FIELD
(
	FIELD_ID
);

