CREATE TABLE GL_ACCOUNT
(
    GL_ACCOUNT_ID NVARCHAR(40) NOT NULL,
    ACCOUNT_NUMBER NVARCHAR(40),
    ACCOUNT_NAME NVARCHAR(255),
    ACCOUNT_TYPE NVARCHAR(40),
    PARENT_ACCOUNT_ID NVARCHAR(40),
    NORMAL_BALANCE NVARCHAR(10),
    OPENING_BALANCE NUMERIC(18,2),
    CURRENT_BALANCE NUMERIC(18,2),
    DESCRIPTION NVARCHAR(4000),
    ACTIVE_IND NVARCHAR(1),
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(4000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(40),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);

