raiserror ('CREATING TABLE INVOICE', 10,1) with nowait
CREATE TABLE INVOICE
(
    INVOICE_ID NVARCHAR(40) NOT NULL,
    INVOICE_NUMBER NVARCHAR(40),
    CUSTOMER_BA_ID NVARCHAR(40),
    INVOICE_DATE DATE,
    DUE_DATE DATE,
    SUBTOTAL NUMERIC(18,2),
    TAX_AMOUNT NUMERIC(18,2),
    TOTAL_AMOUNT NUMERIC(18,2),
    PAID_AMOUNT NUMERIC(18,2),
    BALANCE_DUE NUMERIC(18,2),
    STATUS NVARCHAR(40),
    CURRENCY_CODE NVARCHAR(10),
    DESCRIPTION NVARCHAR(4000),
    ACTIVE_IND NVARCHAR(1),
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(4000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(40),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);

