raiserror ('CREATING TABLE JIB_COST_ALLOCATION', 10,1) with nowait
CREATE TABLE jib_cost_allocation
(
	JIB_COST_ALLOCATION_ID NVARCHAR(40) NOT NULL,
	JIB_ID NVARCHAR(40) NOT NULL,
	FINANCE_ID NVARCHAR(40),  -- Link to FINANCE transaction
	COST_CATEGORY NVARCHAR(40),  -- 'DRILLING', 'COMPLETION', 'FACILITIES', 'OPERATIONS'
	GROSS_COST NUMERIC(18,2) NOT NULL,
	WORKING_INTEREST_SHARE NUMERIC(10,4),
	NET_COST NUMERIC(18,2) NOT NULL,
	DESCRIPTION NVARCHAR(2000),
	ACTIVE_IND NVARCHAR(1),
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_ID NVARCHAR(40) NOT NULL,
	CONSTRAINT jib_cost_allocation_PK PRIMARY KEY (JIB_COST_ALLOCATION_ID)
)

