raiserror ('CREATING TABLE JOINT_INTEREST_BILL', 10,1) with nowait
CREATE TABLE joint_interest_bill
(
	JIB_ID NVARCHAR(40) NOT NULL,
	INTEREST_SET_ID NVARCHAR(40),  -- Link to INTEREST_SET (JOA)
	FIELD_ID NVARCHAR(40) NOT NULL,
	OPERATOR_ID NVARCHAR(40),  -- BUSINESS_ASSOCIATE_ID of operator
	BILL_PERIOD_START_DATE DATE NOT NULL,
	BILL_PERIOD_END_DATE DATE NOT NULL,
	TOTAL_BILL_AMOUNT NUMERIC(18,2) NOT NULL,
	WORKING_INTEREST_SHARE NUMERIC(10,4),
	NET_AMOUNT_DUE NUMERIC(18,2),
	BILL_STATUS NVARCHAR(40),  -- 'DRAFT', 'ISSUED', 'PAID', 'DISPUTED'
	DESCRIPTION NVARCHAR(2000),
	ACTIVE_IND NVARCHAR(1),
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_ID NVARCHAR(40) NOT NULL,
	CONSTRAINT joint_interest_bill_PK PRIMARY KEY (JIB_ID)
)

