raiserror ('CREATING FOREIGN KEY CONSTRAINT LEAD_FIELD_FK', 10, 1) with nowait
ALTER TABLE LEAD ADD CONSTRAINT LEAD_FIELD_FK FOREIGN KEY
(
	FIELD_ID
)
REFERENCES FIELD
(
	FIELD_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT LEAD_PLAY_FK', 10, 1) with nowait
ALTER TABLE LEAD ADD CONSTRAINT LEAD_PLAY_FK FOREIGN KEY
(
	PLAY_ID
)
REFERENCES PLAY
(
	PLAY_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT LEAD_STATUS_FK', 10, 1) with nowait
ALTER TABLE LEAD ADD CONSTRAINT LEAD_STATUS_FK FOREIGN KEY
(
	LEAD_STATUS
)
REFERENCES R_LEAD_STATUS
(
	LEAD_STATUS
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT LEAD_PROSPECT_FK', 10, 1) with nowait
ALTER TABLE LEAD ADD CONSTRAINT LEAD_PROSPECT_FK FOREIGN KEY
(
	PROMOTED_TO_PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);

