-- ============================================================================
-- Phase 2 — Workflow Engine Enhancement: Extension Tables
-- Created: 2026-07-02
-- Module: LifeCycleModule (Order 50)
-- ============================================================================

-- 1. DELEGATION_OF_AUTHORITY — financial threshold-based approval routing
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DELEGATION_OF_AUTHORITY')
BEGIN
    CREATE TABLE DELEGATION_OF_AUTHORITY (
        DOA_ID              NVARCHAR(128)    NOT NULL PRIMARY KEY,
        DOA_NAME            NVARCHAR(256)    NOT NULL,
        ENTITY_TYPE         NVARCHAR(128)    NOT NULL,
        FIELD_NAME          NVARCHAR(128)    NOT NULL,
        COMPARISON_OPERATOR NVARCHAR(32)     NOT NULL DEFAULT 'GREATER_THAN',
        THRESHOLD_VALUE     DECIMAL(18,2)    NOT NULL,
        THRESHOLD_VALUE_MAX DECIMAL(18,2)    NULL,
        CURRENCY_CODE       NVARCHAR(3)      NULL,
        APPROVAL_LEVEL      NVARCHAR(32)     NOT NULL DEFAULT 'LEVEL_1',
        REQUIRED_ROLE       NVARCHAR(128)    NOT NULL,
        APPROVAL_SEQUENCE   INT              NOT NULL DEFAULT 1,
        REQUIRES_UNANIMOUS  NVARCHAR(1)      NOT NULL DEFAULT 'N',
        ESCALATION_ROLE     NVARCHAR(128)    NULL,
        ESCALATION_HOURS    INT              NULL,
        PROCESS_TYPE        NVARCHAR(128)    NOT NULL DEFAULT '',
        NOTES               NVARCHAR(MAX)    NULL,

        -- ModelEntityBase audit columns
        ACTIVE_IND          NVARCHAR(1)      NOT NULL DEFAULT 'Y',
        ROW_CREATED_BY      NVARCHAR(128)    NOT NULL DEFAULT 'SYSTEM',
        ROW_CREATED_DATE    DATETIME         NULL,
        ROW_CHANGED_BY      NVARCHAR(128)    NOT NULL DEFAULT 'SYSTEM',
        ROW_CHANGED_DATE    DATETIME         NULL,
        ROW_EFFECTIVE_DATE  DATETIME         NULL,
        ROW_EXPIRY_DATE     DATETIME         NULL,
        ROW_QUALITY         NVARCHAR(MAX)    NULL,
        PPDM_GUID           NVARCHAR(128)    NULL,
        EXPIRY_DATE         DATETIME         NULL,
        EFFECTIVE_DATE      DATETIME         NULL,
        REMARK              NVARCHAR(MAX)    NULL,
        SOURCE              NVARCHAR(256)    NULL
    );

    CREATE INDEX IX_DOA_ENTITY_TYPE ON DELEGATION_OF_AUTHORITY(ENTITY_TYPE, PROCESS_TYPE);
    CREATE INDEX IX_DOA_LEVEL ON DELEGATION_OF_AUTHORITY(APPROVAL_LEVEL, APPROVAL_SEQUENCE);
END
GO

-- 2. WORKFLOW_VERSION — process definition version history
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'WORKFLOW_VERSION')
BEGIN
    CREATE TABLE WORKFLOW_VERSION (
        VERSION_ID              NVARCHAR(128)    NOT NULL PRIMARY KEY,
        PROCESS_DEFINITION_ID   NVARCHAR(128)    NOT NULL,
        VERSION_NUMBER          NVARCHAR(32)     NOT NULL DEFAULT '1.0',
        CHANGE_DESCRIPTION      NVARCHAR(MAX)    NOT NULL,
        PREVIOUS_VERSION_ID     NVARCHAR(128)    NULL,
        PROCESS_CONFIG_SNAPSHOT NVARCHAR(MAX)    NULL,
        EFFECTIVE_DATE          DATETIME         NOT NULL,
        DEPRECATED_STEP_IDS     NVARCHAR(MAX)    NULL,
        STEP_REMAPPING_JSON     NVARCHAR(MAX)    NULL,
        CREATED_BY              NVARCHAR(128)    NULL,

        -- ModelEntityBase audit columns
        ACTIVE_IND              NVARCHAR(1)      NOT NULL DEFAULT 'Y',
        ROW_CREATED_BY          NVARCHAR(128)    NOT NULL DEFAULT 'SYSTEM',
        ROW_CREATED_DATE        DATETIME         NULL,
        ROW_CHANGED_BY          NVARCHAR(128)    NOT NULL DEFAULT 'SYSTEM',
        ROW_CHANGED_DATE        DATETIME         NULL,
        ROW_EFFECTIVE_DATE      DATETIME         NULL,
        ROW_EXPIRY_DATE         DATETIME         NULL,
        ROW_QUALITY             NVARCHAR(MAX)    NULL,
        PPDM_GUID               NVARCHAR(128)    NULL,
        EXPIRY_DATE             DATETIME         NULL,
        EFFECTIVE_DATE          DATETIME         NULL,
        REMARK                  NVARCHAR(MAX)    NULL,
        SOURCE                  NVARCHAR(256)    NULL
    );

    CREATE INDEX IX_WF_VERSION_PROCESS ON WORKFLOW_VERSION(PROCESS_DEFINITION_ID, VERSION_NUMBER);
END
GO

-- 3. WORKFLOW_DEPENDENCY — cross-workflow dependency gates
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'WORKFLOW_DEPENDENCY')
BEGIN
    CREATE TABLE WORKFLOW_DEPENDENCY (
        DEPENDENCY_ID               NVARCHAR(128)    NOT NULL PRIMARY KEY,
        DEPENDENT_PROCESS_DEF_ID    NVARCHAR(128)    NOT NULL,
        DEPENDENT_STEP_ID           NVARCHAR(128)    NULL,
        PREREQUISITE_PROCESS_DEF_ID NVARCHAR(128)    NOT NULL,
        PREREQUISITE_STEP_ID        NVARCHAR(128)    NULL,
        DEPENDENCY_TYPE             NVARCHAR(32)     NOT NULL DEFAULT 'BLOCKING',
        CONDITION_EXPRESSION        NVARCHAR(MAX)    NULL,
        DESCRIPTION                 NVARCHAR(MAX)    NULL,

        -- ModelEntityBase audit columns
        ACTIVE_IND          NVARCHAR(1)      NOT NULL DEFAULT 'Y',
        ROW_CREATED_BY      NVARCHAR(128)    NOT NULL DEFAULT 'SYSTEM',
        ROW_CREATED_DATE    DATETIME         NULL,
        ROW_CHANGED_BY      NVARCHAR(128)    NOT NULL DEFAULT 'SYSTEM',
        ROW_CHANGED_DATE    DATETIME         NULL,
        ROW_EFFECTIVE_DATE  DATETIME         NULL,
        ROW_EXPIRY_DATE     DATETIME         NULL,
        ROW_QUALITY         NVARCHAR(MAX)    NULL,
        PPDM_GUID           NVARCHAR(128)    NULL,
        EXPIRY_DATE         DATETIME         NULL,
        EFFECTIVE_DATE      DATETIME         NULL,
        REMARK              NVARCHAR(MAX)    NULL,
        SOURCE              NVARCHAR(256)    NULL
    );

    CREATE INDEX IX_WF_DEP_DEPENDENT ON WORKFLOW_DEPENDENCY(DEPENDENT_PROCESS_DEF_ID);
    CREATE INDEX IX_WF_DEP_PREREQ ON WORKFLOW_DEPENDENCY(PREREQUISITE_PROCESS_DEF_ID);
END
GO
