-- ============================================================================
-- Phase 3 & 4 — Cross-Role Orchestration + Governance & Compliance
-- Created: 2026-07-02
-- Modules: LifeCycleModule (Order 50) + SecurityModule (Order 40)
-- ============================================================================

-- ═══ Phase 3: Cross-Role Orchestration ═══

-- 1. ROLE_HANDOFF_CONTRACT
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ROLE_HANDOFF_CONTRACT')
BEGIN
    CREATE TABLE ROLE_HANDOFF_CONTRACT (
        HANDOFF_CONTRACT_ID     NVARCHAR(128)    NOT NULL PRIMARY KEY,
        PROCESS_DEFINITION_ID   NVARCHAR(128)    NOT NULL,
        FROM_STEP_ID            NVARCHAR(128)    NOT NULL,
        FROM_ROLE               NVARCHAR(128)    NOT NULL,
        TO_STEP_ID              NVARCHAR(128)    NOT NULL,
        TO_ROLE                 NVARCHAR(128)    NOT NULL,
        REQUIRED_DATA_FIELDS_JSON NVARCHAR(MAX)  NULL,
        REQUIRED_DOCUMENTS_JSON NVARCHAR(MAX)    NULL,
        SLA_CONTEXT_JSON        NVARCHAR(MAX)    NULL,
        APPROVAL_CONTEXT_JSON   NVARCHAR(MAX)    NULL,
        VALIDATION_RULES_JSON   NVARCHAR(MAX)    NULL,
        DESCRIPTION             NVARCHAR(MAX)    NULL,
        -- audit columns
        ACTIVE_IND NVARCHAR(1) NOT NULL DEFAULT 'Y', ROW_CREATED_BY NVARCHAR(128) DEFAULT 'SYSTEM',
        ROW_CREATED_DATE DATETIME NULL, ROW_CHANGED_BY NVARCHAR(128) DEFAULT 'SYSTEM',
        ROW_CHANGED_DATE DATETIME NULL, ROW_EFFECTIVE_DATE DATETIME NULL, ROW_EXPIRY_DATE DATETIME NULL,
        ROW_QUALITY NVARCHAR(MAX) NULL, PPDM_GUID NVARCHAR(128) NULL,
        EXPIRY_DATE DATETIME NULL, EFFECTIVE_DATE DATETIME NULL, REMARK NVARCHAR(MAX) NULL, SOURCE NVARCHAR(256) NULL
    );
    CREATE INDEX IX_HANDOFF_PROCESS ON ROLE_HANDOFF_CONTRACT(PROCESS_DEFINITION_ID);
END
GO

-- 2. BUSINESS_EVENT_TRIGGER
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'BUSINESS_EVENT_TRIGGER')
BEGIN
    CREATE TABLE BUSINESS_EVENT_TRIGGER (
        TRIGGER_ID              NVARCHAR(128)    NOT NULL PRIMARY KEY,
        TRIGGER_NAME            NVARCHAR(256)    NOT NULL,
        EVENT_TYPE              NVARCHAR(32)     NOT NULL DEFAULT 'STATUS_CHANGED',
        ENTITY_TYPE             NVARCHAR(128)    NOT NULL,
        WATCH_FIELD             NVARCHAR(128)    NULL,
        CONDITION_EXPRESSION    NVARCHAR(MAX)    NULL,
        TARGET_PROCESS_DEF_ID   NVARCHAR(128)    NOT NULL,
        IS_ACTIVE               NVARCHAR(1)      NOT NULL DEFAULT 'Y',
        PRIORITY                INT              NOT NULL DEFAULT 10,
        DESCRIPTION             NVARCHAR(MAX)    NULL,
        -- audit columns
        ACTIVE_IND NVARCHAR(1) NOT NULL DEFAULT 'Y', ROW_CREATED_BY NVARCHAR(128) DEFAULT 'SYSTEM',
        ROW_CREATED_DATE DATETIME NULL, ROW_CHANGED_BY NVARCHAR(128) DEFAULT 'SYSTEM',
        ROW_CHANGED_DATE DATETIME NULL, ROW_EFFECTIVE_DATE DATETIME NULL, ROW_EXPIRY_DATE DATETIME NULL,
        ROW_QUALITY NVARCHAR(MAX) NULL, PPDM_GUID NVARCHAR(128) NULL,
        EXPIRY_DATE DATETIME NULL, EFFECTIVE_DATE DATETIME NULL, REMARK NVARCHAR(MAX) NULL, SOURCE NVARCHAR(256) NULL
    );
    CREATE INDEX IX_BT_ENTITY ON BUSINESS_EVENT_TRIGGER(ENTITY_TYPE, IS_ACTIVE);
END
GO

-- 3. CROSS_PERSONA_TASK
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CROSS_PERSONA_TASK')
BEGIN
    CREATE TABLE CROSS_PERSONA_TASK (
        CROSS_TASK_ID           NVARCHAR(128)    NOT NULL PRIMARY KEY,
        PROCESS_INSTANCE_ID     NVARCHAR(128)    NOT NULL,
        PROCESS_STEP_INSTANCE_ID NVARCHAR(128)   NOT NULL,
        TARGET_PERSONA_CODE     NVARCHAR(64)     NOT NULL,
        ASSIGNED_ROLE           NVARCHAR(128)    NOT NULL,
        TASK_TYPE               NVARCHAR(32)     NOT NULL DEFAULT 'REVIEW',
        PRIORITY                INT              NOT NULL DEFAULT 3,
        TASK_STATUS             NVARCHAR(32)     NOT NULL DEFAULT 'PENDING',
        DUE_DATE                DATETIME         NULL,
        ENTITY_TYPE             NVARCHAR(128)    NULL,
        ENTITY_ID               NVARCHAR(128)    NULL,
        ENTITY_DESCRIPTION      NVARCHAR(MAX)    NULL,
        ROUTE                   NVARCHAR(512)    NULL,
        TASK_CONTEXT_JSON       NVARCHAR(MAX)    NULL,
        -- audit columns
        ACTIVE_IND NVARCHAR(1) NOT NULL DEFAULT 'Y', ROW_CREATED_BY NVARCHAR(128) DEFAULT 'SYSTEM',
        ROW_CREATED_DATE DATETIME NULL, ROW_CHANGED_BY NVARCHAR(128) DEFAULT 'SYSTEM',
        ROW_CHANGED_DATE DATETIME NULL, ROW_EFFECTIVE_DATE DATETIME NULL, ROW_EXPIRY_DATE DATETIME NULL,
        ROW_QUALITY NVARCHAR(MAX) NULL, PPDM_GUID NVARCHAR(128) NULL,
        EXPIRY_DATE DATETIME NULL, EFFECTIVE_DATE DATETIME NULL, REMARK NVARCHAR(MAX) NULL, SOURCE NVARCHAR(256) NULL
    );
    CREATE INDEX IX_CPT_PERSONA ON CROSS_PERSONA_TASK(TARGET_PERSONA_CODE, TASK_STATUS);
    CREATE INDEX IX_CPT_INSTANCE ON CROSS_PERSONA_TASK(PROCESS_INSTANCE_ID);
END
GO

-- ═══ Phase 4: Governance & Compliance ═══

-- 4. SOD_RULE
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SOD_RULE')
BEGIN
    CREATE TABLE SOD_RULE (
        SOD_RULE_ID             NVARCHAR(128)    NOT NULL PRIMARY KEY,
        RULE_NAME               NVARCHAR(256)    NOT NULL,
        RULE_CATEGORY           NVARCHAR(32)     NOT NULL DEFAULT 'FINANCIAL',
        CONFLICTING_PERMISSION_A NVARCHAR(256)   NOT NULL,
        CONFLICTING_PERMISSION_B NVARCHAR(256)   NOT NULL,
        CONFLICT_DESCRIPTION    NVARCHAR(MAX)    NOT NULL,
        SEVERITY                NVARCHAR(16)     NOT NULL DEFAULT 'HIGH',
        REGULATION_REFERENCE    NVARCHAR(256)    NULL,
        IS_BLOCKING             NVARCHAR(1)      NOT NULL DEFAULT 'Y',
        SCOPE_TYPE              NVARCHAR(32)     NOT NULL DEFAULT 'GLOBAL',
        MITIGATION_GUIDANCE     NVARCHAR(MAX)    NULL,
        -- audit columns
        ACTIVE_IND NVARCHAR(1) NOT NULL DEFAULT 'Y', ROW_CREATED_BY NVARCHAR(128) DEFAULT 'SYSTEM',
        ROW_CREATED_DATE DATETIME NULL, ROW_CHANGED_BY NVARCHAR(128) DEFAULT 'SYSTEM',
        ROW_CHANGED_DATE DATETIME NULL, ROW_EFFECTIVE_DATE DATETIME NULL, ROW_EXPIRY_DATE DATETIME NULL,
        ROW_QUALITY NVARCHAR(MAX) NULL, PPDM_GUID NVARCHAR(128) NULL,
        EXPIRY_DATE DATETIME NULL, EFFECTIVE_DATE DATETIME NULL, REMARK NVARCHAR(MAX) NULL, SOURCE NVARCHAR(256) NULL
    );
    CREATE UNIQUE INDEX IX_SOD_RULE_NAME ON SOD_RULE(RULE_NAME);
END
GO

-- 5. SOD_CONFLICT
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SOD_CONFLICT')
BEGIN
    CREATE TABLE SOD_CONFLICT (
        SOD_CONFLICT_ID         NVARCHAR(128)    NOT NULL PRIMARY KEY,
        SOD_RULE_ID             NVARCHAR(128)    NOT NULL,
        RULE_NAME               NVARCHAR(256)    NOT NULL,
        USER_ID                 NVARCHAR(128)    NOT NULL,
        ROLE_A                  NVARCHAR(128)    NULL,
        ROLE_B                  NVARCHAR(128)    NULL,
        DETECTED_DATE           DATETIME         NOT NULL,
        CONFLICT_STATUS         NVARCHAR(32)     NOT NULL DEFAULT 'ACTIVE',
        COMPENSATING_CONTROL_ID NVARCHAR(128)    NULL,
        RESOLVED_DATE           DATETIME         NULL,
        RESOLVED_BY             NVARCHAR(128)    NULL,
        RESOLUTION_NOTES        NVARCHAR(MAX)    NULL,
        -- audit columns
        ACTIVE_IND NVARCHAR(1) NOT NULL DEFAULT 'Y', ROW_CREATED_BY NVARCHAR(128) DEFAULT 'SYSTEM',
        ROW_CREATED_DATE DATETIME NULL, ROW_CHANGED_BY NVARCHAR(128) DEFAULT 'SYSTEM',
        ROW_CHANGED_DATE DATETIME NULL, ROW_EFFECTIVE_DATE DATETIME NULL, ROW_EXPIRY_DATE DATETIME NULL,
        ROW_QUALITY NVARCHAR(MAX) NULL, PPDM_GUID NVARCHAR(128) NULL,
        EXPIRY_DATE DATETIME NULL, EFFECTIVE_DATE DATETIME NULL, REMARK NVARCHAR(MAX) NULL, SOURCE NVARCHAR(256) NULL
    );
    CREATE INDEX IX_SOD_CONFLICT_USER ON SOD_CONFLICT(USER_ID, CONFLICT_STATUS);
END
GO

-- 6. COMPENSATING_CONTROL
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'COMPENSATING_CONTROL')
BEGIN
    CREATE TABLE COMPENSATING_CONTROL (
        CONTROL_ID              NVARCHAR(128)    NOT NULL PRIMARY KEY,
        SOD_CONFLICT_ID         NVARCHAR(128)    NOT NULL,
        USER_ID                 NVARCHAR(128)    NOT NULL,
        CONTROL_TYPE            NVARCHAR(32)     NOT NULL DEFAULT 'MANAGER_REVIEW',
        CONTROL_DESCRIPTION     NVARCHAR(MAX)    NOT NULL,
        APPROVED_BY             NVARCHAR(128)    NOT NULL,
        APPROVED_DATE           DATETIME         NOT NULL,
        EFFECTIVE_FROM          DATETIME         NOT NULL,
        EFFECTIVE_TO            DATETIME         NOT NULL,
        REVIEW_FREQUENCY        NVARCHAR(16)     NOT NULL DEFAULT 'MONTHLY',
        LAST_REVIEWED_DATE      DATETIME         NULL,
        LAST_REVIEWED_BY        NVARCHAR(128)    NULL,
        STATUS                  NVARCHAR(32)     NOT NULL DEFAULT 'ACTIVE',
        APPROVAL_PROCESS_INSTANCE_ID NVARCHAR(128) NULL,
        -- audit columns
        ACTIVE_IND NVARCHAR(1) NOT NULL DEFAULT 'Y', ROW_CREATED_BY NVARCHAR(128) DEFAULT 'SYSTEM',
        ROW_CREATED_DATE DATETIME NULL, ROW_CHANGED_BY NVARCHAR(128) DEFAULT 'SYSTEM',
        ROW_CHANGED_DATE DATETIME NULL, ROW_EFFECTIVE_DATE DATETIME NULL, ROW_EXPIRY_DATE DATETIME NULL,
        ROW_QUALITY NVARCHAR(MAX) NULL, PPDM_GUID NVARCHAR(128) NULL,
        EXPIRY_DATE DATETIME NULL, EFFECTIVE_DATE DATETIME NULL, REMARK NVARCHAR(MAX) NULL, SOURCE NVARCHAR(256) NULL
    );
    CREATE INDEX IX_CC_USER ON COMPENSATING_CONTROL(USER_ID, STATUS);
    CREATE INDEX IX_CC_EXPIRY ON COMPENSATING_CONTROL(EFFECTIVE_TO, STATUS);
END
GO

-- 7. ACCESS_REVIEW_CAMPAIGN
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ACCESS_REVIEW_CAMPAIGN')
BEGIN
    CREATE TABLE ACCESS_REVIEW_CAMPAIGN (
        CAMPAIGN_ID     NVARCHAR(128) NOT NULL PRIMARY KEY,
        CAMPAIGN_NAME   NVARCHAR(256) NOT NULL,
        START_DATE      DATETIME NOT NULL,
        DUE_DATE        DATETIME NOT NULL,
        STATUS          NVARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
        INITIATED_BY    NVARCHAR(128) NOT NULL,
        DESCRIPTION     NVARCHAR(MAX) NULL,
        -- audit columns
        ACTIVE_IND NVARCHAR(1) NOT NULL DEFAULT 'Y', ROW_CREATED_BY NVARCHAR(128) DEFAULT 'SYSTEM',
        ROW_CREATED_DATE DATETIME NULL, ROW_CHANGED_BY NVARCHAR(128) DEFAULT 'SYSTEM',
        ROW_CHANGED_DATE DATETIME NULL, ROW_EFFECTIVE_DATE DATETIME NULL, ROW_EXPIRY_DATE DATETIME NULL,
        ROW_QUALITY NVARCHAR(MAX) NULL, PPDM_GUID NVARCHAR(128) NULL,
        EXPIRY_DATE DATETIME NULL, EFFECTIVE_DATE DATETIME NULL, REMARK NVARCHAR(MAX) NULL, SOURCE NVARCHAR(256) NULL
    );
END
GO

-- 8. ACCESS_REVIEW_ITEM
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ACCESS_REVIEW_ITEM')
BEGIN
    CREATE TABLE ACCESS_REVIEW_ITEM (
        REVIEW_ITEM_ID          NVARCHAR(128) NOT NULL PRIMARY KEY,
        CAMPAIGN_ID             NVARCHAR(128) NOT NULL,
        USER_ID                 NVARCHAR(128) NOT NULL,
        REVIEWER_ID             NVARCHAR(128) NOT NULL,
        CURRENT_ROLES_JSON      NVARCHAR(MAX) NULL,
        CURRENT_PERMISSIONS_JSON NVARCHAR(MAX) NULL,
        DECISION                NVARCHAR(32) NOT NULL DEFAULT 'PENDING',
        COMMENTS                NVARCHAR(MAX) NULL,
        REVIEWED_DATE           DATETIME NULL,
        -- audit columns
        ACTIVE_IND NVARCHAR(1) NOT NULL DEFAULT 'Y', ROW_CREATED_BY NVARCHAR(128) DEFAULT 'SYSTEM',
        ROW_CREATED_DATE DATETIME NULL, ROW_CHANGED_BY NVARCHAR(128) DEFAULT 'SYSTEM',
        ROW_CHANGED_DATE DATETIME NULL, ROW_EFFECTIVE_DATE DATETIME NULL, ROW_EXPIRY_DATE DATETIME NULL,
        ROW_QUALITY NVARCHAR(MAX) NULL, PPDM_GUID NVARCHAR(128) NULL,
        EXPIRY_DATE DATETIME NULL, EFFECTIVE_DATE DATETIME NULL, REMARK NVARCHAR(MAX) NULL, SOURCE NVARCHAR(256) NULL
    );
    CREATE INDEX IX_ARI_CAMPAIGN ON ACCESS_REVIEW_ITEM(CAMPAIGN_ID, DECISION);
    CREATE INDEX IX_ARI_REVIEWER ON ACCESS_REVIEW_ITEM(REVIEWER_ID, DECISION);
END
GO
