raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_MATERIAL_PIPELINE_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_MATERIAL ADD CONSTRAINT PIPELINE_MATERIAL_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

