raiserror ('CREATING TABLE PIPELINE_COMPONENT', 10,1) with nowait
CREATE TABLE pipeline_component
(
	PIPELINE_ID NVARCHAR(40) NOT NULL,
	COMPONENT_ID NVARCHAR(40) NOT NULL,
	COMPONENT_TYPE NVARCHAR(40),
	PART_NUMBER NVARCHAR(40),
	SEGMENT_ID NVARCHAR(40),
	MATERIAL_TYPE NVARCHAR(40),
	MATERIAL_GRADE NVARCHAR(40),
	MANUFACTURER NVARCHAR(40),
	INSTALLATION_DATE DATE,
	DESCRIPTION NVARCHAR(240),
	ACTIVE_IND NVARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);

