raiserror ('CREATING TABLE PIPELINE_INCIDENT', 10,1) with nowait
CREATE TABLE pipeline_incident
(
	PIPELINE_ID NVARCHAR(40) NOT NULL,
	INCIDENT_ID NVARCHAR(40) NOT NULL,
	INCIDENT_DATE DATE,
	INCIDENT_TYPE NVARCHAR(40),
	SEVERITY NVARCHAR(40),
	CAUSE NVARCHAR(240),
	VOLUME_RELEASED NUMERIC(10,2),
	VOLUME_RELEASED_OUOM NVARCHAR(40),
	ENVIRONMENTAL_IMPACT NVARCHAR(2000),
	DESCRIPTION NVARCHAR(240),
	ACTIVE_IND NVARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);

