raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_SEGMENT_PIPELINE_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_SEGMENT ADD CONSTRAINT PIPELINE_SEGMENT_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_SEGMENT_START_FACILITY_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_SEGMENT ADD CONSTRAINT PIPELINE_SEGMENT_START_FACILITY_FK FOREIGN KEY 
(
	START_STATION_ID,
	START_STATION_TYPE
)
REFERENCES FACILITY
(
	FACILITY_ID,
	FACILITY_TYPE
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_SEGMENT_END_FACILITY_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_SEGMENT ADD CONSTRAINT PIPELINE_SEGMENT_END_FACILITY_FK FOREIGN KEY 
(
	END_STATION_ID,
	END_STATION_TYPE
)
REFERENCES FACILITY
(
	FACILITY_ID,
	FACILITY_TYPE
);
