raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_TEST_PIPELINE_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_TEST ADD CONSTRAINT PIPELINE_TEST_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_TEST_SEGMENT_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_TEST ADD CONSTRAINT PIPELINE_TEST_SEGMENT_FK FOREIGN KEY 
(
	PIPELINE_ID,
	SEGMENT_ID
)
REFERENCES PIPELINE_SEGMENT
(
	PIPELINE_ID,
	SEGMENT_ID
);

