raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_CONSTRUCTION_PIPELINE_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_CONSTRUCTION ADD CONSTRAINT PIPELINE_CONSTRUCTION_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_CONSTRUCTION_CONTRACTOR_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_CONSTRUCTION ADD CONSTRAINT PIPELINE_CONSTRUCTION_CONTRACTOR_FK FOREIGN KEY 
(
	CONTRACTOR
)
REFERENCES BUSINESS_ASSOCIATE
(
	BUSINESS_ASSOCIATE_ID
);

