raiserror ('CREATING TABLE PIPELINE_RISK_ASSESSMENT', 10,1) with nowait
CREATE TABLE pipeline_risk_assessment
(
	PIPELINE_ID NVARCHAR(40) NOT NULL,
	RISK_ASSESSMENT_ID NVARCHAR(40) NOT NULL,
	ASSESSMENT_DATE DATE,
	RISK_SCORE NUMERIC(10,2),
	ASSESSMENT_METHOD NVARCHAR(40),
	RISK_FACTORS NVARCHAR(2000),
	SEGMENT_ID NVARCHAR(40),
	DESCRIPTION NVARCHAR(240),
	ACTIVE_IND NVARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);

