raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_DESIGN_PIPELINE_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_DESIGN ADD CONSTRAINT PIPELINE_DESIGN_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

