raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_FACILITY_PIPELINE_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_FACILITY ADD CONSTRAINT PIPELINE_FACILITY_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_FACILITY_FACILITY_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_FACILITY ADD CONSTRAINT PIPELINE_FACILITY_FACILITY_FK FOREIGN KEY 
(
	FACILITY_ID,
	FACILITY_TYPE
)
REFERENCES FACILITY
(
	FACILITY_ID,
	FACILITY_TYPE
);
