raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_INCIDENT_PIPELINE_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_INCIDENT ADD CONSTRAINT PIPELINE_INCIDENT_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

