raiserror ('CREATING TABLE PIPELINE_STATION', 10,1) with nowait
CREATE TABLE pipeline_station
(
	PIPELINE_ID NVARCHAR(40) NOT NULL,
	STATION_ID NVARCHAR(40) NOT NULL,
	STATION_NAME NVARCHAR(255),
	STATION_SHORT_NAME NVARCHAR(30),
	STATION_TYPE NVARCHAR(40),
	FACILITY_ID NVARCHAR(40),
	FACILITY_TYPE NVARCHAR(40),
	STATION_FUNCTION NVARCHAR(40),
	DESCRIPTION NVARCHAR(240),
	ACTIVE_IND NVARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);
