raiserror ('CREATING TABLE PIPELINE_MAINTENANCE', 10,1) with nowait
CREATE TABLE pipeline_maintenance
(
	PIPELINE_ID NVARCHAR(40) NOT NULL,
	MAINTENANCE_ID NVARCHAR(40) NOT NULL,
	MAINTENANCE_TYPE NVARCHAR(40),
	SCHEDULE_DATE DATE,
	COMPLETION_DATE DATE,
	CREW NVARCHAR(40),
	MAINTENANCE_COST NUMERIC(15,2),
	MAINTENANCE_COST_OUOM NVARCHAR(40),
	SEGMENT_ID NVARCHAR(40),
	DESCRIPTION NVARCHAR(240),
	ACTIVE_IND NVARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);

