raiserror ('CREATING TABLE PIPELINE_ANOMALY', 10,1) with nowait
CREATE TABLE pipeline_anomaly
(
	PIPELINE_ID NVARCHAR(40) NOT NULL,
	ANOMALY_ID NVARCHAR(40) NOT NULL,
	ANOMALY_TYPE NVARCHAR(40),
	INSPECTION_ID NVARCHAR(40),
	LOCATION_STATION_MILEPOST NUMERIC(10,2),
	LOCATION_STATION_MILEPOST_OUOM NVARCHAR(40),
	SEVERITY NVARCHAR(40),
	ANOMALY_LENGTH NUMERIC(10,2),
	ANOMALY_LENGTH_OUOM NVARCHAR(40),
	ANOMALY_DEPTH NUMERIC(10,2),
	ANOMALY_DEPTH_OUOM NVARCHAR(40),
	ANOMALY_WIDTH NUMERIC(10,2),
	ANOMALY_WIDTH_OUOM NVARCHAR(40),
	SEGMENT_ID NVARCHAR(40),
	DESCRIPTION NVARCHAR(240),
	ACTIVE_IND NVARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);

