raiserror ('CREATING PRIMARY KEY PIPELINE_CONSTRUCTION_PK', 10, 1) with nowait
ALTER TABLE PIPELINE_CONSTRUCTION ADD CONSTRAINT PIPELINE_CONSTRUCTION_PK PRIMARY KEY
(
	PIPELINE_ID,
	CONSTRUCTION_PHASE_NO
);

