raiserror ('CREATING TABLE PIPELINE_WELL', 10,1) with nowait
CREATE TABLE pipeline_well
(
	PIPELINE_ID NVARCHAR(40) NOT NULL,
	UWI NVARCHAR(40) NOT NULL,
	CONNECTION_SEQ_NO NUMERIC(8,0) NOT NULL,
	CONNECTION_TYPE NVARCHAR(40),
	CONNECTION_DATE DATE,
	FLOW_DIRECTION NVARCHAR(40),
	DESCRIPTION NVARCHAR(240),
	ACTIVE_IND NVARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);
