raiserror ('CREATING PRIMARY KEY PIPELINE_RISK_ASSESSMENT_PK', 10, 1) with nowait
ALTER TABLE PIPELINE_RISK_ASSESSMENT ADD CONSTRAINT PIPELINE_RISK_ASSESSMENT_PK PRIMARY KEY
(
	PIPELINE_ID,
	RISK_ASSESSMENT_ID
);

