raiserror ('CREATING TABLE PIPELINE_OPERATION', 10,1) with nowait
CREATE TABLE pipeline_operation
(
	PIPELINE_ID NVARCHAR(40) NOT NULL,
	OPERATION_ID NVARCHAR(40) NOT NULL,
	OPERATION_DATE DATE,
	FLOW_RATE NUMERIC(10,2),
	FLOW_RATE_OUOM NVARCHAR(40),
	PRESSURE NUMERIC(10,2),
	PRESSURE_OUOM NVARCHAR(40),
	TEMPERATURE NUMERIC(10,2),
	TEMPERATURE_OUOM NVARCHAR(40),
	THROUGHPUT NUMERIC(10,2),
	THROUGHPUT_OUOM NVARCHAR(40),
	STATION_ID NVARCHAR(40),
	DESCRIPTION NVARCHAR(240),
	ACTIVE_IND NVARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);

