raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_INSPECTION_PIPELINE_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_INSPECTION ADD CONSTRAINT PIPELINE_INSPECTION_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_INSPECTION_SEGMENT_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_INSPECTION ADD CONSTRAINT PIPELINE_INSPECTION_SEGMENT_FK FOREIGN KEY 
(
	PIPELINE_ID,
	SEGMENT_ID
)
REFERENCES PIPELINE_SEGMENT
(
	PIPELINE_ID,
	SEGMENT_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_INSPECTION_TYPE_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_INSPECTION ADD CONSTRAINT PIPELINE_INSPECTION_TYPE_FK FOREIGN KEY 
(
	INSPECTION_TYPE
)
REFERENCES R_INSPECTION_TYPE
(
	INSPECTION_TYPE
);

