raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_OPERATION_PIPELINE_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_OPERATION ADD CONSTRAINT PIPELINE_OPERATION_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_OPERATION_STATION_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_OPERATION ADD CONSTRAINT PIPELINE_OPERATION_STATION_FK FOREIGN KEY 
(
	PIPELINE_ID,
	STATION_ID
)
REFERENCES PIPELINE_STATION
(
	PIPELINE_ID,
	STATION_ID
);

