raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_WELL_PIPELINE_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_WELL ADD CONSTRAINT PIPELINE_WELL_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_WELL_WELL_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_WELL ADD CONSTRAINT PIPELINE_WELL_WELL_FK FOREIGN KEY 
(
	UWI
)
REFERENCES WELL
(
	UWI
);
