raiserror ('CREATING TABLE PIPELINE_INSPECTION', 10,1) with nowait
CREATE TABLE pipeline_inspection
(
	PIPELINE_ID NVARCHAR(40) NOT NULL,
	INSPECTION_ID NVARCHAR(40) NOT NULL,
	INSPECTION_TYPE NVARCHAR(40),
	INSPECTION_DATE DATE,
	INSPECTOR NVARCHAR(40),
	TOOL_MODEL NVARCHAR(255),
	TOOL_MANUFACTURER NVARCHAR(40),
	SEGMENT_ID NVARCHAR(40),
	STATION_MILEPOST NUMERIC(10,2),
	STATION_MILEPOST_OUOM NVARCHAR(40),
	INSPECTION_RESULT NVARCHAR(40),
	DESCRIPTION NVARCHAR(240),
	ACTIVE_IND NVARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);

