raiserror ('CREATING TABLE PIPELINE_TEST', 10,1) with nowait
CREATE TABLE pipeline_test
(
	PIPELINE_ID NVARCHAR(40) NOT NULL,
	TEST_ID NVARCHAR(40) NOT NULL,
	TEST_TYPE NVARCHAR(40),
	TEST_DATE DATE,
	TEST_PRESSURE NUMERIC(10,5),
	TEST_PRESSURE_OUOM NVARCHAR(40),
	TEST_RESULT NVARCHAR(40),
	TEST_DURATION NUMERIC(10,2),
	TEST_DURATION_OUOM NVARCHAR(40),
	SEGMENT_ID NVARCHAR(40),
	TEST_METHOD NVARCHAR(40),
	INSPECTOR NVARCHAR(40),
	DESCRIPTION NVARCHAR(240),
	ACTIVE_IND NVARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);

