raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_MAINTENANCE_SCHEDULE_PIPELINE_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_MAINTENANCE_SCHEDULE ADD CONSTRAINT PIPELINE_MAINTENANCE_SCHEDULE_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

