raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_FIELD_PIPELINE_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_FIELD ADD CONSTRAINT PIPELINE_FIELD_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_FIELD_FIELD_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_FIELD ADD CONSTRAINT PIPELINE_FIELD_FIELD_FK FOREIGN KEY 
(
	FIELD_ID
)
REFERENCES FIELD
(
	FIELD_ID
);
