raiserror ('CREATING TABLE PIPELINE_DESIGN', 10,1) with nowait
CREATE TABLE pipeline_design
(
	PIPELINE_ID NVARCHAR(40) NOT NULL,
	DESIGN_VERSION_NO NVARCHAR(40) NOT NULL,
	DESIGN_PRESSURE NUMERIC(10,5),
	DESIGN_PRESSURE_OUOM NVARCHAR(40),
	DESIGN_TEMPERATURE NUMERIC(10,5),
	DESIGN_TEMPERATURE_OUOM NVARCHAR(40),
	MATERIAL_GRADE NVARCHAR(40),
	COATING_TYPE NVARCHAR(40),
	CATHODIC_PROTECTION_TYPE NVARCHAR(40),
	CP_SYSTEM_TYPE NVARCHAR(40),
	DESIGN_SPECIFICATION NVARCHAR(255),
	DESIGN_STANDARD NVARCHAR(40),
	DESIGN_DATE DATE,
	DESIGNER NVARCHAR(40),
	DESCRIPTION NVARCHAR(240),
	ACTIVE_IND NVARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);

