raiserror ('CREATING PRIMARY KEY PIPELINE_MAINTENANCE_SCHEDULE_PK', 10, 1) with nowait
ALTER TABLE PIPELINE_MAINTENANCE_SCHEDULE ADD CONSTRAINT PIPELINE_MAINTENANCE_SCHEDULE_PK PRIMARY KEY
(
	PIPELINE_ID,
	SCHEDULE_ID
);

