raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_ANOMALY_PIPELINE_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_ANOMALY ADD CONSTRAINT PIPELINE_ANOMALY_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_ANOMALY_INSPECTION_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_ANOMALY ADD CONSTRAINT PIPELINE_ANOMALY_INSPECTION_FK FOREIGN KEY 
(
	PIPELINE_ID,
	INSPECTION_ID
)
REFERENCES PIPELINE_INSPECTION
(
	PIPELINE_ID,
	INSPECTION_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_ANOMALY_TYPE_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_ANOMALY ADD CONSTRAINT PIPELINE_ANOMALY_TYPE_FK FOREIGN KEY 
(
	ANOMALY_TYPE
)
REFERENCES R_ANOMALY_TYPE
(
	ANOMALY_TYPE
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PIPELINE_ANOMALY_SEGMENT_FK', 10, 1) with nowait
ALTER TABLE PIPELINE_ANOMALY ADD CONSTRAINT PIPELINE_ANOMALY_SEGMENT_FK FOREIGN KEY 
(
	PIPELINE_ID,
	SEGMENT_ID
)
REFERENCES PIPELINE_SEGMENT
(
	PIPELINE_ID,
	SEGMENT_ID
);

