raiserror ('CREATING FOREIGN KEY CONSTRAINT PLAY_FIELD_FK', 10, 1) with nowait
ALTER TABLE PLAY ADD CONSTRAINT PLAY_FIELD_FK FOREIGN KEY
(
	FIELD_ID
)
REFERENCES FIELD
(
	FIELD_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PLAY_TYPE_FK', 10, 1) with nowait
ALTER TABLE PLAY ADD CONSTRAINT PLAY_TYPE_FK FOREIGN KEY
(
	PLAY_TYPE
)
REFERENCES R_PLAY_TYPE
(
	PLAY_TYPE
);

