-- ============================================
-- Process Workflow Tables (Application Database)
-- These tables are NOT part of PPDM standard
-- They should be created in a separate application database
-- ============================================

-- PROCESS_DEFINITION Table
CREATE TABLE PROCESS_DEFINITION
(
    PROCESS_DEFINITION_ID NVARCHAR(50) PRIMARY KEY,
    PROCESS_NAME NVARCHAR(200) NOT NULL,
    PROCESS_TYPE NVARCHAR(50), -- EXPLORATION, DEVELOPMENT, PRODUCTION, DECOMMISSIONING
    ENTITY_TYPE NVARCHAR(50), -- WELL, FIELD, RESERVOIR, PROSPECT, POOL, FACILITY
    DESCRIPTION NVARCHAR(2000),
    PROCESS_CONFIG_JSON NVARCHAR(MAX), -- JSON with steps, transitions, configuration
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    ROW_CREATED_DATE DATETIME DEFAULT GETDATE(),
    ROW_CREATED_BY NVARCHAR(50),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(50)
);

-- PROCESS_INSTANCE Table
CREATE TABLE PROCESS_INSTANCE
(
    PROCESS_INSTANCE_ID NVARCHAR(50) PRIMARY KEY,
    PROCESS_DEFINITION_ID NVARCHAR(50) NOT NULL,
    ENTITY_ID NVARCHAR(50), -- Well, Field, Reservoir, etc.
    ENTITY_TYPE NVARCHAR(50),
    FIELD_ID NVARCHAR(50),
    CURRENT_STATE NVARCHAR(100),
    CURRENT_STEP_ID NVARCHAR(50),
    STATUS NVARCHAR(50), -- NOT_STARTED, IN_PROGRESS, COMPLETED, FAILED, CANCELLED
    START_DATE DATETIME,
    COMPLETION_DATE DATETIME,
    STARTED_BY NVARCHAR(50),
    PROCESS_DATA_JSON NVARCHAR(MAX), -- JSON with process-specific data
    ROW_CREATED_DATE DATETIME DEFAULT GETDATE(),
    ROW_CREATED_BY NVARCHAR(50),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(50),
    FOREIGN KEY (PROCESS_DEFINITION_ID) REFERENCES PROCESS_DEFINITION(PROCESS_DEFINITION_ID)
);

-- PROCESS_STEP_INSTANCE Table
CREATE TABLE PROCESS_STEP_INSTANCE
(
    PROCESS_STEP_INSTANCE_ID NVARCHAR(50) PRIMARY KEY,
    PROCESS_INSTANCE_ID NVARCHAR(50) NOT NULL,
    STEP_ID NVARCHAR(50),
    SEQUENCE_NUMBER INT,
    STATUS NVARCHAR(50), -- PENDING, IN_PROGRESS, COMPLETED, FAILED, SKIPPED
    START_DATE DATETIME,
    COMPLETION_DATE DATETIME,
    COMPLETED_BY NVARCHAR(50),
    STEP_DATA_JSON NVARCHAR(MAX),
    OUTCOME NVARCHAR(50), -- SUCCESS, FAILED, CONDITIONAL
    NOTES NVARCHAR(2000),
    ROW_CREATED_DATE DATETIME DEFAULT GETDATE(),
    ROW_CREATED_BY NVARCHAR(50),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(50),
    FOREIGN KEY (PROCESS_INSTANCE_ID) REFERENCES PROCESS_INSTANCE(PROCESS_INSTANCE_ID)
);

-- PROCESS_HISTORY Table
CREATE TABLE PROCESS_HISTORY
(
    PROCESS_HISTORY_ID NVARCHAR(50) PRIMARY KEY,
    PROCESS_INSTANCE_ID NVARCHAR(50) NOT NULL,
    PROCESS_STEP_INSTANCE_ID NVARCHAR(50),
    ACTION NVARCHAR(100), -- STATE_CHANGE, STEP_STARTED, STEP_COMPLETED, etc.
    PREVIOUS_STATE NVARCHAR(100),
    NEW_STATE NVARCHAR(100),
    ACTION_DATE DATETIME DEFAULT GETDATE(),
    PERFORMED_BY NVARCHAR(50),
    NOTES NVARCHAR(2000),
    ACTION_DATA_JSON NVARCHAR(MAX),
    ROW_CREATED_DATE DATETIME DEFAULT GETDATE(),
    ROW_CREATED_BY NVARCHAR(50),
    FOREIGN KEY (PROCESS_INSTANCE_ID) REFERENCES PROCESS_INSTANCE(PROCESS_INSTANCE_ID),
    FOREIGN KEY (PROCESS_STEP_INSTANCE_ID) REFERENCES PROCESS_STEP_INSTANCE(PROCESS_STEP_INSTANCE_ID)
);

-- PROCESS_APPROVAL Table
CREATE TABLE PROCESS_APPROVAL
(
    PROCESS_APPROVAL_ID NVARCHAR(50) PRIMARY KEY,
    PROCESS_STEP_INSTANCE_ID NVARCHAR(50) NOT NULL,
    APPROVAL_TYPE NVARCHAR(50), -- STEP_APPROVAL, STATE_TRANSITION_APPROVAL
    REQUESTED_DATE DATETIME DEFAULT GETDATE(),
    REQUESTED_BY NVARCHAR(50),
    APPROVED_DATE DATETIME,
    APPROVED_BY NVARCHAR(50),
    APPROVAL_STATUS NVARCHAR(50), -- PENDING, APPROVED, REJECTED
    APPROVAL_NOTES NVARCHAR(2000),
    ROW_CREATED_DATE DATETIME DEFAULT GETDATE(),
    ROW_CREATED_BY NVARCHAR(50),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(50),
    FOREIGN KEY (PROCESS_STEP_INSTANCE_ID) REFERENCES PROCESS_STEP_INSTANCE(PROCESS_STEP_INSTANCE_ID)
);

-- Indexes for performance
CREATE INDEX IX_PROCESS_INSTANCE_ENTITY ON PROCESS_INSTANCE(ENTITY_ID, ENTITY_TYPE);
CREATE INDEX IX_PROCESS_INSTANCE_FIELD ON PROCESS_INSTANCE(FIELD_ID);
CREATE INDEX IX_PROCESS_INSTANCE_STATUS ON PROCESS_INSTANCE(STATUS);
CREATE INDEX IX_PROCESS_STEP_INSTANCE_PROCESS ON PROCESS_STEP_INSTANCE(PROCESS_INSTANCE_ID);
CREATE INDEX IX_PROCESS_HISTORY_INSTANCE ON PROCESS_HISTORY(PROCESS_INSTANCE_ID);
CREATE INDEX IX_PROCESS_APPROVAL_STEP ON PROCESS_APPROVAL(PROCESS_STEP_INSTANCE_ID);

