raiserror ('CREATING TABLE PRODUCTION_ALLOCATION', 10,1) with nowait
CREATE TABLE production_allocation
(
	PRODUCTION_ALLOCATION_ID NVARCHAR(40) NOT NULL,
	PDEN_ID NVARCHAR(40),
	FIELD_ID NVARCHAR(40),
	WELL_ID NVARCHAR(40),
	POOL_ID NVARCHAR(40),
	ALLOCATION_DATE DATE NOT NULL,
	TOTAL_PRODUCTION NUMERIC(18,2) NOT NULL,  -- barrels
	ALLOCATION_METHOD NVARCHAR(40) NOT NULL,  -- 'WORKING_INTEREST', 'NET_REVENUE_INTEREST', 'MEASURED', 'EQUAL'
	ALLOCATION_RESULTS_JSON NVARCHAR(MAX),  -- JSON serialized allocation results
	DESCRIPTION NVARCHAR(2000),
	ACTIVE_IND NVARCHAR(1),
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_ID NVARCHAR(40) NOT NULL,
	CONSTRAINT production_allocation_PK PRIMARY KEY (PRODUCTION_ALLOCATION_ID)
)

