raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_WORKFLOW_STAGE_PROSPECT_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_WORKFLOW_STAGE ADD CONSTRAINT PROSPECT_WORKFLOW_STAGE_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_WORKFLOW_STAGE_STAGE_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_WORKFLOW_STAGE ADD CONSTRAINT PROSPECT_WORKFLOW_STAGE_STAGE_FK FOREIGN KEY
(
	WORKFLOW_STAGE
)
REFERENCES R_WORKFLOW_STAGE
(
	WORKFLOW_STAGE
);
