raiserror ('CREATING TABLE PROSPECT_RANKING', 10,1) with nowait
CREATE TABLE prospect_ranking
(
	PROSPECT_ID NVARCHAR(40) NOT NULL,
	RANKING_ID NVARCHAR(40) NOT NULL,
	RANKING_SCORE NUMERIC(10,5),
	PRIORITY_ORDER NUMERIC(10,0),
	RANKING_CRITERIA NVARCHAR(2000),
	RANKING_DATE DATE,
	RANKER NVARCHAR(40),
	METHODOLOGY NVARCHAR(240),
	DESCRIPTION NVARCHAR(240),
	ACTIVE_IND NVARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);
