raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_RISK_ASSESSMENT_PROSPECT_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_RISK_ASSESSMENT ADD CONSTRAINT PROSPECT_RISK_ASSESSMENT_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);
