raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_FIELD_FK', 10, 1) with nowait
ALTER TABLE PROSPECT ADD CONSTRAINT PROSPECT_FIELD_FK FOREIGN KEY
(
	PRIMARY_FIELD_ID
)
REFERENCES FIELD
(
	FIELD_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_PLAY_FK', 10, 1) with nowait
ALTER TABLE PROSPECT ADD CONSTRAINT PROSPECT_PLAY_FK FOREIGN KEY
(
	PLAY_ID
)
REFERENCES PLAY
(
	PLAY_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_TYPE_FK', 10, 1) with nowait
ALTER TABLE PROSPECT ADD CONSTRAINT PROSPECT_TYPE_FK FOREIGN KEY
(
	PROSPECT_TYPE
)
REFERENCES R_PROSPECT_TYPE
(
	PROSPECT_TYPE
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_STATUS_FK', 10, 1) with nowait
ALTER TABLE PROSPECT ADD CONSTRAINT PROSPECT_STATUS_FK FOREIGN KEY
(
	PROSPECT_STATUS
)
REFERENCES R_PROSPECT_STATUS
(
	PROSPECT_STATUS
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_RISK_LEVEL_FK', 10, 1) with nowait
ALTER TABLE PROSPECT ADD CONSTRAINT PROSPECT_RISK_LEVEL_FK FOREIGN KEY
(
	RISK_LEVEL
)
REFERENCES R_RISK_LEVEL
(
	RISK_LEVEL
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_BA_FK', 10, 1) with nowait
ALTER TABLE PROSPECT ADD CONSTRAINT PROSPECT_BA_FK FOREIGN KEY
(
	CURRENT_OPERATOR
)
REFERENCES BUSINESS_ASSOCIATE
(
	BUSINESS_ASSOCIATE_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_STRAT_UNIT_FK', 10, 1) with nowait
ALTER TABLE PROSPECT ADD CONSTRAINT PROSPECT_STRAT_UNIT_FK FOREIGN KEY
(
	STRAT_UNIT_ID
)
REFERENCES STRAT_UNIT
(
	STRAT_UNIT_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_CS_FK', 10, 1) with nowait
ALTER TABLE PROSPECT ADD CONSTRAINT PROSPECT_CS_FK FOREIGN KEY
(
	COORD_SYSTEM_ID
)
REFERENCES CS_COORDINATE_SYSTEM
(
	COORD_SYSTEM_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_LOCAL_CS_FK', 10, 1) with nowait
ALTER TABLE PROSPECT ADD CONSTRAINT PROSPECT_LOCAL_CS_FK FOREIGN KEY
(
	LOCAL_COORD_SYSTEM_ID
)
REFERENCES CS_COORDINATE_SYSTEM
(
	COORD_SYSTEM_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_CA_FK', 10, 1) with nowait
ALTER TABLE PROSPECT ADD CONSTRAINT PROSPECT_CA_FK FOREIGN KEY
(
	COORD_ACQUISITION_ID
)
REFERENCES CS_COORD_ACQUISITION
(
	ACQUISITION_ID
);

