raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_TRAP_PROSPECT_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_TRAP ADD CONSTRAINT PROSPECT_TRAP_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_TRAP_TYPE_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_TRAP ADD CONSTRAINT PROSPECT_TRAP_TYPE_FK FOREIGN KEY
(
	TRAP_TYPE
)
REFERENCES R_TRAP_TYPE
(
	TRAP_TYPE
);
