raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_SEIS_SURVEY_PROSPECT_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_SEIS_SURVEY ADD CONSTRAINT PROSPECT_SEIS_SURVEY_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_SEIS_SURVEY_SEIS_SET_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_SEIS_SURVEY ADD CONSTRAINT PROSPECT_SEIS_SURVEY_SEIS_SET_FK FOREIGN KEY
(
	SEIS_SET_ID
)
REFERENCES SEIS_SET
(
	SEIS_SET_ID
);

