raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_FIELD_PROSPECT_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_FIELD ADD CONSTRAINT PROSPECT_FIELD_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_FIELD_FIELD_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_FIELD ADD CONSTRAINT PROSPECT_FIELD_FIELD_FK FOREIGN KEY
(
	FIELD_ID
)
REFERENCES FIELD
(
	FIELD_ID
);

