raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_PLAY_PROSPECT_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_PLAY ADD CONSTRAINT PROSPECT_PLAY_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_PLAY_PLAY_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_PLAY ADD CONSTRAINT PROSPECT_PLAY_PLAY_FK FOREIGN KEY
(
	PLAY_ID
)
REFERENCES PLAY
(
	PLAY_ID
);

