raiserror ('CREATING TABLE PROSPECT_ANALOG', 10,1) with nowait
CREATE TABLE prospect_analog
(
	PROSPECT_ID NVARCHAR(40) NOT NULL,
	ANALOG_ID NVARCHAR(40) NOT NULL,
	ANALOG_TYPE NVARCHAR(40),
	ANALOG_PROSPECT_ID NVARCHAR(40),
	ANALOG_FIELD_ID NVARCHAR(40),
	SIMILARITY_SCORE NUMERIC(5,4),
	KEY_SIMILARITIES NVARCHAR(2000),
	USE_CASE NVARCHAR(240),
	DESCRIPTION NVARCHAR(240),
	ACTIVE_IND NVARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);
