raiserror ('CREATING PRIMARY KEY PROSPECT_VOLUME_ESTIMATE_PK', 10, 1) with nowait
ALTER TABLE PROSPECT_VOLUME_ESTIMATE ADD CONSTRAINT PROSPECT_VOLUME_ESTIMATE_PK PRIMARY KEY
(
	PROSPECT_ID,
	ESTIMATE_ID
);
