raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_VOLUME_ESTIMATE_PROSPECT_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_VOLUME_ESTIMATE ADD CONSTRAINT PROSPECT_VOLUME_ESTIMATE_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);
