raiserror ('CREATING TABLE PROSPECT_HISTORY', 10,1) with nowait
CREATE TABLE prospect_history
(
	PROSPECT_ID NVARCHAR(40) NOT NULL,
	HISTORY_SEQ_NO NUMERIC(10,0) NOT NULL,
	FIELD_NAME NVARCHAR(40),
	OLD_VALUE NVARCHAR(2000),
	NEW_VALUE NVARCHAR(2000),
	CHANGE_REASON NVARCHAR(240),
	CHANGED_BY NVARCHAR(40),
	CHANGE_DATE DATE,
	DESCRIPTION NVARCHAR(240),
	ACTIVE_IND NVARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);
