raiserror ('CREATING TABLE PROSPECT_MIGRATION', 10,1) with nowait
CREATE TABLE prospect_migration
(
	PROSPECT_ID NVARCHAR(40) NOT NULL,
	MIGRATION_ID NVARCHAR(40) NOT NULL,
	MIGRATION_PATHWAY NVARCHAR(240),
	MIGRATION_DISTANCE NUMERIC(10,5),
	MIGRATION_DISTANCE_OUOM NVARCHAR(40),
	MIGRATION_EFFICIENCY NUMERIC(5,4),
	MIGRATION_TIMING NVARCHAR(40),
	CARRIER_BED NVARCHAR(40),
	SEAL_BREACH_RISK NUMERIC(5,4),
	DESCRIPTION NVARCHAR(240),
	ACTIVE_IND NVARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);
