raiserror ('CREATING PRIMARY KEY PROSPECT_WORKFLOW_STAGE_PK', 10, 1) with nowait
ALTER TABLE PROSPECT_WORKFLOW_STAGE ADD CONSTRAINT PROSPECT_WORKFLOW_STAGE_PK PRIMARY KEY
(
	PROSPECT_ID,
	STAGE_SEQ_NO
);
