raiserror ('CREATING TABLE PROSPECT_WORKFLOW_STAGE', 10,1) with nowait
CREATE TABLE prospect_workflow_stage
(
	PROSPECT_ID NVARCHAR(40) NOT NULL,
	STAGE_SEQ_NO NUMERIC(10,0) NOT NULL,
	WORKFLOW_STAGE NVARCHAR(40),
	STAGE_START_DATE DATE,
	STAGE_END_DATE DATE,
	STAGE_OUTCOME NVARCHAR(40),
	NEXT_STAGE NVARCHAR(40),
	APPROVALS_REQUIRED NVARCHAR(2000),
	DESCRIPTION NVARCHAR(240),
	ACTIVE_IND NVARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);
