raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_DISCOVERY_PROSPECT_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_DISCOVERY ADD CONSTRAINT PROSPECT_DISCOVERY_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_DISCOVERY_TYPE_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_DISCOVERY ADD CONSTRAINT PROSPECT_DISCOVERY_TYPE_FK FOREIGN KEY
(
	DISCOVERY_TYPE
)
REFERENCES R_DISCOVERY_TYPE
(
	DISCOVERY_TYPE
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_DISCOVERY_WELL_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_DISCOVERY ADD CONSTRAINT PROSPECT_DISCOVERY_WELL_FK FOREIGN KEY
(
	DISCOVERY_WELL
)
REFERENCES WELL
(
	UWI
);
