raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_RANKING_PROSPECT_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_RANKING ADD CONSTRAINT PROSPECT_RANKING_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);
