raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_ANALOG_PROSPECT_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_ANALOG ADD CONSTRAINT PROSPECT_ANALOG_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_ANALOG_ANALOG_PROSPECT_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_ANALOG ADD CONSTRAINT PROSPECT_ANALOG_ANALOG_PROSPECT_FK FOREIGN KEY
(
	ANALOG_PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_ANALOG_ANALOG_FIELD_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_ANALOG ADD CONSTRAINT PROSPECT_ANALOG_ANALOG_FIELD_FK FOREIGN KEY
(
	ANALOG_FIELD_ID
)
REFERENCES FIELD
(
	FIELD_ID
);
