raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_WELL_PROSPECT_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_WELL ADD CONSTRAINT PROSPECT_WELL_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_WELL_WELL_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_WELL ADD CONSTRAINT PROSPECT_WELL_WELL_FK FOREIGN KEY
(
	UWI
)
REFERENCES WELL
(
	UWI
);

