raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_SOURCE_ROCK_PROSPECT_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_SOURCE_ROCK ADD CONSTRAINT PROSPECT_SOURCE_ROCK_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_SOURCE_ROCK_STRAT_UNIT_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_SOURCE_ROCK ADD CONSTRAINT PROSPECT_SOURCE_ROCK_STRAT_UNIT_FK FOREIGN KEY
(
	STRAT_UNIT_ID
)
REFERENCES STRAT_UNIT
(
	STRAT_UNIT_ID
);
