raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_MIGRATION_PROSPECT_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_MIGRATION ADD CONSTRAINT PROSPECT_MIGRATION_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);
