raiserror ('CREATING PRIMARY KEY PROSPECT_RISK_ASSESSMENT_PK', 10, 1) with nowait
ALTER TABLE PROSPECT_RISK_ASSESSMENT ADD CONSTRAINT PROSPECT_RISK_ASSESSMENT_PK PRIMARY KEY
(
	PROSPECT_ID,
	ASSESSMENT_ID
);
