raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_BA_PROSPECT_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_BA ADD CONSTRAINT PROSPECT_BA_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT PROSPECT_BA_BA_FK', 10, 1) with nowait
ALTER TABLE PROSPECT_BA ADD CONSTRAINT PROSPECT_BA_BA_FK FOREIGN KEY
(
	BUSINESS_ASSOCIATE_ID
)
REFERENCES BUSINESS_ASSOCIATE
(
	BUSINESS_ASSOCIATE_ID
);
