raiserror ('CREATING TABLE PURCHASE_ORDER', 10,1) with nowait
CREATE TABLE PURCHASE_ORDER
(
    PURCHASE_ORDER_ID NVARCHAR(40) NOT NULL,
    PO_NUMBER NVARCHAR(40),
    VENDOR_BA_ID NVARCHAR(40),
    PO_DATE DATE,
    EXPECTED_DELIVERY_DATE DATE,
    TOTAL_AMOUNT NUMERIC(18,2),
    STATUS NVARCHAR(40),
    DESCRIPTION NVARCHAR(4000),
    ACTIVE_IND NVARCHAR(1),
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(4000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(40),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);

