raiserror ('CREATING TABLE R_PLAY_TYPE', 10,1) with nowait
CREATE TABLE r_play_type
(
	PLAY_TYPE NVARCHAR(40) NOT NULL,
	ABBREVIATION NVARCHAR(12),
	ACTIVE_IND NVARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	LONG_NAME NVARCHAR(255),
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SHORT_NAME NVARCHAR(30),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY NVARCHAR(40)
);
