raiserror ('CREATING TABLE RESERVOIR_STATUS', 10,1) with nowait
CREATE TABLE RESERVOIR_STATUS
(
	RESERVOIR_STATUS_ID NVARCHAR(50) NOT NULL,
	RESERVE_ENTITY_ID NVARCHAR(40), -- Links to RESERVE_ENTITY or POOL_ID
	POOL_ID NVARCHAR(40), -- Alternative link to POOL
	STATUS NVARCHAR(50) NOT NULL, -- DISCOVERED, APPRAISED, DEVELOPED, PRODUCING, DEPLETED, ABANDONED, REJECTED
	STATUS_DATE DATETIME NOT NULL,
	STATUS_CHANGED_BY NVARCHAR(50),
	NOTES NVARCHAR(2000),
	ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATETIME,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATETIME,
	ROW_EFFECTIVE_DATE DATETIME,
	ROW_EXPIRY_DATE DATETIME,
	ROW_QUALITY NVARCHAR(40)
);

