raiserror ('CREATING FOREIGN KEY CONSTRAINT RESERVOIR_STATUS_RESERVE_ENTITY_FK', 10, 1) with nowait
ALTER TABLE RESERVOIR_STATUS ADD CONSTRAINT RESERVOIR_STATUS_RESERVE_ENTITY_FK FOREIGN KEY
(
	RESERVE_ENTITY_ID
)
REFERENCES RESERVE_ENTITY
(
	RESERVE_ENTITY_ID
);

raiserror ('CREATING FOREIGN KEY CONSTRAINT RESERVOIR_STATUS_POOL_FK', 10, 1) with nowait
ALTER TABLE RESERVOIR_STATUS ADD CONSTRAINT RESERVOIR_STATUS_POOL_FK FOREIGN KEY
(
	POOL_ID
)
REFERENCES POOL
(
	POOL_ID
);

