raiserror ('CREATING TABLE REVENUE_DISTRIBUTION', 10,1) with nowait
CREATE TABLE revenue_distribution
(
	REVENUE_DISTRIBUTION_ID NVARCHAR(40) NOT NULL,
	REVENUE_TRANSACTION_ID NVARCHAR(40) NOT NULL,
	INT_SET_PARTNER_ID NVARCHAR(40),  -- Link to INT_SET_PARTNER for NRI
	BUSINESS_ASSOCIATE_ID NVARCHAR(40),  -- Party receiving revenue
	WORKING_INTEREST_PERCENTAGE NUMERIC(10,4),
	NET_REVENUE_INTEREST_PERCENTAGE NUMERIC(10,4),
	REVENUE_AMOUNT NUMERIC(18,2) NOT NULL,
	DESCRIPTION NVARCHAR(2000),
	ACTIVE_IND NVARCHAR(1),
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_ID NVARCHAR(40) NOT NULL,
	CONSTRAINT revenue_distribution_PK PRIMARY KEY (REVENUE_DISTRIBUTION_ID)
)

