raiserror ('CREATING TABLE REVENUE_DEDUCTION', 10,1) with nowait
CREATE TABLE revenue_deduction
(
	REVENUE_DEDUCTION_ID NVARCHAR(40) NOT NULL,
	REVENUE_TRANSACTION_ID NVARCHAR(40) NOT NULL,
	DEDUCTION_TYPE NVARCHAR(40) NOT NULL,  -- 'TRANSPORTATION', 'PROCESSING', 'MARKETING', 'TAXES'
	AMOUNT NUMERIC(18,2) NOT NULL,
	DESCRIPTION NVARCHAR(2000),
	ACTIVE_IND NVARCHAR(1),
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_ID NVARCHAR(40) NOT NULL,
	CONSTRAINT revenue_deduction_PK PRIMARY KEY (REVENUE_DEDUCTION_ID)
)

