raiserror ('CREATING TABLE REVENUE_TRANSACTION', 10,1) with nowait
CREATE TABLE revenue_transaction
(
	REVENUE_TRANSACTION_ID NVARCHAR(40) NOT NULL,
	FINANCE_ID NVARCHAR(40),  -- Link to parent FINANCE transaction
	FIELD_ID NVARCHAR(40),
	WELL_ID NVARCHAR(40),
	PDEN_ID NVARCHAR(40),
	PRODUCTION_DATE DATE NOT NULL,
	OIL_VOLUME NUMERIC(18,2),
	GAS_VOLUME NUMERIC(18,2),
	OIL_PRICE NUMERIC(18,2),
	GAS_PRICE NUMERIC(18,2),
	GROSS_REVENUE NUMERIC(18,2) NOT NULL,
	NET_REVENUE NUMERIC(18,2),
	REVENUE_RECOGNITION_STATUS NVARCHAR(40),  -- 'PENDING', 'RECOGNIZED', 'DEFERRED'
	DESCRIPTION NVARCHAR(2000),
	ACTIVE_IND NVARCHAR(1),
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_ID NVARCHAR(40) NOT NULL,
	CONSTRAINT revenue_transaction_PK PRIMARY KEY (REVENUE_TRANSACTION_ID)
)

