raiserror ('CREATING TABLE ROYALTY_CALCULATION', 10,1) with nowait
CREATE TABLE royalty_calculation
(
	ROYALTY_CALCULATION_ID NVARCHAR(40) NOT NULL,
	OBLIGATION_ID NVARCHAR(40),  -- Link to OBLIGATION
	REVENUE_TRANSACTION_ID NVARCHAR(40),
	FIELD_ID NVARCHAR(40),
	WELL_ID NVARCHAR(40),
	CALCULATION_DATE DATE NOT NULL,
	PRODUCTION_VOLUME NUMERIC(18,2),
	ROYALTY_RATE NUMERIC(10,4) NOT NULL,
	ROYALTY_AMOUNT NUMERIC(18,2) NOT NULL,
	GROSS_REVENUE NUMERIC(18,2),
	DEDUCTIONS NUMERIC(18,2),
	NET_REVENUE NUMERIC(18,2),
	DESCRIPTION NVARCHAR(2000),
	ACTIVE_IND NVARCHAR(1),
	PPDM_GUID NVARCHAR(38),
	REMARK NVARCHAR(2000),
	SOURCE NVARCHAR(40),
	ROW_CHANGED_BY NVARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY NVARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_ID NVARCHAR(40) NOT NULL,
	CONSTRAINT royalty_calculation_PK PRIMARY KEY (ROYALTY_CALCULATION_ID)
)

