ALTER TABLE "DIVISION_ORDER"
ADD CONSTRAINT FK_DIVISION_ORDER_PROPERTY FOREIGN KEY ("PROPERTY_ID") REFERENCES "PROPERTY"("PROPERTY_ID");

ALTER TABLE "DIVISION_ORDER"
ADD CONSTRAINT FK_DIVISION_ORDER_OWNER_BA FOREIGN KEY ("OWNER_BA_ID") REFERENCES "OWNER_BA"("OWNER_BA_ID");
