CREATE TABLE "OWNERSHIP_INTEREST"
(
    "OWNERSHIP_INTEREST_ID" VARCHAR(40) NOT NULL,
    "PROPERTY_ID" VARCHAR(40),
    "OWNER_BA_ID" VARCHAR(40),
    "WORKING_INTEREST" NUMERIC(18,2),
    "NET_REVENUE_INTEREST" NUMERIC(18,2),
    "ROYALTY_INTEREST" NUMERIC(18,2),
    "OVERRIDING_ROYALTY_INTEREST" NUMERIC(18,2),
    "EFFECTIVE_START_DATE" TIMESTAMP,
    "EFFECTIVE_END_DATE" TIMESTAMP,
    "DIVISION_ORDER_ID" VARCHAR(40),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP
);
