CREATE TABLE "TRANSFER_ORDER"
(
    "TRANSFER_ORDER_ID" VARCHAR(40) NOT NULL,
    "PROPERTY_ID" VARCHAR(40),
    "FROM_OWNER_BA_ID" VARCHAR(40),
    "TO_OWNER_BA_ID" VARCHAR(40),
    "INTEREST_TRANSFERRED" NUMERIC(18,2),
    "EFFECTIVE_DATE" TIMESTAMP,
    "IS_APPROVED" VARCHAR(255),
    "APPROVAL_DATE" TIMESTAMP,
    "APPROVED_BY" VARCHAR(255),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP
);
