CREATE TABLE "GOVERNMENT_LEASE"
(
    "LEASE_ID" VARCHAR(40),
    "PROPERTY_ID" VARCHAR(40),
    "GOVERNMENT_AGENCY" VARCHAR(255),
    "LEASE_NUMBER" VARCHAR(255),
    "IS_FEDERAL" VARCHAR(255),
    "IS_INDIAN" VARCHAR(255),
    "EFFECTIVE_DATE" TIMESTAMP,
    "EXPIRATION_DATE" TIMESTAMP,
    "WORKING_INTEREST" NUMERIC(18,2),
    "NET_REVENUE_INTEREST" NUMERIC(18,2),
    "ROYALTY_RATE" NUMERIC(18,2),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP
);
