CREATE TABLE `ROD_SECTION`
(
    `ROD_SECTION_ID` VARCHAR(40) NOT NULL,
    `SUCKER_ROD_STRING_ID` VARCHAR(40),
    `DIAMETER` DECIMAL(18,2),
    `LENGTH` DECIMAL(18,2),
    `DENSITY` DECIMAL(18,2),
    `WEIGHT` DECIMAL(18,2),
    `SECTION_ORDER` INT,
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_QUALITY` VARCHAR(40)
);
