using System.ComponentModel;

namespace Beep.OilandGas.Models.Enums.Shared
{
    public enum CurrencyCode
    {
        [Description("US Dollar (USD)")] USD,
        [Description("Euro (EUR)")] EUR,
        [Description("British Pound (GBP)")] GBP,
        [Description("Japanese Yen (JPY)")] JPY,
        [Description("Canadian Dollar (CAD)")] CAD,
        [Description("Australian Dollar (AUD)")] AUD,
        [Description("Swiss Franc (CHF)")] CHF,
        [Description("Chinese Yuan (CNY)")] CNY,
        [Description("UAE Dirham (AED)")] AED,
        [Description("Afghan Afghani (AFN)")] AFN,
        [Description("Albanian Lek (ALL)")] ALL,
        [Description("Armenian Dram (AMD)")] AMD,
        [Description("Neth. Antillean Guilder (ANG)")] ANG,
        [Description("Angolan Kwanza (AOA)")] AOA,
        [Description("Argentine Peso (ARS)")] ARS,
        [Description("Azerbaijani Manat (AZN)")] AZN,
        [Description("Bosnia-Herzegovina Mark (BAM)")] BAM,
        [Description("Barbados Dollar (BBD)")] BBD,
        [Description("Bangladesh Taka (BDT)")] BDT,
        [Description("Bulgarian Lev (BGN)")] BGN,
        [Description("Bahraini Dinar (BHD)")] BHD,
        [Description("Burundian Franc (BIF)")] BIF,
        [Description("Bermudian Dollar (BMD)")] BMD,
        [Description("Brunei Dollar (BND)")] BND,
        [Description("Boliviano (BOB)")] BOB,
        [Description("Brazilian Real (BRL)")] BRL,
        [Description("Bahamian Dollar (BSD)")] BSD,
        [Description("Bhutanese Ngultrum (BTN)")] BTN,
        [Description("Botswana Pula (BWP)")] BWP,
        [Description("Belarusian Ruble (BYN)")] BYN,
        [Description("Belize Dollar (BZD)")] BZD,
        [Description("Congolese Franc (CDF)")] CDF,
        [Description("Chilean Peso (CLP)")] CLP,
        [Description("Colombian Peso (COP)")] COP,
        [Description("Costa Rican Colon (CRC)")] CRC,
        [Description("Cuban Peso (CUP)")] CUP,
        [Description("Cape Verde Escudo (CVE)")] CVE,
        [Description("Czech Koruna (CZK)")] CZK,
        [Description("Djiboutian Franc (DJF)")] DJF,
        [Description("Danish Krone (DKK)")] DKK,
        [Description("Dominican Peso (DOP)")] DOP,
        [Description("Algerian Dinar (DZD)")] DZD,
        [Description("Egyptian Pound (EGP)")] EGP,
        [Description("Eritrean Nakfa (ERN)")] ERN,
        [Description("Ethiopian Birr (ETB)")] ETB,
        [Description("Fiji Dollar (FJD)")] FJD,
        [Description("Falkland Islands Pound (FKP)")] FKP,
        [Description("Georgian Lari (GEL)")] GEL,
        [Description("Ghanaian Cedi (GHS)")] GHS,
        [Description("Gibraltar Pound (GIP)")] GIP,
        [Description("Gambian Dalasi (GMD)")] GMD,
        [Description("Guinean Franc (GNF)")] GNF,
        [Description("Guatemalan Quetzal (GTQ)")] GTQ,
        [Description("Guyanese Dollar (GYD)")] GYD,
        [Description("Hong Kong Dollar (HKD)")] HKD,
        [Description("Honduran Lempira (HNL)")] HNL,
        [Description("Croatian Kuna (HRK)")] HRK,
        [Description("Haitian Gourde (HTG)")] HTG,
        [Description("Hungarian Forint (HUF)")] HUF,
        [Description("Indonesian Rupiah (IDR)")] IDR,
        [Description("Israeli New Shekel (ILS)")] ILS,
        [Description("Indian Rupee (INR)")] INR,
        [Description("Iraqi Dinar (IQD)")] IQD,
        [Description("Iranian Rial (IRR)")] IRR,
        [Description("Icelandic Krona (ISK)")] ISK,
        [Description("Jamaican Dollar (JMD)")] JMD,
        [Description("Jordanian Dinar (JOD)")] JOD,
        [Description("Kenyan Shilling (KES)")] KES,
        [Description("Kyrgyzstani Som (KGS)")] KGS,
        [Description("Cambodian Riel (KHR)")] KHR,
        [Description("Comorian Franc (KMF)")] KMF,
        [Description("North Korean Won (KPW)")] KPW,
        [Description("South Korean Won (KRW)")] KRW,
        [Description("Kuwaiti Dinar (KWD)")] KWD,
        [Description("Cayman Islands Dollar (KYD)")] KYD,
        [Description("Kazakhstani Tenge (KZT)")] KZT,
        [Description("Lao Kip (LAK)")] LAK,
        [Description("Lebanese Pound (LBP)")] LBP,
        [Description("Sri Lankan Rupee (LKR)")] LKR,
        [Description("Liberian Dollar (LRD)")] LRD,
        [Description("Lesotho Loti (LSL)")] LSL,
        [Description("Libyan Dinar (LYD)")] LYD,
        [Description("Moroccan Dirham (MAD)")] MAD,
        [Description("Moldovan Leu (MDL)")] MDL,
        [Description("Malagasy Ariary (MGA)")] MGA,
        [Description("Macedonian Denar (MKD)")] MKD,
        [Description("Myanmar Kyat (MMK)")] MMK,
        [Description("Mongolian Tugrik (MNT)")] MNT,
        [Description("Macanese Pataca (MOP)")] MOP,
        [Description("Mauritanian Ouguiya (MRU)")] MRU,
        [Description("Mauritian Rupee (MUR)")] MUR,
        [Description("Maldivian Rufiyaa (MVR)")] MVR,
        [Description("Malawian Kwacha (MWK)")] MWK,
        [Description("Mexican Peso (MXN)")] MXN,
        [Description("Malaysian Ringgit (MYR)")] MYR,
        [Description("Mozambican Metical (MZN)")] MZN,
        [Description("Namibian Dollar (NAD)")] NAD,
        [Description("Nigerian Naira (NGN)")] NGN,
        [Description("Nicaraguan Cordoba (NIO)")] NIO,
        [Description("Norwegian Krone (NOK)")] NOK,
        [Description("Nepalese Rupee (NPR)")] NPR,
        [Description("New Zealand Dollar (NZD)")] NZD,
        [Description("Omani Rial (OMR)")] OMR,
        [Description("Panamanian Balboa (PAB)")] PAB,
        [Description("Peruvian Sol (PEN)")] PEN,
        [Description("Papua New Guinean Kina (PGK)")] PGK,
        [Description("Philippine Peso (PHP)")] PHP,
        [Description("Pakistani Rupee (PKR)")] PKR,
        [Description("Polish Zloty (PLN)")] PLN,
        [Description("Paraguayan Guarani (PYG)")] PYG,
        [Description("Qatari Riyal (QAR)")] QAR,
        [Description("Romanian Leu (RON)")] RON,
        [Description("Serbian Dinar (RSD)")] RSD,
        [Description("Russian Ruble (RUB)")] RUB,
        [Description("Rwandan Franc (RWF)")] RWF,
        [Description("Saudi Riyal (SAR)")] SAR,
        [Description("Solomon Islands Dollar (SBD)")] SBD,
        [Description("Seychellois Rupee (SCR)")] SCR,
        [Description("Sudanese Pound (SDG)")] SDG,
        [Description("Swedish Krona (SEK)")] SEK,
        [Description("Singapore Dollar (SGD)")] SGD,
        [Description("Saint Helena Pound (SHP)")] SHP,
        [Description("Sierra Leonean Leone (SLL)")] SLL,
        [Description("Somali Shilling (SOS)")] SOS,
        [Description("Surinamese Dollar (SRD)")] SRD,
        [Description("South Sudanese Pound (SSP)")] SSP,
        [Description("Sao Tome Dobra (STN)")] STN,
        [Description("Syrian Pound (SYP)")] SYP,
        [Description("Eswatini Lilangeni (SZL)")] SZL,
        [Description("Thai Baht (THB)")] THB,
        [Description("Tajikistani Somoni (TJS)")] TJS,
        [Description("Turkmenistani Manat (TMT)")] TMT,
        [Description("Tunisian Dinar (TND)")] TND,
        [Description("Tongan Pa'anga (TOP)")] TOP,
        [Description("Turkish Lira (TRY)")] TRY,
        [Description("Trinidad and Tobago Dollar (TTD)")] TTD,
        [Description("New Taiwan Dollar (TWD)")] TWD,
        [Description("Tanzanian Shilling (TZS)")] TZS,
        [Description("Ukrainian Hryvnia (UAH)")] UAH,
        [Description("Ugandan Shilling (UGX)")] UGX,
        [Description("Uruguayan Peso (UYU)")] UYU,
        [Description("Uzbekistani Som (UZS)")] UZS,
        [Description("Venezuelan Bolivar (VEF)")] VEF,
        [Description("Vietnamese Dong (VND)")] VND,
        [Description("Vanuatu Vatu (VUV)")] VUV,
        [Description("Samoan Tala (WST)")] WST,
        [Description("CFA Franc BEAC (XAF)")] XAF,
        [Description("East Caribbean Dollar (XCD)")] XCD,
        [Description("CFA Franc BCEAO (XOF)")] XOF,
        [Description("CFP Franc (XPF)")] XPF,
        [Description("Yemeni Rial (YER)")] YER,
        [Description("South African Rand (ZAR)")] ZAR,
        [Description("Zambian Kwacha (ZMW)")] ZMW,
        [Description("Zimbabwean Dollar (ZWL)")] ZWL,
        [Description("Unknown")] Unknown
    }
}
