ALTER TABLE `DATA_QUALITY_METRICS`
ADD CONSTRAINT FK_DATA_QUALITY_METRICS_METRICS FOREIGN KEY (`METRICS_ID`) REFERENCES `METRICS`(`METRICS_ID`);

ALTER TABLE `DATA_QUALITY_METRICS`
ADD CONSTRAINT FK_DATA_QUALITY_METRICS_AREA FOREIGN KEY (`AREA_ID`) REFERENCES `AREA`(`AREA_ID`);

ALTER TABLE `DATA_QUALITY_METRICS`
ADD CONSTRAINT FK_DATA_QUALITY_METRICS_BUSINESS_ASSOCIATE FOREIGN KEY (`BUSINESS_ASSOCIATE_ID`) REFERENCES `BUSINESS_ASSOCIATE`(`BUSINESS_ASSOCIATE_ID`);
