ALTER TABLE `DATA_QUALITY_ISSUE`
ADD CONSTRAINT FK_DATA_QUALITY_ISSUE_QUALITY_ISSUE FOREIGN KEY (`QUALITY_ISSUE_ID`) REFERENCES `QUALITY_ISSUE`(`QUALITY_ISSUE_ID`);

ALTER TABLE `DATA_QUALITY_ISSUE`
ADD CONSTRAINT FK_DATA_QUALITY_ISSUE_ENTITY FOREIGN KEY (`ENTITY_ID`) REFERENCES `ENTITY`(`ENTITY_ID`);

ALTER TABLE `DATA_QUALITY_ISSUE`
ADD CONSTRAINT FK_DATA_QUALITY_ISSUE_AREA FOREIGN KEY (`AREA_ID`) REFERENCES `AREA`(`AREA_ID`);

ALTER TABLE `DATA_QUALITY_ISSUE`
ADD CONSTRAINT FK_DATA_QUALITY_ISSUE_BUSINESS_ASSOCIATE FOREIGN KEY (`BUSINESS_ASSOCIATE_ID`) REFERENCES `BUSINESS_ASSOCIATE`(`BUSINESS_ASSOCIATE_ID`);
