raiserror ('CREATING TABLE PRODUCTION_COSTS', 10,1) with nowait

CREATE TABLE PRODUCTION_COSTS
(
    PRODUCTION_COST_ID NVARCHAR(40),
    PROPERTY_ID NVARCHAR(40),
    OPERATING_COSTS NUMERIC(18,2),
    WORKOVER_COSTS NUMERIC(18,2),
    MAINTENANCE_COSTS NUMERIC(18,2),
    TOTAL_PRODUCTION_COSTS NUMERIC(18,2),
    COST_PERIOD DATETIME,
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
