ALTER TABLE PRODUCTION_COSTS
ADD CONSTRAINT FK_PRODUCTION_COSTS_PRODUCTION_COST FOREIGN KEY (PRODUCTION_COST_ID) REFERENCES PRODUCTION_COST(PRODUCTION_COST_ID);

ALTER TABLE PRODUCTION_COSTS
ADD CONSTRAINT FK_PRODUCTION_COSTS_PROPERTY FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID);
