CREATE TABLE "HEAT_MAP_DATA_POINT"
(
    "HEAT_MAP_DATA_POINT_ID" VARCHAR2(40) NOT NULL,
    "HEAT_MAP_ID" VARCHAR2(40),
    "X" NUMBER(18,2),
    "Y" NUMBER(18,2),
    "ORIGINAL_X" NUMBER(18,2),
    "ORIGINAL_Y" NUMBER(18,2),
    "VALUE" NUMBER(18,2),
    "LABEL" VARCHAR2(255),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_QUALITY" VARCHAR2(40)
);
