ALTER TABLE "ESP_DESIGN_PROPERTIES"
ADD CONSTRAINT FK_ESP_DESIGN_PROPERTIES_AREA FOREIGN KEY ("AREA_ID") REFERENCES "AREA"("AREA_ID");

ALTER TABLE "ESP_DESIGN_PROPERTIES"
ADD CONSTRAINT FK_ESP_DESIGN_PROPERTIES_BUSINESS_ASSOCIATE FOREIGN KEY ("BUSINESS_ASSOCIATE_ID") REFERENCES "BUSINESS_ASSOCIATE"("BUSINESS_ASSOCIATE_ID");
