CREATE TABLE `FIELD_PHASE`
(
    `FIELD_PHASE_ID` VARCHAR(40) NOT NULL,
    `FIELD_ID` VARCHAR(40),
    `PHASE` VARCHAR(255),
    `PHASE_START_DATE` DATETIME,
    `PHASE_END_DATE` DATETIME,
    `PHASE_STATUS` VARCHAR(50),
    `TRANSITION_REASON` VARCHAR(255),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_QUALITY` VARCHAR(40)
);
