CREATE TABLE `GOVERNMENT_LEASE`
(
    `LEASE_ID` VARCHAR(40),
    `PROPERTY_ID` VARCHAR(40),
    `GOVERNMENT_AGENCY` VARCHAR(255),
    `LEASE_NUMBER` VARCHAR(255),
    `IS_FEDERAL` VARCHAR(255),
    `IS_INDIAN` VARCHAR(255),
    `EFFECTIVE_DATE` DATETIME,
    `EXPIRATION_DATE` DATETIME,
    `WORKING_INTEREST` DECIMAL(18,2),
    `NET_REVENUE_INTEREST` DECIMAL(18,2),
    `ROYALTY_RATE` DECIMAL(18,2),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME
);
