ALTER TABLE `ROLE_PERMISSION`
ADD CONSTRAINT FK_ROLE_PERMISSION_ROLE FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE`(`ROLE_ID`);

ALTER TABLE `ROLE_PERMISSION`
ADD CONSTRAINT FK_ROLE_PERMISSION_PERMISSION FOREIGN KEY (`PERMISSION_ID`) REFERENCES `PERMISSION`(`PERMISSION_ID`);
