CREATE TABLE `USER_ASSET_ACCESS`
(
    `USER_ID` VARCHAR(40),
    `ASSET_TYPE` VARCHAR(50),
    `ASSET_ID` VARCHAR(40),
    `ACCESS_LEVEL` VARCHAR(255),
    `INHERIT_IND` VARCHAR(255),
    `ORGANIZATION_ID` VARCHAR(40),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `EFFECTIVE_DATE` DATETIME,
    `EXPIRY_DATE` DATETIME,
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_QUALITY` VARCHAR(40)
);
