CREATE TABLE `USER_PROFILE`
(
    `USER_ID` VARCHAR(40),
    `PRIMARY_ROLE` VARCHAR(255),
    `PREFERRED_LAYOUT` VARCHAR(255),
    `USER_PREFERENCES` VARCHAR(255),
    `LAST_LOGIN_DATE` DATETIME,
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `EFFECTIVE_DATE` DATETIME,
    `EXPIRY_DATE` DATETIME,
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_QUALITY` VARCHAR(40)
);
