CREATE TABLE ALLOCATION_DETAIL
(
    ALLOCATION_DETAIL_ID NVARCHAR(40) NOT NULL,
    ALLOCATION_RESULT_ID NVARCHAR(40) NOT NULL,
    ENTITY_ID NVARCHAR(40),
    ENTITY_TYPE NVARCHAR(100),
    ENTITY_NAME NVARCHAR(255),
    ALLOCATED_VOLUME NUMERIC(18,2),
    ALLOCATION_PERCENTAGE NUMERIC(18,6),
    ALLOCATION_BASIS NUMERIC(18,6),
    ACTIVE_IND NVARCHAR(1),
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(4000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(40),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);

