CREATE TABLE LIST_OF_VALUE
(
    LIST_OF_VALUE_ID NVARCHAR(40) NOT NULL,
    VALUE_TYPE NVARCHAR(100) NOT NULL,
    VALUE_CODE NVARCHAR(100) NOT NULL,
    VALUE_NAME NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    CATEGORY NVARCHAR(100),
    MODULE NVARCHAR(100),
    SORT_ORDER INT,
    PARENT_VALUE_ID NVARCHAR(40),
    IS_DEFAULT NVARCHAR(1),
    ACTIVE_IND NVARCHAR(1),
    PPDM_GUID NVARCHAR(38),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATE,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATE,
    ROW_EFFECTIVE_DATE DATE,
    ROW_EXPIRY_DATE DATE,
    ROW_ID BIGINT
);

