CREATE TABLE SALES_AGREEMENT
(
    AGREEMENT_ID TEXT,
    AGREEMENT_NAME TEXT,
    SELLER_BA_ID TEXT,
    PURCHASER_BA_ID TEXT,
    EFFECTIVE_DATE DATETIME,
    EXPIRATION_DATE DATETIME,
    PRICING_METHOD TEXT,
    BASE_PRICE REAL,
    PRICE_INDEX TEXT,
    DIFFERENTIAL REAL,
    PAYMENT_TERMS_DAYS INTEGER,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
