CREATE TABLE STORAGE_AGREEMENT
(
    AGREEMENT_ID TEXT,
    STORAGE_FACILITY_ID TEXT,
    EFFECTIVE_DATE DATETIME,
    EXPIRATION_DATE DATETIME,
    STORAGE_FEE REAL,
    RESERVED_CAPACITY REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT,
    AREA_ID TEXT,
    AREA_TYPE TEXT,
    BUSINESS_ASSOCIATE_ID TEXT,
    EXPIRY_DATE DATETIME
);
