CREATE TABLE TRANSPORTATION_AGREEMENT
(
    AGREEMENT_ID TEXT,
    CARRIER_BA_ID TEXT,
    ORIGIN_POINT TEXT,
    DESTINATION_POINT TEXT,
    EFFECTIVE_DATE DATETIME,
    EXPIRATION_DATE DATETIME,
    TARIFF_RATE REAL,
    MINIMUM_VOLUME_COMMITMENT REAL,
    MAXIMUM_CAPACITY REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
