CREATE TABLE "IMBALANCE"
(
    "IMBALANCE_ID" VARCHAR(40) NOT NULL,
    "NOMINATION_ID" VARCHAR(40),
    "PERIOD_START" TIMESTAMP,
    "PERIOD_END" TIMESTAMP,
    "NOMINATED_VOLUME" NUMERIC(18,2),
    "ACTUAL_VOLUME" NUMERIC(18,2),
    "IMBALANCE_AMOUNT" NUMERIC(18,2),
    "TOLERANCE_PERCENTAGE" NUMERIC(18,6),
    "STATUS" VARCHAR(50),
    "SETTLEMENT_DATE" TIMESTAMP,
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP
);
