CREATE TABLE "PRODUCTION_AVAIL"
(
    "PRODUCTION_AVAIL_ID" VARCHAR(40) NOT NULL,
    "PROPERTY_ID" VARCHAR(40),
    "AVAIL_DATE" TIMESTAMP,
    "ESTIMATED_VOLUME" NUMERIC(18,2),
    "AVAILABLE_FOR_DELIVERY" NUMERIC(18,2),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP
);
