CREATE TABLE GAS_LIFT_PERFORMANCE
(
    GAS_LIFT_PERFORMANCE_ID VARCHAR(40) NOT NULL,
    WELL_UWI VARCHAR(40),
    PERFORMANCE_DATE DATETIME,
    GAS_INJECTION_RATE NUMERIC(18,6),
    PRODUCTION_RATE NUMERIC(18,6),
    GAS_LIQUID_RATIO NUMERIC(18,6),
    BOTTOM_HOLE_PRESSURE NUMERIC(18,6),
    WELLHEAD_PRESSURE NUMERIC(18,6),
    EFFICIENCY NUMERIC(18,6),
    ACTIVE_IND VARCHAR(1),
    PPDM_GUID VARCHAR(40),
    REMARK VARCHAR(4000),
    SOURCE VARCHAR(40),
    ROW_QUALITY VARCHAR(40),
    ROW_CREATED_BY VARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY VARCHAR(40),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID BIGINT
);

