CREATE TABLE GAS_COMPOSITION
(
    GAS_COMPOSITION_ID VARCHAR(40) NOT NULL,
    COMPOSITION_NAME VARCHAR(255),
    COMPOSITION_DATE DATETIME,
    TOTAL_MOLE_FRACTION NUMERIC(18,10),
    MOLECULAR_WEIGHT NUMERIC(18,6),
    SPECIFIC_GRAVITY NUMERIC(18,10),
    ACTIVE_IND VARCHAR(1),
    PPDM_GUID VARCHAR(40),
    REMARK VARCHAR(4000),
    SOURCE VARCHAR(40),
    ROW_QUALITY VARCHAR(40),
    ROW_CREATED_BY VARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY VARCHAR(40),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID BIGINT
);

