CREATE TABLE GAS_LIFT_DESIGN
(
    GAS_LIFT_DESIGN_ID VARCHAR(40) NOT NULL,
    WELL_UWI VARCHAR(40),
    DESIGN_DATE DATETIME,
    GAS_INJECTION_PRESSURE NUMERIC(18,6),
    NUMBER_OF_VALVES INT,
    OPTIMAL_GAS_INJECTION_RATE NUMERIC(18,6),
    EXPECTED_PRODUCTION_RATE NUMERIC(18,6),
    USE_SI_UNITS VARCHAR(1),
    ACTIVE_IND VARCHAR(1),
    PPDM_GUID VARCHAR(40),
    REMARK VARCHAR(4000),
    SOURCE VARCHAR(40),
    ROW_QUALITY VARCHAR(40),
    ROW_CREATED_BY VARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY VARCHAR(40),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID BIGINT
);

