CREATE TABLE HEAT_MAP_CONFIGURATION
(
    HEAT_MAP_ID VARCHAR(40) NOT NULL,
    CONFIGURATION_NAME VARCHAR(255),
    FIELD_ID VARCHAR(40),
    START_DATE DATETIME,
    END_DATE DATETIME,
    WIDTH NUMERIC(18,2),
    HEIGHT NUMERIC(18,2),
    COLOR_SCHEME VARCHAR(100),
    ACTIVE_IND VARCHAR(1),
    PPDM_GUID VARCHAR(40),
    REMARK VARCHAR(4000),
    SOURCE VARCHAR(40),
    ROW_QUALITY VARCHAR(40),
    ROW_CREATED_BY VARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY VARCHAR(40),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID BIGINT
);

