CREATE TABLE LIST_OF_VALUE
(
    LIST_OF_VALUE_ID VARCHAR(40) NOT NULL,
    VALUE_TYPE VARCHAR(100) NOT NULL,
    VALUE_CODE VARCHAR(100) NOT NULL,
    VALUE_NAME VARCHAR(255),
    DESCRIPTION VARCHAR(2000),
    CATEGORY VARCHAR(100),
    MODULE VARCHAR(100),
    SORT_ORDER INT,
    PARENT_VALUE_ID VARCHAR(40),
    IS_DEFAULT VARCHAR(1),
    ACTIVE_IND VARCHAR(1),
    PPDM_GUID VARCHAR(38),
    REMARK VARCHAR(2000),
    SOURCE VARCHAR(40),
    ROW_QUALITY VARCHAR(40),
    ROW_CREATED_BY VARCHAR(30),
    ROW_CREATED_DATE DATE,
    ROW_CHANGED_BY VARCHAR(30),
    ROW_CHANGED_DATE DATE,
    ROW_EFFECTIVE_DATE DATE,
    ROW_EXPIRY_DATE DATE,
    ROW_ID BIGINT
);

