CREATE TABLE OIL_COMPOSITION
(
    OIL_COMPOSITION_ID VARCHAR(40) NOT NULL,
    COMPOSITION_NAME VARCHAR(255),
    COMPOSITION_DATE DATETIME,
    OIL_GRAVITY NUMERIC(18,6),
    GAS_OIL_RATIO NUMERIC(18,6),
    WATER_CUT NUMERIC(18,10),
    BUBBLE_POINT_PRESSURE NUMERIC(18,6),
    ACTIVE_IND VARCHAR(1),
    PPDM_GUID VARCHAR(40),
    REMARK VARCHAR(4000),
    SOURCE VARCHAR(40),
    ROW_QUALITY VARCHAR(40),
    ROW_CREATED_BY VARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY VARCHAR(40),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID BIGINT
);

