CREATE TABLE PRODUCTION_DATA
(
    PRODUCTION_ID VARCHAR(40) NOT NULL,
    WELL_UWI VARCHAR(40),
    FIELD_ID VARCHAR(40),
    PRODUCTION_DATE DATETIME,
    OIL_VOLUME NUMERIC(18,6),
    GAS_VOLUME NUMERIC(18,6),
    WATER_VOLUME NUMERIC(18,6),
    STATUS VARCHAR(50),
    ACTIVE_IND VARCHAR(1),
    PPDM_GUID VARCHAR(40),
    REMARK VARCHAR(4000),
    SOURCE VARCHAR(40),
    ROW_QUALITY VARCHAR(40),
    ROW_CREATED_BY VARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY VARCHAR(40),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID BIGINT
);

