CREATE TABLE PROSPECT
(
    PROSPECT_ID VARCHAR(40) NOT NULL,
    PROSPECT_NAME VARCHAR(255),
    FIELD_ID VARCHAR(40),
    EVALUATION_DATE DATETIME,
    ESTIMATED_RESERVES NUMERIC(18,2),
    RISK_FACTOR NUMERIC(18,6),
    STATUS VARCHAR(50),
    ACTIVE_IND VARCHAR(1),
    PPDM_GUID VARCHAR(40),
    REMARK VARCHAR(4000),
    SOURCE VARCHAR(40),
    ROW_QUALITY VARCHAR(40),
    ROW_CREATED_BY VARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY VARCHAR(40),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID BIGINT
);

