CREATE TABLE TANK_INVENTORY
(
    TANK_INVENTORY_ID VARCHAR(40) NOT NULL,
    INVENTORY_DATE DATETIME,
    TANK_BATTERY_ID VARCHAR(40),
    OPENING_INVENTORY NUMERIC(18,2),
    RECEIPTS NUMERIC(18,2),
    DELIVERIES NUMERIC(18,2),
    ADJUSTMENTS NUMERIC(18,2),
    SHRINKAGE NUMERIC(18,2),
    THEFT_LOSS NUMERIC(18,2),
    ACTUAL_CLOSING_INVENTORY NUMERIC(18,2),
    ACTIVE_IND VARCHAR(1),
    PPDM_GUID VARCHAR(40),
    REMARK VARCHAR(4000),
    SOURCE VARCHAR(40),
    ROW_QUALITY VARCHAR(40),
    ROW_CREATED_BY VARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY VARCHAR(40),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID BIGINT
);

