CREATE TABLE DECOMMISSIONING_STATUS
(
    DECOMMISSIONING_STATUS_ID TEXT NOT NULL,
    FACILITY_DECOMMISSIONING_ID TEXT,
    STATUS TEXT,
    STATUS_DATE DATETIME,
    STATUS_CHANGED_BY TEXT,
    NOTES TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT
);
