-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: ACCESS_CONTROL_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE USER_ASSET_ACCESS
CREATE TABLE user_asset_access
(
	USER_ID VARCHAR(40) NOT NULL,
	ASSET_TYPE VARCHAR(40) NOT NULL,
	ASSET_ID VARCHAR(40) NOT NULL,
	ACCESS_LEVEL VARCHAR(40),
	INHERIT_IND VARCHAR(1),
	ORGANIZATION_ID VARCHAR(40),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);

-- CREATING TABLE ROLE_PERMISSION
CREATE TABLE role_permission
(
	ROLE_ID VARCHAR(40) NOT NULL,
	PERMISSION_ID VARCHAR(40) NOT NULL,
	ORGANIZATION_ID VARCHAR(40),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);

-- CREATING TABLE ORGANIZATION_HIERARCHY_CONFIG
CREATE TABLE organization_hierarchy_config
(
	ORGANIZATION_ID VARCHAR(40) NOT NULL,
	HIERARCHY_LEVEL DECIMAL(8,0) NOT NULL,
	LEVEL_NAME VARCHAR(255),
	ASSET_TYPE VARCHAR(40),
	PARENT_LEVEL DECIMAL(8,0),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);

-- CREATING TABLE USER_PROFILE
CREATE TABLE user_profile
(
	USER_ID VARCHAR(40) NOT NULL,
	PRIMARY_ROLE VARCHAR(40),
	PREFERRED_LAYOUT VARCHAR(40),
	USER_PREFERENCES VARCHAR(MAX),
	LAST_LOGIN_DATE DATE,
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);

-- CREATING TABLE SETUP_WIZARD_LOG
CREATE TABLE setup_wizard_log
(
	SETUP_LOG_ID VARCHAR(40) NOT NULL,
	ORGANIZATION_ID VARCHAR(40),
	SETUP_STEP VARCHAR(255),
	SETUP_DATA VARCHAR(MAX),
	EXECUTED_BY VARCHAR(40),
	EXECUTION_DATE DATE,
	STATUS VARCHAR(40),
	ERROR_MESSAGE VARCHAR(MAX),
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);
