-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: EXPLORATION_BUDGET_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE EXPLORATION_BUDGET
CREATE TABLE exploration_budget
(
	PROGRAM_ID VARCHAR(40) NOT NULL,
	BUDGET_YEAR DECIMAL(4,0) NOT NULL,
	BUDGET_AMOUNT DECIMAL(18,5),
	BUDGET_CURRENCY VARCHAR(40),
	BUDGET_CATEGORY VARCHAR(40),
	ACTUAL_AMOUNT DECIMAL(18,5),
	VARIANCE DECIMAL(18,5),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);
