-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: EXPLORATION_BUDGET_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT EXPLORATION_BUDGET_PROGRAM_FK
ALTER TABLE EXPLORATION_BUDGET ADD CONSTRAINT EXPLORATION_BUDGET_PROGRAM_FK FOREIGN KEY
(
	PROGRAM_ID
)
REFERENCES EXPLORATION_PROGRAM
(
	PROGRAM_ID
);
