-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: EXPLORATION_PROGRAM_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE EXPLORATION_PROGRAM
CREATE TABLE exploration_program
(
	PROGRAM_ID VARCHAR(40) NOT NULL,
	PROGRAM_NAME VARCHAR(255),
	FIELD_ID VARCHAR(40),
	OPERATOR VARCHAR(40),
	OBJECTIVES VARCHAR(2000),
	PROGRAM_START_DATE DATE,
	PROGRAM_END_DATE DATE,
	BUDGET DECIMAL(18,5),
	BUDGET_CURRENCY VARCHAR(40),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);
