-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: LEAD_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE LEAD
CREATE TABLE lead
(
	LEAD_ID VARCHAR(40) NOT NULL,
	LEAD_NAME VARCHAR(255),
	LEAD_SHORT_NAME VARCHAR(30),
	FIELD_ID VARCHAR(40),
	PLAY_ID VARCHAR(40),
	LEAD_STATUS VARCHAR(40),
	DESCRIPTION VARCHAR(240),
	LEAD_SOURCE VARCHAR(40),
	INITIAL_ASSESSMENT_DATE DATE,
	PROMOTED_TO_PROSPECT_DATE DATE,
	REJECTED_DATE DATE,
	REJECTION_REASON VARCHAR(2000),
	LATITUDE DECIMAL(14,9),
	LONGITUDE DECIMAL(14,9),
	ELEVATION DECIMAL(10,5),
	ELEVATION_OUOM VARCHAR(40),
	LOCATION_DESCRIPTION VARCHAR(240),
	INITIAL_RISK_ASSESSMENT VARCHAR(40),
	INITIAL_VOLUME_ESTIMATE_OIL DECIMAL(18,5),
	INITIAL_VOLUME_ESTIMATE_GAS DECIMAL(18,5),
	INITIAL_VOLUME_ESTIMATE_OUOM VARCHAR(40),
	PROMOTED_TO_PROSPECT_ID VARCHAR(40),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);

