-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PIPELINE_ROUTE_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_ROUTE
CREATE TABLE pipeline_route
(
	PIPELINE_ID VARCHAR(40) NOT NULL,
	ROUTE_SEQ_NO DECIMAL(8,0) NOT NULL,
	LATITUDE DECIMAL(14,9),
	LONGITUDE DECIMAL(14,9),
	ELEVATION DECIMAL(10,5),
	ELEVATION_OUOM VARCHAR(40),
	STATION_MILEPOST DECIMAL(15,5),
	STATION_MILEPOST_OUOM VARCHAR(40),
	LINEAR_REFERENCE DECIMAL(15,5),
	COORD_SYSTEM_ID VARCHAR(40),
	LOCAL_COORD_SYSTEM_ID VARCHAR(40),
	COORD_ACQUISITION_ID VARCHAR(40),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);
