-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PIPELINE_SEGMENT_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_SEGMENT
CREATE TABLE pipeline_segment
(
	PIPELINE_ID VARCHAR(40) NOT NULL,
	SEGMENT_ID VARCHAR(40) NOT NULL,
	SEGMENT_NAME VARCHAR(255),
	SEGMENT_SHORT_NAME VARCHAR(30),
	START_STATION_ID VARCHAR(40),
	START_STATION_TYPE VARCHAR(40),
	END_STATION_ID VARCHAR(40),
	END_STATION_TYPE VARCHAR(40),
	SEGMENT_LENGTH DECIMAL(15,5),
	SEGMENT_LENGTH_OUOM VARCHAR(40),
	SEGMENT_DIAMETER DECIMAL(10,5),
	SEGMENT_DIAMETER_OUOM VARCHAR(40),
	WALL_THICKNESS DECIMAL(10,5),
	WALL_THICKNESS_OUOM VARCHAR(40),
	MATERIAL_TYPE VARCHAR(40),
	MATERIAL_GRADE VARCHAR(40),
	DESCRIPTION VARCHAR(240),
	INSTALLATION_DATE DATE,
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);
