-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PIPELINE_MATERIAL_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PIPELINE_MATERIAL_PK
ALTER TABLE PIPELINE_MATERIAL ADD CONSTRAINT PIPELINE_MATERIAL_PK PRIMARY KEY
(
	PIPELINE_ID,
	MATERIAL_SEQ_NO
);

