-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PIPELINE_SEGMENT_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_SEGMENT_PIPELINE_FK
ALTER TABLE PIPELINE_SEGMENT ADD CONSTRAINT PIPELINE_SEGMENT_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_SEGMENT_START_FACILITY_FK
ALTER TABLE PIPELINE_SEGMENT ADD CONSTRAINT PIPELINE_SEGMENT_START_FACILITY_FK FOREIGN KEY 
(
	START_STATION_ID,
	START_STATION_TYPE
)
REFERENCES FACILITY
(
	FACILITY_ID,
	FACILITY_TYPE
);

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_SEGMENT_END_FACILITY_FK
ALTER TABLE PIPELINE_SEGMENT ADD CONSTRAINT PIPELINE_SEGMENT_END_FACILITY_FK FOREIGN KEY 
(
	END_STATION_ID,
	END_STATION_TYPE
)
REFERENCES FACILITY
(
	FACILITY_ID,
	FACILITY_TYPE
);
