-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PIPELINE_INCIDENT_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_INCIDENT
CREATE TABLE pipeline_incident
(
	PIPELINE_ID VARCHAR(40) NOT NULL,
	INCIDENT_ID VARCHAR(40) NOT NULL,
	INCIDENT_DATE DATE,
	INCIDENT_TYPE VARCHAR(40),
	SEVERITY VARCHAR(40),
	CAUSE VARCHAR(240),
	VOLUME_RELEASED DECIMAL(10,2),
	VOLUME_RELEASED_OUOM VARCHAR(40),
	ENVIRONMENTAL_IMPACT VARCHAR(2000),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);

