-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PIPELINE_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE
CREATE TABLE pipeline
(
	PIPELINE_ID VARCHAR(40) NOT NULL,
	PIPELINE_NAME VARCHAR(255),
	PIPELINE_SHORT_NAME VARCHAR(30),
	PIPELINE_TYPE VARCHAR(40),
	PIPELINE_STATUS VARCHAR(40),
	REGULATORY_ID VARCHAR(40),
	PRIMARY_FIELD_ID VARCHAR(40),
	CURRENT_OPERATOR VARCHAR(40),
	DESCRIPTION VARCHAR(240),
	INSTALLATION_DATE DATE,
	COMMISSIONING_DATE DATE,
	DECOMMISSIONING_DATE DATE,
	ABANDONED_DATE DATE,
	ACTIVE_DATE DATE,
	INACTIVE_DATE DATE,
	DESIGN_PRESSURE DECIMAL(10,5),
	DESIGN_PRESSURE_OUOM VARCHAR(40),
	DESIGN_TEMPERATURE DECIMAL(10,5),
	DESIGN_TEMPERATURE_OUOM VARCHAR(40),
	COORD_SYSTEM_ID VARCHAR(40),
	LOCAL_COORD_SYSTEM_ID VARCHAR(40),
	COORD_ACQUISITION_ID VARCHAR(40),
	LATITUDE DECIMAL(14,9),
	LONGITUDE DECIMAL(14,9),
	ELEVATION DECIMAL(10,5),
	ELEVATION_OUOM VARCHAR(40),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);
