-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PIPELINE_ANOMALY_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_ANOMALY
CREATE TABLE pipeline_anomaly
(
	PIPELINE_ID VARCHAR(40) NOT NULL,
	ANOMALY_ID VARCHAR(40) NOT NULL,
	ANOMALY_TYPE VARCHAR(40),
	INSPECTION_ID VARCHAR(40),
	LOCATION_STATION_MILEPOST DECIMAL(10,2),
	LOCATION_STATION_MILEPOST_OUOM VARCHAR(40),
	SEVERITY VARCHAR(40),
	ANOMALY_LENGTH DECIMAL(10,2),
	ANOMALY_LENGTH_OUOM VARCHAR(40),
	ANOMALY_DEPTH DECIMAL(10,2),
	ANOMALY_DEPTH_OUOM VARCHAR(40),
	ANOMALY_WIDTH DECIMAL(10,2),
	ANOMALY_WIDTH_OUOM VARCHAR(40),
	SEGMENT_ID VARCHAR(40),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);

