-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PIPELINE_INSPECTION_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PIPELINE_INSPECTION_PK
ALTER TABLE PIPELINE_INSPECTION ADD CONSTRAINT PIPELINE_INSPECTION_PK PRIMARY KEY
(
	PIPELINE_ID,
	INSPECTION_ID
);

