-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PIPELINE_MAINTENANCE_SCHEDULE_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_MAINTENANCE_SCHEDULE_PIPELINE_FK
ALTER TABLE PIPELINE_MAINTENANCE_SCHEDULE ADD CONSTRAINT PIPELINE_MAINTENANCE_SCHEDULE_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

