-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PIPELINE_ROUTE_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_ROUTE_PIPELINE_FK
ALTER TABLE PIPELINE_ROUTE ADD CONSTRAINT PIPELINE_ROUTE_PIPELINE_FK FOREIGN KEY 
(
	PIPELINE_ID
)
REFERENCES PIPELINE
(
	PIPELINE_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_ROUTE_CS_FK
ALTER TABLE PIPELINE_ROUTE ADD CONSTRAINT PIPELINE_ROUTE_CS_FK FOREIGN KEY 
(
	COORD_SYSTEM_ID
)
REFERENCES CS_COORDINATE_SYSTEM
(
	COORD_SYSTEM_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_ROUTE_LOCAL_CS_FK
ALTER TABLE PIPELINE_ROUTE ADD CONSTRAINT PIPELINE_ROUTE_LOCAL_CS_FK FOREIGN KEY 
(
	LOCAL_COORD_SYSTEM_ID
)
REFERENCES CS_COORDINATE_SYSTEM
(
	COORD_SYSTEM_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PIPELINE_ROUTE_CA_FK
ALTER TABLE PIPELINE_ROUTE ADD CONSTRAINT PIPELINE_ROUTE_CA_FK FOREIGN KEY 
(
	COORD_ACQUISITION_ID
)
REFERENCES CS_COORD_ACQUISITION
(
	ACQUISITION_ID
);
