-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PIPELINE_FACILITY_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_FACILITY
CREATE TABLE pipeline_facility
(
	PIPELINE_ID VARCHAR(40) NOT NULL,
	FACILITY_ID VARCHAR(40) NOT NULL,
	FACILITY_TYPE VARCHAR(40) NOT NULL,
	CONNECTION_SEQ_NO DECIMAL(8,0) NOT NULL,
	CONNECTION_TYPE VARCHAR(40),
	CONNECTION_DATE DATE,
	STATION_FUNCTION VARCHAR(40),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);
