-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PIPELINE_DESIGN_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_DESIGN
CREATE TABLE pipeline_design
(
	PIPELINE_ID VARCHAR(40) NOT NULL,
	DESIGN_VERSION_NO VARCHAR(40) NOT NULL,
	DESIGN_PRESSURE DECIMAL(10,5),
	DESIGN_PRESSURE_OUOM VARCHAR(40),
	DESIGN_TEMPERATURE DECIMAL(10,5),
	DESIGN_TEMPERATURE_OUOM VARCHAR(40),
	MATERIAL_GRADE VARCHAR(40),
	COATING_TYPE VARCHAR(40),
	CATHODIC_PROTECTION_TYPE VARCHAR(40),
	CP_SYSTEM_TYPE VARCHAR(40),
	DESIGN_SPECIFICATION VARCHAR(255),
	DESIGN_STANDARD VARCHAR(40),
	DESIGN_DATE DATE,
	DESIGNER VARCHAR(40),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);

