-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PIPELINE_RISK_ASSESSMENT_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PIPELINE_RISK_ASSESSMENT
CREATE TABLE pipeline_risk_assessment
(
	PIPELINE_ID VARCHAR(40) NOT NULL,
	RISK_ASSESSMENT_ID VARCHAR(40) NOT NULL,
	ASSESSMENT_DATE DATE,
	RISK_SCORE DECIMAL(10,2),
	ASSESSMENT_METHOD VARCHAR(40),
	RISK_FACTORS VARCHAR(2000),
	SEGMENT_ID VARCHAR(40),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);

