-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PROSPECT_RANKING_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PROSPECT_RANKING_PK
ALTER TABLE PROSPECT_RANKING ADD CONSTRAINT PROSPECT_RANKING_PK PRIMARY KEY
(
	PROSPECT_ID,
	RANKING_ID
);
