-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PROSPECT_DISCOVERY_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PROSPECT_DISCOVERY
CREATE TABLE prospect_discovery
(
	PROSPECT_ID VARCHAR(40) NOT NULL,
	DISCOVERY_ID VARCHAR(40) NOT NULL,
	DISCOVERY_TYPE VARCHAR(40),
	DISCOVERY_DATE DATE,
	DISCOVERY_WELL VARCHAR(40),
	VOLUMES_DISCOVERED_OIL DECIMAL(18,5),
	VOLUMES_DISCOVERED_GAS DECIMAL(18,5),
	VOLUMES_DISCOVERED_OUOM VARCHAR(40),
	SIGNIFICANCE VARCHAR(40),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);
