-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PROSPECT_HISTORY_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PROSPECT_HISTORY_PK
ALTER TABLE PROSPECT_HISTORY ADD CONSTRAINT PROSPECT_HISTORY_PK PRIMARY KEY
(
	PROSPECT_ID,
	HISTORY_SEQ_NO
);
