-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PROSPECT_RESERVOIR_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PROSPECT_RESERVOIR_PK
ALTER TABLE PROSPECT_RESERVOIR ADD CONSTRAINT PROSPECT_RESERVOIR_PK PRIMARY KEY
(
	PROSPECT_ID,
	RESERVOIR_ID
);
