-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PROSPECT_VOLUME_ESTIMATE_TAB.sql
-- This script is for the PPDM39 model

-- CREATING TABLE PROSPECT_VOLUME_ESTIMATE
CREATE TABLE prospect_volume_estimate
(
	PROSPECT_ID VARCHAR(40) NOT NULL,
	ESTIMATE_ID VARCHAR(40) NOT NULL,
	OIL_VOLUME_P10 DECIMAL(18,5),
	OIL_VOLUME_P50 DECIMAL(18,5),
	OIL_VOLUME_P90 DECIMAL(18,5),
	GAS_VOLUME_P10 DECIMAL(18,5),
	GAS_VOLUME_P50 DECIMAL(18,5),
	GAS_VOLUME_P90 DECIMAL(18,5),
	VOLUME_OUOM VARCHAR(40),
	UNRISKED_OIL_VOLUME DECIMAL(18,5),
	UNRISKED_GAS_VOLUME DECIMAL(18,5),
	RISKED_OIL_VOLUME DECIMAL(18,5),
	RISKED_GAS_VOLUME DECIMAL(18,5),
	RECOVERY_FACTOR DECIMAL(5,4),
	FORMATION_VOLUME_FACTOR DECIMAL(10,5),
	ESTIMATE_METHOD VARCHAR(40),
	ESTIMATE_DATE DATE,
	ESTIMATOR VARCHAR(40),
	DESCRIPTION VARCHAR(240),
	ACTIVE_IND VARCHAR(1),
	EFFECTIVE_DATE DATE,
	EXPIRY_DATE DATE,
	PPDM_GUID VARCHAR(38),
	REMARK VARCHAR(2000),
	SOURCE VARCHAR(40),
	ROW_CHANGED_BY VARCHAR(30),
	ROW_CHANGED_DATE DATE,
	ROW_CREATED_BY VARCHAR(30),
	ROW_CREATED_DATE DATE,
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRY_DATE DATE,
	ROW_QUALITY VARCHAR(40)
);
