-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PROSPECT_BA_PK.sql
-- This script is for the PPDM39 model

-- CREATING PRIMARY KEY PROSPECT_BA_PK
ALTER TABLE PROSPECT_BA ADD CONSTRAINT PROSPECT_BA_PK PRIMARY KEY
(
	PROSPECT_ID,
	BUSINESS_ASSOCIATE_ID,
	ROLE_TYPE
);
