-- PPDM39 MARIADB DDL Script
-- Converted from SQL Server script: PROSPECT_FIELD_FK.sql
-- This script is for the PPDM39 model

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_FIELD_PROSPECT_FK
ALTER TABLE PROSPECT_FIELD ADD CONSTRAINT PROSPECT_FIELD_PROSPECT_FK FOREIGN KEY
(
	PROSPECT_ID
)
REFERENCES PROSPECT
(
	PROSPECT_ID
);

-- CREATING FOREIGN KEY CONSTRAINT PROSPECT_FIELD_FIELD_FK
ALTER TABLE PROSPECT_FIELD ADD CONSTRAINT PROSPECT_FIELD_FIELD_FK FOREIGN KEY
(
	FIELD_ID
)
REFERENCES FIELD
(
	FIELD_ID
);

