CREATE TABLE "ACTUAL_DELIVERY"
(
    "ACTUAL_DELIVERY_ID" VARCHAR2(40) NOT NULL,
    "NOMINATION_ID" VARCHAR2(40),
    "DELIVERY_DATE" DATE,
    "ACTUAL_VOLUME" NUMBER(18,2),
    "DELIVERY_POINT" VARCHAR2(255),
    "ALLOCATION_METHOD" VARCHAR2(255),
    "RUN_TICKET_NUMBER" VARCHAR2(255),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE
);
