CREATE TABLE "IMBALANCE"
(
    "IMBALANCE_ID" VARCHAR2(40) NOT NULL,
    "NOMINATION_ID" VARCHAR2(40),
    "PERIOD_START" DATE,
    "PERIOD_END" DATE,
    "NOMINATED_VOLUME" NUMBER(18,2),
    "ACTUAL_VOLUME" NUMBER(18,2),
    "IMBALANCE_AMOUNT" NUMBER(18,2),
    "TOLERANCE_PERCENTAGE" NUMBER(18,6),
    "STATUS" VARCHAR2(50),
    "SETTLEMENT_DATE" DATE,
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE
);
