CREATE TABLE CHOKE_PROPERTIES
(
    CHOKE_PROPERTIES_ID TEXT NOT NULL,
    CHOKE_DIAMETER REAL,
    CHOKE_TYPE TEXT,
    DISCHARGE_COEFFICIENT REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT
);
