CREATE TABLE GAS_CHOKE_PROPERTIES
(
    GAS_CHOKE_PROPERTIES_ID TEXT NOT NULL,
    GAS_SPECIFIC_GRAVITY REAL,
    UPSTREAM_PRESSURE REAL,
    DOWNSTREAM_PRESSURE REAL,
    TEMPERATURE REAL,
    Z_FACTOR REAL,
    FLOW_RATE REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT
);
