CREATE TABLE GOVERNMENT_LEASE
(
    LEASE_ID TEXT,
    PROPERTY_ID TEXT,
    GOVERNMENT_AGENCY TEXT,
    LEASE_NUMBER TEXT,
    IS_FEDERAL TEXT,
    IS_INDIAN TEXT,
    EFFECTIVE_DATE DATETIME,
    EXPIRATION_DATE DATETIME,
    WORKING_INTEREST REAL,
    NET_REVENUE_INTEREST REAL,
    ROYALTY_RATE REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
