raiserror ('CREATING TABLE OIL_PROPERTY_CONDITIONS', 10,1) with nowait

CREATE TABLE OIL_PROPERTY_CONDITIONS
(
    OIL_PROPERTY_CONDITIONS_ID NVARCHAR(40) NOT NULL,
    PRESSURE NUMERIC(18,2),
    TEMPERATURE NUMERIC(18,2),
    API_GRAVITY NUMERIC(18,2),
    GAS_SPECIFIC_GRAVITY NUMERIC(18,2),
    SOLUTION_GAS_OIL_RATIO NUMERIC(18,6),
    BUBBLE_POINT_PRESSURE NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME
);
