CREATE TABLE CENTRIFUGAL_COMPRESSOR_PROPERTIES
(
    CENTRIFUGAL_COMPRESSOR_PROPERTIES_ID TEXT NOT NULL,
    COMPRESSOR_OPERATING_CONDITIONS_ID TEXT,
    POLYTROPIC_EFFICIENCY REAL,
    SPECIFIC_HEAT_RATIO REAL,
    NUMBER_OF_STAGES INTEGER,
    SPEED REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT
);
