CREATE TABLE COMPRESSOR_OPERATING_CONDITIONS
(
    COMPRESSOR_OPERATING_CONDITIONS_ID TEXT NOT NULL,
    SUCTION_PRESSURE REAL,
    DISCHARGE_PRESSURE REAL,
    SUCTION_TEMPERATURE REAL,
    DISCHARGE_TEMPERATURE REAL,
    GAS_FLOW_RATE REAL,
    GAS_SPECIFIC_GRAVITY REAL,
    GAS_MOLECULAR_WEIGHT REAL,
    COMPRESSOR_EFFICIENCY REAL,
    MECHANICAL_EFFICIENCY REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT
);
