CREATE TABLE RECIPROCATING_COMPRESSOR_PROPERTIES
(
    RECIPROCATING_COMPRESSOR_PROPERTIES_ID TEXT NOT NULL,
    COMPRESSOR_OPERATING_CONDITIONS_ID TEXT,
    CYLINDER_DIAMETER REAL,
    STROKE_LENGTH REAL,
    ROTATIONAL_SPEED REAL,
    NUMBER_OF_CYLINDERS INTEGER,
    VOLUMETRIC_EFFICIENCY REAL,
    CLEARANCE_FACTOR REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT
);
