CREATE TABLE `HEAT_MAP_DATA_POINT`
(
    `HEAT_MAP_DATA_POINT_ID` VARCHAR(40) NOT NULL,
    `HEAT_MAP_ID` VARCHAR(40),
    `X` DECIMAL(18,2),
    `Y` DECIMAL(18,2),
    `ORIGINAL_X` DECIMAL(18,2),
    `ORIGINAL_Y` DECIMAL(18,2),
    `VALUE` DECIMAL(18,2),
    `LABEL` VARCHAR(255),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_QUALITY` VARCHAR(40)
);
