raiserror ('CREATING TABLE NPV_PROFILE_POINT', 10,1) with nowait

CREATE TABLE NPV_PROFILE_POINT
(
    NPV_PROFILE_POINT_ID NVARCHAR(40) NOT NULL,
    ECONOMIC_ANALYSIS_RESULT_ID NVARCHAR(40),
    RATE NUMERIC(18,2),
    NPV NUMERIC(18,2),
    POINT_ORDER INT,
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME
);
