ALTER TABLE NPV_PROFILE_POINT
ADD CONSTRAINT FK_NPV_PROFILE_POINT_ECONOMIC_ANALYSIS_RESULT FOREIGN KEY (ECONOMIC_ANALYSIS_RESULT_ID) REFERENCES ECONOMIC_ANALYSIS_RESULT(ECONOMIC_ANALYSIS_RESULT_ID);

ALTER TABLE NPV_PROFILE_POINT
ADD CONSTRAINT FK_NPV_PROFILE_POINT_AREA FOREIGN KEY (AREA_ID) REFERENCES AREA(AREA_ID);

ALTER TABLE NPV_PROFILE_POINT
ADD CONSTRAINT FK_NPV_PROFILE_POINT_BUSINESS_ASSOCIATE FOREIGN KEY (BUSINESS_ASSOCIATE_ID) REFERENCES BUSINESS_ASSOCIATE(BUSINESS_ASSOCIATE_ID);
