raiserror ('CREATING TABLE CHART_CONFIGURATION', 10,1) with nowait

CREATE TABLE CHART_CONFIGURATION
(
    CHART_CONFIGURATION_ID NVARCHAR(40) NOT NULL,
    CHART_TYPE NVARCHAR(50),
    CONFIGURATION_NAME NVARCHAR(255),
    CONFIGURATION_DATA NVARCHAR(255),
    CREATED_BY NVARCHAR(30),
    IS_DEFAULT NVARCHAR(255),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME
);
