raiserror ('CREATING TABLE CENTRIFUGAL_COMPRESSOR_PROPERTIES', 10,1) with nowait

CREATE TABLE CENTRIFUGAL_COMPRESSOR_PROPERTIES
(
    CENTRIFUGAL_COMPRESSOR_PROPERTIES_ID NVARCHAR(40) NOT NULL,
    COMPRESSOR_OPERATING_CONDITIONS_ID NVARCHAR(40),
    POLYTROPIC_EFFICIENCY NUMERIC(18,2),
    SPECIFIC_HEAT_RATIO NUMERIC(18,6),
    NUMBER_OF_STAGES INT,
    SPEED NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
