raiserror ('CREATING TABLE RECIPROCATING_COMPRESSOR_PROPERTIES', 10,1) with nowait

CREATE TABLE RECIPROCATING_COMPRESSOR_PROPERTIES
(
    RECIPROCATING_COMPRESSOR_PROPERTIES_ID NVARCHAR(40) NOT NULL,
    COMPRESSOR_OPERATING_CONDITIONS_ID NVARCHAR(40),
    CYLINDER_DIAMETER NUMERIC(18,2),
    STROKE_LENGTH NUMERIC(18,2),
    ROTATIONAL_SPEED NUMERIC(18,2),
    NUMBER_OF_CYLINDERS INT,
    VOLUMETRIC_EFFICIENCY NUMERIC(18,2),
    CLEARANCE_FACTOR NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
