ALTER TABLE "ESP_MOTOR_PROPERTIES"
ADD CONSTRAINT FK_ESP_MOTOR_PROPERTIES_ESP_DESIGN_RESULT FOREIGN KEY ("ESP_DESIGN_RESULT_ID") REFERENCES "ESP_DESIGN_RESULT"("ESP_DESIGN_RESULT_ID");

ALTER TABLE "ESP_MOTOR_PROPERTIES"
ADD CONSTRAINT FK_ESP_MOTOR_PROPERTIES_AREA FOREIGN KEY ("AREA_ID") REFERENCES "AREA"("AREA_ID");

ALTER TABLE "ESP_MOTOR_PROPERTIES"
ADD CONSTRAINT FK_ESP_MOTOR_PROPERTIES_BUSINESS_ASSOCIATE FOREIGN KEY ("BUSINESS_ASSOCIATE_ID") REFERENCES "BUSINESS_ASSOCIATE"("BUSINESS_ASSOCIATE_ID");
