ALTER TABLE "ESP_PUMP_POINT"
ADD CONSTRAINT FK_ESP_PUMP_POINT_ESP_DESIGN_RESULT FOREIGN KEY ("ESP_DESIGN_RESULT_ID") REFERENCES "ESP_DESIGN_RESULT"("ESP_DESIGN_RESULT_ID");

ALTER TABLE "ESP_PUMP_POINT"
ADD CONSTRAINT FK_ESP_PUMP_POINT_AREA FOREIGN KEY ("AREA_ID") REFERENCES "AREA"("AREA_ID");

ALTER TABLE "ESP_PUMP_POINT"
ADD CONSTRAINT FK_ESP_PUMP_POINT_BUSINESS_ASSOCIATE FOREIGN KEY ("BUSINESS_ASSOCIATE_ID") REFERENCES "BUSINESS_ASSOCIATE"("BUSINESS_ASSOCIATE_ID");
