ALTER TABLE "EXPLORATION_PERMIT"
ADD CONSTRAINT FK_EXPLORATION_PERMIT_PERMIT FOREIGN KEY ("PERMIT_ID") REFERENCES "PERMIT"("PERMIT_ID");

ALTER TABLE "EXPLORATION_PERMIT"
ADD CONSTRAINT FK_EXPLORATION_PERMIT_FIELD FOREIGN KEY ("FIELD_ID") REFERENCES "FIELD"("FIELD_ID");
