CREATE TABLE "EXPLORATION_BUDGET"
(
    "PROGRAM_ID" VARCHAR(40),
    "BUDGET_YEAR" NUMERIC(18,2) NOT NULL,
    "BUDGET_AMOUNT" NUMERIC(18,2),
    "BUDGET_CURRENCY" VARCHAR(255),
    "BUDGET_CATEGORY" VARCHAR(255),
    "ACTUAL_AMOUNT" NUMERIC(18,2),
    "VARIANCE" NUMERIC(18,2),
    "DESCRIPTION" VARCHAR(2000),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "EFFECTIVE_DATE" TIMESTAMP,
    "EXPIRY_DATE" TIMESTAMP,
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_QUALITY" VARCHAR(40)
);
