ALTER TABLE "PROSPECT_TRAP"
ADD CONSTRAINT FK_PROSPECT_TRAP_PROSPECT FOREIGN KEY ("PROSPECT_ID") REFERENCES "PROSPECT"("PROSPECT_ID");

ALTER TABLE "PROSPECT_TRAP"
ADD CONSTRAINT FK_PROSPECT_TRAP_TRAP FOREIGN KEY ("TRAP_ID") REFERENCES "TRAP"("TRAP_ID");
