CREATE TABLE "GAS_CHOKE_PROPERTIES"
(
    "GAS_CHOKE_PROPERTIES_ID" VARCHAR2(40) NOT NULL,
    "GAS_SPECIFIC_GRAVITY" NUMBER(18,2),
    "UPSTREAM_PRESSURE" NUMBER(18,2),
    "DOWNSTREAM_PRESSURE" NUMBER(18,2),
    "TEMPERATURE" NUMBER(18,2),
    "Z_FACTOR" NUMBER(18,2),
    "FLOW_RATE" NUMBER(18,2),
    "ACTIVE_IND" VARCHAR2(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR2(40),
    "REMARK" VARCHAR2(2000),
    "SOURCE" VARCHAR2(40),
    "ROW_CREATED_DATE" DATE,
    "ROW_CREATED_BY" VARCHAR2(30),
    "ROW_CHANGED_DATE" DATE,
    "ROW_CHANGED_BY" VARCHAR2(30),
    "ROW_EFFECTIVE_DATE" DATE,
    "ROW_EXPIRY_DATE" DATE,
    "ROW_QUALITY" VARCHAR2(40)
);
