CREATE TABLE "ROD_SECTION"
(
    "ROD_SECTION_ID" VARCHAR(40) NOT NULL,
    "SUCKER_ROD_STRING_ID" VARCHAR(40),
    "DIAMETER" NUMERIC(18,2),
    "LENGTH" NUMERIC(18,2),
    "DENSITY" NUMERIC(18,2),
    "WEIGHT" NUMERIC(18,2),
    "SECTION_ORDER" INTEGER,
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_QUALITY" VARCHAR(40)
);
