CREATE TABLE `OWNERSHIP_INTEREST`
(
    `OWNERSHIP_INTEREST_ID` VARCHAR(40) NOT NULL,
    `PROPERTY_ID` VARCHAR(40),
    `OWNER_BA_ID` VARCHAR(40),
    `WORKING_INTEREST` DECIMAL(18,2),
    `NET_REVENUE_INTEREST` DECIMAL(18,2),
    `ROYALTY_INTEREST` DECIMAL(18,2),
    `OVERRIDING_ROYALTY_INTEREST` DECIMAL(18,2),
    `EFFECTIVE_START_DATE` DATETIME,
    `EFFECTIVE_END_DATE` DATETIME,
    `DIVISION_ORDER_ID` VARCHAR(40),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME
);
