ALTER TABLE `OWNERSHIP_INTEREST`
ADD CONSTRAINT FK_OWNERSHIP_INTEREST_PROPERTY FOREIGN KEY (`PROPERTY_ID`) REFERENCES `PROPERTY`(`PROPERTY_ID`);

ALTER TABLE `OWNERSHIP_INTEREST`
ADD CONSTRAINT FK_OWNERSHIP_INTEREST_OWNER_BA FOREIGN KEY (`OWNER_BA_ID`) REFERENCES `OWNER_BA`(`OWNER_BA_ID`);

ALTER TABLE `OWNERSHIP_INTEREST`
ADD CONSTRAINT FK_OWNERSHIP_INTEREST_DIVISION_ORDER FOREIGN KEY (`DIVISION_ORDER_ID`) REFERENCES `DIVISION_ORDER`(`DIVISION_ORDER_ID`);
