CREATE TABLE `TRANSFER_ORDER`
(
    `TRANSFER_ORDER_ID` VARCHAR(40) NOT NULL,
    `PROPERTY_ID` VARCHAR(40),
    `FROM_OWNER_BA_ID` VARCHAR(40),
    `TO_OWNER_BA_ID` VARCHAR(40),
    `INTEREST_TRANSFERRED` DECIMAL(18,2),
    `EFFECTIVE_DATE` DATETIME,
    `IS_APPROVED` VARCHAR(255),
    `APPROVAL_DATE` DATETIME,
    `APPROVED_BY` VARCHAR(255),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME
);
