CREATE TABLE `ROYALTY_STATEMENT`
(
    `ROYALTY_STATEMENT_ID` VARCHAR(40) NOT NULL,
    `ROYALTY_OWNER_BA_ID` VARCHAR(40),
    `PROPERTY_ID` VARCHAR(40),
    `STATEMENT_PERIOD_START` DATETIME,
    `STATEMENT_PERIOD_END` DATETIME,
    `TOTAL_ROYALTY_AMOUNT` DECIMAL(18,2),
    `TOTAL_DEDUCTIONS` DECIMAL(18,2),
    `NET_PAYMENT_AMOUNT` DECIMAL(18,2),
    `STATEMENT_DATE` DATETIME,
    `STATUS` VARCHAR(50),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME
);
