CREATE TABLE `ROYALTY_INTEREST`
(
    `ROYALTY_INTEREST_ID` VARCHAR(40) NOT NULL,
    `PROPERTY_ID` VARCHAR(40),
    `ROYALTY_OWNER_BA_ID` VARCHAR(40),
    `INTEREST_TYPE` VARCHAR(50),
    `INTEREST_PERCENTAGE` DECIMAL(18,6),
    `ROYALTY_RATE` DECIMAL(18,2),
    `EFFECTIVE_DATE` DATETIME,
    `EXPIRY_DATE` DATETIME,
    `DIVISION_ORDER_ID` VARCHAR(40),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_QUALITY` VARCHAR(40)
);
