raiserror ('CREATING TABLE CHOKE_PROPERTIES', 10,1) with nowait

CREATE TABLE CHOKE_PROPERTIES
(
    CHOKE_PROPERTIES_ID NVARCHAR(40) NOT NULL,
    CHOKE_DIAMETER NUMERIC(18,2),
    CHOKE_TYPE NVARCHAR(50),
    DISCHARGE_COEFFICIENT NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
