raiserror ('CREATING TABLE GAS_CHOKE_PROPERTIES', 10,1) with nowait

CREATE TABLE GAS_CHOKE_PROPERTIES
(
    GAS_CHOKE_PROPERTIES_ID NVARCHAR(40) NOT NULL,
    GAS_SPECIFIC_GRAVITY NUMERIC(18,2),
    UPSTREAM_PRESSURE NUMERIC(18,2),
    DOWNSTREAM_PRESSURE NUMERIC(18,2),
    TEMPERATURE NUMERIC(18,2),
    Z_FACTOR NUMERIC(18,2),
    FLOW_RATE NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
