CREATE TABLE ACCOUNTING_METHOD
(
    ACCOUNTING_METHOD_ID TEXT NOT NULL,
    ROW_QUALITY TEXT,
    FIELD_ID TEXT,
    COST_CENTER_ID TEXT,
    METHOD_TYPE TEXT,
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    DESCRIPTION TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
