CREATE TABLE ADDRESS
(
    ADDRESS_ID TEXT NOT NULL,
    OWNER_INFORMATION_ID TEXT,
    STREET_ADDRESS TEXT,
    CITY TEXT,
    STATE TEXT,
    ZIP_CODE TEXT,
    COUNTRY TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
