CREATE TABLE ALLOCATION_DETAIL
(
    ALLOCATION_DETAIL_ID TEXT NOT NULL,
    ALLOCATION_RESULT_ID TEXT,
    ENTITY_ID TEXT,
    ENTITY_TYPE TEXT,
    ENTITY_NAME TEXT,
    ALLOCATED_VOLUME REAL,
    ALLOCATION_PERCENTAGE REAL,
    ALLOCATION_BASIS REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT,
    AllocationRequest_ID TEXT
);
