CREATE TABLE ALLOCATION_REPORT_SUMMARY
(
    ALLOCATION_REPORT_SUMMARY_ID TEXT NOT NULL,
    WELLS_ALLOCATED INTEGER,
    LEASES_ALLOCATED INTEGER,
    TOTAL_ALLOCATED_VOLUME REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
