CREATE TABLE AP_CREDIT_MEMO
(
    AP_CREDIT_MEMO_ID TEXT NOT NULL,
    AP_INVOICE_ID TEXT,
    CREDIT_MEMO_NUMBER TEXT,
    CREDIT_MEMO_DATE DATETIME,
    CREDIT_AMOUNT REAL,
    REASON TEXT,
    STATUS TEXT,
    DESCRIPTION TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
