CREATE TABLE AP_INVOICE
(
    AP_INVOICE_ID TEXT NOT NULL,
    INVOICE_NUMBER TEXT,
    VENDOR_BA_ID TEXT,
    INVOICE_DATE DATETIME,
    DUE_DATE DATETIME,
    TOTAL_AMOUNT REAL,
    PAID_AMOUNT REAL,
    BALANCE_DUE REAL,
    STATUS TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
