CREATE TABLE AR_PAYMENT
(
    AR_PAYMENT_ID TEXT NOT NULL,
    AR_INVOICE_ID TEXT,
    PAYMENT_NUMBER TEXT,
    PAYMENT_DATE DATETIME,
    PAYMENT_AMOUNT REAL,
    PAYMENT_METHOD TEXT,
    CHECK_NUMBER TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
