CREATE TABLE AVAILS_ALLOCATION
(
    AVAILS_ALLOCATION_ID TEXT NOT NULL,
    PRODUCTION_AVAILS_ID TEXT,
    ENTITY_ID TEXT,
    ALLOCATED_VOLUME REAL,
    ALLOCATION_PERCENTAGE REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
