CREATE TABLE CEILING_TEST_CALCULATION
(
    CEILING_TEST_CALCULATION_ID TEXT NOT NULL,
    PROPERTY_ID TEXT,
    CALCULATION_DATE DATETIME,
    NET_CAPITALIZED_COST REAL,
    DISCOUNTED_FUTURE_NET_CASH_FLOWS REAL,
    CEILING_VALUE REAL,
    IMPAIRMENT_AMOUNT REAL,
    DISCOUNT_RATE REAL,
    DESCRIPTION TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
