CREATE TABLE COST_REPORT_SUMMARY
(
    COST_REPORT_SUMMARY_ID TEXT NOT NULL,
    TOTAL_LIFTING_COSTS REAL,
    TOTAL_OPERATING_COSTS REAL,
    TOTAL_MARKETING_COSTS REAL,
    TOTAL_COSTS REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
