CREATE TABLE COST_ALLOCATION
(
    COST_ALLOCATION_ID TEXT NOT NULL,
    COST_TRANSACTION_ID TEXT,
    PROPERTY_ID TEXT,
    WELL_ID TEXT,
    COST_CENTER_ID TEXT,
    ALLOCATED_AMOUNT REAL,
    ALLOCATION_PERCENTAGE REAL,
    ALLOCATION_METHOD TEXT,
    DESCRIPTION TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
