CREATE TABLE CRUDE_OIL_INVENTORY_TRANSACTION
(
    TRANSACTION_ID TEXT,
    INVENTORY_ID TEXT,
    TRANSACTION_DATE DATETIME,
    TRANSACTION_TYPE TEXT,
    VOLUME REAL,
    UNIT_COST REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
