CREATE TABLE CRUDE_OIL_INVENTORY
(
    INVENTORY_ID TEXT,
    PROPERTY_OR_LEASE_ID TEXT,
    TANK_BATTERY_ID TEXT,
    INVENTORY_DATE DATETIME,
    VOLUME REAL,
    UNIT_COST REAL,
    VALUATION_METHOD TEXT,
    MARKET_PRICE REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
