CREATE TABLE EXCHANGE_CONTRACT
(
    CONTRACT_ID TEXT,
    CONTRACT_NAME TEXT,
    CONTRACT_TYPE TEXT,
    PARTIES_JSON TEXT,
    EFFECTIVE_DATE DATETIME,
    EXPIRATION_DATE DATETIME,
    EXCHANGE_TERMS_JSON TEXT,
    DELIVERY_POINTS_JSON TEXT,
    PRICING_TERMS_JSON TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
