CREATE TABLE GL_ACCOUNT
(
    GL_ACCOUNT_ID TEXT NOT NULL,
    ACCOUNT_NUMBER TEXT,
    ACCOUNT_NAME TEXT,
    ACCOUNT_TYPE TEXT,
    PARENT_ACCOUNT_ID TEXT,
    NORMAL_BALANCE TEXT,
    OPENING_BALANCE REAL,
    CURRENT_BALANCE REAL,
    DESCRIPTION TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
