CREATE TABLE IMBALANCE_STATEMENT
(
    IMBALANCE_STATEMENT_ID TEXT NOT NULL,
    STATEMENT_PERIOD_START DATETIME,
    STATEMENT_PERIOD_END DATETIME,
    IMBALANCE_RECONCILIATION_ID TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
