CREATE TABLE IMBALANCE_SUMMARY
(
    IMBALANCE_SUMMARY_ID TEXT NOT NULL,
    IMBALANCE_STATEMENT_ID TEXT,
    SUMMARY_TYPE TEXT,
    TOTAL_VOLUME REAL,
    TRANSACTION_COUNT INTEGER,
    AVERAGE_DAILY_VOLUME REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
