CREATE TABLE IMPAIRMENT_RECORD
(
    IMPAIRMENT_RECORD_ID TEXT NOT NULL,
    PROPERTY_ID TEXT,
    COST_CENTER_ID TEXT,
    IMPAIRMENT_DATE DATETIME,
    IMPAIRMENT_AMOUNT REAL,
    REASON TEXT,
    IMPAIRMENT_TYPE TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
