CREATE TABLE INVENTORY_ITEM
(
    INVENTORY_ITEM_ID TEXT NOT NULL,
    ITEM_NUMBER TEXT,
    ITEM_NAME TEXT,
    ITEM_TYPE TEXT,
    UNIT_OF_MEASURE TEXT,
    QUANTITY_ON_HAND REAL,
    UNIT_COST REAL,
    TOTAL_VALUE REAL,
    VALUATION_METHOD TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
