CREATE TABLE INVENTORY_ADJUSTMENT
(
    INVENTORY_ADJUSTMENT_ID TEXT NOT NULL,
    INVENTORY_ITEM_ID TEXT,
    ADJUSTMENT_DATE DATETIME,
    ADJUSTMENT_TYPE TEXT,
    QUANTITY_ADJUSTMENT REAL,
    UNIT_COST_ADJUSTMENT REAL,
    REASON TEXT,
    DESCRIPTION TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
