CREATE TABLE JIB_PARTICIPANT
(
    JIB_PARTICIPANT_ID TEXT NOT NULL,
    JOINT_INTEREST_STATEMENT_ID TEXT,
    COMPANY_NAME TEXT,
    WORKING_INTEREST REAL,
    NET_REVENUE_INTEREST REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
