CREATE TABLE JIB_COST_ALLOCATION
(
    JIB_COST_ALLOCATION_ID TEXT NOT NULL,
    JIB_ID TEXT,
    ROW_QUALITY TEXT,
    FINANCE_ID TEXT,
    COST_CATEGORY TEXT,
    GROSS_COST REAL NOT NULL,
    WORKING_INTEREST_SHARE REAL,
    NET_COST REAL NOT NULL,
    DESCRIPTION TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
