CREATE TABLE JOA_INTEREST
(
    JOA_INTEREST_ID TEXT NOT NULL,
    JOA_ID TEXT,
    INTEREST_OWNER_BA_ID TEXT,
    WORKING_INTEREST_PERCENTAGE REAL,
    REVENUE_INTEREST_PERCENTAGE REAL,
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    DESCRIPTION TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
