CREATE TABLE JOIB_LINE_ITEM
(
    JOIB_LINE_ITEM_ID TEXT NOT NULL,
    JOINT_INTEREST_BILL_ID TEXT,
    LINE_ITEM_NUMBER TEXT,
    COST_CATEGORY TEXT,
    DESCRIPTION TEXT,
    AMOUNT REAL,
    PROPERTY_ID TEXT,
    WELL_ID TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
