CREATE TABLE JOIB_ALLOCATION
(
    JOIB_ALLOCATION_ID TEXT NOT NULL,
    JOINT_INTEREST_BILL_ID TEXT,
    JOIB_LINE_ITEM_ID TEXT,
    INTEREST_OWNER_BA_ID TEXT,
    ALLOCATED_AMOUNT REAL,
    ALLOCATION_PERCENTAGE REAL,
    ALLOCATION_METHOD TEXT,
    DESCRIPTION TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
