CREATE TABLE LEASE_ALLOCATION_DATA
(
    LEASE_ALLOCATION_DATA_ID TEXT NOT NULL,
    LEASE_ID TEXT,
    WORKING_INTEREST REAL,
    NET_REVENUE_INTEREST REAL,
    MEASURED_PRODUCTION REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
