CREATE TABLE LOCATION_ADJUSTMENTS
(
    LOCATION_ADJUSTMENTS_ID TEXT NOT NULL,
    LOCATION_DIFFERENTIAL REAL,
    TRANSPORTATION_ADJUSTMENT REAL,
    TOTAL_ADJUSTMENT REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
