CREATE TABLE MEASUREMENT_ACCURACY
(
    MEASUREMENT_ACCURACY_ID TEXT NOT NULL,
    MINIMUM_ACCURACY REAL,
    MAXIMUM_ERROR REAL,
    CALIBRATION_REQUIRED TEXT,
    CALIBRATION_FREQUENCY_DAYS INTEGER,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
