CREATE TABLE MEASUREMENT_CORRECTIONS
(
    MEASUREMENT_CORRECTIONS_ID TEXT NOT NULL,
    MEASUREMENT_RECORD_ID TEXT,
    TEMPERATURE_CORRECTION_FACTOR REAL,
    PRESSURE_CORRECTION_FACTOR REAL,
    METER_FACTOR REAL,
    SHRINKAGE_FACTOR REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
