CREATE TABLE NOMINATION
(
    NOMINATION_ID TEXT NOT NULL,
    PERIOD_START DATETIME,
    PERIOD_END DATETIME,
    NOMINATED_VOLUME REAL,
    DELIVERY_POINTS_JSON TEXT,
    STATUS TEXT,
    SUBMISSION_DATE DATETIME,
    APPROVAL_DATE DATETIME,
    APPROVED_BY TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
