CREATE TABLE OWNER_INFORMATION
(
    OWNER_INFORMATION_ID TEXT NOT NULL,
    OWNER_NAME TEXT,
    TAX_ID TEXT,
    ADDRESS_ID TEXT,
    CONTACT_INFORMATION_ID TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
