CREATE TABLE PARTICIPATING_AREA
(
    PARTICIPATING_AREA_ID TEXT NOT NULL,
    UNIT_ID TEXT,
    PARTICIPATING_AREA_NAME TEXT,
    TRACTS_JSON TEXT,
    EFFECTIVE_DATE DATETIME,
    EXPIRATION_DATE DATETIME,
    TOTAL_PARTICIPATION REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
