CREATE TABLE PRICE_INDEX
(
    PRICE_INDEX_ID TEXT NOT NULL,
    INDEX_NAME TEXT,
    COMMODITY_TYPE TEXT,
    PRICE_DATE DATETIME,
    PRICE_VALUE REAL,
    CURRENCY_CODE TEXT,
    UNIT_OF_MEASURE TEXT,
    DESCRIPTION TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
