CREATE TABLE PURCHASE_ORDER
(
    PURCHASE_ORDER_ID TEXT NOT NULL,
    PO_NUMBER TEXT,
    VENDOR_BA_ID TEXT,
    PO_DATE DATETIME,
    EXPECTED_DELIVERY_DATE DATETIME,
    TOTAL_AMOUNT REAL,
    STATUS TEXT,
    DESCRIPTION TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
