CREATE TABLE REVENUE_DISTRIBUTION
(
    REVENUE_DISTRIBUTION_ID TEXT NOT NULL,
    REVENUE_TRANSACTION_ID TEXT,
    INT_SET_PARTNER_ID TEXT,
    ROW_QUALITY TEXT,
    BUSINESS_ASSOCIATE_ID TEXT,
    WORKING_INTEREST_PERCENTAGE REAL,
    NET_REVENUE_INTEREST_PERCENTAGE REAL,
    REVENUE_AMOUNT REAL NOT NULL,
    DESCRIPTION TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
