CREATE TABLE REVENUE_DEDUCTION
(
    REVENUE_DEDUCTION_ID TEXT NOT NULL,
    REVENUE_TRANSACTION_ID TEXT,
    DEDUCTION_TYPE TEXT,
    AMOUNT REAL NOT NULL,
    DESCRIPTION TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY TEXT,
    ROW_ID TEXT
);
