CREATE TABLE ROYALTY_CALCULATION
(
    ROYALTY_CALCULATION_ID TEXT NOT NULL,
    CALCULATION_DATE DATETIME,
    PROPERTY_OR_LEASE_ID TEXT,
    GROSS_REVENUE REAL,
    ROYALTY_DEDUCTIONS_ID TEXT,
    NET_REVENUE REAL,
    ROYALTY_INTEREST REAL,
    ROYALTY_AMOUNT REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
