CREATE TABLE ROYALTY_DEDUCTIONS
(
    ROYALTY_DEDUCTIONS_ID TEXT NOT NULL,
    PRODUCTION_TAXES REAL,
    TRANSPORTATION_COSTS REAL,
    PROCESSING_COSTS REAL,
    MARKETING_COSTS REAL,
    OTHER_DEDUCTIONS REAL,
    TOTAL_DEDUCTIONS REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
