CREATE TABLE ROYALTY_PAYMENT_DETAIL
(
    ROYALTY_PAYMENT_DETAIL_ID TEXT NOT NULL,
    ROYALTY_PAYMENT_ID TEXT,
    REVENUE_TRANSACTION_ID TEXT,
    OIL_VOLUME REAL,
    GAS_VOLUME REAL,
    OIL_REVENUE REAL,
    GAS_REVENUE REAL,
    ROYALTY_AMOUNT REAL,
    DESCRIPTION TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
