CREATE TABLE TIME_ADJUSTMENTS
(
    TIME_ADJUSTMENTS_ID TEXT NOT NULL,
    TIME_DIFFERENTIAL REAL,
    INTEREST_ADJUSTMENT REAL,
    TOTAL_ADJUSTMENT REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
