CREATE TABLE TRACT_PARTICIPATION
(
    TRACT_PARTICIPATION_ID TEXT NOT NULL,
    TRACT_ID TEXT,
    UNIT_ID TEXT,
    PARTICIPATING_AREA_ID TEXT,
    PARTICIPATION_PERCENTAGE REAL,
    WORKING_INTEREST REAL,
    NET_REVENUE_INTEREST REAL,
    TRACT_ACREAGE REAL,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
