CREATE TABLE TRANSFER_ORDER
(
    TRANSFER_ORDER_ID TEXT NOT NULL,
    PROPERTY_OR_LEASE_ID TEXT,
    FROM_OWNER_ID TEXT,
    TO_OWNER_ID TEXT,
    INTEREST_TRANSFERRED REAL,
    EFFECTIVE_DATE DATETIME,
    IS_APPROVED TEXT,
    APPROVAL_DATE DATETIME,
    APPROVED_BY TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
