CREATE TABLE UNIT_OPERATING_AGREEMENT
(
    UNIT_OPERATING_AGREEMENT_ID TEXT NOT NULL,
    UNIT_ID TEXT,
    VOTING_RIGHTS_ID TEXT,
    COST_SHARING_ID TEXT,
    REVENUE_SHARING_ID TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
