CREATE TABLE VOTING_RIGHTS
(
    VOTING_RIGHTS_ID TEXT NOT NULL,
    UNIT_OPERATING_AGREEMENT_ID TEXT,
    BASED_ON_WORKING_INTEREST TEXT,
    MINIMUM_VOTING_THRESHOLD REAL,
    UNANIMOUS_CONSENT_REQUIRED TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    REMARK TEXT,
    SOURCE TEXT,
    ROW_QUALITY TEXT,
    ROW_CREATED_BY TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID TEXT
);
