CREATE TABLE "NPV_PROFILE_POINT"
(
    "NPV_PROFILE_POINT_ID" VARCHAR(40) NOT NULL,
    "ECONOMIC_ANALYSIS_RESULT_ID" VARCHAR(40),
    "RATE" NUMERIC(18,2),
    "NPV" NUMERIC(18,2),
    "POINT_ORDER" INTEGER,
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP,
    "ROW_QUALITY" VARCHAR(40),
    "AREA_ID" VARCHAR(40),
    "AREA_TYPE" VARCHAR(50),
    "BUSINESS_ASSOCIATE_ID" VARCHAR(40),
    "EFFECTIVE_DATE" TIMESTAMP,
    "EXPIRY_DATE" TIMESTAMP
);
