ALTER TABLE `LIQUID_PIPELINE_FLOW_PROPERTIES`
ADD CONSTRAINT FK_LIQUID_PIPELINE_FLOW_PROPERTIES_PIPELINE_PROPERTIES FOREIGN KEY (`PIPELINE_PROPERTIES_ID`) REFERENCES `PIPELINE_PROPERTIES`(`PIPELINE_PROPERTIES_ID`);
