CREATE TABLE `PIPELINE_RISK_ASSESSMENT`
(
    `PIPELINE_ID` VARCHAR(40),
    `RISK_ASSESSMENT_ID` VARCHAR(40),
    `ASSESSMENT_DATE` DATETIME,
    `RISK_SCORE` DECIMAL(18,2) NOT NULL,
    `ASSESSMENT_METHOD` VARCHAR(255),
    `RISK_FACTORS` VARCHAR(255),
    `SEGMENT_ID` VARCHAR(40),
    `DESCRIPTION` VARCHAR(2000),
    `ACTIVE_IND` VARCHAR(1) DEFAULT 'Y',
    `EFFECTIVE_DATE` DATETIME,
    `EXPIRY_DATE` DATETIME,
    `PPDM_GUID` VARCHAR(40),
    `REMARK` VARCHAR(2000),
    `SOURCE` VARCHAR(40),
    `ROW_CHANGED_BY` VARCHAR(30),
    `ROW_CHANGED_DATE` DATETIME,
    `ROW_CREATED_BY` VARCHAR(30),
    `ROW_CREATED_DATE` DATETIME,
    `ROW_EFFECTIVE_DATE` DATETIME,
    `ROW_EXPIRY_DATE` DATETIME,
    `ROW_QUALITY` VARCHAR(40)
);
