ALTER TABLE `PIPELINE_RISK_ASSESSMENT`
ADD CONSTRAINT FK_PIPELINE_RISK_ASSESSMENT_PIPELINE FOREIGN KEY (`PIPELINE_ID`) REFERENCES `PIPELINE`(`PIPELINE_ID`);

ALTER TABLE `PIPELINE_RISK_ASSESSMENT`
ADD CONSTRAINT FK_PIPELINE_RISK_ASSESSMENT_RISK_ASSESSMENT FOREIGN KEY (`RISK_ASSESSMENT_ID`) REFERENCES `RISK_ASSESSMENT`(`RISK_ASSESSMENT_ID`);

ALTER TABLE `PIPELINE_RISK_ASSESSMENT`
ADD CONSTRAINT FK_PIPELINE_RISK_ASSESSMENT_SEGMENT FOREIGN KEY (`SEGMENT_ID`) REFERENCES `SEGMENT`(`SEGMENT_ID`);
