CREATE TABLE "EXPORT_HISTORY"
(
    "EXPORT_HISTORY_ID" VARCHAR(40) NOT NULL,
    "EXPORT_TYPE" VARCHAR(50),
    "EXPORT_FORMAT" VARCHAR(255),
    "EXPORT_DATE" TIMESTAMP,
    "EXPORTED_BY" VARCHAR(255),
    "FILE_PATH" VARCHAR(255),
    "RECORD_COUNT" INTEGER,
    "STATUS" VARCHAR(50),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP
);
