raiserror ('CREATING TABLE EXPLORATION_BUDGET', 10,1) with nowait

CREATE TABLE EXPLORATION_BUDGET
(
    PROGRAM_ID NVARCHAR(40),
    BUDGET_YEAR NUMERIC(18,2) NOT NULL,
    BUDGET_AMOUNT NUMERIC(18,2),
    BUDGET_CURRENCY NVARCHAR(255),
    BUDGET_CATEGORY NVARCHAR(255),
    ACTUAL_AMOUNT NUMERIC(18,2),
    VARIANCE NUMERIC(18,2),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
