raiserror ('CREATING TABLE EXPLORATION_PERMIT', 10,1) with nowait

CREATE TABLE EXPLORATION_PERMIT
(
    PERMIT_ID NVARCHAR(40),
    PERMIT_NUMBER NVARCHAR(255),
    FIELD_ID NVARCHAR(40),
    PERMIT_HOLDER NVARCHAR(255),
    PERMIT_START_DATE DATETIME,
    PERMIT_END_DATE DATETIME,
    PERMIT_AREA NUMERIC(18,2),
    PERMIT_AREA_OUOM NVARCHAR(255),
    PERMIT_TERMS NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
