raiserror ('CREATING TABLE EXPLORATION_COSTS', 10,1) with nowait

CREATE TABLE EXPLORATION_COSTS
(
    EXPLORATION_COST_ID NVARCHAR(40),
    PROPERTY_ID NVARCHAR(40),
    GEOLOGICAL_GEOPHYSICAL_COSTS NUMERIC(18,2),
    EXPLORATORY_DRILLING_COSTS NUMERIC(18,2),
    EXPLORATORY_WELL_EQUIPMENT NUMERIC(18,2),
    TOTAL_EXPLORATION_COSTS NUMERIC(18,6),
    COST_DATE DATETIME,
    WELL_ID NVARCHAR(40),
    IS_DRY_HOLE NVARCHAR(255),
    FOUND_PROVED_RESERVES NVARCHAR(255),
    IS_DEFERRED_CLASSIFICATION NVARCHAR(255),
    COST_CENTER_ID NVARCHAR(40),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_QUALITY NVARCHAR(40),
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_ID NVARCHAR(40)
);
