raiserror ('CREATING TABLE EXPLORATION_PROGRAM', 10,1) with nowait

CREATE TABLE EXPLORATION_PROGRAM
(
    PROGRAM_ID NVARCHAR(40),
    PROGRAM_NAME NVARCHAR(255),
    FIELD_ID NVARCHAR(40),
    OPERATOR NVARCHAR(255),
    OBJECTIVES NVARCHAR(255),
    PROGRAM_START_DATE DATETIME,
    PROGRAM_END_DATE DATETIME,
    BUDGET NUMERIC(18,2),
    BUDGET_CURRENCY NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
