ALTER TABLE LEAD
ADD CONSTRAINT FK_LEAD_FIELD FOREIGN KEY (FIELD_ID) REFERENCES FIELD(FIELD_ID);

ALTER TABLE LEAD
ADD CONSTRAINT FK_LEAD_PLAY FOREIGN KEY (PLAY_ID) REFERENCES PLAY(PLAY_ID);

ALTER TABLE LEAD
ADD CONSTRAINT FK_LEAD_PROMOTED_TO_PROSPECT FOREIGN KEY (PROMOTED_TO_PROSPECT_ID) REFERENCES PROMOTED_TO_PROSPECT(PROMOTED_TO_PROSPECT_ID);
