ALTER TABLE PROSPECT_MIGRATION
ADD CONSTRAINT FK_PROSPECT_MIGRATION_PROSPECT FOREIGN KEY (PROSPECT_ID) REFERENCES PROSPECT(PROSPECT_ID);

ALTER TABLE PROSPECT_MIGRATION
ADD CONSTRAINT FK_PROSPECT_MIGRATION_MIGRATION FOREIGN KEY (MIGRATION_ID) REFERENCES MIGRATION(MIGRATION_ID);
