raiserror ('CREATING TABLE PROSPECT_HISTORY', 10,1) with nowait

CREATE TABLE PROSPECT_HISTORY
(
    PROSPECT_ID NVARCHAR(40),
    HISTORY_SEQ_NO NUMERIC(18,2) NOT NULL,
    FIELD_NAME NVARCHAR(255),
    OLD_VALUE NVARCHAR(255),
    NEW_VALUE NVARCHAR(255),
    CHANGE_REASON NVARCHAR(255),
    CHANGED_BY NVARCHAR(30),
    CHANGE_DATE DATETIME,
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
