raiserror ('CREATING TABLE PROSPECT_WORKFLOW_STAGE', 10,1) with nowait

CREATE TABLE PROSPECT_WORKFLOW_STAGE
(
    PROSPECT_ID NVARCHAR(40),
    STAGE_SEQ_NO NUMERIC(18,2) NOT NULL,
    WORKFLOW_STAGE NVARCHAR(255),
    STAGE_START_DATE DATETIME,
    STAGE_END_DATE DATETIME,
    STAGE_OUTCOME NVARCHAR(255),
    NEXT_STAGE NVARCHAR(255),
    APPROVALS_REQUIRED NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
