ALTER TABLE PROSPECT_BA
ADD CONSTRAINT FK_PROSPECT_BA_PROSPECT FOREIGN KEY (PROSPECT_ID) REFERENCES PROSPECT(PROSPECT_ID);

ALTER TABLE PROSPECT_BA
ADD CONSTRAINT FK_PROSPECT_BA_BUSINESS_ASSOCIATE FOREIGN KEY (BUSINESS_ASSOCIATE_ID) REFERENCES BUSINESS_ASSOCIATE(BUSINESS_ASSOCIATE_ID);
