raiserror ('CREATING TABLE PROSPECT_RANKING', 10,1) with nowait

CREATE TABLE PROSPECT_RANKING
(
    PROSPECT_ID NVARCHAR(40),
    RANKING_ID NVARCHAR(40),
    RANKING_SCORE NUMERIC(18,2),
    PRIORITY_ORDER NUMERIC(18,2),
    RANKING_CRITERIA NVARCHAR(255),
    RANKING_DATE DATETIME,
    RANKER NVARCHAR(255),
    METHODOLOGY NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
