raiserror ('CREATING TABLE PROSPECT_TRAP', 10,1) with nowait

CREATE TABLE PROSPECT_TRAP
(
    PROSPECT_ID NVARCHAR(40),
    TRAP_ID NVARCHAR(40),
    TRAP_TYPE NVARCHAR(50),
    TRAP_GEOMETRY NVARCHAR(255),
    CLOSURE_AREA NUMERIC(18,2),
    CLOSURE_AREA_OUOM NVARCHAR(255),
    CLOSURE_HEIGHT NUMERIC(18,2),
    CLOSURE_HEIGHT_OUOM NVARCHAR(255),
    SEAL_QUALITY NVARCHAR(40),
    SEAL_THICKNESS NUMERIC(18,2),
    SEAL_THICKNESS_OUOM NVARCHAR(255),
    TRAP_EFFECTIVENESS NUMERIC(18,2),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
