raiserror ('CREATING TABLE PROSPECT_MIGRATION', 10,1) with nowait

CREATE TABLE PROSPECT_MIGRATION
(
    PROSPECT_ID NVARCHAR(40),
    MIGRATION_ID NVARCHAR(40),
    MIGRATION_PATHWAY NVARCHAR(255),
    MIGRATION_DISTANCE NUMERIC(18,6),
    MIGRATION_DISTANCE_OUOM NVARCHAR(255),
    MIGRATION_EFFICIENCY NUMERIC(18,6),
    MIGRATION_TIMING NVARCHAR(255),
    CARRIER_BED NVARCHAR(255),
    SEAL_BREACH_RISK NUMERIC(18,2),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
