raiserror ('CREATING TABLE PROSPECT_SEIS_SURVEY', 10,1) with nowait

CREATE TABLE PROSPECT_SEIS_SURVEY
(
    PROSPECT_ID NVARCHAR(40),
    SEIS_SET_ID NVARCHAR(40),
    ASSOCIATION_TYPE NVARCHAR(50),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
