ALTER TABLE PROSPECT_SEIS_SURVEY
ADD CONSTRAINT FK_PROSPECT_SEIS_SURVEY_PROSPECT FOREIGN KEY (PROSPECT_ID) REFERENCES PROSPECT(PROSPECT_ID);

ALTER TABLE PROSPECT_SEIS_SURVEY
ADD CONSTRAINT FK_PROSPECT_SEIS_SURVEY_SEIS_SET FOREIGN KEY (SEIS_SET_ID) REFERENCES SEIS_SET(SEIS_SET_ID);
