raiserror ('CREATING TABLE PROSPECT_PORTFOLIO', 10,1) with nowait

CREATE TABLE PROSPECT_PORTFOLIO
(
    PORTFOLIO_ID NVARCHAR(40),
    PORTFOLIO_NAME NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    STRATEGIC_OBJECTIVES NVARCHAR(255),
    CREATION_DATE DATETIME,
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
