ALTER TABLE PROSPECT_VOLUME_ESTIMATE
ADD CONSTRAINT FK_PROSPECT_VOLUME_ESTIMATE_PROSPECT FOREIGN KEY (PROSPECT_ID) REFERENCES PROSPECT(PROSPECT_ID);

ALTER TABLE PROSPECT_VOLUME_ESTIMATE
ADD CONSTRAINT FK_PROSPECT_VOLUME_ESTIMATE_ESTIMATE FOREIGN KEY (ESTIMATE_ID) REFERENCES ESTIMATE(ESTIMATE_ID);
