raiserror ('CREATING TABLE PROSPECT_SOURCE_ROCK', 10,1) with nowait

CREATE TABLE PROSPECT_SOURCE_ROCK
(
    PROSPECT_ID NVARCHAR(40),
    SOURCE_ID NVARCHAR(40),
    STRAT_UNIT_ID NVARCHAR(40),
    TOC NUMERIC(18,2),
    HI NUMERIC(18,2),
    KEROGEN_TYPE NVARCHAR(50),
    VITRINITE_REFLECTANCE NUMERIC(18,2),
    TMAX NUMERIC(18,2),
    MATURITY_STAGE NVARCHAR(255),
    GENERATION_POTENTIAL NUMERIC(18,6),
    EXPULSION_EFFICIENCY NUMERIC(18,2),
    MIGRATION_DISTANCE NUMERIC(18,6),
    MIGRATION_DISTANCE_OUOM NVARCHAR(255),
    DESCRIPTION NVARCHAR(2000),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME,
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CREATED_DATE DATETIME,
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
