CREATE TABLE "SALES_AGREEMENT"
(
    "AGREEMENT_ID" VARCHAR(40),
    "AGREEMENT_NAME" VARCHAR(255),
    "SELLER_BA_ID" VARCHAR(40),
    "PURCHASER_BA_ID" VARCHAR(40),
    "EFFECTIVE_DATE" TIMESTAMP,
    "EXPIRATION_DATE" TIMESTAMP,
    "PRICING_METHOD" VARCHAR(255),
    "BASE_PRICE" NUMERIC(18,2),
    "PRICE_INDEX" VARCHAR(255),
    "DIFFERENTIAL" NUMERIC(18,2),
    "PAYMENT_TERMS_DAYS" INTEGER,
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP
);
