CREATE TABLE "TRANSPORTATION_AGREEMENT"
(
    "AGREEMENT_ID" VARCHAR(40),
    "CARRIER_BA_ID" VARCHAR(40),
    "ORIGIN_POINT" VARCHAR(255),
    "DESTINATION_POINT" VARCHAR(255),
    "EFFECTIVE_DATE" TIMESTAMP,
    "EXPIRATION_DATE" TIMESTAMP,
    "TARIFF_RATE" NUMERIC(18,2),
    "MINIMUM_VOLUME_COMMITMENT" NUMERIC(18,2),
    "MAXIMUM_CAPACITY" NUMERIC(18,2),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP
);
