raiserror ('CREATING TABLE NODAL_VLP_POINT', 10,1) with nowait

CREATE TABLE NODAL_VLP_POINT
(
    NODAL_VLP_POINT_ID NVARCHAR(40) NOT NULL,
    NODAL_ANALYSIS_ID NVARCHAR(40),
    FLOW_RATE NUMERIC(18,2),
    REQUIRED_BOTTOMHOLE_PRESSURE NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40)
);
