raiserror ('CREATING TABLE NODAL_RESERVOIR_PROPERTIES', 10,1) with nowait

CREATE TABLE NODAL_RESERVOIR_PROPERTIES
(
    NODAL_RESERVOIR_PROPERTIES_ID NVARCHAR(40) NOT NULL,
    NODAL_ANALYSIS_RESULT_ID NVARCHAR(40),
    RESERVOIR_PRESSURE NUMERIC(18,2),
    BUBBLE_POINT_PRESSURE NUMERIC(18,2),
    PRODUCTIVITY_INDEX NUMERIC(18,2),
    WATER_CUT NUMERIC(18,2),
    GAS_OIL_RATIO NUMERIC(18,6),
    OIL_GRAVITY NUMERIC(18,2),
    FORMATION_VOLUME_FACTOR NUMERIC(18,2),
    OIL_VISCOSITY NUMERIC(18,2),
    ACTIVE_IND NVARCHAR(1) DEFAULT 'Y',
    PPDM_GUID NVARCHAR(40),
    REMARK NVARCHAR(2000),
    SOURCE NVARCHAR(40),
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY NVARCHAR(30),
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY NVARCHAR(30),
    ROW_EFFECTIVE_DATE DATETIME,
    ROW_EXPIRY_DATE DATETIME,
    ROW_QUALITY NVARCHAR(40),
    AREA_ID NVARCHAR(40),
    AREA_TYPE NVARCHAR(50),
    BUSINESS_ASSOCIATE_ID NVARCHAR(40),
    EFFECTIVE_DATE DATETIME,
    EXPIRY_DATE DATETIME
);
