CREATE TABLE "LACT_UNIT"
(
    "LACT_UNIT_ID" VARCHAR(40) NOT NULL,
    "LACT_NAME" VARCHAR(255),
    "SERVICE_UNIT_ID" VARCHAR(40),
    "METER_TYPE" VARCHAR(50),
    "MAXIMUM_FLOW_RATE" NUMERIC(18,2),
    "METER_FACTOR" NUMERIC(18,2),
    "LAST_CALIBRATION_DATE" TIMESTAMP,
    "NEXT_CALIBRATION_DATE" TIMESTAMP,
    "IS_ACTIVE" VARCHAR(255),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP
);
