CREATE TABLE "TANK_BATTERY"
(
    "TANK_BATTERY_ID" VARCHAR(40) NOT NULL,
    "BATTERY_NAME" VARCHAR(255),
    "STORAGE_FACILITY_ID" VARCHAR(40),
    "LEASE_ID" VARCHAR(40),
    "CURRENT_INVENTORY" NUMERIC(18,2),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP
);
