ALTER TABLE "DRILLING_PERMIT_APPLICATION"
ADD CONSTRAINT FK_DRILLING_PERMIT_APPLICATION_PERMIT_APPLICATION FOREIGN KEY ("PERMIT_APPLICATION_ID") REFERENCES "PERMIT_APPLICATION"("PERMIT_APPLICATION_ID");

ALTER TABLE "DRILLING_PERMIT_APPLICATION"
ADD CONSTRAINT FK_DRILLING_PERMIT_APPLICATION_AREA FOREIGN KEY ("AREA_ID") REFERENCES "AREA"("AREA_ID");

ALTER TABLE "DRILLING_PERMIT_APPLICATION"
ADD CONSTRAINT FK_DRILLING_PERMIT_APPLICATION_BUSINESS_ASSOCIATE FOREIGN KEY ("BUSINESS_ASSOCIATE_ID") REFERENCES "BUSINESS_ASSOCIATE"("BUSINESS_ASSOCIATE_ID");
