CREATE TABLE "EXCHANGE_COMMITMENT"
(
    "EXCHANGE_COMMITMENT_ID" VARCHAR(40) NOT NULL,
    "EXCHANGE_CONTRACT_ID" VARCHAR(40),
    "COMMITMENT_TYPE" VARCHAR(50),
    "COMMITTED_VOLUME" NUMERIC(18,2),
    "ACTUAL_VOLUME_DELIVERED" NUMERIC(18,2),
    "DELIVERY_PERIOD_START" TIMESTAMP,
    "DELIVERY_PERIOD_END" TIMESTAMP,
    "STATUS" VARCHAR(50),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP
);
