CREATE TABLE "EXCHANGE_TRANSACTION"
(
    "EXCHANGE_TRANSACTION_ID" VARCHAR(40) NOT NULL,
    "EXCHANGE_CONTRACT_ID" VARCHAR(40),
    "TRANSACTION_DATE" TIMESTAMP,
    "RECEIPT_VOLUME" NUMERIC(18,2),
    "RECEIPT_PRICE" NUMERIC(18,2),
    "RECEIPT_LOCATION" VARCHAR(255),
    "DELIVERY_VOLUME" NUMERIC(18,2),
    "DELIVERY_PRICE" NUMERIC(18,2),
    "DELIVERY_LOCATION" VARCHAR(255),
    "STATUS" VARCHAR(50),
    "DESCRIPTION" VARCHAR(2000),
    "ACTIVE_IND" VARCHAR(1) DEFAULT 'Y',
    "PPDM_GUID" VARCHAR(40),
    "REMARK" VARCHAR(2000),
    "SOURCE" VARCHAR(40),
    "ROW_CREATED_DATE" TIMESTAMP,
    "ROW_CREATED_BY" VARCHAR(30),
    "ROW_CHANGED_DATE" TIMESTAMP,
    "ROW_CHANGED_BY" VARCHAR(30),
    "ROW_EFFECTIVE_DATE" TIMESTAMP,
    "ROW_EXPIRY_DATE" TIMESTAMP
);
