CREATE TABLE HEAT_MAP_CONFIGURATION
(
    HEAT_MAP_ID TEXT,
    CONFIGURATION_NAME TEXT,
    ACTIVE_IND TEXT,
    PPDM_GUID TEXT,
    ROW_CREATED_DATE DATETIME,
    ROW_CREATED_BY TEXT,
    ROW_CHANGED_DATE DATETIME,
    ROW_CHANGED_BY TEXT
);
