ALTER TABLE `STORAGE_AGREEMENT`
ADD CONSTRAINT FK_STORAGE_AGREEMENT_AGREEMENT FOREIGN KEY (`AGREEMENT_ID`) REFERENCES `AGREEMENT`(`AGREEMENT_ID`);

ALTER TABLE `STORAGE_AGREEMENT`
ADD CONSTRAINT FK_STORAGE_AGREEMENT_STORAGE_FACILITY FOREIGN KEY (`STORAGE_FACILITY_ID`) REFERENCES `STORAGE_FACILITY`(`STORAGE_FACILITY_ID`);
